Repository FerretDB/FerretDB, pull requests merged in 2021-12, with the labels that each got.

#121 Return version in `serverStatus` command.
  internal/handlers/handler_test.go
  internal/handlers/shared/msg_buildinfo.go
  internal/handlers/shared/msg_serverstatus.go
Labels: code/enhancement

#205 Fix build info parsing.
  internal/util/version/version.go
Labels: code/bug

#206 Support `collStats` command.
  internal/handlers/handler.go
  internal/handlers/handler_test.go
  internal/handlers/shared/msg_collstats.go
  internal/pg/pool.go
Labels: code/feature
