Repository FerretDB/FerretDB, pull requests merged in 2022-08, with the labels that each got.

#967 `tjson`: Check how we support `binary`
  internal/tjson/binary_test.go
  internal/tjson/bool_test.go
  internal/tjson/double_test.go
  internal/tjson/int32_test.go
  internal/tjson/int64_test.go
  internal/tjson/string_test.go
  internal/tjson/tjson_test.go
Labels: code/chore, code/tigris

#965 Move logic operators tests to compatibility tests
  integration/query_compat_test.go
  integration/query_logical_compat_test.go
  integration/query_logical_test.go
Labels: code/chore

#790 Support `multi` `update`'s argument
  integration/update_test.go
  internal/handlers/pg/msg_update.go
  internal/handlers/tigris/msg_update.go
Labels: code/feature

#964 Add compatibility tests for `$inc`
  integration/query_compat_test.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
Labels: code/chore

#954 Support `delete`'s comment
  integration/basic_test.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/pgdb/pool.go
Labels: code/feature

#976 Add test case for an empty update path
  integration/update_field_compat_test.go
Labels: code/chore

#975 Update process docs
  .github/PROCESS.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, project

#973 Improve Document's Path API
  internal/types/document.go
  internal/types/document_test.go
  internal/types/path.go
Labels: code/enhancement

#971 `tjson`: Add unit tests for `ObjectID`
  internal/tjson/object_id_test.go
  internal/tjson/tjson_test.go
Labels: code/chore, code/tigris

#654 Make linter to enforce our preferred types order in type switch
  Taskfile.yml
  internal/handlers/common/filter.go
  internal/handlers/common/params.go
  internal/handlers/common/projection.go
  internal/handlers/common/update.go
  internal/tjson/tjson_test.go
  internal/types/compare.go
  tools/Taskfile.yml
  tools/checkswitch/checkswitch.go
  tools/checkswitch/checkswitch_test.go
  tools/checkswitch/testdata/testdata.go
  tools/checkswitch/testdata/types/types.go
  tools/tools.go
Labels: code/chore

#983 Add back `task env-data`
  Taskfile.yml
  integration/Taskfile.yml
  integration/setup/common.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/shareddata_test.go
Labels: code/chore

#862 Insert test data in random order
  integration/findandmodify_test.go
  integration/query_test.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/shareddata/shareddata.go
Labels: code/chore

#608 Support `maxTimeMS` argument for `find` and `findAndModify` methods
  integration/query_test.go
  internal/handlers/common/params.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/tigris/msg_find.go
Labels: code/feature

#992 `tjson`: Improve ObjectID test
  internal/tjson/object_id.go
  internal/tjson/object_id_test.go
Labels: code/chore, code/tigris

#995 Bump deps
  build/deps/mongo5.Dockerfile
  build/deps/mongo6.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps, trust

#997 Bump Tigris Docker image to alpha.26
  build/deps/tigris.Dockerfile
Labels: code/chore

#968 Tigris: simplify `ObjectID` and filter usage
  .golangci.yml
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  integration/object_id_delete_test.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/tigrisdb/filter/comparison.go
  internal/handlers/tigris/tigrisdb/filter/filter.go
  internal/handlers/tigris/tigrisdb/filter/operations.go
  internal/tjson/tjson.go
  tools/go.mod
  tools/go.sum
Labels: code/chore, code/tigris

#915 Add support for `update`'s `$inc` operator dot notation
  integration/update_field_compat_test.go
  integration/update_field_test.go
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/update.go
  internal/types/document.go
  internal/types/document_test.go
  internal/types/path.go
  internal/types/types.go
Labels: code/feature

#984 Add more scalar values to tests
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
  integration/update_field_compat_test.go
Labels: code/chore

#981 Implement `aggregate` command stub
  internal/clientconn/conn.go
  internal/clientconn/conn_metrics.go
  internal/clientconn/conninfo/conn_info.go
  internal/handlers/common/msg_aggregate.go
  internal/handlers/common/msg_listcommands.go
  internal/handlers/dummy/msg_aggregate.go
  internal/handlers/handlers.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_update.go
  internal/handlers/tigris/msg_aggregate.go
  internal/handlers/tigris/msg_update.go
  internal/util/debug/debug.go
Labels: code/feature, trust

#996 Describe team performance measurement process
  .github/PROCESS.md
Labels: project

#1003 Reformat with Go 1.19
  integration/helpers.go
  internal/bson/bson.go
  internal/clientconn/conn.go
  internal/fjson/fjson.go
  internal/handlers/common/params.go
  internal/handlers/common/update.go
  internal/handlers/dummy/dummy.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/databases.go
  internal/types/types.go
  internal/util/testutil/equal.go
Labels: code/chore

#957 `tjson`: Cover `document` (`object`) type with tests
  integration/commands_administration_test.go
  internal/tjson/document_test.go
  internal/tjson/schema.go
  internal/tjson/tjson_test.go
Labels: code/chore, code/tigris

#1002 Add compatibility `delete` test for Tigris
  integration/delete_compat_test.go
  integration/helpers.go
  integration/query_compat_test.go
  integration/update_compat_test.go
Labels: code/chore

#791 Add support for updates with replacement objects
  integration/update_test.go
  internal/handlers/common/update.go
  internal/handlers/pg/msg_findandmodify.go
Labels: code/feature

#1014 Bump deps
  .github/PULL_REQUEST_TEMPLATE.md
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: deps

#1008 Add support for `$update`'s `$set` and `$setOnInsert` operators dot notation
  integration/update_field_test.go
  internal/handlers/common/update.go
Labels: code/feature

#1022 Fix `Run linters` job in Taskfile.yml
  Taskfile.yml
Labels: code/chore

#1021 Improve and document integration tests
  CONTRIBUTING.md
  cmd/envtool/main.go
  integration/query_compat_test.go
  integration/setup/common.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/shareddata/composites.go
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
  integration/update_field_test.go
  internal/handlers/pg/pgdb/insert.go
Labels: code/chore

#1026 Add missing `MaxTimeMS` support for Tigris
  integration/findandmodify_test.go
  integration/query_test.go
  internal/handlers/tigris/msg_find.go
Labels: code/chore, code/tigris

#1020 Support `$pop` array update operator
  integration/update_field_test.go
  internal/handlers/common/update.go
  internal/types/array.go
Labels: code/feature

#1030 Expose `delete` problem
  integration/delete_compat_test.go
  integration/go.mod
  integration/helpers.go
  integration/query_compat_test.go
  integration/update_compat_test.go
Labels: code/chore

#1032 Bump Tigris version to 1.0.0-alpha.27
  build/deps/tigris.Dockerfile
Labels: deps

#1027 `tjson`: Implement `datetime`
  integration/shareddata/shareddata.go
  internal/tjson/datetime.go
  internal/tjson/datetime_test.go
  internal/tjson/schema.go
  internal/tjson/tjson.go
  internal/tjson/tjson_test.go
Labels: code/chore, code/tigris

#1031 `tjson`: Add package documentation for types mapping
  internal/tjson/tjson.go
Labels: code/chore, code/tigris

#1028 Add support for `$update`'s `$unset` operators dot notation
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  integration/update_field_test.go
  internal/handlers/common/update.go
Labels: code/feature

#1041 Fix `update` operation for Tigris handler
  integration/update_field_compat_test.go
  internal/handlers/tigris/msg_update.go
Labels: code/enhancement

#1038 Rework database and collection creation for Tigris
  integration/shareddata/composites.go
  internal/handlers/tigris/fetch.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_drop.go
  internal/handlers/tigris/msg_dropdatabase.go
  internal/handlers/tigris/msg_getlog.go
  internal/handlers/tigris/msg_hello.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_ismaster.go
  internal/handlers/tigris/msg_listcollections.go
  internal/handlers/tigris/msg_listdatabases.go
  internal/handlers/tigris/msg_ping.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/tigris.go
  internal/handlers/tigris/tigrisdb/collections.go
  internal/handlers/tigris/tigrisdb/databases.go
  internal/handlers/tigris/tigrisdb/errors.go
  internal/handlers/tigris/tigrisdb/filter/comparison.go
  internal/handlers/tigris/tigrisdb/filter/filter.go
  internal/handlers/tigris/tigrisdb/tigrisdb.go
  internal/handlers/tigris/tigrisdb/tigrisdb_test.go
Labels: code/chore, code/tigris

#1049 Add a few more tests for logical query operators
  integration/delete_compat_test.go
  integration/query_compat_test.go
  integration/query_logical_compat_test.go
  integration/update_compat_test.go
Labels: code/chore

#1046 Ensure that database and collection names are unique
  integration/basic_test.go
  integration/commands_administration_test.go
  integration/setup/common.go
  integration/setup/setup_compat.go
  internal/handlers/pg/pgdb/pool_test.go
  internal/util/testutil/db.go
  internal/util/testutil/pg.go
Labels: code/chore

#1047 Implement `MsgDBStats` for Tigris
  integration/commands_administration_test.go
  internal/handlers/tigris/msg_dbstats.go
Labels: code/chore, code/tigris

#1054 Bump Tigris version to 1.0.0-alpha.29
  build/deps/tigris.Dockerfile
Labels: code/chore, code/tigris

#1044 Add tests for update with replacement
  integration/delete_compat_test.go
  integration/query_compat_test.go
  integration/setup/common.go
  integration/shareddata/composites.go
  integration/shareddata/shareddata.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  integration/update_field_test.go
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/tigrisdb/errors.go
  internal/util/testutil/db.go
Labels: code/chore

#1055 Small `pgdb` cleanup
  integration/embedded_test.go
  integration/setup/common.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/databases.go
  internal/handlers/pg/pgdb/delete.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/pool_test.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/pg/pgdb/testutil_test.go
  internal/handlers/pg/pgdb/update.go
  internal/util/testutil/pg.go
Labels: code/chore

#1050 `tjson`: Implement `regex`
  integration/shareddata/shareddata.go
  internal/tjson/document_test.go
  internal/tjson/regex.go
  internal/tjson/regex_test.go
  internal/tjson/schema.go
  internal/tjson/tjson.go
  internal/tjson/tjson_test.go
Labels: code/feature, code/tigris

#1059 Bump deps
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#1060 Implement `MsgDataSize` for Tigris
  integration/commands_administration_test.go
  internal/handlers/tigris/fetch.go
  internal/handlers/tigris/msg_datasize.go
  internal/handlers/tigris/msg_dbstats.go
Labels: code/feature, code/tigris

#1043 Collect sizes in `MsgListDatabases` for Tigris
  integration/commands_administration_test.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/handlers/tigris/msg_listdatabases.go
  internal/handlers/tigris/tigrisdb/errors.go
Labels: code/enhancement

#1053 Less strict delta for `dataSize` in tests
  integration/commands_administration_test.go
Labels: code/chore, code/tigris

#1037 Add `collMod` command stub
  internal/handlers/common/msg_listcommands.go
  internal/handlers/dummy/msg_collmod.go
  internal/handlers/handlers.go
  internal/handlers/pg/msg_collmod.go
  internal/handlers/tigris/msg_collmod.go
Labels: code/chore

#998 Add a linter for Semantic Line Breaks in Markdown files
  .textlintignore
  CODE_OF_CONDUCT.md
  Taskfile.yml
  build/deps/textlint.Dockerfile
  docker-compose.yml
Labels: project

#1062 Improve `TestCommandsAdministrationServerStatus`
  integration/commands_administration_test.go
  internal/handlers/pg/msg_serverstatus.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/tigris/msg_serverstatus.go
Labels: code/bug

#1067 Fix `ModifiedCount` for updates with an empty replacement document
  integration/update_compat_test.go
  internal/handlers/common/update.go
Labels: code/bug

#1072 Fix data race in test
  integration/update_field_test.go
Labels: code/chore

#1073 Use `CODECOV_TOKEN` if available
  .github/workflows/go.yml
  .github/workflows/integration.yml
Labels: code/chore

#1084 Bump dependencies
  build/deps/markdownlint.Dockerfile
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: deps

#1085 Add integration tests for logical operators
  .github/workflows/integration.yml
  integration/helpers.go
  integration/query_logical_test.go
Labels: code/chore

#1063 Implement `MsgCollStats` for Tigris
  integration/commands_administration_test.go
  internal/handlers/pg/msg_listdatabases.go
  internal/handlers/tigris/fetch.go
  internal/handlers/tigris/msg_collstats.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_datasize.go
  internal/handlers/tigris/msg_dbstats.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/tigris.go
  internal/handlers/tigris/tigrisdb/query.go
  internal/handlers/tigris/tigrisdb/stats.go
  internal/handlers/tigris/tigrisdb/tigrisdb.go
  internal/handlers/tigris/tigrisdb/tigrisdb_test.go
Labels: code/chore, code/tigris

#1048 Implement `MsgCreate` for Tigris
  README.md
  docs/diff.md
  integration/create_test.go
  integration/setup/common.go
  internal/handlers/pg/msg_create.go
  internal/handlers/tigris/json_schema.go
  internal/handlers/tigris/msg_create.go
  internal/handlers/tigris/tigrisdb/collections.go
Labels: code/chore, code/tigris

#1004 Support `ordered` argument for `delete` command
  integration/delete_compat_test.go
  internal/handlers/common/error.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/tigris/msg_delete.go
Labels: code/feature

#1087 Handle `findAndModify` and `update` correctly when collection doesn't exist
  integration/findandmodify_test.go
  integration/update_test.go
  internal/handlers/pg/msg_findandmodify.go
Labels: code/bug
