Repository FerretDB/FerretDB, pull requests merged in 2022-12, with the labels that each got.

#1583 Add glossary section to documentation
  website/docs/reference/glossary.md
Labels: documentation

#1606 Replace `docker-compose` with `docker compose`
  CONTRIBUTING.md
  README.md
  Taskfile.yml
  cmd/envtool/envtool.go
  website/docs/quickstart_guide/docker.md
Labels: code/chore

#1602 Fix validation for documents with duplicate keys
  internal/types/document_validation.go
  internal/types/document_validation_test.go
Labels: code/bug

#1585 Fix greater and less operators on array value comparison
  integration/count_compat_test.go
  integration/query_array_compat_test.go
  integration/query_array_test.go
  integration/query_comparison_compat_test.go
  integration/query_projection_compat_test.go
  integration/query_projection_test.go
  integration/query_test.go
  integration/shareddata/composites.go
  integration/update_test.go
  internal/handlers/common/filter.go
  internal/types/array.go
  internal/types/array_test.go
Labels: code/bug

#1612 Add test certificates
  Taskfile.yml
  build/certs/Makefile
  build/certs/rootCA-key.pem
  build/certs/rootCA.pem
  build/certs/server.crt
  build/certs/server.key
  build/trivy-secret.yaml
Labels: code/chore

#1609 Bump deps
  .github/dependabot.yml
  .github/workflows/conform-pr.yml
  .github/workflows/docs.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  .github/workflows/packages.yml
  .github/workflows/security.yml
  Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps, trust

#1622 Infinity values are not allowed in documents
  internal/types/document_validation.go
  website/docs/diff.md
Labels: documentation

#1611 Fix parsing of `OP_MSG` packets with multiple sections
  internal/wire/op_msg.go
  internal/wire/op_msg_test.go
  internal/wire/op_query.go
  internal/wire/testdata/dollar_dot.hex
  internal/wire/validation.go
  internal/wire/wire_test.go
Labels: code/bug, trust

#1629 Bump Go and other deps
  Dockerfile
  build/deps/cockroach.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps, trust

#1625 Refactor integration tests setup functions
  integration/setup/common.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
Labels: code/chore

#1631 Fix `.deb`/`.rpm` package testing
  Taskfile.yml
  build/deps/centos7.Dockerfile
  build/deps/debian11.Dockerfile
  build/deps/ubi9.Dockerfile
  build/deps/ubuntu2204.Dockerfile
  docker-compose.yml
Labels: code/chore

#1633 Fix parsing of `OP_MSG` packets with multiple sections
  internal/wire/op_msg.go
  internal/wire/op_msg_test.go
  internal/wire/wire_test.go
Labels: code/bug, trust

#1597 Compare documents
  integration/query_comparison_compat_test.go
  integration/query_comparison_test.go
  integration/shareddata/composites.go
  integration/update_compat_test.go
  integration/update_test.go
  internal/handlers/common/filter.go
  internal/handlers/common/match.go
  internal/types/compare.go
  internal/types/compare_order.go
  internal/types/compare_test.go
Labels: code/enhancement

#1640 Bump `golang.org/x/net`
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#1635 Introduce schema for `pjson` format
  internal/handlers/pg/pjson/schema.go
  internal/handlers/pg/pjson/schema_test.go
Labels: code/chore

#1623 Use TLS for MongoDB in integration tests
  Taskfile.yml
  build/certs/Makefile
  build/certs/client-cert.pem
  build/certs/client-key.pem
  build/certs/client.pem
  build/certs/server-cert.pem
  build/certs/server-key.pem
  build/certs/server.crt
  build/certs/server.key
  build/certs/server.pem
  build/mongod.conf
  docker-compose.yml
  ferretdb/ferretdb.go
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/setup/common.go
  integration/setup/common_unix.go
  integration/setup/common_windows.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/bson/document.go
  internal/handlers/pg/msg_getparameter.go
Labels: code/chore

#1634 Fix comparison with unset fields
  integration/query_compat_test.go
  integration/query_test.go
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
  integration/update_field_compat_test.go
  internal/handlers/common/filter.go
  internal/handlers/common/sort.go
  internal/handlers/common/update.go
  internal/types/compare_test.go
Labels: code/bug

#1644 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#1651 Bump Tigris deps
  build/deps/tigris.Dockerfile
  cmd/envtool/envtool.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/handlers/tigris/msg_dbstats.go
  internal/handlers/tigris/msg_dropdatabase.go
  internal/handlers/tigris/msg_listdatabases.go
  internal/handlers/tigris/tigrisdb/databases.go
  internal/handlers/tigris/tigrisdb/tigrisdb_test.go
Labels: deps

#1646 Remove Incomparable
  integration/query_compat_test.go
  integration/update_field_compat_test.go
  internal/handlers/common/filter.go
  internal/handlers/common/sort.go
  internal/handlers/common/update.go
  internal/types/array_test.go
  internal/types/compare.go
  internal/types/compare_order.go
  internal/types/compare_order_test.go
  internal/types/compareresult_string.go
  internal/types/numberorderresult_string.go
Labels: code/chore

#1657 Simplify release procedure
  .github/RELEASE_CHECKLIST.md
  Taskfile.yml
  internal/util/version/generate.go
Labels: code/chore, trust

#1620 Modify `pjson` format
  CHANGELOG.md
  internal/handlers/pg/pgdb/delete.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/pg/pgdb/settings.go
  internal/handlers/pg/pgdb/update.go
  internal/handlers/pg/pjson/array.go
  internal/handlers/pg/pjson/array_test.go
  internal/handlers/pg/pjson/binary.go
  internal/handlers/pg/pjson/binary_test.go
  internal/handlers/pg/pjson/bool.go
  internal/handlers/pg/pjson/datetime.go
  internal/handlers/pg/pjson/datetime_test.go
  internal/handlers/pg/pjson/document.go
  internal/handlers/pg/pjson/document_test.go
  internal/handlers/pg/pjson/double.go
  internal/handlers/pg/pjson/double_test.go
  internal/handlers/pg/pjson/int32.go
  internal/handlers/pg/pjson/int64.go
  internal/handlers/pg/pjson/int64_test.go
  internal/handlers/pg/pjson/null.go
  internal/handlers/pg/pjson/object_id.go
  internal/handlers/pg/pjson/object_id_test.go
  internal/handlers/pg/pjson/pjson.go
  internal/handlers/pg/pjson/pjson_marshal_unmarshal_test.go
  internal/handlers/pg/pjson/pjson_test.go
  internal/handlers/pg/pjson/regex.go
  internal/handlers/pg/pjson/regex_test.go
  internal/handlers/pg/pjson/schema.go
  internal/handlers/pg/pjson/schema_test.go
  internal/handlers/pg/pjson/string.go
  internal/handlers/pg/pjson/timestamp.go
  internal/handlers/pg/pjson/timestamp_test.go
Labels: code/chore

#1652 Support $min field update operator
  integration/update_field_compat_test.go
  internal/handlers/common/update.go
  internal/types/document.go
  website/docs/reference/supported_commands.md
Labels: code/feature

#1664 Bump deps
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#1665 Remove leading space from `SELECT` queries
  internal/handlers/pg/pgdb/query.go
Labels: code/bug

#1647 Add section for comparison and logical query operators
  website/docs/basic_operations/update.md
  website/docs/reference/operators/_category_.json
  website/docs/reference/operators/array-operators.md
  website/docs/reference/operators/comparison-operators.md
  website/docs/reference/operators/logical-operators.md
Labels: documentation

#1670 Add `InTransactionRetry` helper
  internal/handlers/common/error.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/databases.go
  internal/handlers/pg/pgdb/insert.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/pg/pgdb/settings.go
  internal/handlers/pg/pgdb/transactions.go
Labels: code/chore

#1600 Add `mongo` test script example
  .gitignore
  Taskfile.yml
  build/deps/legacy-mongo-shell.Dockerfile
  build/legacy-mongo-shell/test.example.js
  build/legacy-mongo-shell/test.js
  build/mongosh/test.js
  docker-compose.yml
  integration/query_array_compat_test.go
  integration/shareddata/scalars.go
  internal/wire/op_query.go
Labels: code/chore

#1678 Use faster runner instances
  .github/workflows/docker.yml
  .github/workflows/integration.yml
Labels: code/chore, trust

#1675 Add documentation for element query operators
  website/docs/reference/operators/comparison-operators.md
  website/docs/reference/operators/element-operators.md
Labels: documentation

#1671 Update issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/chore.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: project

#1680 Bump Tigris version
  build/deps/tigris.Dockerfile
  cmd/envtool/envtool.go
Labels: deps

#1659 Move update tests to compat tests
  integration/helpers.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  integration/update_field_test.go
  integration/update_test.go
  internal/handlers/common/update.go
  internal/types/path.go
Labels: code/chore

#1687 Add TODO comments
  internal/bson/document.go
  internal/types/types.go
Labels: code/chore

#1649 Add `saslStart` stub
  Taskfile.yml
  build/mongod.conf
  docker-compose.yml
  ferretdb/ferretdb.go
  ferretdb/ferretdb_test.go
  integration/commands_administration_test.go
  integration/count_test.go
  integration/query_test.go
  integration/setup/common.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/handlers/common/find.go
  internal/handlers/common/msg_listcommands.go
  internal/handlers/common/msg_saslstart.go
  internal/handlers/dummy/msg_saslstart.go
  internal/handlers/handlers.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_getparameter.go
  internal/handlers/pg/msg_saslstart.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_getparameter.go
  internal/handlers/tigris/msg_saslstart.go
Labels: code/chore

#1650 Improve the way of storing data about collections
  CHANGELOG.md
  integration/create_compat_test.go
  integration/update_compat_test.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/database_metadata.go
  internal/handlers/pg/pgdb/database_metadata_test.go
  internal/handlers/pg/pgdb/databases.go
  internal/handlers/pg/pgdb/delete.go
  internal/handlers/pg/pgdb/indexes.go
  internal/handlers/pg/pgdb/insert.go
  internal/handlers/pg/pgdb/pgdb.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/pg/pgdb/settings.go
  internal/handlers/pg/pgdb/tables.go
  internal/handlers/pg/pgdb/transactions.go
  internal/handlers/pg/pgdb/update.go
Labels: code/chore

#1683 Implement `iterator.Interface` for `types.Document` and `types.Array`
  internal/handlers/pg/msg_getparameter.go
  internal/handlers/tigris/msg_getparameter.go
  internal/types/array.go
  internal/types/array_test.go
  internal/types/document_iterator.go
  internal/types/document_test.go
Labels: code/chore

#1692 Improve issue template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/chore.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: project

#1689 Add basic benchmark for query pushdowns
  integration/benchmarks_test.go
Labels: code/chore

#1713 Update building documentation
  .github/RELEASE_CHECKLIST.md
  .github/workflows/packages.yml
  CONTRIBUTING.md
  README.md
  Taskfile.yml
  build/deps/cockroach.Dockerfile
  build/nfpm.yaml
  build/version/debug_off.go
  build/version/debug_on.go
  build/version/generate.go
  build/version/mongodb.txt
  build/version/version.go
  build/version/version_test.go
  cmd/envtool/envtool.go
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  go.mod
  go.sum
  integration/commands_administration_test.go
  integration/go.mod
  integration/go.sum
  internal/clientconn/listener.go
  internal/handlers/common/msg_buildinfo.go
  internal/handlers/common/serverstatus.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/tigris/msg_explain.go
  internal/handlers/tigris/msg_getlog.go
  internal/util/logging/logging.go
  internal/util/state/metrics.go
  internal/util/state/metrics_test.go
  internal/util/telemetry/reporter.go
  internal/util/version/version.go
  tools/go.mod
  tools/go.sum
  website/docs/contributing.md
  website/docs/diff.md
  website/docs/reference/supported_commands.md
  website/docs/understanding_ferretdb.md
Labels: documentation, code/enhancement

#1695 Add documentation for array query operator
  website/docs/reference/operators/array-operators.md
Labels: documentation

#1716 Enable authentication in PostgreSQL
  README.md
  Taskfile.yml
  cmd/envtool/envtool.go
  cmd/envtool/ports.go
  cmd/ferretdb/main.go
  docker-compose.yml
  ferretdb/ferretdb_test.go
  integration/embedded_test.go
  integration/setup/common.go
  internal/handlers/common/msg_connectionstatus.go
  internal/util/testutil/pg.go
  website/docs/quickstart_guide/docker.md
Labels: code/chore

#1715 Fix Docker build
  .dockerignore
Labels: code/chore, trust

#1673 Support `ordered` argument for `insert` command
  integration/insert_compat_test.go
  integration/insert_run_command_compat_test.go
  internal/handlers/common/error_write.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/tigris/msg_insert.go
  website/docs/reference/supported_commands.md
Labels: code/feature

#1719 Test `ordered` argument validation
  integration/insert_run_command_compat_test.go
Labels: code/chore

#1723 Add stub for getting client-specific connection
  Taskfile.yml
  internal/handlers/pg/msg_collstats.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_datasize.go
  internal/handlers/pg/msg_dbstats.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/msg_dropdatabase.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_hello.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_ismaster.go
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/pg/msg_listdatabases.go
  internal/handlers/pg/msg_ping.go
  internal/handlers/pg/msg_serverstatus.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pg.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/registry/registry.go
  internal/handlers/tigris/tigrisdb/databases.go
Labels: code/chore

#1726 Add compat tests for `InsertOne` in addition to `InsertMany`
  integration/insert_compat_test.go
Labels: code/chore

#1700 Enable blog post section
  docker-compose.yml
  website/blog/2022-12-29-new-blog-section.md
  website/blog/_guide/template.md
  website/blog/authors.yml
  website/docusaurus.config.js
Labels: documentation

#1729 Run `govulncheck` on CI
  Taskfile.yml
  integration/Taskfile.yml
Labels: code/chore
