Repository FerretDB/FerretDB, pull requests merged in 2022-05, with the labels that each got.

#544 Add tests for `sort` and `find` parameters type
  integration/query_test.go
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/typecode.go
  internal/handlers/common/typecode_test.go
  internal/handlers/pg/msg_find.go
Labels: code/chore, trust

#556 Add missing `//nolint`
  internal/handlers/common/typecode_test.go
Labels: code/chore

#534 Set the handler to use via a command-line flag and remove debug handlers from interface
  cmd/envtool/main.go
  cmd/ferretdb/main.go
  integration/setup.go
  internal/clientconn/conn.go
  internal/clientconn/conn_metrics.go
  internal/clientconn/listener.go
  internal/clientconn/listener_metrics.go
  internal/handlers/common/commands.go
  internal/handlers/common/handler.go
  internal/handlers/common/msg_commands.go
  internal/handlers/dummy/dummy.go
  internal/handlers/dummy/dummy_test.go
  internal/handlers/pg/handler.go
  internal/handlers/proxy/proxy.go
Labels: code/chore

#550 Add `altMessage` to `AssertEqualError`
  integration/helpers.go
  integration/query_test.go
  internal/handlers/pg/msg_find.go
Labels: code/chore, trust

#559 Add documentation for values comparision
  integration/query_projection_test.go
  integration/query_test.go
  integration/shareddata/bignumbers.go
  integration/shareddata/composites.go
  internal/handlers/common/match.go
  internal/types/compare.go
  internal/util/testutil/equal.go
  internal/util/testutil/equal_test.go
Labels: code/chore

#561 Add `debug` and `panic` msg handlers to `Command` map
  internal/clientconn/conn.go
  internal/handlers/common/commands.go
  internal/handlers/common/msg_commands.go
  internal/handlers/dummy/dummy_test.go
Labels: code/chore

#566 Add conform CI workflow, improve docs
  .github/workflows/conform-pr.yml
  CONTRIBUTING.md
  README.md
Labels: documentation

#574 Update CONTRIBUTING.md with typo fix and a tiny correction
  CONTRIBUTING.md
Labels: documentation

#575 Add note about forks
  .github/PROCESS.md
Labels: documentation

#577 Use `float64(x)` for `ok` everywhere
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/query_test.go
Labels: code/chore

#578 Improve `AssertEqualAltError` documentation
  integration/helpers.go
Labels: code/chore

#518 Support `$slice` projection query operator
  integration/query_projection_test.go
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/projection.go
Labels: code/feature

#579 Remove `types.MustNewDocument` in some places
  integration/helpers.go
  internal/bson/array_test.go
  internal/fjson/array_test.go
  internal/fjson/document.go
  internal/handlers/pg/msg_dropdatabase.go
  internal/handlers/pg/msg_getcmdlineopts.go
  internal/handlers/pg/msg_hostinfo.go
  internal/util/testutil/path_test.go
  internal/util/version/version.go
  internal/wire/op_msg.go
  internal/wire/op_msg_test.go
  internal/wire/op_query_test.go
  internal/wire/op_reply_test.go
Labels: code/chore

#583 Remove `MustConvertDocument`
  internal/bson/bson.go
  internal/types/document.go
  internal/wire/op_query.go
  internal/wire/op_reply.go
Labels: code/chore

#580 Enable `staticcheck`
  .golangci-required.yml
  .golangci.yml
  Taskfile.yml
  internal/handlers/pg/msg_hostinfo.go
  tools/go.mod
  tools/go.sum
  tools/old.go
  tools/tools.go
Labels: code/chore

#584 Enable `gosimple`
  .golangci-required.yml
  cmd/envtool/main.go
  internal/handlers/common/filter.go
  internal/handlers/common/projection.go
Labels: code/chore

#586 Change the way linters work
  .golangci-new.yml
  .golangci-required.yml
  .golangci.yml
  Taskfile.yml
  internal/bson/bson.go
  internal/bson/document_test.go
  internal/fjson/document_test.go
  internal/handlers/pg/handler.go
Labels: code/chore

#573 Support querying documents
  integration/query_comparison_test.go
  integration/query_logical_test.go
  integration/query_test.go
Labels: code/enhancement, trust

#535 Support `getParameter`'s parameters
  integration/commands_administration_test.go
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/pg/msg_getparameter.go
Labels: code/enhancement

#595 Merge `BigNumbersData` into `Scalars`
  integration/basic_test.go
  integration/query_bitwise_test.go
  integration/query_comparison_test.go
  integration/query_element_test.go
  integration/query_logical_test.go
  integration/query_test.go
  integration/shareddata/bignumbers.go
  integration/shareddata/scalars.go
Labels: code/chore

#597 Set `GOLANGCI_LINT_CACHE`
  .github/workflows/docker.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
Labels: code/chore

#598 Increase `golangci-lint` timeout
  .golangci-new.yml
  .golangci.yml
Labels: code/chore

#588 Support `$regex` evaluation query operator
  integration/query_comparison_test.go
  integration/query_evaluation_test.go
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/filter.go
  internal/types/regex.go
Labels: code/feature, trust

#604 Bump deps
  .github/dependabot.yml
  .github/workflows/go.yml
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#603 Add stubs to make VSCode plugin work
  internal/handlers/pg/msg_connectionstatus.go
  internal/handlers/pg/msg_listdatabases.go
Labels: code/enhancement

#613 Improve negative zero handling
  integration/basic_test.go
  integration/query_array_test.go
  integration/query_element_test.go
  integration/query_projection_test.go
  integration/shareddata/scalars.go
  internal/bson/double_test.go
  internal/fjson/double.go
  internal/fjson/double_test.go
  internal/util/testutil/equal.go
  internal/util/testutil/equal_test.go
Labels: code/bug

#616 Better `-0` handling in tests
  internal/bson/bson_test.go
  internal/fjson/fjson_test.go
Labels: code/chore

#548 Support `findAndModify`
  integration/findandmodify_test.go
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/params.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
Labels: code/feature, trust

#596 Support `$inc` field `update` operator
  integration/helpers.go
  integration/update_test.go
  internal/handlers/common/error.go
  internal/handlers/common/params.go
  internal/handlers/common/update.go
Labels: code/feature, trust

#646 Bump gopkg.in/yaml.v3
  .golangci.yml
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: deps

#635 Make `Path` type
  internal/handlers/common/filter.go
  internal/handlers/common/projection.go
  internal/types/array.go
  internal/types/document.go
  internal/types/path.go
  internal/types/path_test.go
  internal/types/types.go
  internal/util/testutil/path.go
  internal/util/testutil/path_test.go
Labels: code/chore, trust

#652 Skip test on all ARM64 OSes
  integration/query_evaluation_test.go
Labels: code/chore

#650 Add more visibility for the router/proxy error log levels
  internal/clientconn/conn.go
Labels: code/chore, trust
