Repository FerretDB/FerretDB, pull requests merged in 2022-10, with the labels that each got.

#1200 Run linters on integration tests folder
  Taskfile.yml
  integration/.golangci.yml
  integration/Taskfile.yml
  integration/findandmodify_compat_test.go
  integration/setup/common.go
  integration/setup/setup.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/tigris/msg_datasize.go
  internal/handlers/tigris/msg_dbstats.go
Labels: code/chore

#1204 Use codecov upload token
  .github/workflows/go.yml
  .github/workflows/integration.yml
Labels: code/chore

#1142 Add security scan
  .github/workflows/go.yml
  .github/workflows/security.yml
  .gitignore
  Taskfile.yml
  build/.trivyignore
  build/deps/trivy.Dockerfile
  docker-compose.yml
  tools/go.mod
  tools/go.sum
Labels: code/chore

#1005 `tjson`: Support `null`
  integration/commands_administration_test.go
  integration/query_logical_test.go
  integration/setup/setup_compat.go
  integration/shareddata/composites.go
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
  integration/update_field_compat_test.go
  internal/tjson/document.go
  internal/tjson/document_test.go
  internal/tjson/null.go
  internal/tjson/schema.go
  internal/tjson/tjson.go
  internal/types/path.go
Labels: code/feature

#1212 Use single transaction per `msg_update` request
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_update.go
Labels: code/chore

#1211 Use Go 1.19.2
  Dockerfile
Labels: deps

#1194 Documentation for contributors
  website/docs/contributing.md
Labels: documentation

#1218 Fix running `pg` and `tigris` tests in parallel
  integration/create_test.go
  integration/findandmodify_compat_test.go
  integration/setup/common.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/shareddata_test.go
  integration/update_field_compat_test.go
  internal/util/testutil/db.go
Labels: code/chore

#1230 Bump deps
  build/deps/mongo6.Dockerfile
  build/deps/textlint/Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  website/Dockerfile
Labels: deps

#1220 Improve `task env-data`
  .github/PROCESS.md
  Dockerfile
  integration/Taskfile.yml
  integration/commands_administration_test.go
  integration/setup/setup_compat.go
  integration/shareddata_test.go
Labels: code/chore

#1207 Add simple query pushdown for PostgreSQL
  integration/query_test.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_update.go
Labels: code/feature

#1237 Use single transaction for `listDatabases` command
  internal/handlers/pg/msg_listdatabases.go
Labels: code/chore

#1208 Add UUID to log messages
  .gitignore
  Taskfile.yml
  cmd/envtool/main.go
  cmd/ferretdb/main.go
  cmd/ferretdb/main_test.go
  cmd/ferretdb/main_tigris.go
  cmd/fuzztool/fuzztool.go
  ferretdb/ferretdb.go
  go.mod
  integration/setup/common.go
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/tigris/msg_getlog.go
  internal/util/logging/buffer.go
  internal/util/logging/buffer_test.go
  internal/util/logging/logging.go
  internal/util/state/state.go
  internal/util/state/state_test.go
  internal/util/version/generate.go
Labels: code/enhancement

#1238 Add update operators data document fields order test
  integration/update_field_test.go
Labels: code/enhancement

#1245 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#1240 Add UUID to Prometheus metrics if requested
  .golangci.yml
  cmd/envtool/main.go
  cmd/ferretdb/main.go
  integration/Taskfile.yml
  integration/go.mod
  integration/setup/common.go
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/util/debug/debug.go
  internal/util/state/metrics.go
  internal/util/state/metrics_test.go
  internal/util/state/provider.go
  internal/util/state/provider_test.go
Labels: code/enhancement

#1249 Update internal process docs
  .github/PROCESS.md
  Taskfile.yml
Labels: project

#1255 Fix flag name
  cmd/ferretdb/main.go
Labels: code/chore, trust

#1256 Fix CLI flags for Tigris
  cmd/ferretdb/main.go
  cmd/ferretdb/main_tigris.go
  internal/handlers/pg/msg_explain.go
Labels: code/chore

#1258 Remove forked `golangci-lint`
  .golangci-new.yml
  tools/go.mod
  tools/go.sum
Labels: deps

#1254 Cleanup types/fjson package
  internal/types/fjson/array.go
  internal/types/fjson/array_test.go
  internal/types/fjson/binary.go
  internal/types/fjson/binary_test.go
  internal/types/fjson/bool.go
  internal/types/fjson/bool_test.go
  internal/types/fjson/datetime.go
  internal/types/fjson/datetime_test.go
  internal/types/fjson/document.go
  internal/types/fjson/document_test.go
  internal/types/fjson/double.go
  internal/types/fjson/double_test.go
  internal/types/fjson/fjson.go
  internal/types/fjson/fjson_test.go
  internal/types/fjson/int32.go
  internal/types/fjson/int32_test.go
  internal/types/fjson/int64.go
  internal/types/fjson/int64_test.go
  internal/types/fjson/null.go
  internal/types/fjson/object_id.go
  internal/types/fjson/object_id_test.go
  internal/types/fjson/regex.go
  internal/types/fjson/regex_test.go
  internal/types/fjson/string.go
  internal/types/fjson/string_test.go
  internal/types/fjson/timestamp.go
  internal/types/fjson/timestamp_test.go
Labels: code/chore

#1264 Minor handlers refactoring
  internal/handlers/pg/msg_collstats.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_createindexes.go
  internal/handlers/pg/msg_datasize.go
  internal/handlers/pg/msg_dbstats.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/msg_dropdatabase.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/pg/msg_getparameter.go
  internal/handlers/pg/msg_hello.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_ismaster.go
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/pg/msg_listdatabases.go
  internal/handlers/pg/msg_ping.go
  internal/handlers/pg/msg_serverstatus.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pg.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_create.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_update.go
Labels: code/chore

#1246 Add simplest validation to check data documents
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/insert.go
  internal/handlers/pg/pgdb/update.go
  internal/types/document_validation.go
  internal/types/document_validation_test.go
  website/docs/diff.md
Labels: code/enhancement

#1231 Add “metrics” section to `serverStatus` response
  .golangci.yml
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  go.mod
  integration/.golangci.yml
  integration/commands_administration_test.go
  integration/setup/common.go
  internal/clientconn/conn.go
  internal/clientconn/conn_metrics.go
  internal/clientconn/connmetrics/conn_metrics.go
  internal/clientconn/connmetrics/listener_metrics.go
  internal/clientconn/listener.go
  internal/handlers/common/serverstatus.go
  internal/handlers/pg/msg_serverstatus.go
  internal/handlers/pg/pg.go
  internal/handlers/registry/registry.go
  internal/handlers/tigris/msg_serverstatus.go
  internal/handlers/tigris/tigris.go
Labels: code/enhancement

#1274 Skip `pjson` fuzzing of invalid documents for now
  internal/handlers/pg/pjson/pjson.go
  internal/handlers/pg/pjson/pjson_test.go
Labels: code/chore

#1232 Add "CRUD operations" and "Understanding FerretDB" sections
  website/docs/Basic_operations/_category_.json
  website/docs/Basic_operations/create.md
  website/docs/Basic_operations/delete.md
  website/docs/Basic_operations/index.md
  website/docs/Basic_operations/read.md
  website/docs/Basic_operations/update.md
  website/docs/contributing.md
  website/docs/diff.md
  website/docs/understanding_ferretdb.md
Labels: documentation

#1247 Add schema-related test cases to `tjson` package
  internal/tjson/binary_test.go
  internal/tjson/bool_test.go
  internal/tjson/datetime_test.go
  internal/tjson/document_test.go
  internal/tjson/double_test.go
  internal/tjson/int32_test.go
  internal/tjson/int64_test.go
  internal/tjson/object_id_test.go
  internal/tjson/regex_test.go
  internal/tjson/schema.go
  internal/tjson/string_test.go
  internal/tjson/timestamp_test.go
  internal/tjson/tjson_test.go
Labels: code/chore

#1275 Bump deps
  README.md
  build/deps/postgres.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  website/docs/quickstart_guide/docker.md
Labels: deps

#1267 Add documentation for the `.deb` package usage
  website/docs/quickstart_guide/debian.md
Labels: documentation

#1268 Fix documentation for linking PRs and issues
  .github/PROCESS.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: project

#1260 Run tests on CockroachDB
  Taskfile.yml
  build/deps/cockroach.Dockerfile
  docker-compose.yml
  integration/setup/common.go
Labels: code/feature

#1281 Add experimental mergify configuration
  .github/mergify.yml
Labels: code/chore

#1288 Remove implicit mergify rules
  .github/mergify.yml
Labels: code/chore

#1239 Migrate to a newer Tigris version and fix relevant tests
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  integration/update_field_compat_test.go
  internal/tjson/tjson.go
  website/docs/diff.md
Labels: code/chore

#1265 Add ability to subscribe to state changes
  Taskfile.yml
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/common.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/handlers/pg/msg_serverstatus.go
  internal/handlers/pg/pg.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/registry/registry.go
  internal/handlers/registry/tigris.go
  internal/handlers/tigris/msg_serverstatus.go
  internal/handlers/tigris/tigris.go
  internal/handlers/tigris/tigrisdb/tigrisdb_test.go
  internal/util/state/metrics.go
  internal/util/state/metrics_test.go
  internal/util/state/provider.go
  internal/util/state/provider_test.go
  internal/util/state/state.go
Labels: code/chore

#1290 Call data document validation when insert or update documents in Tigris
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/tigrisdb/insert.go
  internal/handlers/tigris/tigrisdb/update.go
Labels: code/enhancement

#1277 Add support for empty command documents
  integration/findandmodify_compat_test.go
  integration/update_field_compat_test.go
  integration/update_field_test.go
  integration/update_test.go
Labels: code/enhancement

#1291 Move tjson into internal/handlers/tigris/tjson
  .golangci.yml
  CONTRIBUTING.md
  Taskfile.yml
  build/.trivyignore
  internal/handlers/tigris/json_schema.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/tigrisdb/insert.go
  internal/handlers/tigris/tigrisdb/query.go
  internal/handlers/tigris/tigrisdb/update.go
  internal/handlers/tigris/tjson/binary.go
  internal/handlers/tigris/tjson/binary_test.go
  internal/handlers/tigris/tjson/bool.go
  internal/handlers/tigris/tjson/bool_test.go
  internal/handlers/tigris/tjson/datetime.go
  internal/handlers/tigris/tjson/datetime_test.go
  internal/handlers/tigris/tjson/document.go
  internal/handlers/tigris/tjson/document_test.go
  internal/handlers/tigris/tjson/double.go
  internal/handlers/tigris/tjson/double_test.go
  internal/handlers/tigris/tjson/int32.go
  internal/handlers/tigris/tjson/int32_test.go
  internal/handlers/tigris/tjson/int64.go
  internal/handlers/tigris/tjson/int64_test.go
  internal/handlers/tigris/tjson/null.go
  internal/handlers/tigris/tjson/object_id.go
  internal/handlers/tigris/tjson/object_id_test.go
  internal/handlers/tigris/tjson/regex.go
  internal/handlers/tigris/tjson/regex_test.go
  internal/handlers/tigris/tjson/schema.go
  internal/handlers/tigris/tjson/schema_test.go
  internal/handlers/tigris/tjson/string.go
  internal/handlers/tigris/tjson/string_test.go
  internal/handlers/tigris/tjson/timestamp.go
  internal/handlers/tigris/tjson/timestamp_test.go
  internal/handlers/tigris/tjson/tjson.go
  internal/handlers/tigris/tjson/tjson_test.go
Labels: code/chore

#1297 Fix a typo in the `types` package docs
  internal/types/types.go
Labels: code/chore

#1278 Make `_id` field required in data documents
  go.mod
  internal/handlers/pg/pgdb/query_test.go
  internal/types/document_validation.go
  internal/types/document_validation_test.go
Labels: code/enhancement

#1292 Disallow usage of old context package
  .golangci.yml
Labels: code/chore

#1298 Disable Unix sockets in tests for now
  integration/setup/common_unix.go
Labels: code/chore

#1294 Fix `explain` command
  integration/commands_diagnostic_test.go
  internal/clientconn/conn.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/pgdb/query.go
Labels: code/bug

#1304 Fix `tjson` schema unmarshalling
  internal/handlers/tigris/tjson/schema.go
  internal/handlers/tigris/tjson/schema_test.go
  internal/handlers/tigris/tjson/tjson_test.go
Labels: code/bug

#1309 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#1303 Expand `debugError` stub
  internal/handlers/common/msg_debugerror.go
Labels: code/chore

#1299 Add basic telemetry
  .golangci.yml
  build/nfpm.yaml
  cmd/ferretdb/main.go
  internal/clientconn/connmetrics/listener_metrics.go
  internal/util/state/metrics.go
  internal/util/state/metrics_test.go
  internal/util/state/state.go
  internal/util/telemetry/telemetry.go
Labels: code/feature

#1302 Add comment about `diff` tests
  website/docs/diff.md
Labels: code/chore

#1296 Deprecate infinity values in data documents
  integration/query_comparison_test.go
  integration/query_element_test.go
  integration/query_evaluation_test.go
  integration/query_test.go
  integration/shareddata/scalars.go
  integration/update_field_test.go
  internal/types/document_validation.go
  internal/types/document_validation_test.go
Labels: code/feature

#1293 Explicitly disallow duplicate keys in data documents
  integration/update_field_compat_test.go
  integration/update_field_test.go
  internal/handlers/common/error.go
  internal/handlers/common/projection.go
  internal/handlers/common/serverstatus.go
  internal/handlers/common/update.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_getparameter.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/settings.go
  internal/handlers/pg/pjson/document.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_findandmodify.go
  internal/handlers/tigris/msg_getparameter.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/tjson/document.go
  internal/types/document.go
  internal/types/document_test.go
  internal/types/document_validation.go
  internal/types/path.go
  internal/types/types.go
  internal/util/testutil/path.go
  internal/util/version/version.go
Labels: code/feature

#1322 Refactor handler errors
  internal/handlers/common/error.go
  internal/handlers/common/error_command.go
  internal/handlers/common/error_write.go
Labels: code/chore

#1311 Add more ways to disable telemetry
  .golangci-new.yml
  .golangci.yml
  Taskfile.yml
  cmd/ferretdb/main.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/tigris/tigrisdb/tigrisdb_test.go
  internal/util/debug/debug.go
  internal/util/hex/hex.go
  internal/util/telemetry/reporter.go
  internal/util/telemetry/telemetry.go
  internal/util/telemetry/telemetry_test.go
  internal/util/testutil/testutil.go
Labels: code/enhancement

#1312 Allow dashes (`-`) in collection names
  integration/basic_test.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/databases.go
  website/docs/diff.md
Labels: code/enhancement

#1327 Collect command metrics in telemetry
  cmd/envtool/main.go
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/commands_administration_test.go
  integration/setup/common.go
  internal/clientconn/conn.go
  internal/clientconn/conninfo/conn_info.go
  internal/clientconn/connmetrics/conn_metrics.go
  internal/clientconn/connmetrics/conn_metrics_test.go
  internal/clientconn/connmetrics/listener_metrics.go
  internal/handlers/common/error.go
  internal/handlers/common/error_command.go
  internal/handlers/common/error_write.go
  internal/handlers/common/msg_aggregate.go
  internal/handlers/common/serverstatus.go
  internal/handlers/common/update.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/registry/registry.go
  internal/handlers/tigris/msg_delete.go
  internal/util/state/state.go
  internal/util/telemetry/reporter.go
Labels: code/enhancement

#1330 Include info about unimplemented arguments
  internal/clientconn/conn.go
  internal/clientconn/connmetrics/conn_metrics.go
  internal/handlers/common/error.go
  internal/handlers/common/error_command.go
  internal/handlers/common/error_write.go
  internal/handlers/common/msg_aggregate.go
  internal/handlers/common/serverstatus.go
  internal/handlers/common/unimplemented.go
  internal/handlers/common/update.go
  internal/util/telemetry/reporter.go
Labels: code/enhancement

#1337 Bump deps
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#1313 Deprecate dotted fields in data documents
  internal/types/document_validation.go
  internal/types/document_validation_test.go
  website/docs/diff.md
Labels: code/enhancement

#1339 A minor clarification about diff tests
  website/docs/diff.md
Labels: code/chore

#1340 Fix syntax highlighting
  .markdownlint.yml
  Taskfile.yml
  website/docs/understanding_ferretdb.md
Labels: documentation

#1318 Add stress tests for `SchemaStats`
  integration/commands_administration_test.go
  internal/handlers/pg/msg_listdatabases.go
Labels: code/chore

#1344 Do not compare error strings
  integration/commands_administration_test.go
  integration/go.mod
Labels: code/chore

#1316 Add stress tests for settings table and fix simple issues with transactions
  integration/create_test.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/pgdb/settings.go
  internal/handlers/tigris/tigrisdb/databases.go
  internal/handlers/tigris/tigrisdb/errors.go
Labels: code/chore
