Repository FerretDB/FerretDB, pull requests merged in 2022-04, with the labels that each got.

#309 Support `$eq` comparision operator
  internal/handlers/common/compare.go
  internal/handlers/common/filter.go
  internal/handlers/handler_test.go
Labels: code/feature, trust

#425 Fix pgdb helpers
  internal/handlers/handler_test.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/pool_test.go
  internal/util/testutil/pg.go
Labels: code/bug, trust

#427 Fix named loggers
  cmd/envtool/main.go
  cmd/ferretdb/main.go
  internal/clientconn/conn.go
  internal/clientconn/listener.go
Labels: code/chore, trust

#430 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps, code/chore, trust

#431 Update CHANGELOG
  CHANGELOG.md
Labels: documentation, project

#435 Ping database in some commands
  internal/handlers/pg/msg_hello.go
  internal/handlers/pg/msg_ismaster.go
  internal/handlers/pg/msg_ping.go
Labels: code/enhancement

#330 Support `$gt` comparision operator
  internal/handlers/common/compare.go
  internal/handlers/common/filter.go
  internal/handlers/handler_test.go
Labels: trust

#441 Integration tests improvements
  integration/basic_test.go
  integration/helpers.go
  integration/query_comparision_test.go
  integration/shareddata/composites.go
  integration/shareddata/scalars.go
  internal/handlers/handler_fuzz_test.go
Labels: code/chore

#443 Add test stub for bitwise operators
  integration/helpers.go
  integration/query_bitwise_test.go
Labels: code/chore

#444 Add tests for collections `create` and `drop`
  integration/commands_administration_test.go
  internal/handlers/handler_test.go
Labels: code/chore

#448 Add tests for more diagnostic commands
  go.mod
  integration/commands_diagnostic_test.go
  integration/helpers.go
  internal/handlers/handler_test.go
  internal/handlers/pg/msg_hostinfo.go
Labels: code/chore

#445 Transfer existing comparison tests
  integration/query_comparision_test.go
  integration/shareddata/composites.go
  internal/handlers/handler_test.go
Labels: code/chore

#450 Move `getParameter` tests
  integration/basic_test.go
  integration/commands_administration_test.go
  integration/query_array_test.go
  integration/query_bitwise_test.go
  internal/handlers/handler_test.go
  internal/handlers/pg/msg_getparameter.go
Labels: code/chore

#426 Improve `envtool` diagnostics
  Taskfile.yml
  cmd/envtool/main.go
  integration/query_bitwise_test.go
  internal/util/version/version.go
Labels: code/chore, trust

#451 Fix Postgres port check for `envtool`
  cmd/envtool/main.go
Labels: code/chore

#458 Add tests for `null` values
  integration/query_comparision_test.go
  internal/handlers/common/filter.go
Labels: code/chore, trust

#463 Update tests for the latest mongo-driver
  go.mod
  go.sum
  integration/basic_test.go
  integration/commands_administration_test.go
  integration/go.mod
  integration/go.sum
  integration/helpers.go
  integration/query_array_test.go
Labels: code/chore

#467 Rearrange tests
  integration/helpers.go
  integration/query_comparision_test.go
  integration/shareddata/scalars.go
  internal/handlers/common/compare.go
  internal/handlers/common/filter.go
  internal/handlers/handler_test.go
Labels: code/chore

#468 Do not invoke Dance tests
  .github/workflows/docker.yml
  Makefile
  internal/handlers/pg/pgdb/pool.go
Labels: code/chore

#469 Minor unification of tests style
  integration/basic_test.go
  integration/query_array_test.go
  integration/query_bitwise_test.go
  integration/query_comparision_test.go
Labels: code/chore

#474 Add helpers that generate ObjectID
  internal/types/object_id.go
  internal/types/object_id_test.go
  internal/types/types.go
  internal/util/must/must.go
Labels: code/chore

#475 Add deep copy helpers
  internal/types/array.go
  internal/types/array_test.go
  internal/types/document.go
  internal/types/document_test.go
  internal/types/object_id_test.go
  internal/types/types.go
  internal/types/types_test.go
Labels: code/chore

#476 Ensure that `_id` fields are always the first
  internal/types/document.go
  internal/types/document_test.go
Labels: code/enhancement

#477 Allow the usage of proxy/diff mode in tests
  integration/setup.go
Labels: code/chore

#473 Add basic `upsert` support
  integration/update_test.go
  internal/handlers/common/update.go
  internal/handlers/pg/msg_update.go
Labels: code/feature

#480 Improve contributing guidelines
  .github/PROCESS.md
  .github/RELEASE_CHECKLIST.md
  .github/workflows/go.yml
  .markdownlint.yaml
  CONTRIBUTING.md
  Taskfile.yml
Labels: documentation

#453 Add `$type` operator
  integration/query_element_test.go
  internal/handlers/common/filter.go
  internal/handlers/common/params.go
  internal/handlers/common/typecode.go
  internal/handlers/common/typecode_string.go
Labels: code/feature, trust

#471 Composite data type find handling
  integration/query_comparision_test.go
  integration/shareddata/composites.go
  internal/handlers/common/compare.go
  internal/handlers/common/filter.go
Labels: code/chore

#482 Fix failing tests
  integration/query_element_test.go
  integration/update_test.go
  internal/handlers/common/filter.go
Labels: code/chore, trust

#484 Rename `q` to `filter` in tests
  integration/query_element_test.go
  internal/util/version/version.go
Labels: code/chore

#440 Support `$mod` evaluation query operator
  integration/query_evalution_test.go
  internal/handlers/common/filter.go
Labels: code/feature

#465 Support logical operators
  integration/query_logical_test.go
  internal/handlers/common/filter.go
Labels: code/feature, trust

#485 Supress linter warning
  internal/handlers/common/params.go
  internal/handlers/pg/msg_update.go
Labels: code/chore

#494 Skip one test for now
  integration/query_evalution_test.go
Labels: code/chore

#483 Support querying with dot notation for documents
  integration/query_comparision_test.go
  internal/handlers/common/filter.go
Labels: code/feature

#495 Bump MongoDB version
  docker-compose.yml
Labels: code/chore

#464 Add support for `$ne` operator
  integration/query_comparision_test.go
  internal/handlers/common/filter.go
Labels: code/feature

#498 Use `goimports` to group imports on `task fmt`
  Taskfile.yml
  tools/tools.go
Labels: code/chore

#466 Fix large numbers comparision
  integration/basic_test.go
  integration/query_comparision_test.go
  integration/shareddata/bignumbers.go
  internal/handlers/common/compare.go
Labels: code/bug

#500 Mention force pushes
  .github/PROCESS.md
Labels: documentation, project

#502 Make default Docker arguments a bit more useful
  Dockerfile
Labels: code/chore

#504 Return better errors for unimplemented operations
  internal/handlers/common/update.go
  internal/handlers/pg/handler.go
Labels: code/enhancement

#499 Add support for `$in` operator
  integration/query_comparision_test.go
  internal/handlers/common/filter.go
  internal/handlers/handler_test.go
Labels: code/feature

#505 Export helpers that will be used in other package
  integration/basic_test.go
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/helpers.go
  integration/query_array_test.go
  integration/query_bitwise_test.go
  integration/query_comparision_test.go
  integration/query_element_test.go
  integration/query_evalution_test.go
  integration/query_logical_test.go
  integration/update_test.go
Labels: code/chore

#506 Correctly override `FUZZTIME` on CI
  .github/workflows/docker.yml
  .github/workflows/go.yml
Labels: code/chore, trust

#507 Pass context to PostgreSQL pool
  .codecov.yml
  cmd/envtool/main.go
  cmd/ferretdb/main.go
  cmd/fuzztool/fuzztool.go
  internal/handlers/common/error.go
  internal/handlers/handlers.go
  internal/handlers/pg/handler.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/pool_test.go
  internal/util/testutil/pg.go
Labels: code/chore

#514 Bump dependencies
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: code/chore

#515 Remove `Array.Subslice` method
  .codecov.yml
  integration/commands_administration_test.go
  internal/handlers/handler_test.go
  internal/handlers/pg/msg_listdatabases.go
  internal/handlers/pg/pgdb/pool.go
  internal/types/array.go
Labels: code/chore

#496 Update guidelines
  .github/PROCESS.md
  CONTRIBUTING.md
Labels: project

#524 Implement `nameOnly` for `listDatabases`
  internal/handlers/pg/msg_listdatabases.go
Labels: code/enhancement

#488 Fix bitwise operators
  integration/query_bitwise_test.go
  internal/handlers/common/error.go
  internal/handlers/common/filter.go
  internal/handlers/common/params.go
  internal/handlers/handler_test.go
  internal/types/binary.go
  internal/types/binary_test.go
Labels: code/bug, trust

#528 Document `task env-pull` target
  .github/workflows/go.yml
  CONTRIBUTING.md
  Taskfile.yml
Labels: documentation, project

#529 Remove `types.CString`
  internal/bson/bson.go
  internal/fjson/cstring.go
  internal/fjson/cstring_test.go
  internal/fjson/fjson.go
  internal/types/types.go
  internal/util/testutil/equal.go
Labels: code/chore

#530 Make test helpers harder to misuse
  internal/util/testutil/equal.go
Labels: code/chore

#531 Move existing comparision code to `types`
  internal/handlers/common/compare.go
  internal/handlers/common/error.go
  internal/handlers/common/filter.go
  internal/handlers/common/match.go
  internal/handlers/common/projection.go
  internal/handlers/common/sort.go
  internal/handlers/common/sorttype_string.go
  internal/types/compare.go
  internal/types/compareresult_string.go
Labels: code/chore

#521 Extract common interface for handlers
  internal/handlers/common/commands.go
  internal/handlers/common/error.go
  internal/handlers/common/handler.go
  internal/handlers/dummy/dummy.go
  internal/handlers/dummy/dummy_test.go
  internal/handlers/pg/cmd_query.go
  internal/handlers/pg/command.go
  internal/handlers/pg/handler.go
  internal/handlers/pg/msg_list_commands.go
  internal/handlers/pg/query_cmd.go
Labels: code/chore

#523 Move all handler test to integration tests
  integration/commands_administration_test.go
  integration/query_comparison_test.go
  integration/query_evaluation_test.go
  integration/query_logical_test.go
  integration/query_projection_test.go
  integration/query_test.go
  internal/handlers/common/projection.go
  internal/handlers/handler_fuzz_test.go
  internal/handlers/handler_test.go
Labels: code/chore, trust

#543 Delete old tests
  .github/workflows/integration.yml
  .gitignore
  Taskfile.yml
  internal/handlers/handler_fuzz_test.go
  internal/handlers/msg_delete_test.go
  internal/handlers/msg_update_test.go
Labels: code/chore

#509 Improve `hostInfo` command's `os` response
  integration/commands_diagnostic_test.go
  internal/handlers/common/parse_osrelease.go
  internal/handlers/common/parse_osrelease_test.go
  internal/handlers/pg/msg_hostinfo.go
Labels: code/enhancement
