Repository FerretDB/FerretDB, pull requests merged in 2022-09, with the labels that each got.

#1099 Bump deps
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: deps, trust

#1066 Require `limit` parameter in `delete` command
  integration/delete_test.go
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/params.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/tigris/msg_delete.go
Labels: code/bug, code/enhancement

#1104 Simplify/sync `delete` a bit
  integration/delete_compat_test.go
  integration/helpers.go
  internal/handlers/common/error.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/tigris/msg_create.go
  internal/handlers/tigris/msg_delete.go
Labels: code/chore

#1105 Enable `errorlint` for new code
  .golangci-new.yml
Labels: code/chore

#1108 Add missing TODO
  internal/handlers/tigris/msg_delete.go
Labels: code/chore

#1074 Migrate to MongoDB 6
  README.md
  build/deps/mongo5.Dockerfile
  build/deps/mongo6.Dockerfile
  build/nfpm.yaml
  docker-compose.yml
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/commands_replication_test.go
  integration/query_array_test.go
  integration/query_bitwise_test.go
  integration/query_evaluation_test.go
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/filter.go
  internal/handlers/common/params.go
  internal/handlers/pg/cmd_query.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/pg/msg_hello.go
  internal/handlers/pg/msg_ismaster.go
  internal/handlers/tigris/cmd_query.go
  internal/handlers/tigris/msg_create.go
  internal/handlers/tigris/msg_getlog.go
  internal/handlers/tigris/msg_hello.go
  internal/handlers/tigris/msg_ismaster.go
  internal/types/path.go
  internal/util/version/gen/mongodb.txt
  internal/util/version/version_test.go
Labels: code/chore

#1100 Add GitHub Pages with documentation
  .gitattributes
  .github/dependabot.yml
  .github/workflows/docs.yml
  .github/workflows/go.yml
  .github/workflows/packages.yml
  .gitignore
  .textlintignore
  CONTRIBUTING.md
  README.md
  Taskfile.yml
  build/deps/textlint/Dockerfile
  build/deps/textlint/package-lock.json
  build/deps/textlint/package.json
  docker-compose.yml
  website/.gitignore
  website/Dockerfile
  website/babel.config.js
  website/blog/2019-05-28-first-blog-post.md
  website/blog/2019-05-29-long-blog-post.md
  website/blog/2021-08-01-mdx-blog-post.mdx
  website/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  website/blog/2021-08-26-welcome/index.md
  website/blog/authors.yml
  website/docs/diff.md
  website/docs/intro.md
  website/docs/tutorial-basics/_category_.json
  website/docs/tutorial-basics/congratulations.md
  website/docs/tutorial-basics/create-a-blog-post.md
  website/docs/tutorial-basics/create-a-document.md
  website/docs/tutorial-basics/create-a-page.md
  website/docs/tutorial-basics/deploy-your-site.md
  website/docs/tutorial-basics/markdown-features.mdx
  website/docs/tutorial-extras/_category_.json
  website/docs/tutorial-extras/img/docsVersionDropdown.png
  website/docs/tutorial-extras/img/localeDropdown.png
  website/docs/tutorial-extras/manage-docs-versions.md
  website/docs/tutorial-extras/translate-your-site.md
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/sidebars.js
  website/src/components/HomepageFeatures/index.js
  website/src/components/HomepageFeatures/styles.module.css
  website/src/css/custom.css
  website/src/pages/index.js
  website/src/pages/index.module.css
  website/src/pages/markdown-page.md
  website/static/img/docusaurus.png
  website/static/img/favicon.ico
  website/static/img/logo.svg
  website/static/img/undraw_docusaurus_mountain.svg
  website/static/img/undraw_docusaurus_react.svg
  website/static/img/undraw_docusaurus_tree.svg
Labels: documentation

#1065 Implement `MsgFindAndModify` for Tigris
  integration/commands_administration_test.go
  integration/findandmodify_compat_test.go
  integration/findandmodify_test.go
  internal/handlers/common/msg_findandmodify.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_findandmodify.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/tigrisdb/query.go
Labels: code/feature, code/tigris

#1123 Switch to Go 1.19, bump dependencies
  CONTRIBUTING.md
  Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/types/regex.go
  tools/check.go
  tools/go.mod
  tools/go.sum
  tools/old.go
  tools/tools.go
  website/package-lock.json
  website/package.json
Labels: deps

#1107 Record incoming data for fuzzing
  cmd/ferretdb/main.go
  internal/clientconn/conn.go
  internal/clientconn/listener.go
Labels: code/chore, fuzz

#1114 Improve contribution guidelines and documentation website
  CONTRIBUTING.md
  website/blog/2019-05-28-first-blog-post.md
  website/blog/2019-05-29-long-blog-post.md
  website/blog/2021-08-01-mdx-blog-post.mdx
  website/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  website/blog/2021-08-26-welcome/index.md
  website/blog/authors.yml
  website/docs/diff.md
  website/docs/intro.md
  website/docs/tutorial-basics/_category_.json
  website/docs/tutorial-basics/congratulations.md
  website/docs/tutorial-basics/create-a-blog-post.md
  website/docs/tutorial-basics/create-a-document.md
  website/docs/tutorial-basics/create-a-page.md
  website/docs/tutorial-basics/debian.md
  website/docs/tutorial-basics/deploy-your-site.md
  website/docs/tutorial-basics/docker.md
  website/docs/tutorial-basics/macos.md
  website/docs/tutorial-basics/markdown-features.mdx
  website/docs/tutorial-basics/rpm.md
  website/docs/tutorial-basics/windows.md
  website/docs/tutorial-extras/_category_.json
  website/docs/tutorial-extras/img/docsVersionDropdown.png
  website/docs/tutorial-extras/img/localeDropdown.png
  website/docs/tutorial-extras/manage-docs-versions.md
  website/docs/tutorial-extras/translate-your-site.md
  website/docusaurus.config.js
  website/src/components/HomepageFeatures/index.js
  website/src/pages/index.js
  website/static/img/docusaurus.png
  website/static/img/favicon.ico
  website/static/img/logo.svg
Labels: documentation

#1127 Fix macOS spelling
  .github/CODEOWNERS
  website/docs/tutorial-basics/macos.md
Labels: documentation

#1126 Add transaction to `msg_drop_database`
  internal/handlers/pg/msg_dropdatabase.go
Labels: code/chore

#1130 Remove docusaurus references and update documentation
  website/docs/quickstart_guide/_category_.json
  website/docs/quickstart_guide/debian.md
  website/docs/quickstart_guide/docker.md
  website/docs/quickstart_guide/macos.md
  website/docs/quickstart_guide/rpm.md
  website/docs/quickstart_guide/windows.md
  website/docs/understanding_ferretdb.md
  website/docusaurus.config.js
  website/src/components/HomepageFeatures/index.js
  website/static/img/undraw_docusaurus_mountain.svg
  website/static/img/undraw_docusaurus_react.svg
  website/static/img/undraw_docusaurus_tree.svg
  website/static/img/undraw_ferretdb_open_source.svg
  website/static/img/undraw_ferretdb_server.svg
  website/static/img/undraw_ferretdb_usability.svg
Labels: documentation

#1129 Add transaction to `msg_drop`
  internal/handlers/pg/msg_drop.go
Labels: code/chore

#1135 Add transaction to `pg`'s `msg_listcollections`
  internal/handlers/pg/msg_listcollections.go
Labels: code/chore

#1139 Use fixed `-test-record` directory in Task targets
  .gitignore
  Taskfile.yml
Labels: code/chore, fuzz

#1141 Fix a typo in Readme
  README.md
Labels: documentation

#1136 Add missing `$k` to the schema when creating collection in Tigris
  integration/create_test.go
  internal/tjson/schema.go
Labels: code/bug

#1143 Use transaction in more `pgdb` functions
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/insert.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/pool_test.go
  internal/handlers/pg/pgdb/query_test.go
Labels: code/chore

#1158 Bump deps
  build/deps/debian11.Dockerfile
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: deps

#1144 Use transaction in more `pgdb` functions
  integration/object_id_delete_test.go
  internal/handlers/pg/pgdb/databases.go
  internal/handlers/pg/pgdb/pool_test.go
  internal/handlers/pg/pgdb/query_test.go
Labels: code/chore

#1152 Refactor `msg_delete` handlers
  internal/handlers/pg/msg_delete.go
  internal/handlers/tigris/msg_delete.go
Labels: code/chore

#1146 Improve contributing guidelines
  CONTRIBUTING.md
  Taskfile.yml
Labels: project

#1153 Update process documentation
  .github/PROCESS.md
  .github/workflows/conform-pr.yml
Labels: project

#1155 Update issues and PR templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/chore.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: project

#1165 Fix typo
  CONTRIBUTING.md
Labels: project

#1159 Migrate fuzztool to Kong
  .github/workflows/go.yml
  Taskfile.yml
  cmd/fuzztool/fuzztool.go
  go.mod
  go.sum
Labels: code/chore

#1124 Support `$max` field update operator
  integration/update_field_compat_test.go
  internal/handlers/common/update.go
  internal/types/compare.go
  internal/types/compare_order.go
Labels: code/feature

#1157 Use transactions in more `pgdb` functions
  cmd/envtool/main.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/databases.go
  internal/handlers/pg/pgdb/pgdb.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/pg/pgdb/pool_test.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
Labels: code/chore

#1171 Add `task` targets for offline work
  Taskfile.yml
Labels: code/chore

#1175 Bump deps
  build/deps/textlint/package-lock.json
  build/deps/textlint/package.json
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#1174 Update introduction documentation
  website/docs/intro.md
Labels: documentation

#1178 Add local search plugin
  website/package-lock.json
  website/package.json
Labels: documentation

#1168 Fuzz `wire` package with recorded data
  internal/wire/records_test.go
  internal/wire/wire_test.go
Labels: code/chore

#1181 DRY known differences documentation
  README.md
  website/docs/diff.md
  website/docs/intro.md
Labels: documentation

#1183 Documentation website tweaks
  README.md
  website/docs/intro.md
  website/docusaurus.config.js
  website/sidebars.js
  website/src/pages/index.js
Labels: documentation

#1185 Fix fluky test, refactor it
  integration/commands_administration_test.go
Labels: code/chore

#1187 Simplify / unify similar cases
  internal/handlers/common/filter.go
Labels: code/chore

#1167 Setup Tigris test cases with explicit schemas
  integration/create_test.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
  internal/tjson/schema.go
  internal/tjson/schema_test.go
Labels: code/chore

#1190 Migrate envtool to Kong
  cmd/envtool/main.go
Labels: code/chore

#1188 Replace `pgxtype.Querier` with `pgx.Tx`
  go.mod
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/schemas.go
  internal/handlers/pg/pgdb/settings.go
  internal/handlers/pg/pgdb/tables.go
Labels: code/chore

#1195 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#1193 Cleanup `pgdb` SQL statements
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/handlers/pg/pgdb/settings.go
Labels: code/chore

#1184 Migrate FerretDB to Kong
  Dockerfile
  README.md
  Taskfile.yml
  cmd/ferretdb/main.go
  cmd/ferretdb/main_test.go
  cmd/ferretdb/main_tigris.go
  website/docs/quickstart_guide/docker.md
Labels: code/feature

#1199 Make embedded FerretDB's address configurable
  ferretdb/ferretdb.go
  ferretdb/ferretdb_test.go
  integration/embedded_test.go
Labels: code/feature
