Repository FerretDB/FerretDB, pull requests merged in 2022-02, with the labels that each got.

#298 Add more metrics
  cmd/envtool/main.go
  cmd/ferretdb/main.go
  internal/clientconn/listener.go
  internal/clientconn/listener_metrics.go
  internal/handlers/handler.go
  internal/handlers/handler_metrics.go
  internal/util/ctxutil/ctxutil.go
Labels: code/feature

#300 Fix compilation with the latest go tip
  go.mod
  go.sum
Labels: code/chore

#299 Use `values` MongoDB database
  cmd/envtool/main.go
  docker-compose.yml
  internal/handlers/handler_test.go
Labels: code/chore

#302 Spend less time fuzzing pull requests
  .github/workflows/go.yml
Labels: code/chore

#304 Add detection action
  .github/workflows/docker.yml
  .github/workflows/go.yml
Labels: code/chore

#307 Remove extra allocation
  internal/wire/bits.go
Labels: code/chore

#308 Micro fixes: type assert order, strings.Split -> strings.Cut
  cmd/fuzztool/fuzztool.go
  internal/handlers/msg_getlog.go
Labels: code/chore

#310 Ignore some parameters
  internal/handlers/msg_listcollections.go
  internal/handlers/msg_listdatabases.go
Labels: code/bug

#315 Remove Docker volumes on `make env-down`
  Makefile
Labels: code/chore

#320 Update deps
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#324 Integrate with dance PRs
  .github/RELEASE_CHECKLIST.md
  .github/workflows/docker.yml
  .github/workflows/go.yml
  CONTRIBUTING.md
Labels: code/chore

#305 Add Docker badge
  README.md
Labels: documentation, trust
