Repository FerretDB/FerretDB, pull requests merged in 2022-01, with the labels that each got.

#225 Fix Docker workflow
  .github/workflows/docker.yml
Labels: code/chore

#212 Support projections
  internal/handlers/handler_test.go
  internal/handlers/jsonb1/msg_find_or_count.go
  internal/handlers/jsonb1/projection.go
  internal/handlers/sql/msg_find_or_count.go
Labels: code/feature

#234 Forbid short document keys like `$k`
  internal/bson/bson_test.go
  internal/types/document.go
  internal/types/document_test.go
  internal/wire/op_msg_test.go
  internal/wire/wire_test.go
Labels: code/bug

#232 Support `dbStats`
  internal/handlers/handler.go
  internal/handlers/handler_test.go
  internal/handlers/shared/msg_dbstats.go
  internal/pg/pool.go
Labels: code/feature

#236 Fix benchmarks
  Makefile
  internal/bson/bson_test.go
  internal/fjson/fjson_test.go
Labels: code/bug

#239 Move handler tests
  .golangci.yml
  internal/handlers/msg_delete_test.go
  internal/handlers/msg_update_test.go
  internal/handlers/sql/convert_test.go
  internal/handlers/sql/sql_test.go
Labels: code/bug

#240 Fix and enable fuzzing
  .github/workflows/go.yml
  internal/bson/array_test.go
  internal/bson/binary_test.go
  internal/bson/bson_test.go
  internal/bson/datetime_test.go
  internal/bson/document_test.go
  internal/bson/double_test.go
  internal/bson/int32_test.go
  internal/bson/int64_test.go
  internal/bson/objectid_test.go
  internal/bson/regex_test.go
  internal/bson/string_test.go
  internal/bson/timestamp_test.go
  internal/fjson/array_test.go
  internal/fjson/binary_test.go
  internal/fjson/bool_test.go
  internal/fjson/cstring_test.go
  internal/fjson/datetime_test.go
  internal/fjson/document_test.go
  internal/fjson/double_test.go
  internal/fjson/fjson_test.go
  internal/fjson/int32_test.go
  internal/fjson/int64_test.go
  internal/fjson/objectid_test.go
  internal/fjson/regex_test.go
  internal/fjson/timestamp_test.go
  internal/wire/op_msg.go
  internal/wire/op_msg_test.go
  internal/wire/testdata/msg_fuzz1.hex
  internal/wire/wire_test.go
Labels: code/bug

#243 Make `db.collection.stats()` & `.dataSize()` work from `mongosh`
  internal/handlers/handler.go
  internal/handlers/handler_test.go
  internal/handlers/shared/msg_collstats.go
  internal/pg/pool.go
Labels: code/bug

#218 Add `buildEnvironment` and `debug` to `buildInfo` command
  go.mod
  go.sum
  internal/handlers/handler_test.go
  internal/handlers/shared/msg_buildinfo.go
  internal/util/version/version.go
Labels: code/enhancement

#245 Use generics for CompositeType
  .golangci.yml
  Makefile
  internal/bson/bson.go
  internal/fjson/fjson.go
  internal/handlers/handler_test.go
  internal/types/array.go
  internal/types/document.go
  internal/types/path.go
  internal/types/types.go
  internal/util/testutil/path.go
Labels: code/chore

#231 Unexport `fjson` types
  internal/bson/array.go
  internal/bson/binary.go
  internal/bson/bool.go
  internal/bson/bson.go
  internal/bson/cstring.go
  internal/bson/datetime.go
  internal/bson/document.go
  internal/bson/double.go
  internal/bson/int32.go
  internal/bson/int64.go
  internal/bson/objectid.go
  internal/bson/regex.go
  internal/bson/string.go
  internal/bson/timestamp.go
  internal/fjson/array.go
  internal/fjson/array_test.go
  internal/fjson/binary.go
  internal/fjson/binary_test.go
  internal/fjson/bool.go
  internal/fjson/bool_test.go
  internal/fjson/cstring.go
  internal/fjson/cstring_test.go
  internal/fjson/datetime.go
  internal/fjson/datetime_test.go
  internal/fjson/document.go
  internal/fjson/document_test.go
  internal/fjson/double.go
  internal/fjson/double_test.go
  internal/fjson/fjson.go
  internal/fjson/fjson_test.go
  internal/fjson/int32.go
  internal/fjson/int32_test.go
  internal/fjson/int64.go
  internal/fjson/int64_test.go
  internal/fjson/objectid.go
  internal/fjson/objectid_test.go
  internal/fjson/regex.go
  internal/fjson/regex_test.go
  internal/fjson/string.go
  internal/fjson/string_test.go
  internal/fjson/timestamp.go
  internal/fjson/timestamp_test.go
Labels: code/chore

#262 Update documentation about `fjson` package
  .golangci.yml
  CONTRIBUTING.md
  internal/bson/bson.go
  internal/bson/document.go
  internal/clientconn/conn.go
  internal/fjson/fjson.go
  internal/handlers/handler_test.go
  internal/handlers/msg_buildinfo.go
  internal/handlers/msg_getcmdlineopts.go
  internal/handlers/msg_hello.go
  internal/handlers/query_cmd.go
  internal/types/array.go
  internal/types/binary.go
  internal/types/types.go
  internal/wire/op_msg.go
  internal/wire/op_query.go
  internal/wire/op_reply.go
  internal/wire/wire.go
Labels: documentation, code/chore

#264 Fix `make gen`
  Makefile
  tools/go.mod
  tools/go.sum
Labels: code/chore

#265 Use FerretDB/github-actions/linters
  .github/workflows/go.yml
Labels: code/chore

#266 Make PRs from forks work
  .github/workflows/go.yml
Labels: code/chore

#267 Add helper for checking for unimplemented fields
  internal/handlers/command.go
  internal/handlers/common/error.go
  internal/handlers/common/unimplemented.go
  internal/handlers/handler.go
  internal/handlers/jsonb1/msg_createindexes.go
  internal/handlers/jsonb1/msg_delete.go
  internal/handlers/jsonb1/msg_find_or_count.go
  internal/handlers/jsonb1/msg_insert.go
  internal/handlers/jsonb1/msg_update.go
  internal/handlers/jsonb1/where.go
  internal/handlers/msg_create.go
  internal/handlers/msg_datasize.go
  internal/handlers/msg_drop.go
  internal/handlers/msg_dropdatabase.go
  internal/handlers/msg_getlog.go
  internal/handlers/msg_getparameter.go
  internal/handlers/msg_listcollections.go
  internal/handlers/msg_listdatabases.go
  internal/handlers/query_cmd.go
  internal/handlers/sql/msg_createindexes.go
  internal/handlers/sql/msg_delete.go
  internal/handlers/sql/msg_find_or_count.go
  internal/handlers/sql/msg_insert.go
  internal/handlers/sql/msg_update.go
  internal/handlers/sql/where.go
  internal/types/document.go
Labels: code/enhancement

#279 Add `make fuzz-corpus` target
  .github/workflows/go.yml
  .gitignore
  Makefile
  docker-compose.yml
Labels: code/chore

#280 Unexport some `bson` types
  internal/bson/array.go
  internal/bson/array_test.go
  internal/bson/binary.go
  internal/bson/binary_test.go
  internal/bson/bool.go
  internal/bson/bool_test.go
  internal/bson/bson.go
  internal/bson/bson_test.go
  internal/bson/datetime.go
  internal/bson/datetime_test.go
  internal/bson/document.go
  internal/bson/double.go
  internal/bson/double_test.go
  internal/bson/int32.go
  internal/bson/int32_test.go
  internal/bson/int64.go
  internal/bson/int64_test.go
  internal/bson/objectid.go
  internal/bson/objectid_test.go
  internal/bson/regex.go
  internal/bson/regex_test.go
  internal/bson/string.go
  internal/bson/string_test.go
  internal/bson/timestamp.go
  internal/bson/timestamp_test.go
  internal/types/types.go
Labels: code/chore

#283 Catch concurrent schema/table creation
  internal/handlers/handler.go
  internal/handlers/handler_test.go
  internal/handlers/msg_dbstats.go
  internal/handlers/msg_listcollections.go
  internal/handlers/msg_listdatabases.go
  internal/pg/pool.go
  internal/pg/pool_test.go
  internal/util/testutil/testutil.go
Labels: code/bug

#286 Fix some typos and style
  internal/handlers/handler.go
  internal/pg/pool.go
Labels: code/chore

#288 Add Docker workflow stub
  .github/workflows/docker.yml
  Makefile
  internal/wire/op_msg.go
Labels: code/chore

#290 Split Docker Build and Push
  .github/workflows/docker-build.yml
  .github/workflows/docker-push.yml
Labels: code/chore

#289 Support `serverStatus`.
  cmd/ferretdb/main.go
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/handlers/handler.go
  internal/handlers/handler_test.go
  internal/handlers/msg_serverstatus.go
Labels: code/feature

#292 Securely build and push Docker images
  .github/workflows/docker-build.yml
  .github/workflows/docker-push.yml
  .github/workflows/docker.yml
  .github/workflows/go.yml
  .gitignore
  Dockerfile
  Makefile
  internal/util/version/generate.sh
  internal/util/version/version.go
Labels: code/chore

#294 Update golangci-lint
  .golangci.yml
  tools/go.mod
  tools/go.sum
Labels: code/chore, trust

#295 Make fuzztool less verbose
  cmd/fuzztool/fuzztool.go
Labels: trust
