Repository FerretDB/FerretDB, pull requests merged in 2022-06, with the labels that each got.

#675 Use `"` instead of `'` in all .yml files
  .github/workflows/docker.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  .golangci.yml
  .markdownlint.yml
  docker-compose.yml
Labels: code/chore

#671 Add empty Tigris handler
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/handlers/tigris/base.go
  internal/handlers/tigris/cmd_query.go
  internal/handlers/tigris/fetch.go
  internal/handlers/tigris/msg_buildinfo.go
  internal/handlers/tigris/msg_collstats.go
  internal/handlers/tigris/msg_connectionstatus.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_create.go
  internal/handlers/tigris/msg_createindexes.go
  internal/handlers/tigris/msg_datasize.go
  internal/handlers/tigris/msg_dbstats.go
  internal/handlers/tigris/msg_debugerror.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_drop.go
  internal/handlers/tigris/msg_dropdatabase.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_findandmodify.go
  internal/handlers/tigris/msg_getcmdlineopts.go
  internal/handlers/tigris/msg_getlog.go
  internal/handlers/tigris/msg_getparameter.go
  internal/handlers/tigris/msg_hello.go
  internal/handlers/tigris/msg_hostinfo.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_ismaster.go
  internal/handlers/tigris/msg_listcollections.go
  internal/handlers/tigris/msg_listcommands.go
  internal/handlers/tigris/msg_listdatabases.go
  internal/handlers/tigris/msg_ping.go
  internal/handlers/tigris/msg_serverstatus.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/msg_whatsmyuri.go
Labels: code/chore

#672 Enable `revive` linter
  .golangci-new.yml
  .golangci.yml
  internal/types/compare_order.go
  internal/types/comparetypeorderresult_string.go
  internal/util/version/version.go
Labels: code/chore

#644 Support `$setOnInsert` field update operator
  integration/update_test.go
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/update.go
  internal/handlers/pg/msg_update.go
Labels: code/feature

#688 Handle both `buildinfo` and `buildInfo` commands
  integration/basic_test.go
  internal/handlers/common/msg_listcommands.go
Labels: code/bug

#660 More tests for dot notation support
  integration/query_comparison_test.go
  integration/query_test.go
  internal/handlers/common/update.go
Labels: code/chore

#676 Array comparison substitution
  integration/query_comparison_test.go
  internal/handlers/common/filter.go
  internal/handlers/common/match.go
  internal/types/compare.go
Labels: code/enhancement

#662 Support `$currentDate` field update operator
  integration/helpers.go
  integration/update_test.go
  internal/handlers/common/update.go
  internal/types/timestamp.go
  internal/types/types.go
  internal/util/testutil/path.go
Labels: code/feature

#703 Fix build
  cmd/ferretdb/handler_tigris.go
Labels: code/chore, trust

#705 Fix a bug with proxy response logs
  internal/clientconn/conn.go
Labels: code/bug-regression

#712 Improve function comment
  internal/handlers/common/params.go
Labels: code/chore

#713 Use separate encodings for ObjectID and binary
  internal/bson/object_id.go
  internal/bson/object_id_test.go
  internal/fjson/object_id.go
  internal/fjson/object_id_test.go
  internal/tjson/object_id.go
  internal/tjson/schema.go
  internal/tjson/schema_test.go
  internal/tjson/tjson.go
  internal/tjson/tjson_test.go
Labels: code/chore

#717 Add workaround for Dependabot
  .github/dependabot.yml
  build/deps/README.md
  build/deps/markdownlint.Dockerfile
  build/deps/mongo.Dockerfile
  build/deps/postgres.Dockerfile
  docker-compose.yml
Labels: code/chore

#723 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps, trust

#718 Always install Go and skip test cache
  .github/workflows/conform-pr.yml
  .github/workflows/docker.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  Taskfile.yml
Labels: code/chore

#715 Better dummy handler errors
  internal/handlers/dummy/cmd_query.go
  internal/handlers/dummy/dummy.go
  internal/handlers/dummy/msg_collstats.go
  internal/handlers/dummy/msg_count.go
  internal/handlers/dummy/msg_create.go
  internal/handlers/dummy/msg_createindexes.go
  internal/handlers/dummy/msg_datasize.go
  internal/handlers/dummy/msg_dbstats.go
  internal/handlers/dummy/msg_delete.go
  internal/handlers/dummy/msg_drop.go
  internal/handlers/dummy/msg_dropdatabase.go
  internal/handlers/dummy/msg_find.go
  internal/handlers/dummy/msg_findandmodify.go
  internal/handlers/dummy/msg_getlog.go
  internal/handlers/dummy/msg_getparameter.go
  internal/handlers/dummy/msg_hello.go
  internal/handlers/dummy/msg_insert.go
  internal/handlers/dummy/msg_ismaster.go
  internal/handlers/dummy/msg_listcollections.go
  internal/handlers/dummy/msg_listdatabases.go
  internal/handlers/dummy/msg_ping.go
  internal/handlers/dummy/msg_serverstatus.go
  internal/handlers/dummy/msg_update.go
  internal/handlers/dummy/msg_whatsmyuri.go
Labels: code/chore

#725 Add `task run-proxy` command
  Taskfile.yml
Labels: code/chore

#710 Handle `find`, `count` and `delete` correctly when collection doesn't exist
  integration/delete_test.go
  integration/query_test.go
  internal/handlers/pg/fetch.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/pool_test.go
Labels: code/bug, code/bug-regression

#707 Support $elemMatch array query operator
  integration/query_array_test.go
  internal/handlers/common/filter.go
Labels: code/feature

#728 Add arrays with `NaN`, `double` and nested empty array to tests' shared data
  integration/query_array_test.go
  integration/query_comparison_test.go
  integration/query_element_test.go
  integration/query_logical_test.go
  integration/query_test.go
  integration/shareddata/composites.go
Labels: code/chore

#687 Make log level configurable
  cmd/ferretdb/main.go
  internal/util/logging/logging.go
Labels: code/enhancement

#743 Fix default values for flags
  cmd/ferretdb/main.go
Labels: code/bug

#746 Fix pull request template
  .github/pull_request_template.md
Labels: documentation, project

#704 Re-enable `TestStatisticsCommands` tests
  integration/commands_administration_test.go
  integration/setup.go
  internal/handlers/common/msg_buildinfo.go
  internal/handlers/pg/msg_collstats.go
  internal/handlers/pg/msg_datasize.go
  internal/handlers/pg/msg_dbstats.go
  internal/handlers/pg/msg_serverstatus.go
  internal/handlers/pg/pgdb/pool.go
  internal/util/testutil/path.go
Labels: code/chore

#701 `$currentDate` Timestamp fix `DateTime` seconds and milliseconds bug
  integration/helpers.go
  integration/update_test.go
  internal/types/timestamp.go
  internal/util/testutil/path.go
Labels: code/enhancement

#752 Fix `lint-golangci-lint` task for Windows systems
  .golangci.yml
Labels: code/chore

#755 Remove outdated comment
  .github/workflows/docker.yml
Labels: code/chore

#753 Skip `-race` flag on Windows
  Taskfile.yml
Labels: code/chore

#736 Fix embedded array query bug
  integration/query_array_test.go
  integration/query_comparison_test.go
  integration/query_element_test.go
  integration/query_logical_test.go
  integration/query_test.go
  integration/shareddata/composites.go
  internal/handlers/common/filter.go
  internal/types/compare.go
Labels: code/bug

#757 Fix fluky test
  integration/commands_administration_test.go
Labels: code/chore

#760 `tjson` improvements
  internal/fjson/object_id.go
  internal/tjson/object_id.go
  internal/tjson/tjson.go
  internal/tjson/tjson_test.go
Labels: code/chore

#762 Unify similar code in `pg` handler
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_update.go
Labels: code/chore

#761 Add Tigris environment
  .markdownlint.yml
  Taskfile.yml
  build/deps/tigris.Dockerfile
  build/deps/tigris_fdb.Dockerfile
  build/deps/tigris_typesense.Dockerfile
  docker-compose.yml
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: code/chore

#751 Implement `getFreeMonitoringStatus` stub
  integration/commands_freemonitoring_test.go
  internal/handlers/common/msg_getfreemonitoringstatus.go
  internal/handlers/common/msg_listcommands.go
  internal/handlers/dummy/msg_getfreemonitoringstatus.go
  internal/handlers/handlers.go
  internal/handlers/pg/msg_getfreemonitoringstatus.go
  internal/handlers/tigris/msg_getfreemonitoringstatus.go
Labels: code/feature

#759 Implement `setFreeMonitoring` stub
  integration/commands_freemonitoring_test.go
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/msg_listcommands.go
  internal/handlers/common/msg_setfreemonitoring.go
  internal/handlers/dummy/msg_setfreemonitoring.go
  internal/handlers/handlers.go
  internal/handlers/pg/msg_setfreemonitoring.go
  internal/handlers/tigris/msg_setfreemonitoring.go
Labels: code/feature

#690 Implement `tigris` handler
  .golangci.yml
  cmd/ferretdb/handler_tigris.go
  docker-compose.yml
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/handlers/tigris/cmd_query.go
  internal/handlers/tigris/fetch.go
  internal/handlers/tigris/msg_collstats.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_create.go
  internal/handlers/tigris/msg_createindexes.go
  internal/handlers/tigris/msg_datasize.go
  internal/handlers/tigris/msg_dbstats.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_drop.go
  internal/handlers/tigris/msg_dropdatabase.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_findandmodify.go
  internal/handlers/tigris/msg_getlog.go
  internal/handlers/tigris/msg_getparameter.go
  internal/handlers/tigris/msg_hello.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_ismaster.go
  internal/handlers/tigris/msg_listcollections.go
  internal/handlers/tigris/msg_listdatabases.go
  internal/handlers/tigris/msg_ping.go
  internal/handlers/tigris/msg_serverstatus.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/msg_whatsmyuri.go
  internal/handlers/tigris/tigris.go
Labels: code/feature, trust

#783 Update `conform-pr` action
  .github/workflows/conform-pr.yml
Labels: code/chore

#788 Drop `test_db`
  Taskfile.yml
  cmd/envtool/main.go
  docker-compose.yml
  integration/commands_administration_test.go
  internal/handlers/pg/pgdb/pool_test.go
Labels: code/chore

#756 Add `task init-clean` target
  .github/workflows/go.yml
  .github/workflows/integration.yml
  Taskfile.yml
Labels: code/chore

#789 Add `godoc` to tools
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: code/chore

#779 Update contributing docs and PR template according to our best practices
  .github/PROCESS.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE_TEAM.md
  .github/pull_request_template.md
Labels: documentation

#794 Tweak schedule of daily builds
  .github/workflows/docker.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
Labels: code/chore

#799 Do not import `pg` handler explicitly
  integration/go.mod
  integration/go.sum
  integration/setup.go
  internal/handlers/pg/msg_whatsmyuri.go
  internal/handlers/pg/pg.go
  internal/util/testutil/pg.go
Labels: code/chore

#804 Add TODO item
  internal/handlers/common/update.go
Labels: code/chore

#798 Fix embedded usage
  internal/util/version/gen/mongodb.txt
  internal/util/version/generate.go
  internal/util/version/version.go
  internal/util/version/version_test.go
Labels: code/bug

#810 Fix `task env-pull` target
  Taskfile.yml
Labels: code/chore

#795 Improve contributing documentation for Windows development
  CONTRIBUTING.md
Labels: code/chore

#815 Make it easier to trigger rebuilds
  .github/workflows/conform-pr.yml
  .github/workflows/docker.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
Labels: code/chore

#814 Use `github.head_ref` instead of `github.ref`
  .github/workflows/conform-pr.yml
Labels: code/chore
