Repository FerretDB/FerretDB, pull requests merged in 2022-07, with the labels that each got.

#817 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
Labels: deps

#778 Support all valid collection names
  cmd/envtool/main.go
  integration/basic_test.go
  integration/commands_administration_test.go
  internal/handlers/pg/fetch.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/msg_dropdatabase.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/pool_test.go
  internal/handlers/pg/pgdb/settings.go
  internal/util/testutil/pg.go
Labels: code/enhancement

#820 Install QEMU for building Docker images
  .github/workflows/docker.yml
Labels: code/chore, trust

#605 Use multi-stage docker build
  .dockerignore
  Dockerfile
  Taskfile.yml
Labels: code/chore, trust

#809 Unify `update` tests
  integration/update_array_test.go
  integration/update_bitwise_test.go
  integration/update_field_test.go
  integration/update_test.go
Labels: code/chore

#838 Export integration tests helpers
  integration/basic_test.go
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/commands_freemonitoring_test.go
  integration/commands_replication_test.go
  integration/delete_test.go
  integration/findandmodify_test.go
  integration/query_array_test.go
  integration/query_bitwise_test.go
  integration/query_comparison_test.go
  integration/query_element_test.go
  integration/query_evaluation_test.go
  integration/query_logical_test.go
  integration/query_projection_test.go
  integration/query_test.go
  integration/setup.go
  integration/shareddata_test.go
  integration/update_field_test.go
  integration/update_test.go
Labels: code/chore

#839 Remove old style of `+build` tags where possible
  cmd/ferretdb/main_test.go
  cmd/ferretdb/main_tigris.go
  cmd/ferretdb/main_unix.go
  internal/handlers/registry/tigris.go
  internal/util/version/generate.go
  tools/check.go
  tools/old.go
  tools/tools.go
Labels: code/chore

#840 Export fields
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/commands_freemonitoring_test.go
  integration/setup.go
  integration/shareddata_test.go
Labels: code/chore

#841 Update Tigris version
  Taskfile.yml
  build/deps/tigris.Dockerfile
  build/deps/tigris_fdb.Dockerfile
  build/deps/tigris_main.Dockerfile
  build/deps/tigris_typesense.Dockerfile
  docker-compose.yml
Labels: code/chore

#842 Create Tigris databases
  cmd/envtool/main.go
Labels: code/chore

#846 Test with the `main` version of Tigris too
  .github/workflows/integration.yml
  docker-compose.yml
Labels: code/chore, trust

#843 Update contributing documentation
  .github/PROCESS.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE_TEAM.md
  CONTRIBUTING.md
  Taskfile.yml
Labels: documentation

#854 Wait for Tigris to be fully up
  cmd/envtool/main.go
Labels: code/chore

#860 Fill MongoDB on `task env-data` too
  Taskfile.yml
Labels: code/chore

#855 Add CI job for short tests without environment
  .github/workflows/go.yml
Labels: code/chore

#865 Document that NUL (`\0`) strings is not supported
  README.md
Labels: documentation, code/chore

#833 pgdb: cover transactions with `inTransaction` function to simplify error handling
  go.mod
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/msg_dropdatabase.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/pool_test.go
  internal/handlers/pg/pgdb/settings.go
  internal/util/testutil/pg.go
Labels: code/bug

#868 Fix invalid variable names
  integration/embedded_test.go
  integration/tigris/embedded_test.go
Labels: code/chore

#869 Add `ferretdb_` prefix to our custom build tags
  Dockerfile
  Taskfile.yml
  cmd/ferretdb/main_test.go
  cmd/ferretdb/main_tigris.go
  internal/handlers/registry/tigris.go
  internal/util/version/version.go
Labels: code/chore, trust

#819 Support `gt` `lt` operator comparison for Array type
  integration/query_comparison_test.go
  internal/handlers/common/filter.go
  internal/handlers/common/projection.go
  internal/types/compare.go
  internal/types/compare_order.go
Labels: code/enhancement

#874 Add a few testing helpers
  integration/helpers.go
  internal/util/testutil/dump.go
  internal/util/testutil/equal.go
Labels: code/chore

#876 Add support for `no ci` label
  .github/workflows/conform-pr.yml
  .github/workflows/docker.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
Labels: code/chore

#880 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps, trust

#875 Extract two more helpers
  .golangci-new.yml
  .golangci.yml
  Taskfile.yml
  integration/setup.go
  internal/handlers/common/msg_hostinfo.go
  internal/util/testutil/db.go
  internal/util/testutil/pg.go
Labels: code/chore

#884 Cancel request's context when request processed
  internal/clientconn/conn.go
Labels: code/chore

#888 Disable logs during test setup
  integration/setup.go
  internal/clientconn/conn.go
  internal/handlers/pg/pgdb/pool.go
  internal/util/testutil/pg.go
Labels: code/chore

#889 Restart development containers faster
  Taskfile.yml
  cmd/envtool/main.go
Labels: code/chore

#887 Cover more logic in transactions
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/databases.go
  internal/handlers/pg/pgdb/insert.go
  internal/handlers/pg/pgdb/pgdb.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/pool_test.go
  internal/handlers/pg/pgdb/query_documents.go
  internal/handlers/pg/pgdb/schemas.go
  internal/handlers/pg/pgdb/settings.go
  internal/handlers/pg/pgdb/tables.go
  internal/util/testutil/pg.go
Labels: code/chore

#891 Fix edge cases in `drop` and `dropDatabase` handlers
  integration/commands_administration_test.go
  integration/setup.go
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/tigris/msg_insert.go
Labels: code/bug

#893 Stop tests on the first data race
  Taskfile.yml
Labels: code/chore

#894 Wait for `Tigris` backend to be ready
  Taskfile.yml
  cmd/envtool/main.go
Labels: code/chore

#895 Handle `42P07` PostgreSQL error to fix the tests
  internal/handlers/pg/pgdb/collections.go
Labels: code/chore

#739 Build .rpm and .deb packages
  .nfpm.yml
  Taskfile.yml
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: code/chore

#808 Optimize documents fetching / filtering
  go.mod
  internal/handlers/pg/fetch.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pg.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/pool_test.go
  internal/handlers/pg/pgdb/query_documents.go
  internal/handlers/pg/pgdb/query_documents_test.go
  internal/handlers/pg/pgdb/testutil_test.go
  internal/util/testutil/pg.go
Labels: code/enhancement

#901 Add setup for compatibility tests
  Taskfile.yml
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/commands_freemonitoring_test.go
  integration/setup.go
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
  integration/shareddata_test.go
  integration/tigris/shareddata_test.go
  integration/tigris/smoke_test.go
Labels: code/chore

#910 Extract parameter list into one variable in `QueryDocuments`
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_dbstats.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pg.go
  internal/handlers/pg/pgdb/query_documents.go
  internal/handlers/pg/pgdb/query_documents_test.go
Labels: code/enhancement

#863 Add first compatibility tests
  integration/query_compat_test.go
  integration/query_logical_compat_test.go
  integration/query_logical_test.go
  integration/setup.go
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
Labels: code/chore

#916 Use `v` instead of `value` in tests
  integration/findandmodify_test.go
  integration/query_array_test.go
  integration/query_bitwise_test.go
  integration/query_comparison_test.go
  integration/query_element_test.go
  integration/query_evaluation_test.go
  integration/query_logical_compat_test.go
  integration/query_logical_test.go
  integration/query_projection_test.go
  integration/query_test.go
  integration/shareddata/shareddata.go
  integration/update_field_compat_test.go
  integration/update_field_test.go
  internal/handlers/common/update.go
Labels: code/chore

#920 Tweak codecov settings
  .codecov.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  Taskfile.yml
Labels: code/chore

#913 Validate database names
  README.md
  integration/basic_test.go
  integration/findandmodify_test.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/databases.go
  internal/handlers/pg/pgdb/pgdb.go
  internal/handlers/pg/pgdb/settings.go
  internal/handlers/pg/pgdb/tables.go
  internal/handlers/tigris/msg_update.go
  internal/util/testutil/db.go
Labels: code/feature

#922 Remove deprecated functions from `pgdb.Pool`
  cmd/envtool/main.go
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/pg/msg_listdatabases.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/pool_test.go
Labels: code/chore

#923 Extract integration tests setup to own package
  integration/basic_test.go
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/commands_freemonitoring_test.go
  integration/commands_replication_test.go
  integration/delete_test.go
  integration/embedded_test.go
  integration/findandmodify_test.go
  integration/query_array_test.go
  integration/query_bitwise_test.go
  integration/query_comparison_test.go
  integration/query_compat_test.go
  integration/query_element_test.go
  integration/query_evaluation_test.go
  integration/query_logical_test.go
  integration/query_projection_test.go
  integration/query_test.go
  integration/setup/setup.go
  integration/shareddata_test.go
  integration/tigris/embedded_test.go
  integration/tigris/shareddata_test.go
  integration/tigris/smoke_test.go
  integration/update_compat_test.go
  integration/update_field_test.go
  integration/update_test.go
Labels: code/chore

#930 comment `url.Values` to prevent test failing
  integration/setup/setup.go
Labels: code/bug-regression

#921 Add test for a database name border case
  README.md
  integration/basic_test.go
Labels: code/enhancement

#929 Add a comment to the setup function about database and collection creation when provider list is empty
  integration/setup/setup.go
Labels: code/chore

#932 Bump `golangci-lint`, remove old hacks
  tools/go.mod
  tools/go.sum
Labels: code/chore

#724 Support `$all` array query operator
  integration/query_array_compat_test.go
  integration/query_array_test.go
  integration/query_compat_test.go
  internal/handlers/common/filter.go
  internal/types/array.go
Labels: code/feature

#936 Add Path tests
  internal/types/path_test.go
Labels: code/chore

#938 Build packages on CI
  .github/RELEASE_CHECKLIST.md
  .github/workflows/packages.yml
  .gitignore
  .nfpm.yml
  README.md
  Taskfile.yml
  build/deb/.gitkeep
  build/deps/centos7.Dockerfile
  build/deps/debian11.Dockerfile
  build/deps/mongo5.Dockerfile
  build/nfpm.yaml
  build/rpm/.gitkeep
  docker-compose.yml
Labels: code/chore

#928 Implement `MsgCount` for Tigris
  Taskfile.yml
  go.mod
  integration/tigris/smoke_test.go
  internal/handlers/tigris/fetch.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_drop.go
  internal/handlers/tigris/msg_dropdatabase.go
  internal/handlers/tigris/tigris.go
Labels: code/feature, code/tigris

#942 Tweak linter settings
  .golangci-new.yml
  .golangci.yml
Labels: code/chore

#935 Port and sync unit testing approach from `fjson` to `tjson`
  internal/fjson/fjson_test.go
  internal/tjson/bool_test.go
  internal/tjson/double_test.go
  internal/tjson/int32_test.go
  internal/tjson/int64_test.go
  internal/tjson/string_test.go
  internal/tjson/tjson_test.go
Labels: code/enhancement

#946 Ensure that update operators are in sync
  internal/handlers/common/update.go
  internal/handlers/pg/msg_findandmodify.go
Labels: code/chore

#909 Support `explain` diagnostic command
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/msg_listcommands.go
  internal/handlers/dummy/msg_explain.go
  internal/handlers/handlers.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/pgdb/query_documents.go
  internal/handlers/tigris/msg_explain.go
  internal/types/document.go
Labels: code/feature

#949 Fix `nModified` count for `update`'s `$set` operator with the same value
  integration/update_field_test.go
  internal/handlers/common/update.go
Labels: code/bug

#937 Support `$comment` `update`'s argument
  integration/basic_test.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/pool.go
Labels: code/feature

#944 `tjson`: Fix schema comparison
  internal/tjson/schema.go
  internal/tjson/schema_test.go
Labels: code/chore

#950 Make compat error messages better
  Taskfile.yml
  integration/Taskfile.yml
  integration/compat_test.go
  integration/compattestcaseresulttype_string.go
  integration/helpers.go
  integration/query_compat_test.go
Labels: code/chore

#856 Enable `wsl` linter for new and changed code
  .golangci-new.yml
  .golangci.yml
  cmd/fuzztool/fuzztool.go
Labels: code/chore

#953 Fix some collection names breaking `listDatabases`
  integration/basic_test.go
  integration/commands_administration_test.go
  internal/handlers/pg/msg_listdatabases.go
  internal/util/testutil/db.go
Labels: code/chore

#959 Remove some tests to make next PRs smaller
  .github/workflows/integration.yml
  Taskfile.yml
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/commands_freemonitoring_test.go
  integration/query_array_compat_test.go
  integration/query_compat_test.go
  integration/query_logical_compat_test.go
  integration/setup/setup.go
  integration/shareddata/scalars.go
  integration/shareddata_test.go
  integration/tigris/embedded_test.go
  integration/tigris/shareddata_test.go
  integration/tigris/smoke_test.go
  integration/update_array_test.go
  integration/update_bitwise_test.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  integration/update_field_test.go
Labels: code/chore

#960 Add `SkipForTigris` helper, use it
  Taskfile.yml
  integration/Taskfile.yml
  integration/basic_test.go
  integration/commands_administration_test.go
  integration/delete_test.go
  integration/embedded_test.go
  integration/findandmodify_test.go
  integration/query_array_test.go
  integration/query_bitwise_test.go
  integration/query_comparison_test.go
  integration/query_element_test.go
  integration/query_evaluation_test.go
  integration/query_logical_test.go
  integration/query_projection_test.go
  integration/query_test.go
  integration/setup/common.go
  integration/setup/setup.go
  integration/update_field_test.go
  integration/update_test.go
Labels: code/chore

#961 Add setup for compatibility tests
  .github/workflows/integration.yml
  Taskfile.yml
  integration/compattestcaseresulttype_string.go
  integration/helpers.go
  integration/setup/common.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/shareddata/composites.go
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
Labels: code/chore

#963 Add compatibility tests for `$and`
  integration/query_compat_test.go
  integration/query_logical_compat_test.go
Labels: code/chore
