Repository FerretDB/FerretDB, pull requests merged in 2022-03, with the labels that each got.

#339 Add helper for getting required parameters
  internal/handlers/common/required.go
  internal/handlers/handler.go
  internal/handlers/jsonb1/msg_delete.go
  internal/handlers/jsonb1/msg_find_or_count.go
  internal/handlers/jsonb1/msg_insert.go
  internal/handlers/jsonb1/msg_update.go
  internal/handlers/msg_collstats.go
  internal/handlers/msg_create.go
  internal/handlers/msg_dbstats.go
  internal/handlers/msg_drop.go
  internal/handlers/msg_dropdatabase.go
  internal/handlers/msg_listcollections.go
  internal/handlers/msg_serverstatus.go
  internal/handlers/sql/msg_delete.go
  internal/handlers/sql/msg_find_or_count.go
  internal/handlers/sql/msg_insert.go
Labels: code/chore, trust

#341 Use safe type assertions for inputs
  internal/handlers/common/params.go
  internal/handlers/sql/where.go
Labels: code/chore

#340 Fix seed fuzz corpus collection
  Makefile
  cmd/fuzztool/fuzztool.go
Labels: code/chore

#345 Fix a few issues found by fuzzing
  internal/handlers/jsonb1/where.go
  internal/handlers/sql/where.go
  internal/types/document.go
  internal/types/document_test.go
Labels: code/chore

#328 Add fuzzing tests for handlers
  .github/workflows/go.yml
  Makefile
  internal/handlers/common/error.go
  internal/handlers/handler.go
  internal/handlers/handler_fuzz_test.go
  internal/handlers/handler_test.go
  internal/util/testutil/fuzz.go
Labels: code/chore, trust

#346 More fixes for bugs found by fuzzing
  .github/workflows/go.yml
  internal/handlers/handler.go
  internal/handlers/jsonb1/msg_find_or_count.go
  internal/handlers/sql/msg_find_or_count.go
Labels: code/bug

#349 Add `bin/task` to tools
  .golangci-required.yml
  .golangci.yml
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: code/chore

#350 Add more checks for Go versions
  Makefile
  tools/check.go
  tools/old.go
  tools/tools.go
Labels: code/chore

#358 Replace `Makefile` with `Taskfile`
  .github/workflows/docker.yml
  .github/workflows/go.yml
  CONTRIBUTING.md
  Taskfile.yml
  Taskfile_linux.yml
  Taskfile_windows.yml
Labels: trust

#365 Fix Taskfile
  Taskfile.yml
Labels: trust

#367 Remove SQL storage
  Taskfile.yml
  cmd/envtool/main.go
  docker-compose.yml
  internal/clientconn/conn.go
  internal/handlers/handler.go
  internal/handlers/handler_test.go
  internal/handlers/msg_listcollections.go
  internal/handlers/msg_listdatabases.go
  internal/handlers/sql/convert.go
  internal/handlers/sql/convert_test.go
  internal/handlers/sql/msg_createindexes.go
  internal/handlers/sql/msg_delete.go
  internal/handlers/sql/msg_find_or_count.go
  internal/handlers/sql/msg_insert.go
  internal/handlers/sql/msg_update.go
  internal/handlers/sql/sql_test.go
  internal/handlers/sql/storage.go
  internal/handlers/sql/where.go
  internal/pg/pool.go
  internal/pg/pool_test.go
Labels: code/chore, trust

#369 Commands are case-sensitive
  internal/handlers/command.go
  internal/handlers/command_test.go
  internal/handlers/handler.go
  internal/handlers/handler_test.go
  internal/handlers/msg_collstats.go
  internal/handlers/msg_hello.go
  internal/handlers/query_cmd.go
  internal/types/document.go
  internal/types/document_test.go
Labels: code/bug, trust

#373 Use square brackets for nicer logs
  internal/util/lazyerrors/lazyerrors.go
  internal/util/lazyerrors/lazyerrors_test.go
Labels: code/chore

#374 Fix build tags
  tools/check.go
Labels: code/chore

#375 Add converter from types.Regex to regexp.Regexp
  internal/types/regex.go
  internal/types/types.go
Labels: code/chore

#376 Log test failures for updates and deletes
  internal/handlers/msg_delete_test.go
  internal/handlers/msg_update_test.go
Labels: code/chore

#377 Projection: `<field>: <1 or true>` and `<field>: <0 or false>`
  .gitignore
  internal/handlers/common/projection.go
  internal/handlers/handler_test.go
Labels: trust

#380 Fix small issues after rewrite
  internal/handlers/common/filter.go
  internal/handlers/handler_test.go
  internal/handlers/jsonb1/msg_count.go
  internal/handlers/jsonb1/msg_find.go
Labels: code/chore, trust

#382 Projection: `<field>: <1 or true>` and `<field>: <0 or false>`: error messages formatting
  internal/handlers/common/error.go
  internal/handlers/common/projection.go
Labels: trust

#384 Projection add error codes when inclusion and exclusion is used
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/projection.go
Labels: trust

#385 Make updates work
  internal/handlers/jsonb1/msg_update.go
Labels: trust, code/bug-regression

#387 Bump dependecnies
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: code/chore

#378 Add SortDocuments
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/filter.go
  internal/handlers/common/params.go
  internal/handlers/common/sort.go
  internal/handlers/common/sort_test.go
Labels: code/enhancement, trust

#351 Fix some fluky tests
  internal/handlers/handler_test.go
Labels: code/chore, trust

#390 Minor CI and build tweaks
  .github/workflows/go.yml
  Taskfile.yml
Labels: code/chore

#386 Add Markdown linter
  .markdownlint.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  Taskfile.yml
Labels: code/chore

#392 Do not cache modules
  .github/workflows/docker.yml
  .github/workflows/go.yml
  Taskfile.yml
Labels: code/chore

#391 Fix more fluky tests
  .github/workflows/go.yml
  internal/handlers/handler_fuzz_test.go
  internal/handlers/handler_test.go
Labels: code/chore, trust

#393 Tweak Markdown linter a bit
  .github/workflows/go.yml
  .markdownlint.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  Taskfile.yml
Labels: documentation

#397 Allow access to actual listener's address
  cmd/ferretdb/main.go
  internal/clientconn/listener.go
  internal/clientconn/tls.go
  internal/handlers/handler_test.go
  internal/util/debug/debug.go
  internal/util/logging/logging.go
Labels: code/chore, trust

#389 Add a new way to write integration tests
  .github/dependabot.yml
  .github/workflows/integration.yml
  .gitignore
  .golangci.yml
  Taskfile.yml
  integration/basic_test.go
  integration/common.go
  integration/go.mod
  integration/go.sum
  integration/setup.go
  tools/go.mod
  tools/go.sum
Labels: code/chore

#399 Handle any number type for `limit`
  internal/handlers/common/filter.go
  internal/handlers/common/limit.go
  internal/handlers/common/params.go
  internal/handlers/common/sort.go
  internal/handlers/handler_test.go
  internal/handlers/jsonb1/msg_count.go
  internal/handlers/jsonb1/msg_delete.go
  internal/handlers/jsonb1/msg_find.go
  internal/handlers/msg_delete_test.go
Labels: trust, code/bug-regression

#394 Implement `$bitsAllClear`
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/filter.go
  internal/handlers/common/params.go
  internal/handlers/handler_test.go
  internal/types/binary.go
  internal/types/binary_test.go
Labels: code/feature, trust

#401 Move `internal/pg` to `internal/handlers/pg/pgdb`
  cmd/envtool/main.go
  cmd/ferretdb/main.go
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/handlers/handler.go
  internal/handlers/handler_test.go
  internal/handlers/jsonb1/msg_delete.go
  internal/handlers/jsonb1/storage.go
  internal/handlers/msg_create.go
  internal/handlers/msg_drop.go
  internal/handlers/msg_dropdatabase.go
  internal/handlers/pg/pgdb/placeholder.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/pool_test.go
  internal/util/testutil/pg.go
Labels: code/chore, trust

#402 Move `handlers/jsonb1` to `handlers/pg`
  internal/clientconn/conn.go
  internal/handlers/handler_test.go
  internal/handlers/pg/fetch.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_createindexes.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/storage.go
Labels: code/chore, trust

#383 Support `$elemMatch` projection query operator
  internal/handlers/common/projection.go
  internal/handlers/pg/handler_test.go
  internal/types/document.go
  internal/types/path_test.go
Labels: code/feature, trust

#407 Use `testutil.AssertEqual` helper
  internal/handlers/handler_test.go
  internal/util/testutil/dump.go
  internal/util/testutil/equal.go
Labels: code/chore, trust

#400 Support all bitwise query operators
  internal/handlers/common/error.go
  internal/handlers/common/filter.go
  internal/handlers/common/params.go
  internal/handlers/handler_test.go
Labels: code/feature, trust

#409 Fix finding zero documents with `FindOne`
  .github/workflows/go.yml
  .github/workflows/integration.yml
  integration/basic_test.go
  internal/handlers/common/limit.go
  internal/types/document.go
Labels: code/bug, trust

#410 Move `$size` tests to integration tests
  README.md
  integration/basic_test.go
  integration/go.mod
  integration/helpers.go
  integration/query_array_test.go
  integration/query_comparision_test.go
  integration/setup.go
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
  internal/handlers/handler_fuzz_test.go
  internal/handlers/handler_test.go
  internal/util/testutil/dump.go
  internal/util/testutil/equal.go
Labels: code/chore, trust

#412 Improve logging in integration tests
  integration/commands_replication_test.go
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/handlers/handler_test.go
Labels: code/chore, trust
