Repository FerretDB/FerretDB, pull requests merged in 2022-11, with the labels that each got.

#1345 Cleanup compat tests
  integration/insert_compat_test.go
  integration/query_compat_test.go
  integration/update_compat_test.go
  internal/handlers/common/error.go
  internal/types/document_validation.go
Labels: code/chore

#1349 Fix ignore patterns for tools
  .textlintignore
  Taskfile.yml
Labels: code/chore

#1336 Make users know about telemetry via `startupWarnings`
  integration/setup/common.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/tigris/msg_getlog.go
  internal/util/telemetry/reporter.go
Labels: code/enhancement

#1334 Deprecate nested arrays
  integration/query_array_test.go
  integration/query_comparison_test.go
  integration/query_element_test.go
  integration/query_test.go
  integration/shareddata/composites.go
  internal/handlers/common/error.go
  internal/types/document.go
  internal/types/document_validation.go
  internal/types/document_validation_test.go
  website/docs/diff.md
Labels: code/enhancement

#1365 Use pre-built Docusaurus image
  .github/dependabot.yml
  .gitignore
  Taskfile.yml
  build/.trivyignore
  build/deps/docusaurus-docs.Dockerfile
  docker-compose.yml
  website/.gitignore
  website/Dockerfile
  website/package-lock.json
  website/package.json
Labels: code/chore

#1367 Bump deps
  Dockerfile
  build/deps/cockroach.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#1364 Add "_id" string to linter exceptions
  .golangci.yml
  internal/types/document.go
  internal/types/document_validation.go
  internal/types/document_validation_test.go
Labels: code/chore

#1348 Remove extra `nolint` directives
  internal/handlers/tigris/tigrisdb/errors.go
Labels: code/chore

#1371 Setup `lfs-warning` GitHub Action check
  .github/workflows/docs.yml
Labels: code/chore

#1368 Update dark and light theme logo for documentation
  website/docusaurus.config.js
  website/static/img/logo.svg
  website/static/img/logo_dark.png
  website/static/img/logo_light.png
Labels: documentation

#1342 Add documentation for configuring telemetry service
  website/docs/Basic_operations/delete.md
  website/docs/Basic_operations/index.md
  website/docs/Basic_operations/update.md
  website/docs/Reference/_category_.json
  website/docs/Reference/telemetry.md
  website/docs/diff.md
Labels: documentation

#1372 Bump Tigris
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: deps

#1373 Remove unsupported NaN and Inf from pjson package documentation
  internal/handlers/pg/pjson/pjson.go
Labels: code/chore

#1377 Provide builds for `linux/arm/v7`
  Dockerfile
  Taskfile.yml
Labels: code/feature, trust

#1261 Tweak supported wire protocol versions
  integration/commands_replication_test.go
  internal/handlers/common/common.go
  internal/handlers/pg/cmd_query.go
  internal/handlers/pg/msg_hello.go
  internal/handlers/pg/msg_ismaster.go
  internal/handlers/tigris/cmd_query.go
  internal/handlers/tigris/msg_hello.go
  internal/handlers/tigris/msg_ismaster.go
Labels: code/enhancement

#1378 Do not cancel in-progress CI runs
  .github/workflows/conform-pr.yml
Labels: code/chore

#1358 Add more `NewCommandErrorMsgWithArgument` calls
  internal/clientconn/conn.go
  internal/handlers/common/error.go
  internal/handlers/common/error_command.go
  internal/handlers/common/filter.go
  internal/handlers/common/findandmodify.go
  internal/handlers/common/limit.go
  internal/handlers/common/msg_aggregate.go
  internal/handlers/common/msg_setfreemonitoring.go
  internal/handlers/common/params.go
  internal/handlers/common/projection.go
  internal/handlers/common/sort.go
  internal/handlers/common/typecode.go
  internal/handlers/common/update.go
  internal/handlers/dummy/dummy.go
  internal/handlers/pg/cmd_query.go
  internal/handlers/pg/msg_collmod.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/pg/msg_getparameter.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/tigris/cmd_query.go
  internal/handlers/tigris/json_schema.go
  internal/handlers/tigris/msg_collmod.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_create.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_drop.go
  internal/handlers/tigris/msg_explain.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_getlog.go
  internal/handlers/tigris/msg_getparameter.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_update.go
Labels: code/enhancement

#1359 Fix `SchemaStats` to return empty stats
  integration/commands_administration_test.go
  integration/go.mod
  internal/handlers/pg/pgdb/pool.go
Labels: code/bug

#1383 Use environment variables for configuration
  .github/workflows/conform-pr.yml
  Dockerfile
  README.md
  cmd/ferretdb/main.go
  internal/util/telemetry/reporter.go
  website/docs/quickstart_guide/docker.md
Labels: code/enhancement, trust

#1381 Add missing locks when update settings table
  integration/.golangci-new.yml
  integration/commands_administration_test.go
  integration/create_test.go
  integration/helpers.go
  internal/handlers/pg/msg_listdatabases.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/settings.go
  internal/handlers/tigris/msg_create.go
  internal/handlers/tigris/tigrisdb/errors.go
Labels: code/enhancement

#1400 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/clientconn/conninfo/conn_info_test.go
  internal/types/path_test.go
  tools/go.mod
  tools/go.sum
Labels: deps

#1393 Make telemetry page visible in documentation sidebar
  website/docs/Reference/_category_.json
  website/docs/telemetry.md
Labels: documentation

#1382 Add documentation for dot notation in arrays, objects, and embedded documents
  website/docs/Basic_operations/create.md
  website/docs/Basic_operations/delete.md
  website/docs/Basic_operations/read.md
  website/docs/Basic_operations/update.md
  website/docs/understanding_ferretdb.md
  website/src/pages/index.js
Labels: documentation

#1374 Restructure text, add unestimated tasks
  .github/PROCESS.md
Labels: project

#1406 Start supported commands table
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/tigris/msg_listcollections.go
  website/docs/Reference/supported_commands.md
Labels: documentation

#1404 Ignore website problems for now
  build/.trivyignore
Labels: code/chore

#1408 Use lowercase directory names
  website/docs/basic_operations/_category_.json
  website/docs/basic_operations/create.md
  website/docs/basic_operations/delete.md
  website/docs/basic_operations/index.md
  website/docs/basic_operations/read.md
  website/docs/basic_operations/update.md
  website/docs/reference/_category_.json
  website/docs/reference/supported_commands.md
Labels: code/chore

#1411 Add aggregation section (collection stages) to the docs
  website/docs/reference/supported_commands.md
Labels: documentation

#1409 Add query and write operation commands to the docs
  website/docs/reference/supported_commands.md
Labels: documentation

#1446 Minor telemetry cleanup
  internal/handlers/common/serverstatus.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/tigris/msg_getlog.go
  internal/util/state/metrics.go
  internal/util/telemetry/reporter.go
  internal/util/telemetry/reporter_test.go
  internal/util/telemetry/telemetry.go
  internal/util/telemetry/telemetry_test.go
Labels: code/chore

#1477 Bump deps
  build/deps/cockroach.Dockerfile
  build/deps/mongo6.Dockerfile
  build/deps/postgres.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#1448 Add aggregation section (database stages, operators) to the docs
  website/docs/reference/supported_commands.md
Labels: documentation

#1391 Allow duplicates in `bson` documents
  integration/update_field_compat_test.go
  internal/bson/array.go
  internal/bson/document.go
  internal/bson/document_test.go
  internal/bson/testdata/fuzz1.hex
  internal/handlers/common/update.go
  internal/types/document.go
  internal/wire/op_msg.go
  website/docs/diff.md
Labels: code/chore

#1402 Implement `debugError` command
  internal/handlers/common/msg_debugerror.go
Labels: code/chore

#1452 Update some TODOs
  integration/commands_administration_test.go
  integration/delete_compat_test.go
  integration/query_logical_test.go
  integration/query_test.go
  integration/update_field_test.go
Labels: code/chore

#1485 Use colored emoji
  website/docs/reference/supported_commands.md
Labels: documentation

#1481 Add update operators to the docs
  website/docs/reference/supported_commands.md
Labels: documentation

#1490 Reorganize a list of supported commands
  website/docs/reference/supported_commands.md
Labels: documentation

#1482 Record integration tests connections
  Taskfile.yml
  integration/Taskfile.yml
  integration/setup/common.go
  internal/clientconn/conn.go
Labels: code/chore

#1479 Add changelog draft
  CHANGELOG.md
Labels: documentation

#1486 Use `primitive.Regex` to test that regex `_id` is not allowed
  integration/insert_compat_test.go
Labels: code/chore

#1489 Add user management commands to the docs
  website/docs/reference/supported_commands.md
Labels: documentation

#1498 Fix information about `delete`'s `comment` argument inside "supported commands" reference
  website/docs/reference/supported_commands.md
Labels: documentation

#1379 Bump Tigris version
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/handlers/tigris/tigrisdb/collections.go
  internal/handlers/tigris/tigrisdb/databases.go
  internal/handlers/tigris/tigrisdb/query.go
  internal/handlers/tigris/tigrisdb/tigrisdb.go
Labels: deps

#1325 Use `-` in test collection names
  integration/basic_test.go
  integration/setup/setup.go
  internal/util/testutil/db.go
Labels: code/chore

#1397 Fix issues for the Unix listener
  .gitignore
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/setup/common.go
  integration/setup/common_unix.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/handlers/pg/msg_explain.go
Labels: code/bug

#1478 Add documentation for embedded/nested documents query
  website/docs/basic_operations/index.md
  website/docs/basic_operations/read.md
  website/docs/basic_operations/update.md
  website/docs/understanding_ferretdb.md
Labels: documentation

#1499 Simplify array comparison, remove `[]CompareResult`
  internal/handlers/common/filter.go
  internal/handlers/common/projection.go
  internal/handlers/common/update.go
  internal/types/array.go
  internal/types/compare.go
  internal/types/compare_order.go
Labels: code/chore

#1524 Disable CockroachDB on GitHub Actions
  .github/workflows/integration.yml
Labels: code/chore

#1525 Add placeholder for testing scripts
  .gitignore
  Taskfile.yml
  build/mongosh/test.js
  docker-compose.yml
Labels: code/chore

#1527 Add authentication and role management commands to the docs
  website/docs/reference/supported_commands.md
Labels: documentation

#1543 Add path to record loading error message
  internal/wire/records_test.go
Labels: code/chore

#1480 Add section for diagnostic command `buildInfo` and `collStats`
  website/docs/reference/supported_commands.md
Labels: documentation

#1526 Move array query tests to compat tests
  integration/basic_test.go
  integration/query_array_compat_test.go
  integration/query_array_test.go
  integration/query_compat_test.go
  integration/query_test.go
Labels: code/chore

#1546 Add session and free monitoring commands to the docs
  website/docs/reference/supported_commands.md
Labels: documentation

#1513 Fix parallel collection inserts for PostgreSQL
  cmd/envtool/main.go
  integration/create_test.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/databases.go
  internal/handlers/pg/pgdb/insert.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/pg/pgdb/query_test.go
Labels: code/bug

#1544 Move `_id` field check to separate function
  internal/types/document.go
  internal/types/document_test.go
  internal/types/document_validation.go
Labels: code/chore

#1562 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps, no ci

#1565 Implement `listIndexes` command stub
  internal/handlers/common/msg_listcommands.go
  internal/handlers/dummy/msg_listindexes.go
  internal/handlers/handlers.go
  internal/handlers/pg/msg_listindexes.go
  internal/handlers/tigris/msg_listindexes.go
Labels: code/chore

#1571 Downgrade min wire protocol version to 13 / 5.0
  integration/commands_replication_test.go
  internal/handlers/common/common.go
Labels: code/enhancement

#1561 Make default telemetry state a bit more clear
  cmd/ferretdb/main.go
Labels: code/enhancement

#1566 Do not record partial files
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/wire/msg_body.go
  internal/wire/msg_header.go
  internal/wire/records_test.go
Labels: code/chore

#1555 Add Mastodon links
  README.md
  website/docs/intro.md
  website/docusaurus.config.js
Labels: documentation

#1573 Sync label descriptions and issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: project

#1563 Auto-merge is required now
  .github/PROCESS.md
Labels: project

#1560 Move more query tests to compat and change filter bad value check order
  integration/query_array_compat_test.go
  integration/query_array_test.go
  integration/query_compat_test.go
  internal/handlers/common/filter.go
Labels: code/chore

#1570 Move more tests to compat query tests
  integration/query_array_test.go
  integration/query_bitwise_test.go
  integration/query_comparison_compat_test.go
  integration/query_comparison_test.go
  integration/query_compat_element_test.go
  integration/query_element_test.go
  integration/query_logical_test.go
Labels: code/chore

#1574 Add `msg_explain` implementation for Tigris
  integration/commands_diagnostic_test.go
  internal/handlers/tigris/msg_explain.go
  internal/handlers/tigris/tigrisdb/query.go
Labels: code/feature

#1401 Add documents validation to `wire` package
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/findandmodify_compat_test.go
  integration/query_array_compat_test.go
  integration/query_array_test.go
  integration/query_bitwise_test.go
  integration/query_element_test.go
  integration/query_evaluation_test.go
  integration/query_projection_test.go
  integration/query_test.go
  integration/shareddata/composites.go
  integration/shareddata/scalars.go
  integration/update_field_test.go
  internal/clientconn/conn.go
  internal/handlers/common/error.go
  internal/handlers/common/filter.go
  internal/handlers/common/params.go
  internal/handlers/common/update.go
  internal/handlers/pg/pjson/double_test.go
  internal/handlers/tigris/tjson/double_test.go
  internal/util/testutil/equal_test.go
  internal/wire/msg_body.go
  internal/wire/op_msg.go
  internal/wire/op_msg_test.go
  internal/wire/op_query.go
  internal/wire/validation.go
  website/docs/diff.md
Labels: code/enhancement

#1567 Add `filter` support to `listCollections`
  Taskfile.yml
  integration/commands_administration_test.go
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/pg/msg_listdatabases.go
  internal/handlers/tigris/msg_listcollections.go
  internal/handlers/tigris/msg_listdatabases.go
  website/docs/reference/supported_commands.md
Labels: code/feature

#1575 Fix test names to make them more consistent
  integration/commands_diagnostic_test.go
Labels: code/chore

#1580 Update documentation for types, add aliases
  internal/bson/bson.go
  internal/handlers/pg/pjson/pjson.go
  internal/handlers/tigris/tjson/tjson.go
  internal/types/fjson/fjson.go
  internal/types/types.go
Labels: code/chore, no ci

#1487 Simplify documents fetching for the `count` operator
  integration/count_compat_test.go
  integration/setup/setup_compat.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/pg/pgdb/query_test.go
  internal/util/iterator/iterator.go
Labels: code/chore

#1582 Allow `-` in database names
  integration/basic_test.go
  integration/findandmodify_test.go
  internal/handlers/pg/pgdb/databases.go
  internal/util/testutil/db.go
  website/docs/diff.md
Labels: code/enhancement

#1584 Simplify documents fetching for `delete`
  internal/handlers/pg/msg_delete.go
Labels: code/chore

#1591 Fix `listIndexes` stub
  internal/handlers/pg/msg_listindexes.go
  internal/handlers/tigris/msg_listindexes.go
Labels: code/chore

#1579 Move query tests to compat by comparing the error code instead of the error message
  integration/helpers.go
  integration/query_array_test.go
  integration/query_bitwise_test.go
  integration/query_compat_test.go
  integration/query_element_compat_test.go
  integration/query_element_test.go
  integration/query_evaluation_compat_test.go
  integration/query_evaluation_test.go
  integration/query_projection_compat_test.go
  integration/query_projection_test.go
  internal/handlers/common/filter.go
Labels: code/chore

#1595 Add TODOs
  ferretdb/ferretdb.go
  integration/setup/common.go
  integration/setup/common_unix.go
Labels: code/chore

#1588 Support more default `find` parameters
  .github/workflows/conform-pr.yml
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  integration/commands_administration_test.go
  internal/handlers/common/find.go
  internal/handlers/pg/msg_find.go
  internal/handlers/tigris/msg_find.go
  internal/types/document.go
  internal/types/fjson/document.go
Labels: code/enhancement, trust

#1538 Simplify documents fetching for `find`, `findAndModify`, and `update`
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
Labels: code/chore

#1592 Improve `iterator.Interface` implementation in `pgdb.queryIterator`
  integration/update_field_test.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/pg/pgdb/query_test.go
Labels: code/chore

#1596 Refactor `pg`'s `MsgListDatabases` and `pgdb`
  internal/handlers/pg/msg_listdatabases.go
  internal/handlers/pg/pgdb/databases.go
Labels: code/chore
