Repository FerretDB/FerretDB, pull requests merged in 2023-05, with the labels that each got.

#2527 Check test database name length in compat test setup
  integration/setup/setup_compat.go
  integration/update_field_compat_test.go
Labels: code/chore

#2541 Handle absent `os-release` file
  internal/handlers/common/msg_hostinfo.go
  internal/handlers/common/parse_osrelease.go
Labels: code/enhancement

#2552 Remove version and name assertions in integration tests
  integration/commands_diagnostic_test.go
Labels: code/chore

#2561 Do various small cleanups
  integration/Taskfile.yml
  internal/handlers/common/params.go
  internal/types/document.go
  internal/util/iterator/count.go
  internal/util/iterator/values.go
  internal/util/must/must.go
  tools/Taskfile.yml
Labels: code/chore

#2530 Pushdown simplest sorting for `aggregate` command
  integration/aggregate_documents_compat_test.go
  internal/handlers/common/aggregations/stages/pushdown.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/tigris/msg_aggregate.go
  internal/handlers/tigris/msg_explain.go
Labels: code/chore

#2534 Fix `$` path errors for sort
  integration/aggregate_documents_compat_test.go
  integration/findandmodify_compat_test.go
  integration/query_compat_test.go
  internal/handlers/common/sort.go
Labels: code/bug

#2562 Fix empty projections panic
  integration/query_projection_compat_test.go
  internal/handlers/common/projection.go
Labels: code/bug-regression

#2529 Move handlers parameters to common
  internal/handlers/common/count.go
  internal/handlers/common/delete.go
  internal/handlers/common/explain.go
  internal/handlers/common/findandmodify.go
  internal/handlers/common/insert.go
  internal/handlers/common/msg_listcommands.go
  internal/handlers/common/update_params.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_explain.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_update.go
Labels: code/chore

#2535 Use our own Prettier Docker image
  .github/workflows/format.yml
  Taskfile.yml
  build/deps/ferretdb-prettier.Dockerfile
  build/deps/prettier.Dockerfile
  docker-compose.yml
Labels: code/chore

#2392 Improve fuzzing with recorded seed data
  internal/clientconn/conn.go
  internal/wire/records_test.go
Labels: code/chore

#2553 Improve handling of `os-release` files
  internal/handlers/common/parse_osrelease.go
  internal/handlers/common/parse_osrelease_test.go
Labels: code/enhancement

#2570 Add proper CLI to `envtool` - `envtool setup` subcommand
  Taskfile.yml
  cmd/envtool/envtool.go
Labels: code/chore

#2488 Document `createIndexes`, `listIndexes`, and `dropIndexes` commands
  website/docs/configuration/_category_.yml
  website/docs/contributing/_category_.yml
  website/docs/diff.md
  website/docs/indexes.md
  website/docs/reference/_category_.yml
  website/docs/reference/glossary.md
  website/docs/security.md
  website/docs/telemetry.md
Labels: documentation, trust

#2572 Tweak issue templates and contributing docs
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/chore.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/PROCESS.md
  .github/workflows/go.yml
  .github/workflows/integration-trust.yml
  .github/workflows/integration.yml
  CONTRIBUTING.md
Labels: project

#2574 Fix `runCommand`'s inserts of documents without `_id`s
  integration/insert_run_command_compat_test.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/tigris/msg_insert.go
Labels: code/bug

#2577 Do panic in integration tests if connection can't be established
  integration/setup/client.go
Labels: code/chore

#2575 Small refactoring
  internal/handlers/common/aggregations/aggregations.go
  internal/handlers/common/aggregations/operators/number.go
  internal/handlers/common/aggregations/operators/sum.go
  internal/handlers/common/aggregations/pushdown.go
  internal/handlers/common/aggregations/stages/collstats.go
  internal/handlers/common/aggregations/stages/count.go
  internal/handlers/common/aggregations/stages/group.go
  internal/handlers/common/aggregations/stages/limit.go
  internal/handlers/common/aggregations/stages/match.go
  internal/handlers/common/aggregations/stages/project.go
  internal/handlers/common/aggregations/stages/skip.go
  internal/handlers/common/aggregations/stages/sort.go
  internal/handlers/common/aggregations/stages/stages.go
  internal/handlers/common/aggregations/stages/statistics.go
  internal/handlers/common/aggregations/stages/unwind.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/tigris/msg_aggregate.go
  internal/handlers/tigris/msg_explain.go
Labels: code/chore

#2343 Implement `renameCollection` command
  integration/renamecollection_compat_test.go
  integration/renamecollection_test.go
  internal/handlers/common/msg_listcommands.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/dummy/msg_renamecollection.go
  internal/handlers/hana/msg_renamecollection.go
  internal/handlers/handlers.go
  internal/handlers/pg/msg_renamecollection.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/database_metadata.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/tigris/msg_renamecollection.go
  website/docs/reference/supported-commands.md
Labels: code/feature

#2576 Prepare v1.1.0 release
  .github/release.yml
  CHANGELOG.md
Labels: code/chore

#2592 Bump deps
  .github/RELEASE_CHECKLIST.md
  CODE_OF_CONDUCT.md
  SECURITY.md
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/markdownlint.Dockerfile
  build/deps/trivy.Dockerfile
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  website/blog/2023-01-25-ferretdb-fetches-data-query-pushdown.md
Labels: deps

#2594 Add FerretDB v1.1.0 release blog post
  website/blog/2023-05-09-ferretdb-v-1-1-0-released.md
Labels: trust, blog/marketing

#2573 Remove `TODO` comment for closed issue
  integration/update_field_test.go
Labels: code/chore

#2601 Update blog post image for 1.1.0
  website/blog/2023-05-09-ferretdb-v-1-1-0-released.md
  website/static/img/blog/ferretdb-1-1-0-release.png
Labels: trust, blog/marketing

#2595 Add experimental integration test flag for pushdown sorting
  cmd/ferretdb/main.go
  integration/query_compat_test.go
  integration/setup/listener.go
  integration/setup/setup.go
Labels: code/chore

#2602 Relax PostgreSQL connection checks
  internal/handlers/pg/pg.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/registry/hana.go
  internal/handlers/registry/tigris.go
  website/docs/security.md
  website/docs/understanding-ferretdb.md
Labels: documentation, code/enhancement, trust

#2596 Add `shell` subcommands (`mkdir`, `rmdir`) in `envtool`
  Taskfile.yml
  cmd/envtool/envtool.go
  cmd/envtool/envtool_test.go
Labels: code/chore

#2607 Add basic postcondition checker for errors
  internal/handlers/pg/pgdb/databases.go
  internal/util/contract/contract.go
  internal/util/contract/contract_test.go
Labels: code/chore

#2610 Make protocol-level crashes easier to understand
  internal/clientconn/conn.go
Labels: code/chore

#2613 Fix compatibility with C# driver
  internal/handlers/pg/cmd_query.go
Labels: code/bug

#2614 Simplify `envtool shell` subcommands
  cmd/envtool/envtool.go
  cmd/envtool/envtool_test.go
Labels: code/chore

#2533 Cleanup old Docker images
  .github/workflows/clean.yml
  tools/cleantool/cleantool.go
  tools/go.mod
  tools/go.sum
Labels: code/chore

#2609 Cleanup `insert` command
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
Labels: code/enhancement

#2578 Fix exponential backoff minimum duration
  internal/util/ctxutil/ctxutil.go
  internal/util/ctxutil/ctxutil_test.go
Labels: code/chore

#2622 Fix `count`'s `query` parameter
  internal/handlers/common/count.go
Labels: code/chore

#2536 Support dot notation in projection
  integration/aggregate_documents_compat_test.go
  integration/query_compat_test.go
  integration/query_projection_compat_test.go
  integration/shareddata/composites.go
  integration/shareddata/shareddata.go
  internal/handlers/common/projection.go
Labels: code/enhancement

#2611 Fix a typo in a blog post
  website/blog/2023-05-09-ferretdb-v-1-1-0-released.md
Labels: blog/marketing

#2628 Fix typo on RPM package file name
  website/docs/quickstart-guide/rpm.md
Labels: documentation

#2620 Use `ExtractParameters` in handlers
  integration/delete_test.go
  integration/findandmodify_test.go
  integration/query_test.go
  internal/handlers/common/count.go
  internal/handlers/common/delete.go
  internal/handlers/common/distinct.go
  internal/handlers/common/explain.go
  internal/handlers/common/find.go
  internal/handlers/common/findandmodify.go
  internal/handlers/common/insert.go
  internal/handlers/common/limit.go
  internal/handlers/common/params.go
  internal/handlers/common/update_params.go
  internal/handlers/commonparams/extract_params.go
  internal/handlers/commonparams/extract_params_test.go
  internal/handlers/commonparams/params.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_getparameter.go
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/pg/msg_listdatabases.go
  internal/handlers/pg/msg_update.go
  internal/handlers/tigris/msg_listcollections.go
  internal/handlers/tigris/msg_listdatabases.go
Labels: code/chore

#2540 Verify `OP_MSG ` message checksum
  internal/wire/msg_body.go
  internal/wire/op_msg.go
  internal/wire/op_msg_test.go
  internal/wire/records_test.go
  internal/wire/wire_test.go
Labels: code/chore

#2642 Return `int64` values for `dbStats` and `collStats`
  integration/commands_administration_test.go
  internal/handlers/common/aggregations/stages/collstats.go
  internal/handlers/common/serverstatus.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_collstats.go
  internal/handlers/pg/msg_dbstats.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/pgdb/stats.go
  internal/handlers/tigris/msg_aggregate.go
  internal/handlers/tigris/msg_collstats.go
  internal/handlers/tigris/msg_datasize.go
  internal/handlers/tigris/msg_explain.go
Labels: code/bug

#2626 Implement `envtool shell read` subcommand
  Taskfile.yml
  cmd/envtool/envtool.go
Labels: code/chore

#2641 Cleanup projection
  integration/aggregate_documents_compat_test.go
  integration/aggregate_documents_test.go
  internal/handlers/common/aggregations/projection.go
  internal/handlers/common/aggregations/projection_iterator.go
  internal/handlers/common/aggregations/stages/project.go
  internal/handlers/common/projection.go
  internal/handlers/common/projection_iterator.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
Labels: code/chore

#2640 Update documentation formatting
  website/docs/reference/supported-commands.md
Labels: documentation, trust

#2636 Add tests for aggregation expressions with dots in `$group` aggregation stage
  integration/aggregate_documents_compat_test.go
Labels: code/chore

#2655 Implement some SQLite backend commands
  internal/backends/backend.go
  internal/backends/database.go
  internal/backends/error.go
  internal/backends/errorcode_string.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/database.go
  internal/handlers/hana/cmd_query.go
  internal/handlers/pg/msg_hello.go
  internal/handlers/pg/msg_ismaster.go
  internal/handlers/sqlite/cmd_query.go
  internal/handlers/sqlite/msg_create.go
  internal/handlers/sqlite/msg_drop.go
  internal/handlers/sqlite/msg_dropdatabase.go
  internal/handlers/sqlite/msg_hello.go
  internal/handlers/sqlite/msg_ismaster.go
  internal/handlers/sqlite/msg_listcollections.go
  internal/handlers/sqlite/msg_listdatabases.go
  internal/handlers/sqlite/msg_ping.go
  internal/handlers/tigris/cmd_query.go
  internal/handlers/tigris/msg_hello.go
  internal/handlers/tigris/msg_ismaster.go
Labels: code/chore

#2644 Aggregation expression refactor
  internal/handlers/common/aggregations/expression.go
  internal/handlers/common/aggregations/expressionerrorcode_string.go
  internal/handlers/common/aggregations/operators/sum.go
  internal/handlers/common/aggregations/stages/group.go
  internal/handlers/common/aggregations/stages/unwind.go
Labels: code/chore

#2661 Add basic observability into backend interfaces
  internal/backends/backend.go
  internal/backends/collection.go
  internal/backends/database.go
  internal/backends/doc.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/database.go
  internal/clientconn/conninfo/conn_info.go
  internal/clientconn/cursor/cursor.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/sqlite/msg_create.go
  internal/handlers/sqlite/msg_drop.go
  internal/handlers/sqlite/msg_dropdatabase.go
  internal/handlers/sqlite/msg_listcollections.go
  internal/handlers/tigris/tigrisdb/query_iterator.go
  internal/types/array_iterator.go
  internal/types/document_iterator.go
  internal/util/iterator/func.go
  internal/util/iterator/slice.go
  internal/util/observability/funccall.go
  internal/util/observability/observability.go
Labels: code/chore

#2656 Implement metadata storage
  .golangci.yml
  internal/backends/collection.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/metadata_storage.go
  internal/backends/sqlite/pool.go
  internal/handlers/sqlite/msg_insert.go
  internal/handlers/sqlite/msg_listdatabases.go
  internal/handlers/sqlite/sqlite.go
Labels: code/chore

#2654 Add blog post on "Meteor and FerretDB"
  website/blog/2023-05-18-ferretdb-meteor-mongodb-alternative.md
  website/static/img/blog/ferretdb-meteor.jpg
Labels: blog/marketing

#2665 Implement query request for SQLite backend
  internal/backends/collection.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/metadata_storage.go
  internal/backends/sqlite/pool.go
  internal/backends/sqlite/query_iterator.go
  internal/handlers/sqlite/msg_find.go
Labels: code/chore

#2657 Add test case for read in envtools
  cmd/envtool/envtool.go
  cmd/envtool/envtool_test.go
Labels: code/chore

#2666 Run integration tests for `sqlite` handler
  .github/workflows/integration.yml
  .gitignore
  Taskfile.yml
  integration/Taskfile.yml
  integration/query_projection_compat_test.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/shareddata/composites.go
  integration/shareddata/provider.go
  integration/shareddata/scalars.go
  internal/backends/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/hana/msg_setfreemonitoring.go
  internal/handlers/registry/sqlite.go
  internal/handlers/sqlite/msg_getfreemonitoringstatus.go
  internal/handlers/sqlite/msg_insert.go
  internal/handlers/sqlite/msg_setfreemonitoring.go
  internal/handlers/sqlite/sqlite.go
Labels: code/chore

#2671 Bump deps
  build/deps/docusaurus-docs.Dockerfile
  build/deps/postgres.Dockerfile
  build/docker/all-in-one.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#2673 Create SQLite directory if needed
  cmd/envtool/envtool.go
  cmd/envtool/envtool_test.go
  integration/commands_diagnostic_test.go
  integration/setup/listener.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/metadata_storage.go
  internal/handlers/registry/sqlite.go
  internal/handlers/sqlite/msg_find.go
  internal/handlers/sqlite/msg_serverstatus.go
  internal/handlers/sqlite/sqlite.go
  internal/util/ctxutil/ctxutil_test.go
Labels: code/chore

#2637 Fix index creation on nested fields
  internal/handlers/pg/pgdb/indexes.go
  internal/handlers/pg/pgdb/indexes_test.go
Labels: code/bug

#2674 Implement SQLite `update` and `delete` commands
  Taskfile.yml
  internal/backends/collection.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/metadata_storage.go
  internal/handlers/sqlite/msg_delete.go
  internal/handlers/sqlite/msg_insert.go
  internal/handlers/sqlite/msg_update.go
Labels: code/chore

#2686 Add release blog post for FerretDB version 1.2.0
  website/blog/2023-05-22-ferretdb-v-1-2-0-minor-release.md
  website/static/img/blog/ferretdb-1-2-0-minor-release.jpg
Labels: documentation

#2634 Refactor `gitBinaryMaskParam` function
  integration/query_bitwise_test.go
  integration/query_test.go
  internal/handlers/common/filter.go
  internal/handlers/common/params.go
  internal/handlers/common/sort.go
  internal/handlers/commonparams/extract_params.go
  internal/handlers/commonparams/params.go
Labels: code/chore

#2687 Add `distinct` command errors test
  integration/distinct_compat_test.go
  integration/distinct_test.go
  internal/handlers/commonparams/extract_params.go
  internal/handlers/commonparams/extract_params_test.go
Labels: code/chore

#2677 Clarify what's left in handling OP_MSG checksum
  internal/wire/msg_body.go
  internal/wire/op_msg.go
Labels: code/chore

#2664 Aggregation operators refactor
  integration/aggregate_documents_compat_test.go
  internal/handlers/common/aggregations/operators/accumulators/accumulators.go
  internal/handlers/common/aggregations/operators/accumulators/count.go
  internal/handlers/common/aggregations/operators/accumulators/sum.go
  internal/handlers/common/aggregations/operators/operators.go
  internal/handlers/common/aggregations/operators/type.go
  internal/handlers/common/aggregations/stages/group.go
  internal/handlers/common/aggregations/stages/project.go
  internal/handlers/common/aggregations/stages/projection/projection.go
  internal/handlers/common/aggregations/stages/projection/projection_iterator.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
Labels: code/chore

#2688 Implement positional operator in projection
  integration/aggregate_documents_test.go
  integration/query_projection_compat_test.go
  integration/query_projection_test.go
  internal/handlers/common/aggregations/stages/projection/projection.go
  internal/handlers/common/positional_operator.go
  internal/handlers/common/projection.go
  internal/handlers/common/projection_iterator.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/pg/msg_find.go
  internal/handlers/sqlite/msg_find.go
  internal/handlers/tigris/msg_find.go
  website/docs/reference/supported-commands.md
Labels: code/feature

#2714 Implement `envtool version` command
  cmd/envtool/envtool.go
  cmd/envtool/envtool_test.go
Labels: code/chore

#2718 Make `go test -list=.` work
  integration/main_test.go
Labels: code/chore

#2715 Include Hana in integration tests
  integration/Taskfile.yml
  integration/setup/listener.go
  integration/setup/setup.go
  integration/shareddata/composites.go
  integration/shareddata/scalars.go
Labels: code/chore

#2702 Bump deps
  build/.textlintrc
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps, trust

#2725 Fix `.deb` and `.rpm` package versions
  Taskfile.yml
  cmd/envtool/envtool.go
  cmd/envtool/envtool_test.go
Labels: code/bug, trust, packages

#2710 Update `$project` in Supported Commands
  website/docs/reference/supported-commands.md
Labels: documentation

#2726 Add `logout` test for all backend
  integration/commands_authentication_test.go
Labels: code/chore

#2707 Fix telemetry reporter logging
  internal/util/telemetry/reporter.go
  internal/util/telemetry/reporter_test.go
Labels: code/chore

#2716 Add supported aggregations to the `buildInfo` output
  integration/commands_administration_test.go
  internal/handlers/commoncommands/msg_buildinfo.go
Labels: code/chore

#2724 Add aggregation operator tests
  integration/aggregate_documents_compat_test.go
  integration/query_projection_compat_test.go
Labels: code/chore

#2717 Add more consistency to table tests' field names
  integration/aggregate_documents_test.go
  integration/commands_diagnostic_test.go
  integration/create_test.go
  integration/delete_test.go
Labels: code/chore

#2740 Reformat and lint more documentation files
  .github/codecov.yml
  CHANGELOG.md
  Taskfile.yml
  build/.markdownlint.yml
  build/.prettierignore
  build/.textlintrc
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/markdownlint.Dockerfile
  internal/handlers/common/update_params.go
  website/blog/2021-12-07-mongodb-compatibility-whats-really-important.md
  website/blog/2022-05-16-using-cla-assistant-with-ferretdb.md
  website/blog/2022-06-27-developers-need-ferretdb-stackoverflow-developer-survey-2022.md
  website/blog/2022-06-28-new-release-ferretdb-0-4-0.md
  website/blog/2022-07-27-new-ferretdb-minor-release-0-5-1.md
  website/blog/2022-09-20-how-to-contribute-to-open-source-2022.md
  website/blog/2022-09-21-how-to-keep-control-of-your-infra-using-ferretdb-and-tigris.md
  website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md
  website/blog/2022-10-06-how-to-start-ferretdb-locally-with-docker.md
  website/blog/2022-10-12-contribute-to-ferretdb-on-windows.md
  website/blog/2022-10-28-5-ways-to-avoid-database-vendor-lock-in.md
  website/blog/2022-11-08-pjson-how-to-store-bson-in-jsonb.md
  website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.md
  website/blog/2022-11-18-ferretdb-percona-university-event-istanbul.md
  website/blog/2022-11-21-ferretdb-0-6-2-version-release.md
  website/blog/2022-12-23-ferretdb-new-release-with-tls.md
  website/blog/2023-01-04-ferretdb-beta-version-authentication.md
  website/blog/2023-01-17-ferretdb-0-8-1-version-release.md
  website/blog/2023-01-25-ferretdb-fetches-data-query-pushdown.md
  website/blog/2023-02-07-5-database-alternatives-mongodb-2023.md
  website/blog/2023-02-14-2023-02-14-ferretdb-v-0-9-1-minor-release.md
  website/blog/2023-02-28-ferretdb-v-0-9-2.md
  website/blog/2023-03-14-ferretdb-v-0-9-3-improved-aggregation-pipeline-support.md
  website/blog/2023-03-30-ferretdb-v-0-9-4-minor-release-update.md
  website/blog/2023-04-11-ferretdb-1-0-ga-opensource-mongodb-alternative.md
  website/blog/2023-04-18-using-ferretdb-with-studio-3t.md
  website/blog/2023-05-09-ferretdb-v-1-1-0-released.md
  website/blog/2023-05-18-ferretdb-meteor-mongodb-alternative.md
  website/docs/basic-operations/update.md
  website/docs/configuration/flags.md
  website/docs/contributing/index.md
  website/docs/operators/update/field-update-operators.md
  website/docs/reference/supported-commands.md
Labels: documentation, code/chore, trust

#2739 Make `testFindAndModifyCompat` work with `compatTestCaseResultType`
  integration/findandmodify_compat_test.go
Labels: code/chore

#2745 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#2746 Call `ListSpecifications` driver's method in tests to check indexes
  integration/indexes_compat_test.go
Labels: code/chore
