Repository FerretDB/FerretDB, pull requests merged in 2023-01, with the labels that each got.

#1732 Add documentation, prepare release
  .textlintignore
  CHANGELOG.md
  build/version/version.go
  cmd/ferretdb/main.go
  integration/query_compat_test.go
  internal/clientconn/listener.go
  internal/handlers/common/limit.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/tigris/msg_explain.go
  website/blog/_guide/template.md
  website/docs/basic_operations/update.md
  website/docs/reference/operators/array-operators.md
  website/docs/reference/operators/comparison-operators.md
  website/docs/reference/operators/element-operators.md
  website/docs/reference/operators/logical-operators.md
  website/docs/reference/supported_commands.md
  website/docs/security.md
Labels: documentation, trust

#1730 Add `findandmodify` to the `common.Commands` map
  internal/handlers/common/msg_listcommands.go
Labels: code/enhancement

#1721 Support arrays in `tjson`
  integration/findandmodify_compat_test.go
  integration/query_array_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_element_compat_test.go
  integration/query_evaluation_compat_test.go
  integration/query_projection_compat_test.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  internal/handlers/tigris/tjson/array.go
  internal/handlers/tigris/tjson/array_test.go
  internal/handlers/tigris/tjson/document_test.go
  internal/handlers/tigris/tjson/schema.go
  internal/handlers/tigris/tjson/tjson.go
  internal/handlers/tigris/tjson/tjson_test.go
Labels: code/chore

#1737 Add documentation about CLI flags and environment variables
  CONTRIBUTING.md
  website/docs/flags.md
  website/docs/operation_modes.md
  website/docs/reference/glossary.md
  website/docs/security.md
Labels: documentation

#1740 Validate client's TLS certificate when root CA certificate is provided
  Taskfile.yml
  build/mongod_secured.conf
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  ferretdb/ferretdb_test.go
  integration/commands_diagnostic_test.go
  integration/embedded_test.go
  integration/setup/common.go
  integration/setup/setup_tls.go
  internal/clientconn/listener.go
  website/docs/flags.md
  website/docs/security.md
Labels: code/feature

#1770 Skip incompatible tests on `arm64`
  integration/query_bitwise_test.go
Labels: code/chore

#1766 Fix filterering in `distinct` for Tigris handler
  integration/commands_administration_test.go
  integration/distinct_compat_test.go
  integration/query_element_compat_test.go
  integration/shareddata/composites.go
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_distinct.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_findandmodify.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/tjson/array_test.go
Labels: code/bug

#1786 Minor cleanups
  .github/workflows/conform-pr.yml
  .github/workflows/docker.yml
  Taskfile.yml
  build/nfpm.yaml
  docker-compose.yml
  internal/handlers/common/msg_listcommands.go
  website/docs/flags.md
Labels: code/chore, trust

#1785 Bump deps
  Dockerfile
  build/.trivyignore
  build/deps/cockroach.Dockerfile
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/legacy-mongo-shell.Dockerfile
  build/deps/tigris.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps, trust

#1788 Build Docker images for tags
  .github/workflows/docker.yml
Labels: code/chore, no ci

#1753 Support `$rename` field update operator
  Taskfile.yml
  integration/shareddata/scalars.go
  integration/update_field_compat_test.go
  internal/handlers/common/error.go
  internal/handlers/common/errorcode_string.go
  internal/handlers/common/update.go
  internal/types/path.go
Labels: code/feature

#1794 Fix links from docs to blog
  website/docusaurus.config.js
Labels: documentation

#1778 Enable support for arrays in Tigris
  Taskfile.yml
  integration/commands_administration_test.go
  integration/query_array_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_projection_compat_test.go
  integration/shareddata/composites.go
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/tigris/tigrisdb/query.go
  internal/types/array_iterator.go
  internal/types/document_iterator.go
Labels: code/feature

#1792 Reformat documentation
  .gitattributes
  .github/workflows/docker.yml
  .github/workflows/docs-preview.yml
  .github/workflows/docs.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  .github/workflows/packages.yml
  .github/workflows/security.yml
  website/blog/2022-10-06-how-to-start-ferretdb-locally-with-docker.md
  website/blog/2022-10-12-contribute_to_ferretdb_on_windows.md
  website/blog/2022-11-08-pjson-how-to-store-bson-in-jsonb.md
  website/blog/authors.yml
Labels: documentation, trust

#1798 Add comments about Git LFS and `lfs-warning`
  .github/workflows/docker.yml
  .github/workflows/docs-preview.yml
  .github/workflows/docs.yml
  Taskfile.yml
  build/deps/ferretdb-wrangler.Dockerfile
Labels: documentation, code/chore, trust

#1793 Simplify `types.Array` `Append` signature
  internal/bson/array.go
  internal/handlers/common/distinct.go
  internal/handlers/common/error_write.go
  internal/handlers/common/msg_connectionstatus.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/pg/msg_listdatabases.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pjson/array.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_getlog.go
  internal/handlers/tigris/msg_listcollections.go
  internal/handlers/tigris/msg_listdatabases.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/tjson/array.go
  internal/types/array.go
  internal/types/array_test.go
  internal/util/logging/buffer.go
  internal/wire/op_msg.go
Labels: code/chore

#1790 Integrate `explain` into tests
  integration/commands_administration_test.go
  integration/query_array_compat_test.go
  integration/query_compat_test.go
  integration/query_projection_compat_test.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/tigris/msg_explain.go
  internal/types/path.go
  internal/types/path_test.go
  internal/util/testutil/path_test.go
Labels: code/chore

#1795 Fix error types and array handling when dot notation is used with `$set` operator
  integration/update_field_compat_test.go
  integration/update_field_test.go
  internal/handlers/common/update.go
  internal/types/document.go
  internal/types/document_test.go
  internal/types/path.go
Labels: code/bug

#1812 Remove lazy connection pools
  cmd/envtool/envtool.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/pg.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/tigris/msg_collstats.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_create.go
  internal/handlers/tigris/msg_datasize.go
  internal/handlers/tigris/msg_dbstats.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_distinct.go
  internal/handlers/tigris/msg_drop.go
  internal/handlers/tigris/msg_dropdatabase.go
  internal/handlers/tigris/msg_explain.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_findandmodify.go
  internal/handlers/tigris/msg_getlog.go
  internal/handlers/tigris/msg_hello.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_ismaster.go
  internal/handlers/tigris/msg_listcollections.go
  internal/handlers/tigris/msg_listdatabases.go
  internal/handlers/tigris/msg_ping.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/tigris.go
  internal/handlers/tigris/tigrisdb/tigrisdb.go
  internal/handlers/tigris/tigrisdb/tigrisdb_test.go
Labels: code/chore

#1760 Support `$mul` field update operator
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  internal/handlers/common/params.go
  internal/handlers/common/update.go
  internal/types/document_validation.go
  internal/types/document_validation_test.go
  internal/wire/op_msg_test.go
  internal/wire/validation.go
  website/docs/diff.md
  website/docs/reference/supported_commands.md
Labels: documentation, code/feature, trust

#1796 Fix internal links and images
  website/blog/2021-11-05-mangodb-overwhelming-enthusiasm.md
  website/blog/2021-12-01-mangodb-has-a-new-name.md
  website/blog/2021-12-07-mongodb-compatibility.md
  website/blog/2022-04-18-ferretdb-v-0-1-1-is-out-and-other-exciting-updates.md
  website/blog/2022-05-16-using-cla-assistant-with-ferretdb.md
  website/blog/2022-06-27-developers-need-ferretdb-stackoverflow-developer-survey-2022.md
  website/blog/2022-06-28-new-release-ferretdb-0-4-0.md
  website/blog/2022-07-11-0-5-0-release-is-out-embedding-ferretdb-into-go-programs.md
  website/blog/2022-07-27-new-ferretdb-minor-release-0-5-1.md
  website/blog/2022-08-23-open-source-is-in-danger.md
  website/blog/2022-09-20-how-to-contribute-to-open-source-2022.md
  website/blog/2022-09-21-how-to-keep-control-of-your-infra-using-ferretdb-and-tigris.md
  website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md
  website/blog/2022-10-06-how-to-start-ferretdb-locally-with-docker.md
  website/blog/2022-10-12-contribute_to_ferretdb_on_windows.md
  website/blog/2022-10-28-5-ways-to-avoid-database-vendor-lock-in.md
  website/blog/2022-11-08-pjson-how-to-store-bson-in-jsonb.md
  website/blog/2022-11-11-new-release-ferretdb-0_6_1.md
  website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.md
  website/blog/2022-11-18-ferretdb-percona-university-event-istanbul.md
  website/blog/2022-11-21-ferretdb-0-6-2-version-release.md
  website/blog/2022-12-23-ferretdb-new-release-with-tls.md
  website/static/img/blog/3g0okbkcve391.jpg
  website/static/img/blog/4ferrets.webp
  website/static/img/blog/BSS_1319-1024x684.jpg
  website/static/img/blog/Maintainer@5x-1-300x300.png
  website/static/img/blog/TLS.webp
  website/static/img/blog/allen-cai-Y4RxCIaYaSk-unsplash-1024x683.jpg
  website/static/img/blog/blog-img-v02.jpg
  website/static/img/blog/blog-img.png
  website/static/img/blog/cf73bb31-fa1b-4465-8277-e73da46127de-1650484034538-1-300x120.png
  website/static/img/blog/christian-wiediger-WkfDrhxDMC8-unsplash-1024x683.jpg
  website/static/img/blog/cla1.jpg
  website/static/img/blog/cla2.jpg
  website/static/img/blog/cla3.jpg
  website/static/img/blog/ferret_rpi-1-1024x390.png
  website/static/img/blog/group-1024x679.jpg
  website/static/img/blog/group-of-ferrets-on-white.jpg
  website/static/img/blog/hacktoberfest.jpg
  website/static/img/blog/home-img.jpg
  website/static/img/blog/image1-1.png
  website/static/img/blog/image2.png
  website/static/img/blog/image3.png
  website/static/img/blog/image4-1024x683.jpg
  website/static/img/blog/image5.png
  website/static/img/blog/image6.png
  website/static/img/blog/image7.png
  website/static/img/blog/markus-spiske-iar-afB0QQw-unsplash-1024x683.jpg
  website/static/img/blog/masaaki-komori-_we0BQQewBo-unsplash-1024x684.jpg
  website/static/img/blog/perconalive.png
  website/static/img/blog/rescue-kitten-komari-ferret-brothers-47.jpg
  website/static/img/blog/six_ferrets-1024x917.jpg
  website/static/img/blog/stackoverflow.jpg
  website/static/img/blog/uriel-sc-11KDtiUWRq4-unsplash-1024x680.jpg
Labels: documentation, trust

#1787 Fix `$inc` operator panics for non-existing array index
  integration/update_field_compat_test.go
Labels: code/bug

#1804 Add Go execution tracing for tests
  .gitignore
  CONTRIBUTING.md
  go.mod
  integration/basic_test.go
  integration/commands_administration_test.go
  integration/create_test.go
  integration/delete_test.go
  integration/findandmodify_test.go
  integration/query_test.go
  integration/setup/common.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  internal/clientconn/conn.go
  internal/util/debug/debug.go
  internal/util/testutil/testutil.go
Labels: code/chore

#1818 Retry transaction more times and log retries
  internal/handlers/pg/pgdb/transactions.go
  internal/handlers/tigris/tigrisdb/databases.go
Labels: code/chore

#1820 Tweak documentation about flags
  .github/RELEASE_CHECKLIST.md
  Dockerfile
  internal/handlers/pg/pgdb/transactions.go
  website/docs/flags.md
Labels: documentation, trust

#1814 Fix `$set` operator to apply correct comparison
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  internal/handlers/common/update.go
  internal/types/identical.go
Labels: code/bug

#1813 Add blog post about FerretDB v0.8.1 release
  website/blog/2023-01-17-ferretdb-0-8-1-version-release.md
  website/static/img/blog/FerretDB_v0.8.1.jpg
Labels: documentation, trust

#1815 Add blog post on FerretDB beta release 0.8.0
  website/blog/2023-01-04-ferretdb-beta-version-authentication.md
  website/static/img/blog/FerretDB-is-now-Beta.-1-980x551.png
Labels: documentation, trust

#1826 Add basic documentation writing guide
  CONTRIBUTING.md
  website/blog/_guide/template.md
  website/docs/basic_operations/index.md
  website/docs/contributing/_category_.json
  website/docs/contributing/contributing.md
  website/docs/contributing/writing-guide.md
  website/docs/flags.md
  website/docs/main.md
  website/docs/operation_modes.md
  website/docs/reference/glossary.md
  website/docs/reference/operators/comparison-operators.md
  website/docs/reference/supported_commands.md
  website/docs/security.md
  website/docs/understanding_ferretdb.md
Labels: documentation, trust

#1810 Migrate to Tigris `beta.27`
  Taskfile.yml
  build/deps/tigris.Dockerfile
  integration/query_array_compat_test.go
  integration/query_comparison_compat_test.go
  integration/shareddata/composites.go
  integration/shareddata/scalars.go
  integration/shareddata_test.go
Labels: code/chore

#1837 Remove `ListenerOpts` from another `ListenerOpts`
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  ferretdb/ferretdb_test.go
  integration/embedded_test.go
  integration/setup/common.go
  internal/clientconn/listener.go
Labels: code/chore

#1819 Support `$push` array update operator
  Taskfile.yml
  integration/commands_administration_test.go
  integration/distinct_compat_test.go
  integration/query_comparison_compat_test.go
  integration/shareddata/composites.go
  integration/shareddata/shareddata.go
  integration/shareddata_test.go
  integration/update_array_compat_test.go
  integration/update_field_compat_test.go
  internal/handlers/common/update.go
  internal/handlers/common/update_array_operators.go
  website/docs/reference/supported_commands.md
Labels: code/feature

#1817 Update docker deployment documentation
  README.md
  website/docs/quickstart_guide/docker.md
Labels: documentation, trust

#1832 Update CONTRIBUTING.md for test data tip
  CONTRIBUTING.md
Labels: code/chore

#1847 Reformat Markdown tables
  website/docs/reference/supported_commands.md
Labels: documentation

#1849 Tiny cleanups
  internal/clientconn/conn.go
  internal/handlers/handlers.go
  internal/wire/validation.go
Labels: code/chore

#1851 Update development documentation
  .github/ISSUE_TEMPLATE/chore.yml
  .github/PROCESS.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: code/chore

#1852 Set default `pool_max_conns` to 20 for PostgreSQL
  internal/handlers/pg/pg.go
  internal/handlers/pg/pgdb/pool.go
Labels: code/enhancement

#1839 Reformat blog and documentation setup
  website/blog/2021-11-05-mangodb-overwhelming-enthusiasm.md
  website/blog/2021-12-01-mangodb-has-a-new-name.md
  website/blog/2021-12-07-mongodb-compatibility.md
  website/blog/2022-04-18-ferretdb-v-0-1-1-is-out-and-other-exciting-updates.md
  website/blog/2022-05-16-using-cla-assistant-with-ferretdb.md
  website/blog/2022-06-27-developers-need-ferretdb-stackoverflow-developer-survey-2022.md
  website/blog/2022-06-28-new-release-ferretdb-0-4-0.md
  website/blog/2022-07-11-0-5-0-release-is-out-embedding-ferretdb-into-go-programs.md
  website/blog/2022-07-27-new-ferretdb-minor-release-0-5-1.md
  website/blog/2022-08-23-open-source-is-in-danger.md
  website/blog/2022-09-20-how-to-contribute-to-open-source-2022.md
  website/blog/2022-09-21-how-to-keep-control-of-your-infra-using-ferretdb-and-tigris.md
  website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md
  website/blog/2022-10-06-how-to-start-ferretdb-locally-with-docker.md
  website/blog/2022-10-12-contribute_to_ferretdb_on_windows.md
  website/blog/2022-10-28-5-ways-to-avoid-database-vendor-lock-in.md
  website/blog/2022-11-08-pjson-how-to-store-bson-in-jsonb.md
  website/blog/2022-11-11-new-release-ferretdb-0_6_1.md
  website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.md
  website/blog/2022-11-18-ferretdb-percona-university-event-istanbul.md
  website/blog/2022-11-21-ferretdb-0-6-2-version-release.md
  website/blog/2022-12-23-ferretdb-new-release-with-tls.md
  website/blog/2023-01-04-ferretdb-beta-version-authentication.md
  website/blog/2023-01-17-ferretdb-0-8-1-version-release.md
  website/docs/reference/_category_.json
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
  website/static/img/logo_dark.jpg
  website/static/img/logo_dark.png
Labels: documentation, trust

#1861 Clarify what command statistics we gather
  internal/clientconn/connmetrics/conn_metrics.go
  internal/util/telemetry/reporter.go
  website/docs/telemetry.md
Labels: documentation, trust

#1853 Add blog post on "How FerretDB fetches data (About query pushdown)"
  website/blog/2023-01-25-ferretdb-fetches-data-query-pushdown.md
  website/static/img/blog/ferretdb-query-pushdown.jpg
Labels: documentation

#1809 Support PostgreSQL pushdowns for numbers
  integration/basic_test.go
  integration/benchmarks_test.go
  integration/commands_administration_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/setup/common.go
  internal/handlers/pg/pgdb/query.go
Labels: code/feature

#1856 Ensure that we don't import extra dependencies
  Dockerfile
  Taskfile.yml
  build/version/version.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/handlers/registry/hana.go
  internal/handlers/registry/registry_test.go
Labels: code/chore

#1872 Extract handler errors into own package
  internal/handlers/common/commonerrors.go
  internal/handlers/common/filter.go
  internal/handlers/common/setfreemonitoring.go
  internal/handlers/commonerrors/command.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/commonerrors/write.go
Labels: code/chore

#1870 Run query compat tests on same collection
  integration/query_array_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_element_compat_test.go
  integration/query_evaluation_compat_test.go
  integration/query_logical_compat_test.go
  integration/query_projection_compat_test.go
  integration/shareddata/scalars.go
Labels: code/chore

#1859 Add content creation process for documentation and blog
  website/blog/_guide/YYYY-MM-DD.blog-template.md
  website/blog/_guide/content-process.md
  website/blog/_guide/template.md
  website/docs/contributing/writing-guide.md
Labels: documentation

#1879 Mention that there is no configuration file
  website/docs/flags.md
  website/docs/quickstart_guide/debian.md
Labels: documentation, trust

#1874 Truncate blog post display
  website/blog/2023-01-25-ferretdb-fetches-data-query-pushdown.md
Labels: documentation

#1881 Fix `InTransaction` helper's edge case
  internal/handlers/pg/pgdb/transactions.go
  internal/handlers/pg/pgdb/transactions_test.go
Labels: code/chore

#1871 Improve insert in Tigris by using single query for multiple documents
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/tigrisdb/insert.go
Labels: code/chore

#1883 Unify reply code in handlers
  internal/handlers/common/commonerrors.go
  internal/handlers/common/getfreemonitoringstatus.go
  internal/handlers/common/setfreemonitoring.go
  internal/handlers/common/validate.go
  internal/handlers/dummy/dummy.go
  internal/handlers/dummy/msg_validate.go
  internal/handlers/pg/msg_collstats.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_createindexes.go
  internal/handlers/pg/msg_datasize.go
  internal/handlers/pg/msg_dbstats.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_distinct.go
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/msg_dropdatabase.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/pg/msg_getparameter.go
  internal/handlers/pg/msg_hello.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_ismaster.go
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/pg/msg_listdatabases.go
  internal/handlers/pg/msg_ping.go
  internal/handlers/pg/msg_update.go
  internal/handlers/tigris/msg_collstats.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_datasize.go
  internal/handlers/tigris/msg_dbstats.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_distinct.go
  internal/handlers/tigris/msg_drop.go
  internal/handlers/tigris/msg_dropdatabase.go
  internal/handlers/tigris/msg_explain.go
  internal/handlers/tigris/msg_getlog.go
  internal/handlers/tigris/msg_getparameter.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_update.go
Labels: code/chore

#1864 Pushdown SQL queries with dot notation
  integration/query_array_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_test.go
  integration/shareddata/composites.go
  integration/shareddata/shareddata.go
  integration/shareddata_test.go
  internal/handlers/pg/pgdb/query.go
Labels: code/feature

#1882 Make iterator interface more strict
  build/version/version.go
  internal/handlers/common/update.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/tigris/tigrisdb/insert.go
  internal/types/array_iterator.go
  internal/types/array_iterator_test.go
  internal/types/document_iterator.go
  internal/types/document_iterator_test.go
  internal/types/document_test.go
  internal/util/debugbuild/debugbuild.go
  internal/util/debugbuild/debugbuild_off.go
  internal/util/debugbuild/debugbuild_on.go
  internal/util/debugbuild/debugbuild_test.go
  internal/util/iterator/iterator.go
Labels: code/chore

#1895 Prepare v0.9.0 release
  .github/PROCESS.md
  CHANGELOG.md
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_saslstart.go
Labels: documentation, code/chore, trust, docker
