Repository FerretDB/FerretDB, pull requests merged in 2023-03, with the labels that each got.

#2068 Temporarily remove pushdown for dot notation
  integration/query_array_compat_test.go
  integration/query_comparison_compat_test.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/tigris/tigrisdb/query.go
  internal/handlers/tigris/tigrisdb/query_test.go
Labels: code/chore

#2073 Restructure documentation
  website/docs/operators/_category_.json
  website/docs/operators/query_operators/_category_.json
  website/docs/operators/query_operators/array-operators.md
  website/docs/operators/query_operators/bitwise-operators.md
  website/docs/operators/query_operators/comparison-operators.md
  website/docs/operators/query_operators/element-operators.md
  website/docs/operators/query_operators/evaluation-operators.md
  website/docs/operators/query_operators/logical-operators.md
  website/docs/reference/operators/_category_.json
Labels: documentation

#2087 Set `retention-days` for all CI artifacts
  .github/workflows/docs.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  .github/workflows/packages.yml
Labels: code/chore

#2009 Relax validation rules a bit
  internal/handlers/pg/pgdb/databases.go
  internal/types/document_validation.go
  internal/types/document_validation_test.go
  website/docs/diff.md
Labels: code/enhancement

#2041 Bump deps
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/types/regex.go
  tools/go.mod
  tools/go.sum
Labels: deps

#2072 Add dot notation support for `$max` and `$min`
  integration/update_field_compat_test.go
  internal/handlers/common/update.go
Labels: code/bug

#2091 Improve social preview for Security page
  Taskfile.yml
  website/blog/2023-02-28-ferretdb-release-0-9-2.md
  website/blog/_guide/YYYY-MM-DD.blog-template.md
  website/docs/security.md
Labels: documentation, trust

#2085 Support aggregation pipeline for Tigris
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/tigris/msg_aggregate.go
Labels: code/feature

#2098 Use Go 1.20
  .github/ISSUE_TEMPLATE/bug.yml
  CONTRIBUTING.md
  Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/check.go
  tools/go.mod
  tools/old.go
  tools/tools.go
Labels: deps, trust, docker

#2107 Small cleanups
  .codecov.yml
  .github/workflows/js.yml
  .gitignore
  Taskfile.yml
  cmd/ferretdb/main_test.go
  integration/Taskfile.yml
  integration/setup/listener.go
  integration/setup/setup.go
  internal/wire/wire_test.go
Labels: code/chore

#2071 Initial setup of `hana` handler
  internal/handlers/hana/cmd_query.go
  internal/handlers/hana/hana.go
  internal/handlers/hana/hana_test.go
  internal/handlers/hana/msg_aggregate.go
  internal/handlers/hana/msg_buildinfo.go
  internal/handlers/hana/msg_collmod.go
  internal/handlers/hana/msg_collstats.go
  internal/handlers/hana/msg_connectionstatus.go
  internal/handlers/hana/msg_count.go
  internal/handlers/hana/msg_create.go
  internal/handlers/hana/msg_createindexes.go
  internal/handlers/hana/msg_currentop.go
  internal/handlers/hana/msg_datasize.go
  internal/handlers/hana/msg_dbstats.go
  internal/handlers/hana/msg_debugerror.go
  internal/handlers/hana/msg_delete.go
  internal/handlers/hana/msg_distinct.go
  internal/handlers/hana/msg_drop.go
  internal/handlers/hana/msg_dropdatabase.go
  internal/handlers/hana/msg_explain.go
  internal/handlers/hana/msg_find.go
  internal/handlers/hana/msg_findandmodify.go
  internal/handlers/hana/msg_getcmdlineopts.go
  internal/handlers/hana/msg_getfreemonitoringstatus.go
  internal/handlers/hana/msg_getlog.go
  internal/handlers/hana/msg_getmore.go
  internal/handlers/hana/msg_getparameter.go
  internal/handlers/hana/msg_hello.go
  internal/handlers/hana/msg_hostinfo.go
  internal/handlers/hana/msg_insert.go
  internal/handlers/hana/msg_ismaster.go
  internal/handlers/hana/msg_listcollections.go
  internal/handlers/hana/msg_listcommands.go
  internal/handlers/hana/msg_listdatabases.go
  internal/handlers/hana/msg_listindexes.go
  internal/handlers/hana/msg_ping.go
  internal/handlers/hana/msg_saslstart.go
  internal/handlers/hana/msg_serverstatus.go
  internal/handlers/hana/msg_setfreemonitoring.go
  internal/handlers/hana/msg_update.go
  internal/handlers/hana/msg_validate.go
  internal/handlers/hana/msg_whatsmyuri.go
Labels: code/chore

#2112 Checkout named branch
  .github/workflows/debug.yml
  .github/workflows/docker.yml
  .github/workflows/docs-preview.yml
Labels: code/chore

#2113 Remove CI optimization that does not work
  .github/workflows/debug.yml
  .github/workflows/docker.yml
  .github/workflows/docs-preview.yml
  .github/workflows/docs.yml
  Taskfile.yml
Labels: code/chore

#2094 Fix `$mul` operator handling dot notation
  integration/shareddata/composites.go
  integration/update_field_compat_test.go
  internal/handlers/common/update.go
  internal/types/path.go
Labels: code/bug

#2119 Add lowercase variant of `dbstats`
  internal/handlers/common/msg_listcommands.go
Labels: code/bug

#2030 Fix querying an embedded field in array
  integration/distinct_compat_test.go
  integration/query_array_compat_test.go
  internal/handlers/common/distinct.go
  internal/handlers/common/filter.go
Labels: code/bug

#2099 Add aggregation pipeline compat tests and fix errors
  integration/aggregate_compat_test.go
  internal/handlers/common/aggregations/count.go
  internal/handlers/common/aggregations/match.go
  internal/handlers/common/aggregations/sort.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/tigris/msg_aggregate.go
Labels: code/chore

#2152 Test that version is set correctly
  .github/workflows/go.yml
  .github/workflows/js.yml
  cmd/ferretdb/version_test.go
Labels: code/chore

#1880 Pushdown `$eq` query operator
  integration/query_comparison_compat_test.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/tigris/tigrisdb/query.go
  internal/handlers/tigris/tigrisdb/query_test.go
Labels: code/feature

#2122 Fix dot notation errors
  integration/update_field_compat_test.go
  internal/handlers/common/update.go
Labels: code/bug

#2154 Update aggregation in supported command document
  website/docs/reference/supported_commands.md
Labels: documentation

#2145 Pushdown `$ne` query operator for PostgreSQL
  integration/query_comparison_compat_test.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/pg/pjson/schema.go
  internal/handlers/pg/pjson/schema_test.go
Labels: code/feature

#2048 Create unqiue index for `_id` automatically
  Taskfile.yml
  integration/basic_test.go
  integration/insert_compat_test.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/database_metadata.go
  internal/handlers/pg/pgdb/database_metadata_test.go
  internal/handlers/pg/pgdb/delete.go
  internal/handlers/pg/pgdb/indexes.go
  internal/handlers/pg/pgdb/insert.go
  internal/handlers/pg/pgdb/pgdb.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/update.go
Labels: code/feature

#2164 Fix `saslStart` for particular clients
  internal/handlers/pg/msg_saslstart.go
Labels: code/bug

#2169 Document explicit telemetry sharing
  internal/handlers/common/aggregations/stage.go
  website/docs/telemetry.md
Labels: documentation, trust

#2176 Bump deps, minor cleanup
  .github/ISSUE_TEMPLATE/bug.yml
  .gitignore
  build/deps/tigris.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/handlers/tigris/tjson/datetime.go
  internal/types/object_id.go
  tools/go.mod
  tools/go.sum
Labels: deps, code/chore

#2181 Refactor common `saslStart` code
  internal/handlers/common/saslstart.go
  internal/handlers/dummy/msg_saslstart.go
  internal/handlers/hana/msg_saslstart.go
  internal/handlers/pg/msg_saslstart.go
  internal/handlers/tigris/msg_saslstart.go
Labels: code/chore

#2144 Use `stringer` for "enums"
  internal/handlers/common/update.go
  internal/types/document_validation.go
  internal/types/documentpatherrorcode_string.go
  internal/types/path.go
  internal/types/validationerrorcode_string.go
Labels: code/chore

#2182 Disable race detector on arm64
  .github/workflows/docs.yml
  .gitignore
  build/docker/development.Dockerfile
Labels: code/chore, trust, docker, packages

#2151 Support `$group` aggregation stage
  integration/aggregate_compat_test.go
  integration/shareddata/scalars.go
  internal/handlers/common/aggregations/count.go
  internal/handlers/common/aggregations/group.go
  internal/handlers/common/aggregations/stage.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
Labels: code/feature

#2188 Update supported command document for `$group` aggregation operator
  website/docs/reference/supported_commands.md
Labels: documentation

#2195 Merge and speedup packages building
  .github/workflows/docker.yml
  .github/workflows/packages.yml
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
Labels: code/chore

#2183 Provide "all-in-one" Docker image
  Taskfile.yml
  build/docker/all-in-one.Dockerfile
Labels: code/chore

#2192 Improve logging of retries
  internal/handlers/pg/pgdb/transactions.go
Labels: code/chore

#2189 Split `TestQueryCompatRunner` back into separate tests
  integration/query_array_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_element_compat_test.go
  integration/query_evaluation_compat_test.go
  integration/query_logical_compat_test.go
  integration/query_projection_compat_test.go
Labels: code/chore

#2156 Support dot notation in sorting
  Taskfile.yml
  integration/aggregate_compat_test.go
  integration/findandmodify_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/shareddata/composites.go
  internal/handlers/common/aggregations/sort.go
  internal/handlers/common/sort_documents.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_findandmodify.go
Labels: code/feature

#2197 Improve build cache usage
  Taskfile.yml
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
Labels: code/chore, trust, packages

#2203 Use `runit` for all-in-one Docker image
  .dockerignore
  Taskfile.yml
  build/docker/all-in-one.Dockerfile
  build/docker/all-in-one/entrypoint.sh
  build/docker/all-in-one/ferretdb.sh
  build/docker/all-in-one/postgresql.sh
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
Labels: code/chore, trust, packages

#2193 Support `skip` argument for `find` and `count`
  integration/count_compat_test.go
  integration/query_compat_test.go
  internal/handlers/common/find.go
  internal/handlers/common/skip.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_find.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_find.go
  website/docs/reference/supported_commands.md
Labels: code/enhancement

#2187 Add support for `$each` modifier to `$addToSet` array update operator
  integration/update_array_compat_test.go
  internal/handlers/common/update_array_operators.go
Labels: code/feature

#2223 Skip a `$mod` test for arm64
  integration/query_evaluation_compat_test.go
Labels: code/chore

#2215 Add documentation for `all-in-one` Docker image
  .github/RELEASE_CHECKLIST.md
  README.md
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/legacy-mongo-shell.Dockerfile
  build/deps/mongo6.Dockerfile
  build/deps/trivy.Dockerfile
  build/docker/all-in-one.Dockerfile
  build/docker/all-in-one/entrypoint.sh
  build/nfpm.yaml
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  website/blog/2023-03-14-ferretdb-v-0-9-3.md
  website/docs/main.md
  website/docs/quickstart_guide/docker.md
Labels: documentation

#2228 Tweak Docker docs a bit
  README.md
  website/docs/quickstart_guide/docker.md
Labels: documentation, trust

#2211 Fix `env-data` Taskfile
  .github/workflows/integration.yml
  CONTRIBUTING.md
  integration/Taskfile.yml
  integration/shareddata/shareddata.go
  integration/shareddata_test.go
Labels: code/chore

#2180 Add section about field update operators
  website/docs/operators/update_operators/_category_.json
  website/docs/operators/update_operators/field-update-operators.md
Labels: documentation

#2214 Make `listIndexes` use data from the database
  internal/handlers/pg/msg_listindexes.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/database_metadata.go
  internal/handlers/pg/pgdb/indexes.go
Labels: code/chore

#2233 Tweak dependabot config
  .github/dependabot.yml
Labels: code/chore

#2234 Fix `hana` and `tigris` handlers initialization
  cmd/ferretdb/main_hana.go
  cmd/ferretdb/main_tigris.go
Labels: code/bug

#2242 Add basic security policy
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/chore.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature.yml
  SECURITY.md
Labels: documentation

#2222 Add support for `$pull` array update operator
  integration/update_array_compat_test.go
  internal/handlers/common/update.go
  internal/handlers/common/update_array_operators.go
Labels: code/feature

#2245 Filter documents with iterators
  internal/clientconn/conninfo/conn_info.go
  internal/handlers/common/filter.go
  internal/handlers/common/filter_iterator.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/tigris/msg_aggregate.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/tigrisdb/query.go
  internal/handlers/tigris/tigrisdb/query_iterator.go
  internal/types/document.go
  internal/types/document_iterator_test.go
  internal/types/documents_iterator.go
Labels: code/chore

#2146 Add new blog post - MongoDB vs PostgreSQL
  website/blog/2023-03-21-mongodb-vs-postgresql.md
  website/static/img/blog/mongodb-postgres.jpg
Labels: documentation

#2232 Fix long overflow detection on `$mul`
  internal/handlers/common/params.go
  internal/handlers/common/params_test.go
Labels: code/bug

#2239 Change collection names mangling for PostgreSQL
  integration/basic_test.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/database_metadata.go
  website/docs/diff.md
Labels: code/enhancement

#2237 Document array update operator
  website/docs/operators/update_operators/array-update-operators.md
Labels: documentation

#2267 Fix traffic recording
  internal/clientconn/conn.go
Labels: code/chore

#2264 Bump deps
  .github/mergify.yml
  .github/workflows/conform-pr.yml
  .github/workflows/debug.yml
  .github/workflows/docs.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  .github/workflows/packages.yml
  .github/workflows/security.yml
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: code/chore

#2224 Collection deletion and metadata refactoring
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/database_metadata.go
  internal/handlers/pg/pgdb/database_metadata_test.go
  internal/handlers/pg/pgdb/delete.go
  internal/handlers/pg/pgdb/indexes.go
  internal/handlers/pg/pgdb/insert.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/schemas.go
  internal/handlers/pg/pgdb/update.go
Labels: code/chore

#2274 Update diff.md for database name differences
  integration/basic_test.go
  website/docs/diff.md
Labels: code/chore

#2278 Remove indexes from `DocumentsIterator`
  internal/handlers/common/filter_iterator.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/tigris/msg_aggregate.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/tigrisdb/query_iterator.go
  internal/handlers/tigris/tigrisdb/query_test.go
  internal/types/documents_iterator.go
Labels: code/chore

#2277 Bump Tigris to 1.0.0-beta.51
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#2247 Implement `nameOnly` for `listCollections` command
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/tigris/msg_listcollections.go
Labels: code/enhancement

#2263 Extract dollar path field expression to types package
  integration/aggregate_compat_test.go
  integration/shareddata/composites.go
  integration/shareddata/shareddata.go
  internal/handlers/common/aggregations/group.go
  internal/handlers/common/aggregations/group_count.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/types/compare.go
  internal/types/expression.go
  internal/types/expressionerrorcode_string.go
Labels: code/enhancement

#2254 Use iterators for `sort`, `limit`, `skip`, and `projection`
  integration/count_compat_test.go
  integration/distinct_compat_test.go
  integration/query_compat_test.go
  internal/handlers/common/aggregations/group.go
  internal/handlers/common/aggregations/stage.go
  internal/handlers/common/find.go
  internal/handlers/common/limit.go
  internal/handlers/common/limit_iterator.go
  internal/handlers/common/projection.go
  internal/handlers/common/projection_iterator.go
  internal/handlers/common/skip.go
  internal/handlers/common/skip_iterator.go
  internal/handlers/common/sort.go
  internal/handlers/common/sort_iterator.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
  internal/handlers/tigris/msg_aggregate.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_explain.go
  internal/handlers/tigris/msg_find.go
  internal/types/documents_iterator.go
  internal/util/iterator/close.go
  internal/util/iterator/iterator.go
  internal/util/iterator/iterator_test.go
  internal/util/iterator/slice.go
  internal/util/iterator/values.go
Labels: code/chore

#2307 Bump dependencies
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#2292 Support `$sum` accumulator of `$group` aggregation
  integration/aggregate_compat_test.go
  integration/shareddata/scalars.go
  integration/shareddata/shareddata.go
  integration/update_field_compat_test.go
  internal/handlers/common/aggregations/group.go
  internal/handlers/common/aggregations/group_sum.go
  internal/handlers/common/aggregations/number.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
Labels: code/feature

#2318 Update supported command for `$sum` aggregation operator
  website/docs/reference/supported_commands.md
Labels: documentation

#2323 Add supported shells and GUIs images
  website/static/img/guis/3t_aggregation.png
  website/static/img/guis/3t_auth.png
  website/static/img/guis/3t_conntest.png
  website/static/img/guis/3t_csv_file.png
  website/static/img/guis/3t_insert.png
  website/static/img/guis/3t_tls.png
  website/static/img/guis/compass_csv_file.png
  website/static/img/guis/compass_find.png
  website/static/img/guis/dbeaver_connection.png
  website/static/img/guis/dbeaver_sql.png
  website/static/img/guis/dbeaver_ssl.png
  website/static/img/guis/dbeaver_view_data.png
  website/static/img/guis/logo_light.png
  website/static/img/guis/mingo_connstr.png
  website/static/img/guis/mingo_csv_file.png
  website/static/img/guis/mingo_find.png
  website/static/img/guis/mingo_nodeshell.png
  website/static/img/guis/mongosh.png
  website/static/img/guis/nosqlbooster_connstr.png
  website/static/img/guis/nosqlbooster_conntest.png
  website/static/img/guis/nosqlbooster_csv_file.png
  website/static/img/guis/nosqlbooster_export_csv.png
  website/static/img/guis/nosqlbooster_find.png
  website/static/img/guis/nosqlbooster_or.png
  website/static/img/guis/vscode_aggregation.png
  website/static/img/guis/vscode_connstr.png
Labels: documentation, no ci

#2319 Improve resource tracking
  internal/clientconn/conn.go
  internal/clientconn/conninfo/conn_info.go
  internal/clientconn/conninfo/cursor.go
  internal/clientconn/listener.go
  internal/handlers/common/aggregations/group.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/pg/pgdb/transactions.go
  internal/handlers/tigris/tigrisdb/query_iterator.go
  internal/handlers/tigris/tigrisdb/query_test.go
  internal/types/array_iterator.go
  internal/types/document_iterator.go
  internal/util/iterator/iterator_test.go
  internal/util/iterator/slice.go
  internal/util/iterator/values.go
  internal/util/resource/resource.go
  internal/util/telemetry/reporter.go
Labels: code/chore

#2309 Add basic `getMore` command
  .github/workflows/integration.yml
  Taskfile.yml
  cmd/ferretdb/main.go
  docker-compose.yml
  integration/query_compat_test.go
  integration/setup/listener.go
  integration/setup/setup.go
  internal/clientconn/conninfo/conn_info.go
  internal/clientconn/cursor/cursor.go
  internal/clientconn/cursor/registry.go
  internal/handlers/common/getmore.go
  internal/handlers/common/msg_getmore.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_getmore.go
  internal/handlers/pg/pg.go
  internal/handlers/registry/registry.go
  internal/handlers/registry/tigris.go
  internal/handlers/tigris/msg_dbstats.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_getmore.go
  internal/handlers/tigris/tigris.go
  internal/util/iterator/values.go
Labels: code/feature

#2325 Add tests for `find`'s and `count`'s `skip` argument
  integration/count_compat_test.go
  integration/query_compat_command_test.go
  integration/query_compat_test.go
  internal/handlers/common/params.go
  internal/handlers/common/skip.go
  internal/handlers/common/skip_iterator.go
Labels: code/chore

#2313 Implement `dropIndexes` command
  integration/indexes_compat_test.go
  internal/handlers/common/msg_listcommands.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/dummy/msg_dropindexes.go
  internal/handlers/hana/msg_dropindexes.go
  internal/handlers/handlers.go
  internal/handlers/pg/msg_createindexes.go
  internal/handlers/pg/msg_dropindexes.go
  internal/handlers/pg/pgdb/indexes.go
  internal/handlers/pg/pgdb/indexes_test.go
  internal/handlers/pg/pgdb/pgdb.go
  internal/handlers/tigris/msg_dropindexes.go
  website/docs/reference/supported-commands.md
Labels: code/feature
