Repository FerretDB/FerretDB, pull requests merged in 2023-08, with the labels that each got.

#3142 Bump deps
  build/deps/ferretdb-wrangler.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#3143 Improve MongoDB/FerretDB error checking in tests
  .github/RELEASE_CHECKLIST.md
  integration/findandmodify_test.go
  integration/getmore_test.go
  integration/helpers.go
  integration/setup/test_helpers.go
Labels: code/chore

#3147 Expect some `aggregate` and `insert` tests to fail for SQLite
  integration/aggregate_documents_compat_test.go
  integration/insert_compat_test.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/util/testutil/testfail/expected_test.go
Labels: code/chore

#3152 Make administration command integration tests pass for SQLite
  integration/commands_administration_compat_test.go
  integration/commands_administration_test.go
  integration/commands_authentication_test.go
  integration/commands_diagnostic_test.go
Labels: code/chore

#3149 Simplify tests a bit
  integration/aggregate_documents_compat_test.go
  integration/insert_compat_test.go
Labels: code/chore

#3159 Make `distinct` and `explain` command integration tests pass for SQLite
  integration/distinct_compat_test.go
  integration/distinct_test.go
  integration/explain_compat_test.go
Labels: code/chore

#3146 Use lock for SQLite metadata
  internal/backends/doc.go
  internal/backends/sqlite/doc.go
  internal/backends/sqlite/metadata/pool/pool.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/backends/sqlite/sqlite.go
Labels: code/chore

#3087 Use one implementation for finding path values
  integration/aggregate_documents_test.go
  integration/compattestcaseresulttype_string.go
  integration/helpers.go
  internal/backends/error.go
  internal/backends/errorcode_string.go
  internal/handlers/common/aggregations/expression.go
  internal/handlers/common/aggregations/operators/accumulators/sum.go
  internal/handlers/common/aggregations/operators/sum.go
  internal/handlers/common/aggregations/operators/type.go
  internal/handlers/common/aggregations/stages/group.go
  internal/handlers/common/aggregations/stages/projection/projection.go
  internal/handlers/common/aggregations/stages/sort.go
  internal/handlers/common/aggregations/stages/unset.go
  internal/handlers/common/aggregations/stages/unwind.go
  internal/handlers/common/distinct.go
  internal/handlers/common/filter.go
  internal/handlers/common/projection.go
  internal/handlers/common/sort.go
  internal/handlers/common/update.go
  internal/handlers/commonpath/commonpath.go
  internal/handlers/commonpath/commonpath_test.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/sqlite/msg_find.go
  internal/types/array.go
  internal/types/document.go
  internal/types/documentpatherrorcode_string.go
  internal/types/format.go
  internal/types/path.go
  internal/types/path_test.go
  internal/types/patherrorcode_string.go
Labels: code/chore

#3150 Make aggregate documents compat tests pass for SQLite
  integration/aggregate_documents_compat_test.go
Labels: code/chore

#3182 Make `query` integration tests pass for SQLite
  integration/query_test.go
Labels: code/chore

#3173 Make `findAndModify` integration tests pass for SQLite
  integration/findandmodify_compat_test.go
Labels: code/chore

#3185 Make index integration tests pass for SQLite
  integration/indexes_compat_test.go
Labels: code/chore

#3180 Add tests for `$$ROOT` aggregation expression variable
  integration/aggregate_documents_compat_test.go
  integration/aggregate_variables_compat_test.go
Labels: code/chore

#3174 Make `getMore` integration tests pass for SQLite
  integration/getmore_test.go
  integration/indexes_command_compat_test.go
Labels: code/chore

#3184 Make `update` integration tests pass for SQLite
  integration/insert_command_test.go
  integration/update_compat_test.go
Labels: code/chore

#3171 Do not return immutable `_id` error from `findAndModify` for upserting same `_id`
  integration/findandmodify_compat_test.go
  internal/handlers/common/findandmodify.go
Labels: code/bug

#3187 Add tests for `$$ROOT`
  integration/aggregate_variables_compat_test.go
Labels: code/chore

#3198 Add blog post for FerretDB v1.8.0
  website/blog/2023-08-14-ferretdb-new-release-v180.md
  website/static/img/blog/ferretdb-v1.8.0.jpg
Labels: blog/marketing

#3208 Configure repo settings with files
  .github/settings.yml
  CONTRIBUTING.md
Labels: project

#3213 Update `go-hdb` to v1.4.1
  CONTRIBUTING.md
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: deps, trust

#3217 Fix typos in documentation
  website/docs/basic-operations/read.md
  website/docs/reference/glossary.md
Labels: documentation

#3215 Bump deps
  .github/settings.yml
  build/deps/jaeger.Dockerfile
  build/deps/postgres.Dockerfile
  build/deps/trivy.Dockerfile
  build/docker/all-in-one.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: deps, trust

#3221 Make the writing guide accessible but unlisted
  website/docs/contributing/writing-guide.md
Labels: documentation, trust

#3195 Add another stress test for SQLite
  internal/backends/sqlite/metadata/registry_test.go
Labels: code/chore

#3222 Fix concurrent SQLite tests
  integration/setup/listener.go
  integration/setup/startup.go
  internal/util/testutil/db.go
Labels: code/chore

#3188 Refactor aggregation operators
  internal/handlers/common/aggregations/operators/operators.go
  internal/handlers/common/aggregations/operators/sum.go
  internal/handlers/common/aggregations/operators/type.go
  internal/handlers/common/aggregations/stages/group.go
Labels: code/chore

#3210 Add Postgres Ibiza event blog post
  website/blog/2023-08-18-ferretdb-going-postgres-ibiza-2023.md
  website/static/img/blog/postgres-ibiza-2023.jpg
Labels: trust, blog/marketing

#3233 Add stubs for `renameCollection`
  cmd/ferretdb/main.go
  internal/backends/database.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/metadata/registry.go
Labels: code/chore

#3234 Update issue links
  integration/explain_compat_test.go
Labels: code/chore

#3230 Add more metrics for `*sql.DB`
  internal/backends/sqlite/metadata/registry.go
  internal/util/fsql/metrics.go
Labels: code/enhancement

#3236 Add stubs for `explain`
  .github/settings.yml
  Taskfile.yml
  internal/backends/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/sjson/sjson_test.go
  internal/handlers/sqlite/msg_explain.go
Labels: code/chore

#3248 Bump deps
  build/deps/legacy-mongo-shell.Dockerfile
  build/deps/mongo6.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: deps, trust

#3154 Add linter for issue comments
  CONTRIBUTING.md
  Taskfile.yml
  cmd/envtool/tests_test.go
  integration/Taskfile.yml
  integration/aggregate_documents_compat_test.go
  integration/aggregate_stats_compat_test.go
  integration/commands_administration_test.go
  integration/count_command_compat_test.go
  integration/count_compat_test.go
  integration/distinct_compat_test.go
  integration/findandmodify_compat_test.go
  integration/getmore_test.go
  integration/query_array_test.go
  integration/query_bitwise_test.go
  integration/query_command_compat_test.go
  integration/query_compat_test.go
  integration/query_evaluation_test.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/shareddata/faker.go
  internal/bson/datetime.go
  internal/clientconn/cursor/registry.go
  internal/handlers/common/aggregations/stages/collstats.go
  internal/handlers/common/aggregations/stages/projection/projection.go
  internal/handlers/common/aggregations/stages/sort.go
  internal/handlers/common/delete.go
  internal/handlers/common/filter.go
  internal/handlers/common/getmore.go
  internal/handlers/common/positional_operator.go
  internal/handlers/common/update.go
  internal/handlers/common/update_params.go
  internal/handlers/commonparams/params.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_createindexes.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_renamecollection.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/stats.go
  internal/handlers/sjson/datetime.go
  internal/handlers/sqlite/msg_find.go
  internal/handlers/sqlite/msg_update.go
  internal/types/compare_order.go
  internal/types/document.go
  internal/types/regex.go
  internal/util/iterator/testiterator/testiterator.go
  internal/util/testutil/pg.go
  internal/wire/msg_body.go
  internal/wire/op_msg.go
  tools/Taskfile.yml
  tools/checkcomments/checkcomments.go
  tools/checkcomments/checkcomments_test.go
  tools/checkcomments/testdata/testdata.go
  tools/checkswitch/checkswitch.go
  tools/tools.go
Labels: code/chore

#3201 Add Civo Navigate event blog post
  website/blog/2023-08-24-meet-us-civo-navigate-london.md
  website/static/img/blog/civo-navigate.jpg
Labels: trust, blog/marketing

#3250 Publish Docker images on quay.io
  .github/workflows/packages.yml
Labels: trust, packages

#3203 Refactor aggregation accumulators
  internal/handlers/common/aggregations/operators/accumulators/accumulators.go
  internal/handlers/common/aggregations/operators/accumulators/count.go
  internal/handlers/common/aggregations/operators/accumulators/sum.go
Labels: code/chore

#3246 Cleanup SQLite tests
  integration/aggregate_documents_compat_test.go
  integration/aggregate_documents_test.go
  integration/aggregate_query_test.go
  integration/aggregate_variables_compat_test.go
  integration/findandmodify_compat_test.go
  integration/findandmodify_test.go
  integration/helpers.go
  integration/indexes_test.go
  integration/insert_command_test.go
  integration/insert_compat_test.go
  integration/update_array_compat_test.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
Labels: code/chore

#3254 Add tests for accessing aggregation variable `$$ROOT` field
  integration/aggregate_variables_compat_test.go
Labels: code/chore

#3255 Remove duplicated `$expr` tests
  integration/aggregate_query_compat_test.go
  integration/aggregate_query_test.go
Labels: code/chore

#3209 Update blog writing guide documentation
  website/blog/_guide/YYYY-MM-DD.blog-template.md
  website/blog/_guide/content-process.md
  website/docs/contributing/writing-guide.md
Labels: documentation

#3262 Update TODO comments
  integration/commands_administration_compat_test.go
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  internal/handlers/sqlite/msg_serverstatus.go
Labels: code/chore

#3258 Simplify and deprecate `commonerrors.WriteErrors`
  .github/RELEASE_CHECKLIST.md
  internal/clientconn/conn.go
  internal/handlers/common/aggregations/operators/accumulators/accumulators.go
  internal/handlers/common/update.go
  internal/handlers/commonerrors/command.go
  internal/handlers/commonerrors/commonerrors_test.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/write.go
  internal/handlers/commonerrors/write_error.go
Labels: code/chore

#3256 Implement `aggregate` for SQLite
  integration/aggregate_documents_compat_test.go
  integration/aggregate_documents_test.go
  integration/aggregate_stats_compat_test.go
  integration/getmore_test.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/sqlite/msg_aggregate.go
Labels: code/feature

#3265 Implement `distinct` for SQLite
  integration/distinct_compat_test.go
  integration/distinct_test.go
  internal/handlers/sqlite/msg_distinct.go
Labels: code/feature

#3267 Add backend interface for `dbStats`
  internal/backends/database.go
  internal/backends/postgresql/database.go
  internal/backends/sqlite/database.go
Labels: code/chore

#3223 Support `ordered` `insert`s for SQLite
  .golangci.yml
  integration/aggregate_stats_compat_test.go
  integration/indexes_command_compat_test.go
  integration/indexes_compat_test.go
  integration/insert_command_test.go
  integration/insert_compat_test.go
  internal/backends/collection.go
  internal/backends/error.go
  internal/backends/errorcode_string.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/collection_test.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/backends/sqlite/sqlite_test.go
  internal/handlers/sqlite/msg_insert.go
  internal/handlers/sqlite/msg_update.go
Labels: code/feature

#3274 Add release blog post on FerretDB v1.9.0
  website/blog/2021-12-07-mongodb-compatibility-whats-really-important.md
  website/blog/2022-06-28-new-release-ferretdb-0-4-0.md
  website/blog/2022-10-12-contribute-to-ferretdb-on-windows.md
  website/blog/2023-03-30-ferretdb-v-0-9-4-minor-release-update.md
  website/blog/2023-06-05-ferretdb-v-1-3-0-new-release.md
  website/blog/2023-06-19-ferretdb-v-1-4-0-new-release.md
  website/blog/2023-06-26-configure-ferretdb-work-percona-distribution-postgresql.md
  website/blog/2023-07-17-ferretdb-v-1-6-0.md
  website/blog/2023-08-18-deploy-run-ferretdb-leafcloud.md
  website/blog/2023-08-18-ferretdb-going-postgres-ibiza-2023.md
  website/blog/2023-08-29-new-ferretdb-release-v190.md
  website/static/img/blog/ferretdb-v1.9.0.png
Labels: blog/marketing

#3284 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#3286 Add tests for validation bug
  internal/types/document_validation_test.go
Labels: code/chore

#3288 Expand architecture docs, add comments
  internal/backends/collection.go
  internal/backends/doc.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/sqlite/msg_collmod.go
  internal/handlers/sqlite/msg_datasize.go
  internal/handlers/sqlite/msg_delete.go
  internal/handlers/sqlite/msg_dropindexes.go
  internal/handlers/sqlite/msg_findandmodify.go
  internal/handlers/sqlite/msg_listindexes.go
  internal/handlers/sqlite/msg_renamecollection.go
  internal/handlers/sqlite/sqlite.go
  internal/types/array.go
  internal/types/document.go
Labels: code/chore

#3291 Make `delete`s atomic for SQLite
  integration/helpers.go
  internal/backends/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/sqlite/msg_delete.go
  internal/types/array.go
  internal/types/array_test.go
  internal/types/document.go
  internal/types/document_test.go
  website/docs/quickstart-guide/rpm.md
Labels: code/enhancement

#3292 Make registry return full collection info
  internal/backends/sqlite/database.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/metadata/registry_test.go
Labels: code/chore

#3270 Implement `dbStats` for SQLite
  integration/commands_administration_compat_test.go
  integration/commands_administration_test.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/database_test.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/handlers/pg/msg_dbstats.go
  internal/handlers/sqlite/msg_dbstats.go
Labels: code/feature
