Repository FerretDB/FerretDB, pull requests merged in 2023-02, with the labels that each got.

#1893 Add blog post on new FerretDB release
  website/blog/2023-01-31-ferretdb-v-0-9-0-developer-preview.md
  website/static/img/blog/developer_preview.png
Labels: documentation

#1902 Bump deps
  .github/workflows/docs.yml
  build/deps/cockroach.Dockerfile
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/legacy-mongo-shell.Dockerfile
  build/deps/mongo6.Dockerfile
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/util/testutil/testutil.go
  tools/go.mod
  tools/go.sum
Labels: documentation, deps, trust, docker

#1878 Use multiple Tigris instances to run tests
  Taskfile.yml
  cmd/envtool/envtool.go
  docker-compose.yml
  integration/setup/common.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/setup/startup.go
  integration/setup/startup_test.go
Labels: code/chore

#1909 Assorted internal tweaks
  .github/RELEASE_CHECKLIST.md
  .github/workflows/docs.yml
  Taskfile.yml
  build/version/version.go
  cmd/ferretdb/main.go
  cmd/ferretdb/main_hana.go
  integration/query_compat_test.go
  integration/setup/common.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/registry/registry_test.go
Labels: code/chore

#1916 Bump Tigris
  build/deps/tigris.Dockerfile
Labels: deps

#1863 Add simple `otel` tracing to collect data from tests
  CONTRIBUTING.md
  README.md
  Taskfile.yml
  cmd/envtool/envtool.go
  docker-compose.yml
  go.mod
  go.sum
  integration/.golangci.yml
  integration/go.mod
  integration/go.sum
  integration/main_test.go
  integration/setup/common.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/setup/startup.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/pg/pgdb/query_test.go
  internal/types/array_iterator.go
  internal/types/document_iterator.go
  internal/util/testutil/testutil.go
  internal/wire/wire_test.go
  website/blog/2023-01-04-ferretdb-beta-version-authentication.md
  website/docs/quickstart_guide/docker.md
Labels: code/chore

#1918 Fix broken link
  README.md
  website/docs/quickstart_guide/docker.md
Labels: documentation

#1919 Remove unused parameter
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/common.go
  internal/handlers/registry/registry.go
Labels: code/chore

#1907 Fix `$pop` operator error handling of non-existent path
  integration/update_array_compat_test.go
  integration/update_field_test.go
  internal/handlers/common/update_array_operators.go
Labels: code/bug

#1857 Rework on integration test setup
  Taskfile.yml
  integration/Taskfile.yml
  integration/commands_administration_test.go
  integration/create_compat_test.go
  integration/create_test.go
  integration/helpers.go
  integration/insert_compat_test.go
  integration/setup/common.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/setup/startup.go
  integration/update_compat_test.go
Labels: code/chore

#1842 Support Tigris pushdowns for numbers
  integration/commands_administration_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  internal/handlers/tigris/tigrisdb/query.go
Labels: code/feature

#1908 Pushdown Tigris queries with dot notation
  integration/query_comparison_compat_test.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/tigris/tigrisdb/query.go
  internal/handlers/tigris/tigrisdb/query_test.go
Labels: code/feature

#1947 Add `iterator.WithClose` helper
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/tigris/tigrisdb/query_iterator.go
  internal/util/iterator/close.go
Labels: code/chore

#1942 Fix SASL response for `PLAIN` authentication
  internal/handlers/pg/msg_saslstart.go
Labels: code/bug

#1948 Tweak CI settings
  .github/workflows/conform-pr.yml
  .github/workflows/docker.yml
  .github/workflows/docs-preview.yml
  .github/workflows/docs.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
Labels: code/chore

#1955 Rename function, add TODO
  integration/commands_administration_test.go
  internal/handlers/pg/msg_explain.go
  internal/types/document_validation_test.go
  internal/types/path.go
  internal/types/path_test.go
  internal/util/testutil/path_test.go
Labels: code/chore

#1957 Remove `skipTigrisPushdown` from tests
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
Labels: code/chore

#1958 Prepare v0.9.1 release
  .github/workflows/docs.yml
  CHANGELOG.md
Labels: documentation, code/chore, trust

#1976 Bump deps
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: documentation, deps, trust, docker

#1978 Add support for `create` with `capped: false`
  internal/handlers/common/unimplemented.go
  internal/handlers/pg/msg_create.go
  internal/handlers/tigris/msg_create.go
Labels: code/bug

#1967 Do not log the latest version if it's unknown
  .github/workflows/go.yml
  .github/workflows/integration.yml
  internal/handlers/common/getfreemonitoringstatus.go
  internal/handlers/common/serverstatus.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/tigris/msg_getlog.go
  internal/util/state/metrics.go
  internal/util/state/metrics_test.go
  internal/util/state/provider_test.go
  internal/util/state/state.go
  internal/util/telemetry/reporter.go
  website/docs/telemetry.md
Labels: code/bug

#1991 Build multiple Docker images for git tags
  .github/workflows/docker.yml
Labels: code/chore, trust, docker

#1960 Support `listIndexes` command
  integration/commands_administration_test.go
  internal/handlers/pg/msg_listindexes.go
  internal/handlers/tigris/msg_listindexes.go
  internal/handlers/tigris/tigrisdb/collections.go
  internal/handlers/tigris/tigrisdb/insert.go
  website/docs/reference/supported_commands.md
Labels: code/feature

#1966 Enable array tests for Tigris
  integration/shareddata/composites.go
  integration/update_array_compat_test.go
Labels: code/chore

#1998 Store cursors in `ConnInfo`
  build/version/version.go
  integration/shareddata/scalars.go
  internal/clientconn/conn.go
  internal/clientconn/conninfo/conn_info.go
  internal/clientconn/conninfo/conn_info_test.go
  internal/handlers/pg/pgdb/query_test.go
  internal/types/object_id.go
  internal/types/object_id_test.go
Labels: code/chore

#1963 Add a flag for disabling query pushdown
  cmd/ferretdb/main.go
  integration/query_compat_test.go
  integration/setup/common.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_distinct.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pg.go
  internal/handlers/pg/pgdb/delete.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/pg/pgdb/update.go
  internal/handlers/registry/registry.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_distinct.go
  internal/handlers/tigris/msg_explain.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_findandmodify.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/tigris.go
  internal/handlers/tigris/tigrisdb/query.go
  internal/handlers/tigris/tigrisdb/query_test.go
Labels: code/enhancement

#1999 Bump Go to 1.19.6
  .github/workflows/docker.yml
  Dockerfile
Labels: deps, trust, docker

#1981 Bump more dependencies
  .github/dependabot.yml
  .github/workflows/integration.yml
  Taskfile.yml
  build/deps/cockroach.Dockerfile
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/postgres.Dockerfile
  build/deps/tigris.Dockerfile
  docker-compose.yml
Labels: deps, no ci

#2002 Bump more deps, update Dependabot config
  .github/dependabot.yml
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: deps

#2008 Simplify pushdown disabling logic
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/pg.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/registry/registry.go
  internal/handlers/registry/tigris.go
  internal/handlers/tigris/msg_explain.go
  internal/handlers/tigris/tigris.go
  internal/handlers/tigris/tigrisdb/query.go
Labels: code/chore

#2006 Extract more `find` command parameters
  internal/handlers/common/find.go
  internal/handlers/common/msg_getmore.go
  internal/handlers/common/msg_listcommands.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/dummy/msg_getmore.go
  internal/handlers/handlers.go
  internal/handlers/pg/msg_getmore.go
  internal/handlers/tigris/msg_getmore.go
  website/docs/reference/supported_commands.md
Labels: code/chore

#2011 Bump Tigris version to `1.0.0-beta.38`
  build/deps/tigris.Dockerfile
Labels: code/chore

#2010 Set up analytics for documentation and blog
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
Labels: documentation

#1941 Add section for evaluation query operators - `$mod` and `$regex`
  website/docs/reference/operators/evaluation-operators.md
Labels: documentation

#1994 Refactor `types.NewPathFromString` to return `(Path, error)`
  integration/commands_diagnostic_test.go
  integration/update_field_compat_test.go
  internal/handlers/common/distinct.go
  internal/handlers/common/filter.go
  internal/handlers/common/update.go
  internal/handlers/common/update_array_operators.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/tigris/msg_explain.go
  internal/handlers/tigris/tigrisdb/query.go
  internal/handlers/tigris/tigrisdb/query_test.go
  internal/types/document_test.go
  internal/types/path.go
Labels: code/chore

#2018 Bump `golang.org/x/net` version to 0.7.0 in `tools/go.mod`
  tools/go.mod
  tools/go.sum
Labels: code/chore

#2017 Embedded FerretDB documentation - examples improvements
  ferretdb/ferretdb_test.go
Labels: documentation

#2022 Bump deps
  Taskfile.yml
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/tigris.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#2023 Do not specify Docker Compose version
  README.md
  docker-compose.yml
  website/blog/2022-10-06-how-to-start-ferretdb-locally-with-docker.md
  website/docs/quickstart_guide/docker.md
Labels: documentation

#2004 Add support for `$addToSet` array update operator
  integration/update_array_compat_test.go
  internal/handlers/common/update.go
  internal/handlers/common/update_array_operators.go
  website/docs/reference/supported_commands.md
Labels: code/feature

#1925 Refactor integration tests
  CONTRIBUTING.md
  Taskfile.yml
  build/certs/rootCA-cert.pem
  build/mongod_secured.conf
  cmd/envtool/envtool.go
  docker-compose.yml
  ferretdb/ferretdb_test.go
  integration/Taskfile.yml
  integration/embedded_test.go
  integration/setup/client.go
  integration/setup/common.go
  integration/setup/common_unix.go
  integration/setup/common_windows.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/setup/setup_tls.go
  integration/setup/startup.go
  integration/setup/test_helpers.go
  integration/shareddata/composites.go
  internal/clientconn/listener.go
Labels: code/chore

#2039 Simplify fields sorting, add TODO
  internal/handlers/common/update.go
  internal/types/document.go
  internal/types/document_test.go
Labels: code/chore

#2032 Add `$pullAll` array update operator
  integration/update_array_compat_test.go
  internal/handlers/common/update.go
  internal/handlers/common/update_array_operators.go
  website/docs/reference/supported_commands.md
Labels: code/feature

#2042 Document bitwise query operators
  website/docs/reference/operators/bitwise-operators.md
Labels: documentation

#2031 Run `task testjs` on CI
  .github/CODEOWNERS
  .github/workflows/docker.yml
  .github/workflows/docs-preview.yml
  .github/workflows/docs.yml
  .github/workflows/go.yml
  .github/workflows/integration.yml
  .github/workflows/js.yml
  .github/workflows/security.yml
  Taskfile.yml
  build/legacy-mongo-shell/test.example.js
  build/legacy-mongo-shell/test.js
Labels: code/chore

#2016 Update documentation definitions for operators
  website/docs/reference/operators/array-operators.md
  website/docs/reference/operators/comparison-operators.md
  website/docs/reference/operators/element-operators.md
  website/docs/reference/operators/evaluation-operators.md
  website/docs/reference/operators/logical-operators.md
Labels: documentation

#2003 Disable query pushdown if the corresponding flag is set
  cmd/ferretdb/main.go
  integration/query_compat_test.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_distinct.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/database_metadata.go
  internal/handlers/pg/pgdb/delete.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/pg/pgdb/update.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_distinct.go
  internal/handlers/tigris/msg_find.go
  internal/handlers/tigris/msg_findandmodify.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_update.go
  internal/handlers/tigris/tigrisdb/query.go
  internal/handlers/tigris/tigrisdb/query_test.go
  website/docs/flags.md
Labels: code/enhancement

#2061 Fix `SkipForTigrisWithReason` helper
  integration/embedded_test.go
  integration/setup/test_helpers.go
Labels: code/chore

#2047 Add dot notation test cases for update operators
  integration/shareddata/composites.go
  integration/update_field_compat_test.go
Labels: code/chore

#2059 Push Docker images to Docker Hub
  .github/RELEASE_CHECKLIST.md
  .github/workflows/docker.yml
Labels: code/chore, trust, docker

#2067 Add blog post on FerretDB v0.92
  website/blog/2023-02-28-ferretdb-release-0-9-2.md
  website/static/img/blog/ferretdb_v0.9.2.jpg
Labels: documentation
