Repository FerretDB/FerretDB, pull requests merged in 2023-11, with the labels that each got.

#3668 Rename main_postgeresql to main_postgresql
  cmd/ferretdb/main_postgresql.go
Labels: code/chore

#3673 Mention proxy flag in docs
  website/docs/migration/premigration-testing.md
Labels: documentation, trust

#3678 Make tests stable on CI
  .github/settings.yml
  CHANGELOG.md
  Taskfile.yml
  cmd/envtool/envtool.go
  cmd/envtool/envtool_test.go
  cmd/envtool/error.tmpl
  cmd/envtool/tests_test.go
Labels: code/chore, trust, packages

#3637 Support `showRecordId` in `find`
  .github/workflows/_integration.yml
  .github/workflows/go-extra.yml
  Taskfile.yml
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  cmd/ferretdb/main.go
  integration/aggregate_documents_compat_test.go
  integration/pushdown.go
  integration/query_command_compat_test.go
  integration/query_compat_test.go
  integration/query_test.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/test_helpers.go
  internal/backends/collection.go
  internal/backends/collection_test.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/collection_test.go
  internal/clientconn/cursor/cursor.go
  internal/clientconn/cursor/registry.go
  internal/handlers/common/find.go
  internal/handlers/common/getmore.go
  internal/handlers/common/projection.go
  internal/handlers/registry/hana.go
  internal/handlers/registry/postgresql.go
  internal/handlers/registry/registry.go
  internal/handlers/registry/sqlite.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_explain.go
  internal/handlers/sqlite/msg_find.go
  internal/handlers/sqlite/sqlite.go
  website/docs/reference/supported-commands.md
Labels: code/feature

#3681 Add release blogpost for FerretDB v.1.14.0
  website/blog/2023-11-07-ferretdb-releases-v1140.md
  website/static/img/blog/ferretdb-v1.14.0.jpg
Labels: trust, blog/marketing

#3676 Add blog post on FastNetMon
  website/blog/2023-11-08-fastnetmon-picked-ferretdb-saas-offering.md
  website/static/img/blog/ferretdb-fastnetmon.jpg
  website/static/img/blog/pavel-odintsov.jpeg
Labels: trust, blog/marketing

#3689 Add JSON format for logging
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/chore.yml
  Taskfile.yml
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/startup.go
  internal/util/debug/debug.go
  internal/util/logging/buffer_test.go
  internal/util/logging/logging.go
  website/docs/configuration/flags.md
  website/docs/configuration/observability.md
  website/docs/quickstart-guide/deb.md
  website/docs/quickstart-guide/docker.md
  website/docs/quickstart-guide/rpm.md
Labels: code/feature

#3690 Bump deps
  Taskfile.yml
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  docker-compose.yml
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: deps

#3694 Fix content error
  website/blog/2023-10-30-building-mongodb-like-developer-experience-vultr.md
Labels: blog/marketing

#3622 Use separate PostgreSQL databases in tests
  .gitignore
  .golangci.yml
  SECURITY.md
  integration/go.mod
  integration/query_comparison_compat_test.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/update_field_compat_test.go
  internal/backends/backend_test.go
  internal/backends/collection_test.go
  internal/backends/helpers_test.go
  internal/backends/postgresql/backend.go
  internal/backends/postgresql/database_test.go
  internal/backends/postgresql/metadata/registry.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/backends/postgresql/query.go
  internal/backends/postgresql/query_test.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/collection_test.go
  internal/backends/sqlite/database_test.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/backends/sqlite/sqlite_test.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_collstats.go
  internal/util/resource/resource.go
  internal/util/testutil/postgresql.go
  internal/util/testutil/sqlite.go
Labels: code/chore

#3677 Add test for tailable cursor with non-capped collection
  integration/query_test.go
  internal/handlers/common/find.go
  internal/handlers/sqlite/msg_find.go
Labels: code/chore

#3698 Add option to disable `--debug-addr`.
  cmd/ferretdb/main.go
  website/docs/configuration/flags.md
Labels: code/feature

#3703 Allow usage without state dir
  cmd/ferretdb/main.go
  website/docs/configuration/flags.md
Labels: code/chore

#3704 Use `-` in addition to the empty string
  cmd/ferretdb/main.go
  website/docs/configuration/flags.md
Labels: code/chore

#3705 Use the standard `*mongo.WriteError` type
  .golangci.yml
  cmd/envtool/tests.go
  go.mod
  go.sum
  internal/handlers/sqlite/msg_delete.go
  internal/handlers/sqlite/msg_findandmodify.go
  internal/handlers/sqlite/msg_insert.go
  internal/handlers/sqlite/msg_update.go
Labels: code/chore

#3604 Fix tests for MongoDB with enabled replica set
  build/mongodb.conf
  cmd/envtool/envtool.go
  integration/basic_test.go
  integration/commands_administration_test.go
  integration/commands_authentication_test.go
  integration/commands_diagnostic_test.go
  integration/commands_freemonitoring_test.go
  integration/commands_replication_test.go
Labels: code/chore

#3711 Handle panicking tests
  cmd/envtool/envtool.go
  cmd/envtool/testdata/panic_test.go
  cmd/envtool/tests.go
  cmd/envtool/tests_test.go
Labels: code/chore

#3679 Add blogpost for "How to Package and Deploy FerretDB with Acorn"
  website/blog/2023-11-15-how-to-package-and-deploy-ferretdb-with-acorn.md
  website/static/img/blog/ferretdb-acorn.jpg
  website/static/img/blog/todo-image.png
Labels: trust, blog/marketing

#3717 Allow the usage of existing PostgreSQL schema
  internal/backends/postgresql/metadata/registry.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/util/testutil/postgresql.go
Labels: code/enhancement

#3659 Enable interactivity on blogpost
  website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.mdx
  website/docusaurus.config-blog.js
  website/static/blog/2022-11-14/delete-1.js
  website/static/blog/2022-11-14/delete-2.js
  website/static/blog/2022-11-14/insert-1.js
  website/static/blog/2022-11-14/insert-2.js
  website/static/blog/2022-11-14/update-1.js
  website/static/blog/2022-11-14/update-2.js
  website/static/blog/2022-11-14/update-3.js
  website/static/codapi/init.js
  website/static/codapi/snippet.css
  website/static/codapi/snippet.js
Labels: trust, blog/marketing

#3710 Make handler accept constructed backend
  .golangci.yml
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/listener.go
  internal/handlers/registry/hana.go
  internal/handlers/registry/postgresql.go
  internal/handlers/registry/registry.go
  internal/handlers/registry/registry_test.go
  internal/handlers/registry/sqlite.go
  internal/handlers/sqlite/sqlite.go
Labels: code/chore

#3632 Add issue tracking to checkcomments analyzer
  Taskfile.yml
  integration/setup/test_helpers.go
  tools/Taskfile.yml
  tools/checkcomments/checkcomments.go
  tools/checkcomments/testdata/testdata.go
  tools/go.mod
Labels: code/chore

#3721 Fix Codapi error on blog post
  website/static/codapi/init.js
Labels: documentation

#3697 Generate SQL queries with comments for find operations
  internal/backends/collection.go
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/query.go
  internal/backends/postgresql/query_test.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/query.go
  internal/backends/sqlite/query_test.go
Labels: code/enhancement

#3709 Add migration blog post
  website/blog/2023-11-16-guide-to-migrating-mongodb-ferretdb.md
  website/static/img/blog/migrating-mongodb-ferretdb.jpg
Labels: trust, blog/marketing

#3723 Add TODOs and fix URLs
  README.md
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/sqlite/msg_insert.go
  website/blog/2023-11-16-guide-to-migrating-mongodb-ferretdb.md
Labels: code/chore

#3525 Move diff tests from dance to integration tests
  integration/diff_01_error_messages_test.go
  integration/diff_02_null_strings_test.go
  integration/diff_03_nested_arrays_test.go
  integration/diff_04_negative_zero_test.go
  integration/diff_05_document_validation_test.go
  integration/diff_06_insert_test.go
  integration/diff_07_update_test.go
  integration/diff_08_names_test.go
  integration/diff_09_dbstats_scale_test.go
  website/docs/diff.md
Labels: code/chore

#3724 Small assorted tweaks
  .github/settings.yml
  Taskfile.yml
  internal/backends/decorators/dummy/backend.go
  internal/backends/decorators/dummy/collection.go
  internal/backends/decorators/dummy/database.go
  internal/backends/decorators/oplog/backend.go
  internal/backends/decorators/oplog/collection.go
  internal/backends/decorators/oplog/database.go
  internal/backends/hana/backend.go
  internal/backends/postgresql/backend.go
  internal/backends/sqlite/backend.go
Labels: code/chore

#3653 Clarify MongoDB version
  README.md
  website/docs/main.md
Labels: documentation, not ready

#3691 Cleanup pushdown terminology
  integration/Taskfile.yml
  integration/aggregate_documents_compat_test.go
  integration/query_command_compat_test.go
  integration/query_compat_test.go
  integration/query_test.go
  internal/backends/collection.go
  internal/backends/collection_test.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/collection_test.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_explain.go
Labels: code/chore

#3728 Add blogpost for release v.1.15
  website/blog/2023-11-20-ferretdb-releases-v1150.md
  website/static/img/blog/ferretdb-v1.15.0.jpg
Labels: trust, blog/marketing

#3740 Make RecordID a signed value
  internal/backends/collection.go
  internal/backends/postgresql/query_iterator.go
  internal/backends/sqlite/query_iterator.go
  internal/handlers/sqlite/msg_explain.go
  internal/handlers/sqlite/msg_find.go
  internal/types/document.go
  internal/types/timestamp.go
  internal/types/timestamp_test.go
Labels: code/chore

#3747 Bump deps
  build/deps/postgres.Dockerfile
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/backends/backend_test.go
  tools/go.mod
  tools/go.sum
Labels: deps

#3751 Add MySQL backend to CI
  .github/workflows/_integration.yml
  .github/workflows/go-extra.yml
  Taskfile.yml
Labels: code/chore

#3753 Remove common `handlers.Interface`
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/handlers/commoncommands/msg_listcommands.go
  internal/handlers/handlers.go
  internal/handlers/registry/hana.go
  internal/handlers/registry/mysql.go
  internal/handlers/registry/postgresql.go
  internal/handlers/registry/registry.go
  internal/handlers/registry/sqlite.go
  internal/handlers/sqlite/cmd_query.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_buildinfo.go
  internal/handlers/sqlite/msg_collmod.go
  internal/handlers/sqlite/msg_collstats.go
  internal/handlers/sqlite/msg_compact.go
  internal/handlers/sqlite/msg_connectionstatus.go
  internal/handlers/sqlite/msg_count.go
  internal/handlers/sqlite/msg_create.go
  internal/handlers/sqlite/msg_createindexes.go
  internal/handlers/sqlite/msg_currentop.go
  internal/handlers/sqlite/msg_datasize.go
  internal/handlers/sqlite/msg_dbstats.go
  internal/handlers/sqlite/msg_debugerror.go
  internal/handlers/sqlite/msg_delete.go
  internal/handlers/sqlite/msg_distinct.go
  internal/handlers/sqlite/msg_drop.go
  internal/handlers/sqlite/msg_dropdatabase.go
  internal/handlers/sqlite/msg_dropindexes.go
  internal/handlers/sqlite/msg_explain.go
  internal/handlers/sqlite/msg_find.go
  internal/handlers/sqlite/msg_findandmodify.go
  internal/handlers/sqlite/msg_getcmdlineopts.go
  internal/handlers/sqlite/msg_getfreemonitoringstatus.go
  internal/handlers/sqlite/msg_getlog.go
  internal/handlers/sqlite/msg_getmore.go
  internal/handlers/sqlite/msg_getparameter.go
  internal/handlers/sqlite/msg_hello.go
  internal/handlers/sqlite/msg_hostinfo.go
  internal/handlers/sqlite/msg_insert.go
  internal/handlers/sqlite/msg_ismaster.go
  internal/handlers/sqlite/msg_killcursors.go
  internal/handlers/sqlite/msg_listcollections.go
  internal/handlers/sqlite/msg_listcommands.go
  internal/handlers/sqlite/msg_listdatabases.go
  internal/handlers/sqlite/msg_listindexes.go
  internal/handlers/sqlite/msg_logout.go
  internal/handlers/sqlite/msg_ping.go
  internal/handlers/sqlite/msg_renamecollection.go
  internal/handlers/sqlite/msg_saslstart.go
  internal/handlers/sqlite/msg_serverstatus.go
  internal/handlers/sqlite/msg_setfreemonitoring.go
  internal/handlers/sqlite/msg_update.go
  internal/handlers/sqlite/msg_validate.go
  internal/handlers/sqlite/msg_whatsmyuri.go
  internal/handlers/sqlite/sqlite.go
Labels: code/chore

#3752 Remove unsafe pushdown
  cmd/ferretdb/main.go
  integration/pushdown.go
  integration/query_compat_test.go
  integration/query_test.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/test_helpers.go
  internal/handlers/registry/hana.go
  internal/handlers/registry/mysql.go
  internal/handlers/registry/postgresql.go
  internal/handlers/registry/registry.go
  internal/handlers/registry/sqlite.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_explain.go
  internal/handlers/sqlite/msg_find.go
  internal/handlers/sqlite/sqlite.go
Labels: code/chore

#3718 Support `DeleteAll` for capped collections
  internal/backends/collection_test.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
Labels: code/chore

#3735 Add startup warning for debug builds
  internal/handlers/sqlite/msg_getlog.go
Labels: code/chore

#3762 Add TODOs about pushdowns
  build/mongodb.conf
  internal/backends/collection.go
Labels: code/chore

#3763 Clean-up old code for multiple handlers
  .github/PROCESS.md
  CONTRIBUTING.md
  integration/aggregate_documents_compat_test.go
  integration/aggregate_stats_compat_test.go
  integration/explain_compat_test.go
  integration/query_command_compat_test.go
  integration/query_compat_test.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/handler/common/aggregations/operators/expr.go
  internal/handler/common/aggregations/operators/operators_errors.go
  internal/handler/common/aggregations/operators/sum.go
  internal/handler/common/client_metadata.go
  internal/handler/common/client_metadata_test.go
  internal/handler/common/common.go
  internal/handler/commoncommands/commoncommands.go
  internal/handler/commoncommands/msg_whatsmyuri_test.go
  internal/handler/commonerrors/error.go
  internal/handler/commonparams/commonparams.go
  internal/handler/commonparams/params.go
  internal/handler/registry/registry.go
  internal/types/document.go
Labels: code/chore

#3764 Add TODOs
  integration/query_test.go
  internal/backends/backend.go
  internal/backends/database.go
  internal/handler/commonerrors/error.go
  internal/handler/msg_find.go
Labels: code/chore

#3766 Move some commands from `common` to the handler
  internal/handler/common/getfreemonitoringstatus.go
  internal/handler/common/getmore.go
  internal/handler/common/killcursors.go
  internal/handler/common/saslstart.go
  internal/handler/common/saslstart_plain.go
  internal/handler/common/serverstatus.go
  internal/handler/common/setfreemonitoring.go
  internal/handler/common/validate.go
  internal/handler/msg_getfreemonitoringstatus.go
  internal/handler/msg_getmore.go
  internal/handler/msg_killcursors.go
  internal/handler/msg_saslstart.go
  internal/handler/msg_saslstart_plain_test.go
  internal/handler/msg_serverstatus.go
  internal/handler/msg_setfreemonitoring.go
Labels: code/chore

#3771 Add TODOs
  build/deps/mongo.Dockerfile
  build/mongodb_secured.conf
  cmd/envtool/envtool.go
  docker-compose.yml
  integration/commands_authentication_test.go
  internal/handler/msg_listcollections.go
  internal/handler/msg_listdatabases.go
  website/docs/reference/supported-commands.md
Labels: code/chore

#3775 Allow `system.` prefix for collections for now
  internal/backends/validation.go
Labels: code/chore

#3758 Setup MySQL integration tests
  Taskfile.yml
  cmd/ferretdb/main.go
  go.mod
  go.sum
  integration/Taskfile.yml
  integration/go.mod
  integration/go.sum
  integration/setup/listener.go
  integration/setup/setup.go
  internal/util/testutil/mysql.go
Labels: code/chore
