Repository FerretDB/FerretDB, pull requests merged in 2023-07, with the labels that each got.

#2922 Convert SQLite directory to URI
  .golangci-new.yml
  Taskfile.yml
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/listener.go
  integration/setup/startup.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/metadata/pool/pool.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/registry.go
  internal/handlers/registry/registry.go
  internal/handlers/registry/sqlite.go
  internal/handlers/sqlite/sqlite.go
Labels: code/chore

#2951 Do not break fuzzing initialization
  internal/handlers/sjson/sjson_test.go
  internal/wire/record.go
  internal/wire/wire_test.go
Labels: code/chore

#2952 Move `find` and `aggregation` cursor integration tests to `getMore`
  integration/aggregate_documents_test.go
  integration/getmore_test.go
  integration/query_test.go
  integration/update_compat_test.go
Labels: code/chore

#2958 Add blog post on FerretDB release v1.5.0
  website/blog/2023-07-04-ferretdb-v-1-5-0-beta-support-sqlite.md
  website/static/img/blog/ferretdb-v1.5.0.jpg
Labels: trust, blog/marketing

#2939 Implement `killCursors` command
  .github/dependabot.yml
  .github/workflows/go.yml
  CONTRIBUTING.md
  cmd/envtool/tests.go
  integration/basic_test.go
  integration/commands_administration_test.go
  integration/create_test.go
  integration/delete_command_compat_test.go
  integration/distinct_test.go
  integration/getmore_test.go
  integration/helpers.go
  integration/indexes_command_compat_test.go
  integration/query_projection_test.go
  integration/renamecollection_test.go
  integration/setup/test_helpers.go
  internal/handlers/common/killcursors.go
  internal/handlers/commoncommands/msg_listcommands.go
  internal/handlers/hana/msg_killcursors.go
  internal/handlers/handlers.go
  internal/handlers/pg/msg_killcursors.go
  internal/handlers/sqlite/msg_killcursors.go
  internal/handlers/tigris/msg_killcursors.go
  internal/util/testutil/xfail.go
  internal/util/testutil/xfail_test.go
  website/docs/reference/supported-commands.md
Labels: code/feature

#2998 Bump deps
  Taskfile.yml
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/Taskfile.yml
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#2999 Remove Tigris from documentation and builds
  CONTRIBUTING.md
  Taskfile.yml
  build/deps/tigris.Dockerfile
  build/deps/tigris_main.Dockerfile
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  build/version/version.go
  cmd/envtool/envtool.go
  docker-compose.yml
  integration/Taskfile.yml
  website/docs/diff.md
  website/docs/reference/glossary.md
  website/docs/reference/supported-commands.md
  website/docs/telemetry.md
Labels: code/chore

#3002 Remove Tigris from tests
  cmd/envtool/tests_test.go
  integration/Taskfile.yml
  integration/aggregate_documents_compat_test.go
  integration/basic_test.go
  integration/commands_administration_test.go
  integration/commands_authentication_test.go
  integration/count_command_compat_test.go
  integration/create_compat_test.go
  integration/create_test.go
  integration/delete_test.go
  integration/findandmodify_compat_test.go
  integration/findandmodify_test.go
  integration/helpers.go
  integration/indexes_command_compat_test.go
  integration/indexes_compat_test.go
  integration/indexes_test.go
  integration/insert_compat_test.go
  integration/object_id_delete_test.go
  integration/query_array_compat_test.go
  integration/query_array_test.go
  integration/query_bitwise_test.go
  integration/query_command_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_evaluation_test.go
  integration/query_projection_compat_test.go
  integration/query_test.go
  integration/renamecollection_compat_test.go
  integration/renamecollection_test.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/setup/test_helpers.go
  integration/shareddata/composites.go
  integration/shareddata/provider.go
  integration/shareddata/scalars.go
  integration/shareddata_test.go
  integration/subdir/subdir_test.go
  integration/update_array_compat_test.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  integration/update_field_test.go
  internal/handlers/sqlite/msg_update.go
Labels: code/chore

#2953 Add integration tests for `maxTimeMS` in `find`, `aggregate` and `getMore`
  integration/aggregate_documents_compat_test.go
  integration/aggregate_documents_test.go
  integration/getmore_test.go
  internal/handlers/common/getmore.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_find.go
Labels: code/enhancement

#2962 Add blog post about using NoSQLBooster with FerretDB
  website/blog/2023-07-10-mongodb-gui-using-ferretdb-nosqlbooster.md
  website/static/img/blog/ferretdb-nosqlbooster/aggregation-count.png
  website/static/img/blog/ferretdb-nosqlbooster/aggregation-operation.png
  website/static/img/blog/ferretdb-nosqlbooster/authentication-tab.png
  website/static/img/blog/ferretdb-nosqlbooster/collection-stats.png
  website/static/img/blog/ferretdb-nosqlbooster/connections-window.png
  website/static/img/blog/ferretdb-nosqlbooster/insert-documents.png
  website/static/img/blog/ferretdb-nosqlbooster/mongo-shell.png
  website/static/img/blog/ferretdb-nosqlbooster/nosqlbooster-download-page.png
  website/static/img/blog/ferretdb-nosqlbooster/query-builder-result.png
  website/static/img/blog/ferretdb-nosqlbooster/read-collection.png
  website/static/img/blog/ferretdb-nosqlbooster/use-query-builder.png
  website/static/img/blog/ferretdb-nosqlbooster/visual-explain-tool.png
  website/static/img/blog/ferretdb-nosqlbooster/visual-query-builder.png
  website/static/img/blog/nosqlbooster-ferretdb.png
Labels: trust, blog/marketing

#3010 Ignore `lsid` field in all commands
  internal/handlers/common/distinct.go
  internal/handlers/common/findandmodify.go
  internal/handlers/common/update_params.go
Labels: code/bug

#3009 Allow `$set` operator to update `_id`
  integration/findandmodify_compat_test.go
  integration/findandmodify_test.go
  integration/update_field_compat_test.go
  integration/update_field_test.go
  internal/handlers/common/update.go
Labels: code/bug

#3022 Move `testutil.TB` to `testtb.TB`
  integration/helpers.go
  integration/setup/client.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/setup/test_helpers.go
  internal/bson/bson_test.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/sjson/sjson_test.go
  internal/util/testutil/db.go
  internal/util/testutil/dump.go
  internal/util/testutil/equal.go
  internal/util/testutil/hexdump.go
  internal/util/testutil/path.go
  internal/util/testutil/pg.go
  internal/util/testutil/testtb/tb.go
  internal/util/testutil/testutil.go
  internal/util/testutil/xfail.go
  internal/wire/wire_test.go
Labels: code/chore

#3019 Move `logout` to `commoncommands`
  internal/handlers/commoncommands/msg_buildinfo.go
  internal/handlers/commoncommands/msg_currentop.go
  internal/handlers/commoncommands/msg_debugerror.go
  internal/handlers/commoncommands/msg_getcmdlineopts.go
  internal/handlers/commoncommands/msg_hostinfo.go
  internal/handlers/commoncommands/msg_listcommands.go
  internal/handlers/commoncommands/msg_logout.go
  internal/handlers/commoncommands/msg_whatsmyuri.go
  internal/handlers/hana/msg_logout.go
  internal/handlers/pg/msg_logout.go
  internal/handlers/sqlite/msg_logout.go
Labels: code/chore

#3023 Make `task all` run only unit tests
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  Taskfile.yml
  integration/setup/setup_compat.go
  internal/handlers/sjson/sjson_test.go
  internal/wire/wire_test.go
Labels: project

#2985 Support `getParameters` for `authenticationMechanisms` and `featureCompatibilityVersion` parameters
  integration/commands_administration_test.go
  internal/handlers/common/getparameter.go
  internal/handlers/hana/msg_getparameter.go
  internal/handlers/pg/msg_getparameter.go
  internal/handlers/sqlite/msg_getparameter.go
Labels: code/chore

#3027 Update closed issue links
  integration/getmore_test.go
  internal/handlers/common/getmore.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_find.go
  internal/handlers/sqlite/msg_find.go
  website/docs/reference/supported-commands.md
Labels: code/chore

#3025 Unskip `findAndModify` `$set` integration test for `_id`
  integration/findandmodify_compat_test.go
Labels: code/bug

#3029 Update blog post image
  website/static/img/blog/ferretdb-nosqlbooster/nosqlbooster-download-page.png
Labels: blog/marketing

#2993 Apply pushdown for `limit`
  integration/explain_command_test.go
  integration/query_test.go
  integration/setup/test_helpers.go
  internal/handlers/common/explain.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/pgdb/query.go
Labels: code/bug

#3030 Fix `killCursors` edge case
  integration/commands_administration_test.go
  internal/handlers/common/killcursors.go
Labels: code/chore

#3031 Fix error checking in backend contracts
  internal/backends/backend.go
  internal/backends/collection.go
  internal/backends/database.go
  internal/backends/doc.go
  internal/backends/error.go
  internal/backends/error_test.go
Labels: code/chore

#3034 Bump deps
  .github/dependabot.yml
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/legacy-mongo-shell.Dockerfile
  build/deps/mongo6.Dockerfile
  build/deps/trivy.Dockerfile
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#3035 Add a note about setting the stable API version
  website/docs/security/authentication.md
Labels: documentation, trust

#2869 Add blog post on "How to run FerretDB on top of StackGres"
  website/blog/2023-07-13-run-ferretdb-on-stackgres.md
  website/static/img/blog/stackgres-ferretdb.png
Labels: trust, blog/marketing

#3045 Remove `Type()` interface from aggregation stage
  internal/handlers/common/aggregations/aggregations.go
  internal/handlers/common/aggregations/stages/add_fields.go
  internal/handlers/common/aggregations/stages/collstats.go
  internal/handlers/common/aggregations/stages/count.go
  internal/handlers/common/aggregations/stages/group.go
  internal/handlers/common/aggregations/stages/limit.go
  internal/handlers/common/aggregations/stages/match.go
  internal/handlers/common/aggregations/stages/project.go
  internal/handlers/common/aggregations/stages/set.go
  internal/handlers/common/aggregations/stages/skip.go
  internal/handlers/common/aggregations/stages/sort.go
  internal/handlers/common/aggregations/stages/unset.go
  internal/handlers/common/aggregations/stages/unwind.go
  internal/handlers/pg/msg_aggregate.go
Labels: code/chore

#3048 Ignore `count.fields` argument
  internal/handlers/common/count.go
Labels: code/chore

#3028 Fix `update` with query operator for `upsert` option
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  integration/update_field_test.go
  internal/handlers/common/filter.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_update.go
  internal/handlers/sqlite/msg_update.go
Labels: code/bug

#3052 Remove fixed issue link and clean up integration test provider setup
  integration/aggregate_documents_compat_test.go
  integration/distinct_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_projection_compat_test.go
  integration/shareddata/shareddata.go
  integration/update_field_compat_test.go
Labels: code/chore

#3056 Prepare v1.6.0 release
  CHANGELOG.md
Labels: project

#3058 Add blog post for FerretDB v1.6.0
  website/blog/2023-07-17-ferretdb-v-1-6-0.md
  website/static/img/blog/ferretdb-v1.6.0.jpg
Labels: trust, blog/marketing

#3064 Bump deps
  build/deps/legacy-mongo-shell.Dockerfile
  build/deps/mongo6.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#3051 Mark some tests as failing for SQLite
  integration/basic_test.go
  integration/create_test.go
  integration/explain_compat_test.go
  integration/findandmodify_test.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/sqlite/msg_explain.go
Labels: code/chore

#3072 Update changelog
  CHANGELOG.md
Labels: documentation

#3071 Improve sjson package fuzzing
  Taskfile.yml
  internal/handlers/sjson/array_test.go
  internal/handlers/sjson/binary_test.go
  internal/handlers/sjson/bool_test.go
  internal/handlers/sjson/datetime_test.go
  internal/handlers/sjson/document_test.go
  internal/handlers/sjson/double_test.go
  internal/handlers/sjson/int32_test.go
  internal/handlers/sjson/int64_test.go
  internal/handlers/sjson/object_id_test.go
  internal/handlers/sjson/regex_test.go
  internal/handlers/sjson/sjson.go
  internal/handlers/sjson/sjson_test.go
  internal/handlers/sjson/string_test.go
  internal/handlers/sjson/timestamp_test.go
Labels: code/chore

#3073 Update blog post for FerretDB v1.6.0
  website/blog/2023-07-17-ferretdb-v-1-6-0.md
Labels: trust, blog/marketing

#2992 Tweak documentation and blog
  website/blog/2021-11-05-mangodb-overwhelming-enthusiasm-for-truly-open-source-mongodb-replacement.md
  website/blog/2021-12-01-mangodb-has-a-new-name-and-the-momentum-is-stronger-than-ever-meet-ferretdb.md
  website/blog/2021-12-07-mongodb-compatibility-whats-really-important.md
  website/blog/2022-04-18-ferretdb-v-0-1-1-is-out-and-other-exciting-updates.md
  website/blog/2022-05-16-using-cla-assistant-with-ferretdb.md
  website/blog/2022-06-27-developers-need-ferretdb-stackoverflow-developer-survey-2022.md
  website/blog/2022-06-28-new-release-ferretdb-0-4-0.md
  website/blog/2022-07-11-0-5-0-release-is-out-embedding-ferretdb-into-go-programs.md
  website/blog/2022-07-27-new-ferretdb-minor-release-0-5-1.md
  website/blog/2022-08-23-open-source-is-in-danger.md
  website/blog/2022-09-20-how-to-contribute-to-open-source-2022.md
  website/blog/2022-09-21-how-to-keep-control-of-your-infra-using-ferretdb-and-tigris.md
  website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md
  website/blog/2022-10-06-how-to-start-ferretdb-locally-with-docker.md
  website/blog/2022-10-12-contribute-to-ferretdb-on-windows.md
  website/blog/2022-10-28-5-ways-to-avoid-database-vendor-lock-in.md
  website/blog/2022-11-08-pjson-how-to-store-bson-in-jsonb.md
  website/blog/2022-11-11-new-release-ferretdb-0-6-1.md
  website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.md
  website/blog/2022-11-18-ferretdb-percona-university-event-istanbul.md
  website/blog/2022-11-21-ferretdb-0-6-2-version-release.md
  website/blog/2022-12-23-ferretdb-new-release-with-tls.md
  website/blog/2023-01-04-ferretdb-beta-version-authentication.md
  website/blog/2023-01-17-ferretdb-0-8-1-version-release.md
  website/blog/2023-01-25-ferretdb-fetches-data-query-pushdown.md
  website/blog/2023-01-31-ferretdb-v-0-9-0-developer-preview.md
  website/blog/2023-02-07-5-database-alternatives-mongodb-2023.md
  website/blog/2023-02-14-2023-02-14-ferretdb-v-0-9-1-minor-release.md
  website/blog/2023-02-28-ferretdb-v-0-9-2.md
  website/blog/2023-03-21-mongodb-vs-postgresql-database-comparison.md
  website/blog/2023-04-11-ferretdb-1-0-ga-opensource-mongodb-alternative.md
  website/blog/2023-04-18-using-ferretdb-with-studio-3t.md
  website/blog/2023-05-18-ferretdb-meteor-mongodb-alternative.md
  website/blog/2023-06-09-document-databases-definition-features-use-cases.md
  website/blog/2023-06-21-meet-ferretdb-percona-university-casablanca-belgrade.md
  website/docs/contributing/writing-guide.md
  website/docs/main.md
  website/docs/understanding-ferretdb.md
Labels: documentation, trust, blog/marketing

#3066 Add blog post on "Community matters: fireside chat with Artem Ervits, CockroachDB"
  website/blog/2023-07-19-community-matters-fireside-chat-cockroachdb.md
  website/static/img/blog/artem-ervits.jpeg
  website/static/img/blog/community-call-cockroachdb.jpg
  website/static/img/blog/marcin-gwozdz.jpeg
Labels: trust, blog/marketing

#3063 Implement `$sum` aggregation standard operator
  integration/aggregate_documents_compat_test.go
  integration/aggregate_documents_test.go
  integration/query_projection_compat_test.go
  internal/handlers/common/aggregations/number.go
  internal/handlers/common/aggregations/operators/accumulators/sum.go
  internal/handlers/common/aggregations/operators/operators.go
  internal/handlers/common/aggregations/operators/sum.go
  internal/handlers/common/aggregations/operators/type.go
  internal/handlers/common/aggregations/stages/projection/projection.go
Labels: code/feature

#3081 Do not import `commonerrors` in tests
  .golangci.yml
  integration/.golangci-new.yml
  integration/.golangci.yml
  integration/delete_test.go
Labels: code/chore

#3086 Update Blog Post
  website/blog/2023-07-19-community-matters-fireside-chat-cockroachdb.md
Labels: trust, blog/marketing

#3093 Remove dead code
  internal/handlers/pg/pgdb/databases.go
  internal/util/contract/contract.go
  internal/util/contract/contract_test.go
Labels: code/chore

#3092 Allow to change SQLite URI in tests
  Taskfile.yml
  integration/Taskfile.yml
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/startup.go
  internal/backends/sqlite/metadata/pool/db.go
  internal/backends/sqlite/metadata/pool/pool.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/pool/uri.go
  internal/backends/sqlite/metadata/pool/uri_test.go
Labels: code/chore

#3024 Replace test doubles with constants
  CONTRIBUTING.md
  integration/query_bitwise_test.go
  integration/shareddata/scalars.go
  internal/handlers/common/filter.go
Labels: code/chore

#3097 Update tags formatting in writing guide
  website/docs/contributing/writing-guide.md
Labels: documentation

#3095 Improve `checkdocs` linter
  tools/checkdocs/checkdocs.go
  tools/checkdocs/checkdocs_test.go
Labels: code/chore

#3074 Add blog post on "Using Mingo with FerretDB"
  .gitattributes
  website/blog/2023-07-24-using-mingo-analyze-visualize-ferretdb-data.md
  website/static/img/blog/ferretdb-mingo.jpg
  website/static/img/blog/ferretdb-mingo/aggregation-operations.gif
  website/static/img/blog/ferretdb-mingo/basic-query.png
  website/static/img/blog/ferretdb-mingo/collection-data.png
  website/static/img/blog/ferretdb-mingo/connection-url-ferretdb.png
  website/static/img/blog/ferretdb-mingo/connection-window.png
  website/static/img/blog/ferretdb-mingo/mingo-dashboard.png
  website/static/img/blog/ferretdb-mingo/timerange-query.gif
Labels: trust, blog/marketing

#2882 Add validating max nested document/array depth
  integration/basic_test.go
  integration/helpers.go
  integration/nested_document_test.go
  internal/bson/array.go
  internal/bson/document.go
  internal/bson/regex.go
Labels: code/enhancement

#3104 Simplify `checkdocs` linter
  Taskfile.yml
  tools/checkdocs/checkdocs.go
  tools/checkdocs/checkdocs_test.go
  website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md
  website/blog/_guide/content-process.md
  website/docs/contributing/writing-guide.md
Labels: documentation, code/chore, trust

#3098 Add daily progress principle to `PROCESS.md`
  .github/PROCESS.md
Labels: project

#3096 Support `_id` aggregation operators for `$group` stage
  integration/aggregate_documents_compat_test.go
  integration/aggregate_documents_test.go
  internal/handlers/common/aggregations/stages/group.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
Labels: code/chore

#3114 Fix pushdown for `find` with `filter` and `limit`
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
Labels: code/bug-regression

#3117 Update MongoDB comparision blog post
  website/blog/2023-03-21-mongodb-vs-postgresql-database-comparison.md
Labels: blog/marketing

#2868 Validate database and collection names for SQLite handler
  integration/basic_test.go
  integration/commands_administration_test.go
  internal/backends/backend.go
  internal/backends/collection.go
  internal/backends/database.go
  internal/backends/doc.go
  internal/backends/error.go
  internal/backends/errorcode_string.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/metadata/metadata.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/validation.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/sqlite/msg_count.go
  internal/handlers/sqlite/msg_create.go
  internal/handlers/sqlite/msg_delete.go
  internal/handlers/sqlite/msg_drop.go
  internal/handlers/sqlite/msg_dropdatabase.go
  internal/handlers/sqlite/msg_find.go
  internal/handlers/sqlite/msg_insert.go
  internal/handlers/sqlite/msg_listcollections.go
  internal/handlers/sqlite/msg_ping.go
  internal/handlers/sqlite/msg_update.go
Labels: code/enhancement

#3123 Add basic metrics, logging and tracing for SQLite
  internal/backends/backend.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/metadata/pool/db.go
  internal/backends/sqlite/metadata/pool/pool.go
  internal/backends/sqlite/metadata/registry.go
  internal/handlers/sqlite/sqlite.go
  internal/util/fsql/db.go
  internal/util/fsql/fsql_test.go
  internal/util/fsql/metrics.go
Labels: code/enhancement

#3107 Backport v1.6.1 fixes
  integration/query_test.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
Labels: code/chore

#3128 Tweak and document SQLite URI parameters
  .gitignore
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/pool/uri.go
  internal/backends/sqlite/metadata/pool/uri_test.go
  internal/handlers/pg/pgdb/pool.go
  website/docs/configuration/flags.md
  website/docs/understanding-ferretdb.md
Labels: documentation, code/enhancement, trust

#3106 Add blog post on Grafana Monitoring for FerretDB
  website/blog/2023-07-27-grafana-monitoring-ferretdb.md
  website/static/img/blog/ferretdb-grafana.jpg
  website/static/img/blog/ferretdb-grafana/complete-dashboard.png
  website/static/img/blog/ferretdb-grafana/complete-table-view.png
  website/static/img/blog/ferretdb-grafana/good-first-issue.png
  website/static/img/blog/ferretdb-grafana/grafana-connection.png
  website/static/img/blog/ferretdb-grafana/issues-not-ready.png
  website/static/img/blog/ferretdb-grafana/issues-per-author.png
  website/static/img/blog/ferretdb-grafana/issues-per-label.png
  website/static/img/blog/ferretdb-grafana/issues-per-milestone.png
  website/static/img/blog/ferretdb-grafana/issues-per-state.png
  website/static/img/blog/ferretdb-grafana/mongodb-plugin.png
Labels: trust, blog/marketing

#3116 Support recursive operator calls for `$sum` aggregation accumulator
  integration/aggregate_documents_compat_test.go
  internal/handlers/common/aggregations/operators/accumulators/sum.go
  internal/handlers/common/aggregations/stages/group.go
Labels: code/chore

#3132 Prepare v1.7.0 release
  CHANGELOG.md
Labels: documentation

#3124 Cache SQLite tables metadata
  .golangci-new.yml
  CHANGELOG.md
  integration/basic_test.go
  integration/create_test.go
  internal/backends/doc.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/metadata/metadata.go
  internal/backends/sqlite/metadata/pool/pool.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/pool/uri.go
  internal/backends/sqlite/metadata/pool/uri_test.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/backends/sqlite/query_iterator.go
  internal/clientconn/connmetrics/listener_metrics.go
  internal/util/fsql/db.go
  internal/util/fsql/metrics.go
  internal/util/fsql/rows.go
  internal/util/state/metrics.go
  internal/util/testutil/teststress/stress.go
  website/docs/configuration/flags.md
Labels: code/enhancement
