Repository FerretDB/FerretDB, pull requests merged in 2023-10, with the labels that each got.

#3470 Speed-up Docker image building
  .github/workflows/format.yml
  .github/workflows/packages.yml
  .github/workflows/security.yml
  .github/workflows/website-preview.yml
  .gitignore
  CHANGELOG.md
  Taskfile.yml
  build/docker/all-in-one.Dockerfile
  build/docker/buildkitd.toml
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  build/nfpm.yml
  cmd/ferretdb/main.go
  go.mod
  go.sum
  internal/util/logging/logging.go
Labels: code/chore, trust, packages

#3477 Build `arm64` binaries and packages
  .github/RELEASE_CHECKLIST.md
  .github/settings.yml
  .github/workflows/packages.yml
  CONTRIBUTING.md
  README.md
  Taskfile.yml
  build/nfpm-amd64.yml
  build/nfpm-arm64.yml
  docker-compose.yml
  website/docs/quickstart-guide/deb.md
  website/docs/quickstart-guide/rpm.md
Labels: code/chore

#3479 Fix running a subset of tests
  .github/workflows/packages.yml
  cmd/envtool/envtool.go
  cmd/envtool/tests.go
Labels: code/chore

#3480 Add a workaround for Docker build failures
  .github/workflows/packages.yml
  Taskfile.yml
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
Labels: code/chore, trust, packages

#3485 Add stubs for `Collection.Compact`
  .github/settings.yml
  go.mod
  integration/go.mod
  internal/backends/collection.go
  internal/backends/collection_test.go
  internal/backends/decorators/dummy/collection.go
  internal/backends/decorators/oplog/collection.go
  internal/backends/hana/collection.go
  internal/backends/helpers_test.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  tools/go.mod
  tools/golangci/go.mod
Labels: code/chore

#3476 Process collection name param using `collection` tag
  internal/handlers/common/count.go
  internal/handlers/common/delete_params.go
  internal/handlers/common/distinct.go
  internal/handlers/common/find.go
  internal/handlers/common/findandmodify.go
  internal/handlers/common/insert.go
  internal/handlers/common/update_params.go
  internal/handlers/commonparams/extract_params.go
  internal/handlers/commonparams/extract_params_test.go
Labels: code/chore

#3465 Implement `explain`
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/helpers.go
Labels: code/feature

#3464 Implement `database.Stats`
  internal/backends/database.go
  internal/backends/postgresql/database.go
  internal/backends/postgresql/database_test.go
  internal/backends/postgresql/postgresql.go
Labels: code/feature

#3494 Revive logic of lower cased key for collection name
  integration/basic_test.go
  internal/handlers/commonparams/extract_params.go
  internal/handlers/commonparams/extract_params_test.go
Labels: code/chore

#3450 Add `$project` and `$unset` to aggregation stages section
  website/docs/aggregation-operations/aggregation-stages.md
Labels: documentation

#3497 Extract `ReservedPrefix` constant
  internal/backends/postgresql/metadata/registry.go
  internal/backends/sqlite/metadata/metadata.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/validation.go
Labels: code/chore

#3502 Fix stress tests
  integration/commands_diagnostic_test.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/util/testutil/teststress/stress.go
Labels: code/chore

#3472 Add operation mode definition to Glossary
  website/docs/reference/glossary.md
Labels: documentation, trust

#3503 Fix concurrent Docker builds
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
Labels: code/chore, trust, packages

#3434 Store indexes metadata
  internal/backends/backends.go
  internal/backends/postgresql/collection_test.go
  internal/backends/postgresql/database_test.go
  internal/backends/postgresql/dummy_test.go
  internal/backends/postgresql/metadata/indexes.go
  internal/backends/postgresql/metadata/metadata.go
  internal/backends/postgresql/metadata/pool/dummy_test.go
  internal/backends/postgresql/metadata/pool/transaction_test.go
  internal/backends/postgresql/metadata/registry.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/backends/sqlite/collection_test.go
  internal/backends/sqlite/metadata/metadata.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/metadata/settings.go
  internal/util/state/state.go
Labels: code/chore

#3491 Relax restrictions when _id is not the first field in projection
  integration/query_projection_test.go
  internal/handlers/common/projection.go
Labels: code/bug

#3499 Improve definitions for aggregation stages
  website/docs/aggregation-operations/aggregation-stages.md
Labels: documentation, trust

#3478 Implement `collection.Stats`
  internal/backends/collection.go
  internal/backends/collection_test.go
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/database_test.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/collection_test.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_collstats.go
  internal/handlers/sqlite/msg_datasize.go
Labels: code/feature

#3468 Implement `CreateIndexes`, `DropIndexes`, `ListIndexes`
  integration/indexes_command_compat_test.go
  integration/indexes_compat_test.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/sqlite/msg_createindexes.go
Labels: code/feature

#3461 Add TODOs for capped collections
  cmd/ferretdb/main.go
  internal/backends/collection.go
  internal/backends/database.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/common/find.go
  internal/handlers/pg/msg_serverstatus.go
  internal/handlers/sqlite/msg_collstats.go
  internal/handlers/sqlite/msg_create.go
  website/docs/reference/supported-commands.md
Labels: documentation, code/chore, trust

#3514 Tweak tests timeouts
  .github/workflows/_integration.yml
  .github/workflows/go.yml
  Taskfile.yml
Labels: code/chore

#3515 Fix blog post formatting
  website/blog/2023-09-29-ferretdb-database-choice-enmeshed-customers.md
Labels: blog/marketing

#3510 Bump Go version
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
Labels: deps, trust, packages

#3512 Disallow importing handlers code from backends
  .golangci.yml
Labels: code/chore

#3507 Fix typo in contributing documentation
  CONTRIBUTING.md
Labels: documentation

#3496 Disable `auto_vacuum` for SQLite
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/pool/uri.go
  internal/backends/sqlite/metadata/pool/uri_test.go
Labels: code/chore

#3519 Use `Ping` for checking connection
  integration/setup/client.go
  internal/backends/collection.go
  internal/backends/database.go
  internal/backends/postgresql/postgresql.go
  internal/backends/sqlite/sqlite.go
Labels: code/chore

#3482 Implement filter pushdown for PostgreSQL
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/query.go
  internal/backends/postgresql/query_test.go
Labels: code/feature

#3524 Add mermaid diagrams
  README.md
Labels: documentation

#3531 Fix unit tests for indexes
  internal/backends/postgresql/metadata/registry_test.go
  internal/backends/postgresql/postgresql.go
Labels: code/chore

#3522 Make new PostgreSQL backend tests pass
  integration/aggregate_documents_compat_test.go
  integration/commands_administration_test.go
  integration/query_array_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_projection_compat_test.go
  integration/query_test.go
  integration/setup/client.go
  integration/setup/test_helpers.go
Labels: code/chore

#3534 Add info about indexes to `dbStats` response
  internal/backends/collection_test.go
  internal/backends/postgresql/database_test.go
  internal/backends/postgresql/postgresql.go
Labels: code/feature

#3530 Update documentation
  .github/PROCESS.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/settings.yml
  CHANGELOG.md
  cmd/ferretdb/main.go
  internal/clientconn/listener.go
  website/docs/configuration/flags.md
Labels: documentation, trust

#3537 Improve embedded package documentation
  ferretdb/ferretdb.go
Labels: code/chore

#3553 Use separate PostgreSQL databases in tests
  .github/workflows/js.yml
  Taskfile.yml
  cmd/envtool/envtool.go
  docker-compose.yml
  integration/Taskfile.yml
  integration/embedded_test.go
  integration/getmore_test.go
  integration/go.mod
  integration/setup/client.go
  integration/setup/listener.go
  internal/backends/helpers_test.go
  internal/backends/postgresql/database_test.go
  internal/backends/postgresql/metadata/pool/opendb.go
  internal/backends/postgresql/metadata/registry.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/handlers/pg/pgdb/database_metadata_test.go
  internal/handlers/pg/pgdb/indexes_test.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/pg/pgdb/transactions_test.go
  internal/util/testutil/db.go
  internal/util/testutil/pg.go
  website/docs/configuration/flags.md
Labels: code/chore

#3555 Add release blog post for FerretDB v1.12
  website/blog/2023-10-11-ferretdb-v112-available.md
  website/static/img/blog/ferretdb-v1.12.png
Labels: trust, blog/marketing

#3561 Crush images
  website/static/img/blog/ferretdb-enmeshed.png
  website/static/img/blog/ferretdb-v1.12.png
Labels: documentation, trust

#3513 Make `collStats` calculate collection size accurately for `PostgreSQL` statistics
  internal/backends/collection_test.go
  internal/backends/postgresql/database_test.go
  internal/backends/postgresql/postgresql.go
  internal/backends/sqlite/sqlite.go
Labels: code/chore

#3536 Implement `Collection.Compact` for SQLite
  internal/backends/collection_test.go
  internal/backends/sqlite/collection.go
Labels: code/chore

#3523 Fix invalid validation for `_id` field
  integration/shareddata/composites.go
  internal/types/document_validation.go
  internal/types/document_validation_test.go
Labels: code/bug

#3569 Use self-hosted runner for packages building
  .github/workflows/cleanup.yml
  .github/workflows/packages.yml
  Taskfile.yml
Labels: code/chore

#3541 Fix `explain` panic for non-existent collection on PostgreSQL
  integration/explain_command_test.go
  internal/backends/collection.go
  internal/backends/postgresql/collection.go
Labels: code/bug

#3560 Add basic logging for PostgreSQL backend
  internal/backends/postgresql/metadata/pool/opendb.go
Labels: code/enhancement

#3570 Report actual backend name
  cmd/ferretdb/main.go
  integration/setup/listener.go
  internal/backends/backend.go
  internal/backends/backend_test.go
  internal/backends/collection_test.go
  internal/backends/decorators/dummy/backend.go
  internal/backends/decorators/oplog/backend.go
  internal/backends/hana/backend.go
  internal/backends/helpers_test.go
  internal/backends/postgresql/backend.go
  internal/backends/postgresql/metadata/pool/opendb.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/metadata/pool/opendb.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/sqlite/msg_getlog.go
  internal/util/state/metrics.go
  internal/util/state/metrics_test.go
  internal/util/state/state.go
  internal/util/telemetry/reporter.go
  internal/util/telemetry/reporter_test.go
Labels: code/enhancement, trust, packages

#3571 Change SQLite directory for Docker images
  CHANGELOG.md
  README.md
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  website/docs/configuration/flags.md
Labels: documentation, code/chore, trust, packages

#3572 Do not create databases during local setup
  Taskfile.yml
  cmd/envtool/envtool.go
  internal/backends/collection.go
  internal/backends/postgresql/query.go
  internal/handlers/common/delete_params.go
  internal/handlers/common/update_params.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/sqlite/msg_find.go
Labels: code/chore

#3577 Build `arm/v7` binaries
  Taskfile.yml
  build/deps/ubi9.Dockerfile
  build/deps/ubuntu2204.Dockerfile
  build/nfpm-amd64.yml
  build/nfpm.yml
  docker-compose.yml
  tools/go.mod
  tools/go.sum
Labels: code/chore, trust, packages

#3565 Add more tests and fixes for `$collStats` aggregation stage
  integration/aggregate_stats_compat_test.go
  integration/aggregate_stats_test.go
  internal/handlers/common/aggregations/stages/collstats.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/sqlite/msg_aggregate.go
Labels: code/chore

#3532 Enable Mermaid diagrams in Docusaurus
  website/docs/basic-operations/index.md
  website/docs/main.md
  website/docs/understanding-ferretdb.md
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
Labels: documentation, code/chore, trust

#3576 Build `arm/v7` `.deb` and `.rpm` packages and binaries
  Taskfile.yml
  build/docker/all-in-one.Dockerfile
Labels: code/chore, trust, packages

#3579 Add tests for insertion of documents with invalid `_id` fields
  integration/insert_command_test.go
Labels: code/chore

#3538 Add more data to output of `collStats` and `dbStats`
  integration/aggregate_stats_test.go
  integration/commands_administration_compat_test.go
  integration/commands_administration_test.go
  internal/backends/collection.go
  internal/backends/collection_test.go
  internal/backends/database.go
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/database.go
  internal/backends/postgresql/database_test.go
  internal/backends/postgresql/postgresql.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/database_test.go
  internal/backends/sqlite/sqlite.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_collstats.go
  internal/handlers/sqlite/msg_datasize.go
  internal/handlers/sqlite/msg_dbstats.go
Labels: code/chore

#3575 Implement `indexSizes` for `collStats`
  integration/aggregate_stats_test.go
  integration/commands_administration_test.go
  internal/backends/collection.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/common/aggregations/stages/collstats.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_collstats.go
Labels: code/enhancement

#3585 Update `dataSize` and `dbStats` integration tests
  integration/commands_administration_test.go
Labels: code/chore

#3588 Do not return stats in `Backend.ListDatabases`
  internal/backends/backend.go
  internal/backends/collection.go
  internal/backends/database.go
  internal/backends/postgresql/backend.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/collection.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_collstats.go
  internal/handlers/sqlite/msg_listdatabases.go
Labels: code/chore

#3591 Integrate Statsviz
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/util/debug/debug.go
Labels: code/chore

#3595 Remove old TODOs
  internal/backends/sqlite/collection.go
  internal/handlers/common/filter.go
  internal/types/compare_order.go
Labels: code/chore

#3590 Use stdlib's `slices` package
  .golangci.yml
  integration/.golangci.yml
  integration/setup/setup.go
  integration/setup/startup.go
  internal/backends/backend.go
  internal/backends/collection_test.go
  internal/backends/database.go
  internal/backends/error.go
  internal/backends/postgresql/metadata/indexes.go
  internal/backends/postgresql/metadata/pool/opendb.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/metadata/settings.go
  internal/handlers/common/aggregations/stages/projection/projection.go
  internal/handlers/common/filter.go
  internal/handlers/common/projection.go
  internal/handlers/common/update.go
  internal/handlers/commonparams/extract_params.go
  internal/handlers/pg/msg_renamecollection.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_collstats.go
  internal/handlers/sqlite/msg_createindexes.go
  internal/types/document.go
  internal/types/path.go
  internal/util/testutil/equal.go
Labels: code/chore

#3596 Remove done TODO
  internal/handlers/pg/msg_aggregate.go
Labels: code/chore

#3277 Check that linked issues are open
  .github/workflows/go.yml
  CONTRIBUTING.md
  tools/checkcomments/checkcomments.go
  tools/checkcomments/testdata/testdata.go
  tools/cleantool/cleantool.go
  tools/go.mod
  tools/go.sum
Labels: code/chore

#3504 Implement sort pushdown for PostgreSQL
  internal/backends/collection.go
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/query.go
  internal/handlers/sqlite/msg_explain.go
  internal/handlers/sqlite/msg_find.go
Labels: code/feature

#3592 Improve `/debug` page
  internal/util/debug/debug.go
Labels: code/chore, community

#3599 Add filter pushdown for `_id: <string>` for SQLite
  integration/pushdown.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_projection_compat_test.go
  integration/query_test.go
  internal/backends/sqlite/collection.go
Labels: code/enhancement, trust, packages

#3598 Make it easier to run old PG handler
  Taskfile.yml
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/listener.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/registry/postgresql.go
  internal/handlers/registry/registry.go
Labels: code/chore

#3578 Enable linters to accept exclamation marks in headers
  build/.markdownlint.yml
Labels: documentation

#3593 Add SQLite info to glossary list
  website/docs/reference/glossary.md
Labels: documentation, trust

#3597 Do not skip invalid TODOs
  .github/workflows/conform-pr.yml
  cmd/envtool/tests_test.go
  integration/aggregate_documents_compat_test.go
  integration/commands_administration_test.go
  integration/create_test.go
  integration/findandmodify_test.go
  integration/setup/listener.go
  integration/setup/setup_compat.go
  integration/shareddata/faker.go
  integration/update_compat_test.go
  internal/backends/decorators/oplog/collection.go
  internal/backends/hana/backend.go
  internal/backends/postgresql/metadata/pool/opendb.go
  internal/backends/postgresql/metadata/pool/pool.go
  internal/bson/document.go
  internal/clientconn/conn.go
  internal/handlers/common/aggregations/number.go
  internal/handlers/common/filter.go
  internal/handlers/common/findandmodify.go
  internal/handlers/common/validate.go
  internal/handlers/hana/hana.go
  internal/handlers/hana/msg_drop.go
  internal/handlers/hana/msg_insert.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/pg.go
  internal/handlers/sqlite/msg_drop.go
  internal/types/array.go
  internal/types/compare.go
  internal/types/compare_test.go
  internal/types/document.go
  internal/types/types.go
  internal/wire/op_msg.go
  internal/wire/record.go
  internal/wire/validation.go
  tools/checkcomments/checkcomments.go
  tools/checkcomments/testdata/testdata.go
Labels: code/chore

#3580 Implement limit pushdown for PostgreSQL
  integration/explain_command_test.go
  integration/query_test.go
  internal/backends/collection.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/common/explain.go
  internal/handlers/common/params.go
  internal/handlers/sqlite/msg_explain.go
  internal/handlers/sqlite/msg_find.go
Labels: code/feature

#3605 Unskip filter pushdown integration tests
  integration/query_array_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_projection_compat_test.go
Labels: code/chore

#3594 Implement free storage in `collStats`, `dbStats` and `aggregate` `$collStats`
  integration/aggregate_stats_test.go
  integration/commands_administration_compat_test.go
  integration/commands_administration_test.go
  internal/backends/collection.go
  internal/backends/database.go
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/database.go
  internal/backends/postgresql/database_test.go
  internal/backends/postgresql/postgresql.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/database_test.go
  internal/backends/sqlite/sqlite.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_collstats.go
  internal/handlers/sqlite/msg_dbstats.go
Labels: code/feature

#3568 Add SQLite set up docs
  website/docs/quickstart-guide/docker.md
Labels: documentation, trust

#3563 Call `ANALYZE` less often
  integration/aggregate_stats_compat_test.go
  integration/aggregate_stats_test.go
  integration/commands_administration_test.go
  internal/backends/collection.go
  internal/backends/collection_test.go
  internal/backends/database.go
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/database.go
  internal/backends/postgresql/database_test.go
  internal/backends/postgresql/postgresql.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/database_test.go
  internal/backends/sqlite/sqlite.go
  internal/backends/sqlite/sqlite_test.go
  internal/handlers/sqlite/msg_collstats.go
  internal/handlers/sqlite/msg_dbstats.go
  internal/handlers/sqlite/msg_validate.go
Labels: code/chore

#2802 Add "How to Install FerretDB on Ubuntu" blog post
  website/blog/2023-10-19-install-ferretdb-mongodb-alternative-ubuntu.md
  website/static/img/blog/install-ferretdb-ubuntu.jpg
Labels: trust, blog/marketing

#3620 Update ILLA blog post
  website/blog/2023-10-18-build-internal-apps-illa-cloud-ferretdb.md
  website/static/img/blog/ferretdb-illacloud.jpg
Labels: trust, blog/marketing

#3609 Keep envtool's version always up-to-date
  Taskfile.yml
Labels: code/chore

#3617 Fix some tests for SQLite backend
  .github/workflows/docs.yml
  .github/workflows/website-preview.yml
  .golangci.yml
  Taskfile.yml
  integration/.golangci.yml
  internal/backends/helpers_test.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/database_test.go
  internal/backends/sqlite/metadata/pool/opendb.go
  internal/backends/sqlite/metadata/pool/pool.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/pool/uri.go
  internal/backends/sqlite/metadata/pool/uri_test.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/backends/sqlite/sqlite_test.go
  internal/handlers/pg/msg_update.go
  website/docs/configuration/flags.md
Labels: code/chore

#3625 Do not create OpLog database/collection on a fly
  internal/backends/decorators/oplog/backend.go
  internal/backends/decorators/oplog/collection.go
  internal/backends/decorators/oplog/database.go
  internal/backends/decorators/oplog/oplog.go
Labels: code/chore

#3623 Add Links to blog
  website/blog/2023-10-19-install-ferretdb-mongodb-alternative-ubuntu.md
Labels: trust, blog/marketing

#3602 Make `listIndexes` return a sorted list
  integration/indexes_command_compat_test.go
  integration/indexes_compat_test.go
  internal/backends/collection.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
Labels: code/chore

#3607 Implement pushdown for `aggregate`
  integration/aggregate_documents_compat_test.go
  internal/backends/postgresql/collection.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_explain.go
Labels: code/chore

#3628 Prepare v1.13.0 release
  CHANGELOG.md
  build/trivy-secret.yml
  tools/go.mod
  tools/go.sum
  website/docs/configuration/flags.md
Labels: documentation, trust, packages

#3614 Support `create` for capped collections
  integration/commands_administration_compat_test.go
  integration/create_test.go
  integration/indexes_command_test.go
  integration/setup/listener.go
  integration/setup/setup.go
  internal/backends/database.go
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/database.go
  internal/backends/postgresql/metadata/metadata.go
  internal/backends/postgresql/metadata/registry.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/metadata/metadata.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/backends/sqlite/metadata/settings.go
  internal/backends/sqlite/sqlite_test.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_serverstatus.go
  internal/handlers/sqlite/msg_create.go
  website/docs/reference/supported-commands.md
Labels: code/feature

#3559 Implement `compact` command
  integration/commands_administration_test.go
  internal/handlers/commoncommands/msg_listcommands.go
  internal/handlers/hana/msg_compact.go
  internal/handlers/handlers.go
  internal/handlers/pg/msg_compact.go
  internal/handlers/sqlite/msg_compact.go
  website/docs/reference/supported-commands.md
Labels: code/feature

#3636 Disallow capped collection creation when disabled
  integration/create_test.go
  internal/backends/database.go
  internal/backends/postgresql/metadata/metadata.go
  internal/backends/postgresql/metadata/registry.go
  internal/backends/sqlite/metadata/registry.go
  internal/handlers/sqlite/msg_create.go
Labels: code/chore

#3639 Add blogpost for Ferretdb v1.13.0
  website/blog/2023-10-24-ferretdb-v1130-new-postgresql-backend.md
  website/static/img/blog/ferretdb-v1.13.0.png
Labels: trust, blog/marketing

#3645 Optimize detection of duplicate fields
  integration/benchmarks_test.go
  internal/types/document.go
  internal/types/document_test.go
  internal/types/types.go
Labels: code/enhancement

#3657 Run backend tests for SAP HANA
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/backends/helpers_test.go
Labels: code/chore

#3651 Update `golangci-lint`
  .golangci-new.yml
  .golangci.yml
  Taskfile.yml
  integration/.golangci-new.yml
  integration/.golangci.yml
  integration/Taskfile.yml
  internal/bson/bson.go
  internal/handlers/common/aggregations/stages/projection/projection.go
  internal/handlers/sjson/sjson.go
  internal/handlers/sjson/sjson_test.go
  internal/types/fjson/fjson.go
  internal/types/types.go
  internal/wire/msg_body.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
  tools/tools.go
Labels: deps

#3586 Remove `pgdb` from `envtool`
  cmd/envtool/envtool.go
Labels: code/chore

#3643 Add test for capped collection in `aggregate` `$collStats`
  integration/aggregate_stats_test.go
  integration/commands_administration_test.go
Labels: code/chore

#3610 Support `InsertAll` and `FindAll` for capped collections
  integration/pushdown.go
  integration/query_compat_test.go
  internal/backends/collection.go
  internal/backends/collection_test.go
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/metadata/metadata.go
  internal/backends/postgresql/query.go
  internal/backends/postgresql/query_iterator.go
  internal/backends/postgresql/query_test.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/collection_test.go
  internal/backends/sqlite/metadata/metadata.go
  internal/backends/sqlite/query.go
  internal/backends/sqlite/query_iterator.go
  internal/backends/sqlite/query_test.go
  internal/util/fsql/rows.go
Labels: code/feature

#3105 Enable `GOMAXPROCS` autotuning
  cmd/ferretdb/main.go
  go.mod
  go.sum
Labels: code/chore

#3646 Add Vultr blog post
  website/blog/2023-10-30-building-mongodb-like-developer-experience-vultr.md
  website/static/img/blog/ferretdb-vultr.jpg
  website/static/img/blog/mike-biondi.jpeg
Labels: trust, blog/marketing

#3658 Update blog post on Ubuntu
  website/blog/2023-10-19-install-ferretdb-mongodb-alternative-ubuntu.md
Labels: trust, blog/marketing

#3200 Add blog post on MongoDB sorting for scalar values
  website/blog/2023-10-31-mongodb-sorting-scalar.md
  website/blog/authors.yml
  website/static/img/blog/mongodb-sorting-scalar.jpg
Labels: trust, blog/engineering

#3621 Optimize `insert` performance by batching
  integration/insert_command_test.go
  integration/insert_compat_test.go
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/insert.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/insert.go
  internal/handlers/sqlite/msg_insert.go
Labels: code/enhancement

#3664 Add timing information to `envtool` output
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  build/nfpm.yml
  cmd/envtool/tests.go
  cmd/envtool/tests_test.go
  tools/go.mod
  tools/go.sum
Labels: code/chore
