Repository FerretDB/FerretDB, pull requests merged in 2023-09, with the labels that each got.

#3296 Make `update`s atomic for SQLite
  internal/backends/collection.go
  internal/backends/doc.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/metadata/pool/pool.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/pool/uri.go
  internal/handlers/common/delete_params.go
  internal/handlers/common/update_params.go
  internal/handlers/sqlite/msg_update.go
Labels: code/enhancement

#3294 Add backend interface for `collStats`
  internal/backends/collection.go
  internal/backends/database.go
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/database.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/database_test.go
  internal/handlers/sqlite/msg_dbstats.go
Labels: code/chore

#3279 Implement `getLog` for SQLite
  integration/commands_diagnostic_test.go
  internal/backends/backend.go
  internal/backends/postgresql/backend.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/collection_test.go
  internal/backends/sqlite/database_test.go
  internal/backends/sqlite/metadata/pool/pool.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/handlers/sqlite/msg_getlog.go
  internal/handlers/sqlite/sqlite.go
Labels: code/feature

#3264 Implement `explain` command for SQLite
  integration/commands_diagnostic_test.go
  integration/explain_compat_test.go
  internal/backends/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/sqlite/msg_explain.go
Labels: code/feature

#3295 Implement `collStats` for SQLite
  integration/aggregate_stats_compat_test.go
  integration/aggregate_stats_test.go
  integration/commands_administration_compat_test.go
  integration/commands_administration_test.go
  internal/backends/collection.go
  internal/backends/database.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/collection_test.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/database_test.go
  internal/handlers/pg/msg_collstats.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_collstats.go
  internal/handlers/sqlite/msg_dbstats.go
Labels: code/feature

#3305 Clean-up `*types.Timestamp` a bit
  integration/helpers.go
  internal/handlers/sjson/schema_test.go
  internal/types/object_id_test.go
  internal/types/timestamp.go
  internal/types/timestamp_test.go
Labels: code/chore

#3266 Support `$bit` bitwise update operator
  integration/update_field_compat_test.go
  integration/update_field_test.go
  internal/handlers/common/params.go
  internal/handlers/common/update.go
Labels: code/feature

#3307 Tweak MongoDB initialization process
  .github/settings.yml
  Taskfile.yml
  build/certs/Makefile
  build/deps/mongo6.Dockerfile
  build/mongod.conf
  build/mongodb.conf
  build/mongodb_secured.conf
  cmd/envtool/envtool.go
  docker-compose.yml
  integration/Taskfile.yml
  integration/commands_administration_test.go
  internal/util/ctxutil/ctxutil.go
  internal/util/ctxutil/ctxutil_test.go
Labels: code/chore

#3249 Add blog post on "Using PgManage as PostgreSQL GUI Admin for FerretDB"
  website/blog/2023-09-06-pgmanage-postgresql-gui-admin-ferretdb.md
  website/static/img/blog/ferretdb-pgmanage.jpg
  website/static/img/blog/ferretdb-pgmanage/connection-settings.png
  website/static/img/blog/ferretdb-pgmanage/imported-data.png
  website/static/img/blog/ferretdb-pgmanage/select-table-data.png
  website/static/img/blog/ferretdb-pgmanage/server-configuration-ui.png
  website/static/img/blog/ferretdb-pgmanage/server-configuration.png
Labels: trust, blog/marketing

#3318 Skip tests for `enable` `setFreeMonitoring` for MongoDB
  integration/commands_administration_test.go
  integration/commands_freemonitoring_test.go
Labels: code/chore

#3302 Implement `findAndModify` for SQLite
  integration/findandmodify_compat_test.go
  integration/findandmodify_test.go
  internal/handlers/sqlite/msg_findandmodify.go
Labels: code/feature

#3316 Implement `serverStatus` and `dataSize` commands for SQLite
  integration/commands_administration_test.go
  internal/backends/backend.go
  internal/backends/postgresql/backend.go
  internal/backends/sqlite/backend.go
  internal/handlers/commonparams/params.go
  internal/handlers/pg/msg_datasize.go
  internal/handlers/pg/msg_renamecollection.go
  internal/handlers/sqlite/msg_datasize.go
  internal/handlers/sqlite/msg_serverstatus.go
Labels: code/feature

#3311 Update the writing guide
  website/docs/contributing/writing-guide.md
Labels: documentation, trust

#3301 Implement `listIndexes` for SQLite
  integration/indexes_command_compat_test.go
  integration/indexes_command_test.go
  integration/indexes_compat_test.go
  internal/backends/collection.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/sqlite/msg_listindexes.go
Labels: code/feature

#3315 Cleanup `$bit` update operator
  integration/update_field_compat_test.go
  internal/handlers/common/update.go
  website/docs/reference/supported-commands.md
Labels: documentation, code/chore

#3303 Add backend decorators and OpLog stub
  Taskfile.yml
  build/deps/mongo6.Dockerfile
  cmd/ferretdb/main.go
  integration/setup/listener.go
  integration/setup/setup.go
  internal/backends/decorators/dummy/backend.go
  internal/backends/decorators/dummy/collection.go
  internal/backends/decorators/dummy/database.go
  internal/backends/decorators/dummy/dummy_test.go
  internal/backends/decorators/oplog/backend.go
  internal/backends/decorators/oplog/collection.go
  internal/backends/decorators/oplog/database.go
  internal/backends/decorators/oplog/oplog_test.go
  internal/handlers/registry/newpg.go
  internal/handlers/registry/registry.go
  internal/handlers/registry/sqlite.go
  internal/handlers/sqlite/sqlite.go
  internal/types/document.go
Labels: code/chore

#3324 Use Go 1.21
  .github/workflows/clean.yml
  .github/workflows/conform-pr.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/go-trust.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  .github/workflows/packages.yml
  .github/workflows/security.yml
  .github/workflows/website-preview.yml
  CONTRIBUTING.md
  build/deps/trivy.Dockerfile
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/check.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
  tools/old.go
  tools/tools.go
Labels: deps

#3327 Remove `Database.Close`
  build/version/version.go
  ferretdb/ferretdb.go
  go.mod
  integration/commands_authentication_test.go
  internal/backends/backend.go
  internal/backends/collection.go
  internal/backends/database.go
  internal/backends/decorators/dummy/backend.go
  internal/backends/decorators/dummy/database.go
  internal/backends/decorators/oplog/backend.go
  internal/backends/decorators/oplog/database.go
  internal/backends/doc.go
  internal/backends/postgresql/backend.go
  internal/backends/postgresql/database.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/collection_test.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/database_test.go
  internal/backends/sqlite/doc.go
  internal/handlers/common/saslstart.go
  internal/handlers/sqlite/cmd_query.go
  internal/handlers/sqlite/msg_aggregate.go
  internal/handlers/sqlite/msg_collstats.go
  internal/handlers/sqlite/msg_count.go
  internal/handlers/sqlite/msg_create.go
  internal/handlers/sqlite/msg_datasize.go
  internal/handlers/sqlite/msg_dbstats.go
  internal/handlers/sqlite/msg_delete.go
  internal/handlers/sqlite/msg_distinct.go
  internal/handlers/sqlite/msg_drop.go
  internal/handlers/sqlite/msg_explain.go
  internal/handlers/sqlite/msg_find.go
  internal/handlers/sqlite/msg_findandmodify.go
  internal/handlers/sqlite/msg_insert.go
  internal/handlers/sqlite/msg_listcollections.go
  internal/handlers/sqlite/msg_listindexes.go
  internal/handlers/sqlite/msg_ping.go
  internal/handlers/sqlite/msg_saslstart.go
  internal/handlers/sqlite/msg_serverstatus.go
  internal/handlers/sqlite/msg_update.go
Labels: code/chore

#3269 Implement `listDatabases` for SQLite
  integration/commands_administration_test.go
  internal/backends/sqlite/backend.go
Labels: code/feature

#3321 Implement `renameCollection` for SQLite
  integration/renamecollection_compat_test.go
  integration/renamecollection_test.go
  internal/backends/database.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/metadata/registry.go
  internal/handlers/sqlite/msg_renamecollection.go
Labels: code/feature

#3304 Implement `createIndexes` for SQLite
  integration/explain_compat_test.go
  integration/indexes_command_compat_test.go
  integration/indexes_command_test.go
  integration/indexes_compat_test.go
  internal/backends/collection.go
  internal/backends/decorators/dummy/collection.go
  internal/backends/decorators/oplog/collection.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/metadata/metadata.go
  internal/backends/sqlite/metadata/pool/pool.go
  internal/backends/sqlite/metadata/registry.go
  internal/handlers/sqlite/msg_createindexes.go
Labels: code/feature

#3268 Document how to test for compatibility
  website/docs/configuration/_category_.yml
  website/docs/contributing/_category_.yml
  website/docs/diff.md
  website/docs/migration.md
  website/docs/reference/_category_.yml
  website/docs/security/_category_.yml
  website/docs/telemetry.md
Labels: documentation, trust

#3330 Support `_id` implicit filter for `ObjectID` in SQLite
  Taskfile.yml
  integration/aggregate_documents_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_test.go
  internal/backends/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/sqlite/msg_count.go
  internal/handlers/sqlite/msg_delete.go
  internal/handlers/sqlite/msg_distinct.go
  internal/handlers/sqlite/msg_explain.go
  internal/handlers/sqlite/msg_find.go
  internal/handlers/sqlite/msg_findandmodify.go
  internal/handlers/sqlite/msg_update.go
Labels: code/feature

#3338 Update blog authors
  website/blog/2021-11-05-mangodb-overwhelming-enthusiasm-for-truly-open-source-mongodb-replacement.md
  website/blog/2021-12-01-mangodb-has-a-new-name-and-the-momentum-is-stronger-than-ever-meet-ferretdb.md
  website/blog/2021-12-07-mongodb-compatibility-whats-really-important.md
  website/blog/2022-04-18-ferretdb-v-0-1-1-is-out-and-other-exciting-updates.md
  website/blog/2022-05-16-using-cla-assistant-with-ferretdb.md
  website/blog/2022-06-27-developers-need-ferretdb-stackoverflow-developer-survey-2022.md
  website/blog/2022-06-28-new-release-ferretdb-0-4-0.md
  website/blog/2022-07-11-0-5-0-release-is-out-embedding-ferretdb-into-go-programs.md
  website/blog/2022-07-27-new-ferretdb-minor-release-0-5-1.md
  website/blog/2022-08-23-open-source-is-in-danger.md
  website/blog/2022-09-21-how-to-keep-control-of-your-infra-using-ferretdb-and-tigris.md
  website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md
  website/blog/2022-10-28-5-ways-to-avoid-database-vendor-lock-in.md
  website/blog/2022-11-11-new-release-ferretdb-0-6-1.md
  website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.md
  website/blog/2022-11-18-ferretdb-percona-university-event-istanbul.md
  website/blog/2022-11-21-ferretdb-0-6-2-version-release.md
  website/blog/2022-12-23-ferretdb-new-release-with-tls.md
  website/blog/2023-01-04-ferretdb-beta-version-authentication.md
  website/blog/2023-01-17-ferretdb-0-8-1-version-release.md
  website/blog/2023-01-31-ferretdb-v-0-9-0-developer-preview.md
  website/blog/2023-02-07-5-database-alternatives-mongodb-2023.md
  website/blog/authors.yml
Labels: trust, blog/marketing

#3336 Add more tests
  Taskfile.yml
  integration/helpers.go
  integration/query_test.go
  integration/update_field_test.go
  internal/backends/sqlite/metadata/metadata.go
Labels: code/chore

#3344 Do not `ConsumeValues` in the `$group` aggregation stage
  internal/handlers/common/aggregations/stages/group.go
Labels: code/chore

#3329 Implement `dropIndexes` for SQLite
  integration/indexes_command_compat_test.go
  integration/indexes_command_test.go
  integration/indexes_compat_test.go
  internal/backends/collection.go
  internal/backends/decorators/dummy/collection.go
  internal/backends/decorators/oplog/collection.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/metadata/registry.go
  internal/handlers/sqlite/msg_dropindexes.go
  internal/handlers/sqlite/sqlite.go
Labels: code/feature

#3350 Fix params handling for `dropIndexes` implementation for SQLite
  integration/indexes_command_compat_test.go
  internal/handlers/sqlite/msg_dropindexes.go
Labels: code/chore

#3353 Return correct response if unique index violation happened on SQLite backend
  integration/update_compat_test.go
  internal/handlers/sqlite/msg_update.go
Labels: code/chore

#3357 Build Docker images for `arm/v6`
  Taskfile.yml
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
Labels: trust, packages

#3323 Update category links in writing guide
  website/docs/contributing/writing-guide.md
Labels: documentation, trust

#3345 Add test for inserting different data types
  integration/insert_command_test.go
Labels: code/feature

#3359 Improve blog format
  website/blog/2023-01-04-ferretdb-beta-version-authentication.md
Labels: trust, blog/marketing

#3364 Recreate test directory
  integration/setup/listener.go
Labels: code/chore

#3365 Use consistent spelling
  CHANGELOG.md
  CONTRIBUTING.md
  internal/bson/bson_test.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_find.go
Labels: code/chore

#3346 Add a blog post for v1.10
  website/blog/2023-09-15-ferretdb-v1-10-production-ready-sqlite.md
  website/blog/_guide/YYYY-MM-DD.blog-template.md
  website/static/img/blog/2023-09-15/image1.png
  website/static/img/blog/2023-09-15/image2.png
  website/static/img/blog/2023-09-15/image3.png
  website/static/img/blog/2023-09-15/image4.png
  website/static/img/blog/2023-09-15/image5.png
  website/static/img/blog/ferretdb-v1.10.png
Labels: trust, blog/marketing

#3343 Use filter and insert more documents in `BenchmarkReplaceSettingsDocument`
  integration/Taskfile.yml
  integration/benchmarks_test.go
  integration/setup/setup.go
  integration/setup/startup.go
  integration/shareddata/benchmark_provider.go
Labels: code/chore

#3368 Replace deprecated Jaeger exporter
  docker-compose.yml
  go.mod
  go.sum
  integration/.golangci.yml
  integration/go.mod
  integration/go.sum
  integration/setup/startup.go
Labels: code/chore

#3358 Fix metadata updates for `dropIndexes`
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/metadata/registry_test.go
Labels: code/bug

#3376 Remove the need to close `conninfo`
  internal/clientconn/conn.go
  internal/clientconn/conninfo/conn_info.go
  internal/clientconn/conninfo/conn_info_test.go
Labels: code/chore

#3377 Add small tweaks
  .github/settings.yml
  internal/handlers/pg/msg_createindexes.go
  internal/handlers/pg/pgdb/indexes_test.go
  internal/handlers/sqlite/msg_createindexes.go
Labels: code/chore

#3384 Enforce valid `types` usage
  internal/handlers/common/saslstart_plain_test.go
  internal/handlers/commonpath/commonpath_test.go
  internal/types/array.go
  internal/types/array_test.go
  internal/types/compare.go
  internal/types/compare_order.go
  internal/types/document.go
  internal/types/document_test.go
  internal/types/document_validation.go
  internal/types/document_validation_test.go
  internal/types/format.go
  internal/types/identical.go
  internal/types/path.go
  internal/types/path_test.go
  internal/types/types.go
  internal/util/testutil/equal.go
  internal/util/testutil/path.go
Labels: code/chore

#3374 Add docs for migrating to MongoDB from FerretDB
  website/docs/migration/_category_.yml
  website/docs/migration/migrating-from-mongodb.md
  website/docs/migration/premigration-testing.md
Labels: documentation, trust

#3382 Reorder codebase in SQLite registry
  internal/backends/sqlite/metadata/registry.go
Labels: code/chore

#3408 Mention SQLite in docs
  website/docs/main.md
Labels: documentation, trust

#3356 Store `PostgreSQL` metadata
  .golangci.yml
  internal/backends/postgresql/metadata/metadata.go
  internal/backends/postgresql/metadata/pool/opendb.go
  internal/backends/postgresql/metadata/registry.go
  internal/backends/postgresql/metadata/registry_test.go
Labels: code/chore

#3412 Add `TODO`s
  internal/backends/postgresql/backend.go
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/database.go
  internal/backends/postgresql/metadata/metadata.go
  internal/backends/postgresql/metadata/registry.go
Labels: code/chore

#3407 Run new PostgreSQL backend tests
  .github/workflows/call-test-integration.yml
  .github/workflows/go-cron.yml
  .github/workflows/go.yml
  Taskfile.yml
  internal/backends/backend.go
  internal/backends/collection.go
  internal/backends/database.go
  internal/backends/doc.go
  internal/handlers/sqlite/sqlite.go
Labels: code/chore

#3430 Implement metrics collection for PostgreSQL backend
  internal/backends/postgresql/metadata/registry.go
Labels: code/feature

#3423 Add CI configurations
  .github/settings.yml
  .github/workflows/_integration.yml
  .github/workflows/go-extra.yml
  .github/workflows/go-trust.yml
  .github/workflows/go.yml
  .github/workflows/packages.yml
  .github/workflows/website-preview.yml
  Taskfile.yml
Labels: not ready

#3436 Fix CI configuration and add TODOs
  .github/workflows/_integration.yml
  .github/workflows/debug.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/go-trusted.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  .github/workflows/packages.yml
  .github/workflows/security.yml
  .github/workflows/website-preview.yml
Labels: code/chore

#3440 Implement `RenameCollection`
  internal/backends/postgresql/database.go
  internal/backends/postgresql/metadata/pool/pool.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/metadata/pool/pool.go
Labels: code/feature

#3439 Add release blog post for FerretDB v1.11.0
  website/blog/2023-09-26-ferretdb-releases-v1110.md
  website/static/img/blog/ferretdb-v1.11.jpg
Labels: trust, blog/marketing

#3437 Bump deps
  .github/workflows/_integration.yml
  .github/workflows/debug.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  .github/workflows/packages.yml
  .github/workflows/security.yml
  .github/workflows/website-preview.yml
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/postgres.Dockerfile
  build/deps/trivy.Dockerfile
  build/docker/all-in-one.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/backends/sqlite/metadata/pool/pool_test.go
  tools/go.mod
  tools/go.sum
Labels: deps

#3373 Implement validation for `createIndexes` and `dropIndexes` commands for SQLite
  integration/indexes_command_compat_test.go
  integration/indexes_command_test.go
  integration/indexes_compat_test.go
  integration/setup/test_helpers.go
  internal/backends/collection.go
  internal/backends/sqlite/metadata/registry.go
  internal/handlers/pg/msg_createindexes.go
  internal/handlers/sqlite/msg_createindexes.go
  internal/handlers/sqlite/msg_dropindexes.go
  internal/handlers/sqlite/msg_listindexes.go
Labels: code/enhancement

#3419 Implement `InsertAll` for `PostgreSQL`
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/collection_test.go
  internal/backends/postgresql/metadata/pool/transaction.go
  internal/backends/postgresql/metadata/pool/transaction_test.go
  internal/backends/postgresql/metadata/registry.go
Labels: code/feature

#3441 Implement `DeleteAll`
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/metadata/placeholder.go
Labels: code/feature

#3447 Remove extra function
  cmd/ferretdb/main.go
  internal/bson/bson.go
  internal/bson/document.go
  internal/bson/document_test.go
  internal/handlers/common/filter.go
  internal/handlers/common/positional_operator.go
  internal/handlers/common/projection.go
  internal/util/debug/debug.go
  internal/wire/op_query.go
  internal/wire/op_reply.go
Labels: code/chore

#3438 Fix fluky `TestRenameCollectionCompat` tests
  integration/renamecollection_compat_test.go
Labels: code/chore

#3194 Verify that client metadata not being mutated
  integration/basic_test.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/clientconn/conninfo/conn_info.go
  internal/handlers/common/client_metadata.go
  internal/handlers/common/client_metadata_test.go
  internal/handlers/common/ismaster.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/hana/cmd_query.go
  internal/handlers/pg/cmd_query.go
  internal/handlers/pg/msg_hello.go
  internal/handlers/pg/msg_ismaster.go
  internal/handlers/sqlite/cmd_query.go
  internal/handlers/sqlite/msg_hello.go
  internal/handlers/sqlite/msg_ismaster.go
Labels: code/bug

#3446 Mark pushdown results based on tested backend
  integration/aggregate_documents_compat_test.go
  integration/pushdown.go
  integration/query_array_compat_test.go
  integration/query_command_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_projection_compat_test.go
  integration/query_test.go
  integration/setup/test_helpers.go
  integration/shareddata/scalars.go
Labels: code/chore

#3417 Fix RSS feed issue with images
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
Labels: trust, blog/engineering

#3429 Republish Hacktobest blog post
  website/blog/2023-09-28-how-to-contribute-to-open-source-2022.md
  website/static/img/blog/hacktoberfest-2023.jpg
Labels: trust, blog/marketing

#3451 Implement `DropDatabase` and `Status`
  internal/backends/postgresql/backend.go
Labels: code/feature

#3449 Implement `UpdateAll`
  integration/update_compat_test.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/sqlite/msg_findandmodify.go
  internal/handlers/sqlite/msg_insert.go
  internal/handlers/sqlite/msg_update.go
Labels: code/feature

#3453 Run tests with `envtool tests run`
  Taskfile.yml
  cmd/envtool/envtool.go
  cmd/envtool/tests.go
  cmd/envtool/tests_test.go
  integration/setup/startup.go
Labels: code/chore

#3455 Remove unused expected failures
  integration/explain_compat_test.go
  integration/insert_command_test.go
Labels: code/chore

#3444 Implement `ListCollections`, `CreateCollection` and `DropCollection`
  internal/backends/postgresql/database.go
  internal/backends/postgresql/metadata/registry.go
  internal/backends/postgresql/metadata/registry_test.go
Labels: code/feature

#3460 Tweak SQLite backend tests
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/registry_test.go
Labels: code/chore

#3456 Add tests for backends contract
  internal/backends/collection_test.go
  internal/backends/doc.go
  internal/backends/helpers_test.go
  internal/backends/postgresql/dummy_test.go
  internal/handlers/sqlite/msg_createindexes.go
Labels: code/chore

#3448 Add blog post on Enmeshed
  website/blog/2023-09-29-ferretdb-database-choice-enmeshed-customers.md
  website/static/img/blog/ferretdb-enmeshed.png
  website/static/img/blog/julian.jpeg
  website/static/img/blog/michael-feygelman.jpeg
Labels: trust, blog/marketing
