Repository FerretDB/FerretDB, pull requests merged in 2023-04, with the labels that each got.

#2310 Implement `$skip` aggregation pipeline stage
  integration/aggregate_compat_test.go
  internal/handlers/common/aggregations/skip.go
  internal/handlers/common/aggregations/stage.go
  internal/handlers/common/params.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  website/docs/reference/supported-commands.md
Labels: code/feature

#2347 Update documentation sidebar
  website/docs/configuration/_category_.json
  website/docs/configuration/flags.md
  website/docs/configuration/operation-modes.md
  website/docs/contributing/_category_.json
  website/docs/diff.md
  website/docs/quickstart-guide/_category_.json
  website/docs/quickstart-guide/debian.md
  website/docs/quickstart-guide/docker.md
  website/docs/reference/glossary.md
  website/docs/reference/supported-commands.md
  website/docs/telemetry.md
Labels: documentation, trust

#2281 Update FerretDB descriptions
  README.md
  build/nfpm.yaml
  website/docs/contributing/contributing.md
  website/docs/main.md
  website/docs/understanding-ferretdb.md
  website/src/components/HomepageFeatures/index.js
  website/static/img/undraw-ferretdb-open-source.svg
  website/static/img/undraw-ferretdb-server.svg
  website/static/img/undraw-ferretdb-usability.svg
Labels: documentation

#2294 Implement `$unwind` aggregation pipeline stage
  README.md
  integration/aggregate_compat_test.go
  internal/handlers/common/aggregations/stage.go
  internal/handlers/common/aggregations/unwind.go
  internal/handlers/common/filter.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/types/expression.go
  internal/types/path.go
  internal/types/path_test.go
  website/docs/main.md
  website/docs/reference/supported-commands.md
  website/docs/understanding-ferretdb.md
Labels: code/feature

#2350 Ignore `unique` index option for now
  internal/handlers/pg/msg_createindexes.go
Labels: code/chore

#2338 Support `count` and `storageStats` fields in `$collStats` aggregation pipeline stage
  integration/aggregate_documents_compat_test.go
  integration/aggregate_stats_compat_test.go
  internal/handlers/common/aggregations/collstats.go
  internal/handlers/common/aggregations/count.go
  internal/handlers/common/aggregations/group.go
  internal/handlers/common/aggregations/limit.go
  internal/handlers/common/aggregations/match.go
  internal/handlers/common/aggregations/skip.go
  internal/handlers/common/aggregations/sort.go
  internal/handlers/common/aggregations/stage.go
  internal/handlers/common/aggregations/statistics.go
  internal/handlers/common/aggregations/unwind.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_collstats.go
  internal/handlers/pg/msg_datasize.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/tigris/msg_aggregate.go
  internal/handlers/tigris/msg_collstats.go
Labels: code/feature

#2351 Apply `skip` before `limit`
  integration/count_compat_test.go
  integration/query_compat_command_test.go
  integration/query_compat_test.go
  internal/handlers/common/find.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_find.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_find.go
Labels: code/bug

#2331 Improve flags documentation
  CONTRIBUTING.md
  README.md
  Taskfile.yml
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  build/nfpm.yml
  build/trivy-secret.yml
  cmd/ferretdb/main.go
  cmd/ferretdb/main_hana.go
  cmd/ferretdb/main_test.go
  cmd/ferretdb/main_tigris.go
  website/blog/2023-03-14-ferretdb-v-0-9-3.md
  website/docs/basic-operations/_category_.json
  website/docs/basic-operations/_category_.yml
  website/docs/configuration/_category_.json
  website/docs/configuration/_category_.yml
  website/docs/configuration/flags.md
  website/docs/configuration/operation-modes.md
  website/docs/contributing/_category_.json
  website/docs/contributing/_category_.yml
  website/docs/contributing/index.md
  website/docs/contributing/writing-guide.md
  website/docs/diff.md
  website/docs/operators/_category_.json
  website/docs/operators/_category_.yml
  website/docs/operators/query/_category_.json
  website/docs/operators/query/_category_.yml
  website/docs/operators/update/_category_.json
  website/docs/operators/update/_category_.yml
  website/docs/quickstart-guide/_category_.json
  website/docs/quickstart-guide/_category_.yml
  website/docs/quickstart-guide/deb.md
  website/docs/quickstart-guide/docker.md
  website/docs/quickstart-guide/rpm.md
  website/docs/reference/_category_.json
  website/docs/reference/_category_.yml
  website/docs/reference/glossary.md
  website/docs/security.md
  website/docs/telemetry.md
  website/docs/understanding-ferretdb.md
Labels: documentation, trust

#2352 Describe supported fields for `$collStats` aggregation stage
  website/docs/reference/supported-commands.md
Labels: documentation

#2353 Document test script
  .github/ISSUE_TEMPLATE/bug.yml
  CONTRIBUTING.md
Labels: documentation

#2357 Allow setting "package" variable with a testing flag
  build/version/version.go
  cmd/ferretdb/main.go
  website/docs/telemetry.md
Labels: code/chore

#2358 Make it easier to use Docker-related Task targets
  Taskfile.yml
Labels: code/chore

#2372 Use `draft` instead of `unlisted`
  website/blog/_guide/YYYY-MM-DD.blog-template.md
  website/blog/_guide/content-process.md
  website/docs/contributing/writing-guide.md
Labels: documentation, trust

#2371 Do not mark released binaries as dirty
  .dockerignore
  .github/workflows/packages.yml
Labels: code/chore

#2367 Bump dependencies
  Taskfile.yml
  build/deps/trivy.Dockerfile
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  website/docs/reference/supported-commands.md
Labels: deps, conflict

#2376 Make example docker compose file restart on failure
  website/docs/configuration/flags.md
  website/docs/quickstart-guide/docker.md
Labels: documentation, trust

#2355 Document how to get logs
  website/docs/configuration/logging.md
  website/docs/quickstart-guide/deb.md
  website/docs/quickstart-guide/docker.md
Labels: documentation, trust

#2373 Update writing guide
  website/docs/contributing/writing-guide.md
Labels: documentation

#2388 Fix version.txt generation for git tags
  .github/workflows/debug.yml
  .github/workflows/packages.yml
Labels: code/chore

#2390 Add comments to our documentation workflow
  .github/workflows/docs-preview.yml
  website/docs/reference/supported-commands.md
Labels: documentation, code/chore, trust

#2397 Add blogpost: Announcing FerretDB 1.0 GA - a truly Open Source MongoDB alternative
  website/blog/2023-04-11-ferretdb-1-0-ga-opensource-mongodb-alternative.md
  website/blog/authors.yml
  website/static/img/blog/ferretdb-v1.0.jpg
Labels: documentation, trust

#2411 Deprecated error cleanup
  integration/delete_test.go
  internal/clientconn/conn.go
  internal/handlers/common/commonerrors.go
  internal/handlers/common/distinct.go
  internal/handlers/common/filter.go
  internal/handlers/common/find.go
  internal/handlers/common/findandmodify.go
  internal/handlers/common/msg_debugerror.go
  internal/handlers/common/params.go
  internal/handlers/common/projection.go
  internal/handlers/common/saslstart.go
  internal/handlers/common/setfreemonitoring.go
  internal/handlers/common/sort.go
  internal/handlers/common/typecode.go
  internal/handlers/common/unimplemented.go
  internal/handlers/common/update.go
  internal/handlers/common/update_array_operators.go
  internal/handlers/dummy/dummy.go
  internal/handlers/pg/cmd_query.go
  internal/handlers/pg/msg_collmod.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/msg_getlog.go
  internal/handlers/pg/msg_getparameter.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_update.go
  internal/handlers/tigris/cmd_query.go
  internal/handlers/tigris/json_schema.go
  internal/handlers/tigris/msg_collmod.go
  internal/handlers/tigris/msg_count.go
  internal/handlers/tigris/msg_create.go
  internal/handlers/tigris/msg_delete.go
  internal/handlers/tigris/msg_drop.go
  internal/handlers/tigris/msg_getlog.go
  internal/handlers/tigris/msg_getparameter.go
  internal/handlers/tigris/msg_insert.go
  internal/handlers/tigris/msg_update.go
Labels: code/chore

#2408 Bump deps
  Taskfile.yml
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/checkswitch/testdata/testdata.go
  tools/go.mod
  tools/go.sum
  website/blog/authors.yml
  website/docs/reference/supported-commands.md
Labels: deps

#2385 Fix `findAndModify` for `$exists` query operator
  integration/findandmodify_compat_test.go
  integration/findandmodify_test.go
  integration/query_element_compat_test.go
  internal/handlers/common/findandmodify.go
  internal/handlers/common/update.go
  internal/handlers/common/upsertoperation_string.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/tigris/msg_findandmodify.go
Labels: code/bug

#2417 Update documentation for index options
  internal/handlers/pg/msg_createindexes.go
  website/docs/reference/supported-commands.md
Labels: documentation, trust

#2409 Parallel tests are consistently used in integration tests
  integration/aggregate_documents_compat_test.go
  integration/basic_test.go
  integration/create_compat_test.go
  integration/explain_compat_test.go
  integration/findandmodify_compat_test.go
  integration/query_compat_command_test.go
  integration/shareddata_test.go
  integration/update_field_compat_test.go
Labels: code/chore

#2339 Add query pushdown documentation
  website/docs/configuration/_category_.yml
  website/docs/contributing/_category_.yml
  website/docs/diff.md
  website/docs/pushdown.md
  website/docs/reference/_category_.yml
  website/docs/security.md
  website/docs/telemetry.md
Labels: documentation, trust

#2420 Update README.md to link to SSPL
  README.md
Labels: documentation

#2419 Use exponential backoff with jitter
  cmd/envtool/envtool.go
  integration/commands_administration_test.go
  internal/clientconn/listener.go
  internal/handlers/pg/pgdb/transactions.go
  internal/handlers/tigris/tigrisdb/databases.go
  internal/util/ctxutil/ctxutil.go
  internal/util/ctxutil/ctxutil_test.go
Labels: code/chore

#2396 Improve documentation for Docker
  .github/workflows/docs-preview.yml
  .github/workflows/integration-trust.yml
  .github/workflows/packages.yml
  .github/workflows/security.yml
  CONTRIBUTING.md
  README.md
  Taskfile.yml
  build/version/generate.go
  build/version/version.go
  internal/handlers/common/aggregations/stage.go
  internal/handlers/common/msg_debugerror.go
  internal/handlers/hana/hana.go
  internal/handlers/pg/pg.go
  internal/handlers/tigris/tigris.go
  website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md
  website/docs/configuration/logging.md
  website/docs/contributing/index.md
  website/docs/quickstart-guide/docker.md
Labels: documentation, trust

#2435 Add more detailed PR guides in CONTRIBUTING.md
  .github/PROCESS.md
  CONTRIBUTING.md
Labels: documentation

#2439 Migrate to `pgx/v5`
  .golangci.yml
  cmd/envtool/envtool.go
  ferretdb/ferretdb.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/msg_createindexes.go
  internal/handlers/pg/msg_datasize.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_distinct.go
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/msg_dropdatabase.go
  internal/handlers/pg/msg_dropindexes.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_listcollections.go
  internal/handlers/pg/msg_listdatabases.go
  internal/handlers/pg/msg_listindexes.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/database_metadata.go
  internal/handlers/pg/pgdb/database_metadata_test.go
  internal/handlers/pg/pgdb/databases.go
  internal/handlers/pg/pgdb/delete.go
  internal/handlers/pg/pgdb/indexes.go
  internal/handlers/pg/pgdb/indexes_test.go
  internal/handlers/pg/pgdb/insert.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/pg/pgdb/tables.go
  internal/handlers/pg/pgdb/transactions.go
  internal/handlers/pg/pgdb/transactions_test.go
  internal/handlers/pg/pgdb/update.go
Labels: deps, code/chore

#2431 Remove a few double spaces
  .github/workflows/debug.yml
  .github/workflows/docs-preview.yml
  .github/workflows/security.yml
  CHANGELOG.md
  website/docs/basic-operations/delete.md
  website/docs/basic-operations/read.md
  website/docs/basic-operations/update.md
  website/docs/operators/query/logical-operators.md
  website/docs/operators/update/array-update-operators.md
Labels: documentation, trust

#2428 Make it harder to misuse iterators
  internal/handlers/common/filter_iterator.go
  internal/handlers/common/limit_iterator.go
  internal/handlers/common/projection_iterator.go
  internal/handlers/common/skip_iterator.go
  internal/handlers/common/sort_iterator.go
  internal/handlers/pg/msg_find.go
  internal/handlers/tigris/msg_find.go
  internal/util/iterator/closer.go
  internal/util/iterator/slice.go
  internal/util/iterator/values.go
  internal/util/iterator/with_close.go
Labels: code/chore

#2441 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: project

#2453 Add image for a future blog post
  website/static/img/blog/ferretdb-studio3t.png
Labels: blog/marketing

#2454 Add blogpost - Using FerretDB with Studio 3T
  website/blog/2023-04-18-using-ferretdb-with-studio-3t.md
  website/static/img/blog/ferretdb-studio3t/image1.png
  website/static/img/blog/ferretdb-studio3t/image2.png
  website/static/img/blog/ferretdb-studio3t/image3.png
  website/static/img/blog/ferretdb-studio3t/image4.png
  website/static/img/blog/ferretdb-studio3t/image5.png
  website/static/img/blog/ferretdb-studio3t/image6.png
  website/static/img/blog/ferretdb-studio3t/image7.png
  website/static/img/blog/ferretdb-studio3t/image8.png
  website/static/img/blog/ferretdb-studio3t/image9.png
Labels: trust, blog/marketing

#2455 Fix YAML indentation
  website/blog/2023-04-18-using-ferretdb-with-studio-3t.md
Labels: blog/marketing

#2457 Update blog post on Using FerretDB with Studio3T
  website/blog/2023-04-18-using-ferretdb-with-studio-3t.md
Labels: blog/marketing

#2443 Minor cleanup of exponential backoff with jitter
  cmd/envtool/envtool.go
  integration/commands_administration_test.go
  internal/clientconn/listener.go
  internal/handlers/pg/pgdb/transactions.go
  internal/handlers/tigris/tigrisdb/databases.go
  internal/util/ctxutil/ctxutil.go
  internal/util/ctxutil/ctxutil_test.go
Labels: code/chore

#2464 Add workaround for CockroachDB issue
  internal/handlers/pg/pgdb/pool.go
Labels: code/chore

#2426 Fix `SchemaStats` to return correct data
  integration/commands_administration_test.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_collstats.go
  internal/handlers/pg/msg_datasize.go
  internal/handlers/pg/msg_dbstats.go
  internal/handlers/pg/msg_serverstatus.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/stats.go
Labels: code/enhancement

#2433 Implement blog posts previews
  .github/workflows/website-preview.yml
  Taskfile.yml
Labels: code/chore

#2381 Introduce integration benchmarks
  Taskfile.yml
  integration/Taskfile.yml
  integration/benchmarks_test.go
  integration/setup/setup.go
  integration/shareddata/benchmark.go
  integration/shareddata/iterator.go
  integration/shareddata/shareddata.go
Labels: code/chore

#2422 Add tests to findAndModify on `$exists` operator
  integration/findandmodify_compat_test.go
  integration/findandmodify_test.go
  internal/handlers/common/findandmodify.go
  internal/handlers/common/update.go
  internal/handlers/pg/msg_findandmodify.go
  internal/handlers/pg/msg_update.go
  internal/handlers/tigris/msg_findandmodify.go
  internal/handlers/tigris/msg_update.go
Labels: code/chore

#2463 Refactor aggregation
  internal/handlers/common/aggregations/operators/count.go
  internal/handlers/common/aggregations/operators/number.go
  internal/handlers/common/aggregations/operators/operators.go
  internal/handlers/common/aggregations/operators/sum.go
  internal/handlers/common/aggregations/stages/collstats.go
  internal/handlers/common/aggregations/stages/count.go
  internal/handlers/common/aggregations/stages/group.go
  internal/handlers/common/aggregations/stages/limit.go
  internal/handlers/common/aggregations/stages/match.go
  internal/handlers/common/aggregations/stages/pushdown.go
  internal/handlers/common/aggregations/stages/skip.go
  internal/handlers/common/aggregations/stages/sort.go
  internal/handlers/common/aggregations/stages/stages.go
  internal/handlers/common/aggregations/stages/statistics.go
  internal/handlers/common/aggregations/stages/unwind.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/tigris/msg_aggregate.go
  internal/handlers/tigris/msg_explain.go
Labels: code/chore

#2452 Small documentation tweaks
  .github/PROCESS.md
  CONTRIBUTING.md
  website/docs/reference/supported-commands.md
Labels: code/chore, no ci

#2386 Fix query projection for top level fields
  integration/query_compat_test.go
  integration/query_projection_compat_test.go
  integration/query_projection_test.go
  integration/shareddata/shareddata.go
  internal/handlers/common/projection.go
  internal/handlers/common/projection_iterator.go
Labels: code/chore

#2484 Implement projection fields assignment
  integration/query_projection_compat_test.go
  internal/handlers/common/projection.go
Labels: code/feature

#2499 Handle `envtool` panic on timeout
  cmd/envtool/envtool.go
Labels: code/chore

#2383 Implement `$project` pipeline aggregation stage
  integration/aggregate_documents_compat_test.go
  internal/handlers/common/aggregations/stages/project.go
  internal/handlers/common/aggregations/stages/stages.go
  internal/handlers/common/projection.go
  internal/handlers/common/projection_iterator.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
Labels: code/feature

#2467 Enable debugging tracing of SQL queries
  go.mod
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/trace.go
Labels: code/chore

#2497 Update blog file names to match with slug
  website/blog/2021-11-05-mangodb-overwhelming-enthusiasm-for-truly-open-source-mongodb-replacement.md
  website/blog/2021-12-01-mangodb-has-a-new-name-and-the-momentum-is-stronger-than-ever-meet-ferretdb.md
  website/blog/2021-12-07-mongodb-compatibility-whats-really-important.md
  website/blog/2023-02-14-2023-02-14-ferretdb-v-0-9-1-minor-release.md
  website/blog/2023-02-28-ferretdb-v-0-9-2.md
  website/blog/2023-03-14-ferretdb-v-0-9-3-improved-aggregation-pipeline-support.md
  website/blog/2023-03-21-mongodb-vs-postgresql-database-comparison.md
  website/blog/2023-03-30-ferretdb-v-0-9-4-minor-release-update.md
Labels: code/chore, blog/engineering

#2482 Add benchmark for replacing large document
  integration/Taskfile.yml
  integration/benchmarks_test.go
  integration/shareddata/benchmark.go
Labels: code/chore

#2494 Add more documentation-related items to definition of done
  .github/ISSUE_TEMPLATE/chore.yml
Labels: code/chore

#2512 Return unsupported operator error for `$` projection operator
  integration/query_projection_compat_test.go
  internal/handlers/common/projection.go
Labels: code/bug

#2496 New version notification uses `update_available` from telemetry
  internal/util/state/state.go
  internal/util/telemetry/reporter.go
  internal/util/telemetry/reporter_test.go
Labels: code/chore

#2480 Aggregation stages uses iterator
  internal/handlers/common/aggregations/stages/collstats.go
  internal/handlers/common/aggregations/stages/count.go
  internal/handlers/common/aggregations/stages/group.go
  internal/handlers/common/aggregations/stages/limit.go
  internal/handlers/common/aggregations/stages/match.go
  internal/handlers/common/aggregations/stages/project.go
  internal/handlers/common/aggregations/stages/skip.go
  internal/handlers/common/aggregations/stages/sort.go
  internal/handlers/common/aggregations/stages/stages.go
  internal/handlers/common/aggregations/stages/unwind.go
  internal/handlers/common/count_iterator.go
  internal/handlers/common/limit_iterator.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/tigris/msg_aggregate.go
Labels: code/chore

#2483 Add coveralls.io integration
  .github/workflows/go.yml
  .github/workflows/integration-trust.yml
  .github/workflows/integration.yml
Labels: code/chore

#2459 Add linter for checking blog posts
  Taskfile.yml
  tools/Taskfile.yml
  tools/checkdocs/checkdocs.go
  tools/checkdocs/checkdocs_test.go
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: code/chore

#2458 Handle `create` and `drop` commands in Hana handler
  internal/handlers/hana/hanadb/collections.go
  internal/handlers/hana/hanadb/databases.go
  internal/handlers/hana/hanadb/hanadb.go
  internal/handlers/hana/msg_create.go
  internal/handlers/hana/msg_drop.go
  internal/handlers/hana/msg_dropdatabase.go
Labels: trust

#2507 `findAndModify` returns error on `$set` operator setting `_id`
  integration/findandmodify_compat_test.go
  integration/update_field_compat_test.go
  internal/handlers/common/update.go
  internal/handlers/pg/msg_findandmodify.go
Labels: code/bug

#2485 Add a YAML formatter
  Taskfile.yml
  build/deps/prettier.Dockerfile
  docker-compose.yml
Labels: code/chore

#2524 Small addition to YAML formatter usage
  .github/workflows/integration.yml
  .golangci-new.yml
  .markdownlint.yml
  Taskfile.yml
  integration/.golangci-new.yml
Labels: code/chore

#2525 Add identifying Arch Linux version in `hostInfo` command
  internal/handlers/common/msg_hostinfo.go
Labels: code/enhancement

#2526 Minor cleanup of blog post linter for slug
  tools/checkdocs/checkdocs.go
  tools/checkdocs/checkdocs_test.go
Labels: code/chore

#2506 Pushdown simplest sorting for `find` command
  cmd/ferretdb/main.go
  internal/handlers/common/sort.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/pg/msg_explain.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/pg.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/database_metadata.go
  internal/handlers/pg/pgdb/query.go
  internal/handlers/pg/pgdb/query_test.go
  internal/handlers/registry/registry.go
Labels: code/chore
