Repository FerretDB/FerretDB, pull requests merged in 2023-12, with the labels that each got.

#3776 Add stubs for authentication commands
  .github/settings.yml
  cmd/ferretdb/main.go
  integration/setup/listener.go
  internal/clientconn/conn.go
  internal/handler/commands.go
  internal/handler/handler.go
  internal/handler/msg_createuser.go
  internal/handler/msg_dropallusersfromdatabase.go
  internal/handler/msg_dropuser.go
  internal/handler/msg_listcommands.go
  internal/handler/msg_updateuser.go
  internal/handler/msg_usersinfo.go
  internal/handler/registry/hana.go
  internal/handler/registry/mysql.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/registry.go
  internal/handler/registry/sqlite.go
Labels: code/chore

#3789 Move `getParameter` out of `common` package
  internal/handler/common/getparameter.go
  internal/handler/msg_getparameter.go
Labels: code/chore

#3780 Remove `commoncommands` package
  internal/handler/commoncommands/msg_buildinfo.go
  internal/handler/commoncommands/msg_connectionstatus.go
  internal/handler/commoncommands/msg_currentop.go
  internal/handler/commoncommands/msg_debugerror.go
  internal/handler/commoncommands/msg_getcmdlineopts.go
  internal/handler/commoncommands/msg_hostinfo.go
  internal/handler/commoncommands/msg_logout.go
  internal/handler/commoncommands/msg_whatsmyuri.go
  internal/handler/msg_buildinfo.go
  internal/handler/msg_connectionstatus.go
  internal/handler/msg_currentop.go
  internal/handler/msg_debugerror.go
  internal/handler/msg_getcmdlineopts.go
  internal/handler/msg_hostinfo.go
  internal/handler/msg_hostinfo_test.go
  internal/handler/msg_logout.go
  internal/handler/msg_whatsmyuri.go
Labels: code/chore

#3794 Ignore `go-consistent` failures
  Taskfile.yml
  integration/Taskfile.yml
  tools/Taskfile.yml
Labels: code/chore

#3772 Update Docusaurus to v3
  build/.markdownlint.yml
  build/deps/docusaurus-docs.Dockerfile
  website/blog/2023-06-19-ferretdb-v-1-4-0-new-release.md
  website/blog/2023-10-19-install-ferretdb-mongodb-alternative-ubuntu.md
  website/blog/2023-11-15-how-to-package-and-deploy-ferretdb-with-acorn.md
  website/docs/configuration/flags.md
  website/docs/indexes.md
  website/docs/main.md
  website/docs/quickstart-guide/go.md
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
Labels: documentation, trust, blog/marketing

#3802 Update domain name in more places
  README.md
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  build/nfpm.yml
  website/blog/2023-10-30-building-mongodb-like-developer-experience-vultr.md
  website/docs/main.md
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
Labels: documentation, trust

#3800 Log batches for `find`, `aggregate`, `getMore`
  .golangci.yml
  internal/backends/postgresql/query_iterator.go
  internal/backends/sqlite/query_iterator.go
  internal/clientconn/cursor/cursor.go
  internal/clientconn/cursor/registry.go
  internal/handler/common/aggregations/stages/unwind.go
  internal/handler/common/sort_iterator.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_find.go
  internal/handler/msg_getmore.go
  internal/util/resource/resource.go
Labels: code/chore

#3791 Generate collection UUIDs
  integration/commands_administration_test.go
  internal/backends/database.go
  internal/backends/postgresql/database.go
  internal/backends/postgresql/metadata/metadata.go
  internal/backends/postgresql/metadata/registry.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/backends/sqlite/database.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/metadata/settings.go
  internal/handler/msg_listcollections.go
Labels: code/feature

#3788 Fix `listDatabases` filtering when using `nameOnly`
  integration/commands_administration_test.go
  internal/handler/msg_listdatabases.go
Labels: code/bug-regression

#3804 Improve `validate` diagnostic command
  integration/commands_diagnostic_test.go
  internal/handler/msg_validate.go
  website/docs/reference/supported-commands.md
Labels: code/enhancement, area/diag

#3803 Allow building without PostgreSQL or SQLite backend
  build/version/version.go
  cmd/ferretdb/main_postgresql.go
  cmd/ferretdb/main_sqlite.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/registry_test.go
  internal/handler/registry/sqlite.go
Labels: code/feature

#3810 Support subdirectories for integration tests
  Taskfile.yml
  cmd/envtool/tests_test.go
  integration/aggregate_documents_test.go
  integration/commands_administration_test.go
  integration/cursors/cursors.go
  integration/cursors/getmore_test.go
  integration/embedded_test.go
  integration/integration.go
  integration/query_test.go
  integration/setup/helpers.go
  integration/setup/listener.go
  integration/setup/setup.go
  internal/clientconn/listener.go
  internal/handler/registry/registry.go
Labels: code/chore

#3811 Move tests for tailbable cursors
  integration/commands_administration_test.go
  integration/cursors/batch_test.go
  integration/cursors/kill_test.go
  integration/cursors/tailable_test.go
  integration/query_test.go
  internal/handler/common/find.go
  internal/handler/msg_find.go
Labels: code/chore

#3808 Add new release FerretDB v1.16.0 blog post
  website/blog/2023-12-05-new-ferretdb-release-v116.md
  website/static/img/blog/ferretdb-v1.16.0.jpg
Labels: trust, blog/marketing

#3817 Bump deps
  .github/workflows/docs.yml
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/trivy.Dockerfile
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#3820 Refactor cursor creation
  internal/clientconn/cursor/cursor.go
  internal/clientconn/cursor/registry.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_find.go
Labels: code/chore

#3825 Change release blogpost image
  website/static/img/blog/ferretdb-v1.16.0.jpg
Labels: trust, blog/marketing

#3830 Ignore `$clusterTime`
  internal/handler/common/count.go
  internal/handler/common/delete_params.go
  internal/handler/common/distinct.go
  internal/handler/common/find.go
  internal/handler/common/findandmodify.go
  internal/handler/common/insert.go
  internal/handler/common/update_params.go
Labels: code/chore

#3822 Allow sorting by `$natural`
  integration/query_compat_test.go
  internal/backends/collection.go
  internal/backends/collection_test.go
  internal/backends/postgresql/query.go
  internal/backends/postgresql/query_test.go
  internal/backends/sqlite/query.go
  internal/backends/sqlite/query_test.go
  internal/handler/common/sort.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_explain.go
  internal/handler/msg_find.go
Labels: code/feature

#3809 Add fields to `listCollections.cursor` response
  integration/commands_administration_compat_test.go
  integration/commands_administration_test.go
  internal/handler/msg_listcollections.go
Labels: code/enhancement, area/cursors

#3832 Disallow `$natural` in compound sort
  integration/query_compat_test.go
  internal/handler/common/sort.go
Labels: code/feature

#3821 Enable versioning on documentation
  .github/RELEASE_CHECKLIST.md
  CHANGELOG.md
  CONTRIBUTING.md
  Taskfile.yml
  build/deps/README.md
  website/blog/2023-01-04-ferretdb-beta-version-authentication.md
  website/blog/2023-02-07-5-database-alternatives-mongodb-2023.md
  website/blog/2023-03-21-mongodb-vs-postgresql-database-comparison.md
  website/blog/2023-04-11-ferretdb-1-0-ga-opensource-mongodb-alternative.md
  website/blog/2023-06-05-ferretdb-v-1-3-0-new-release.md
  website/blog/2023-09-15-ferretdb-v1-10-production-ready-sqlite.md
  website/blog/2023-09-26-ferretdb-releases-v1110.md
  website/blog/2023-10-19-install-ferretdb-mongodb-alternative-ubuntu.md
  website/blog/2023-11-20-ferretdb-releases-v1150.md
  website/docs/aggregation-operations/_category_.yml
  website/docs/aggregation-operations/aggregation-pipeline-and-commands.md
  website/docs/basic-operations/_category_.yml
  website/docs/basic-operations/index.md
  website/docs/configuration/_category_.yml
  website/docs/contributing/_category_.yml
  website/docs/contributing/index.md
  website/docs/contributing/writing-guide.md
  website/docs/migration/_category_.yml
  website/docs/operators/_category_.yml
  website/docs/operators/query/_category_.yml
  website/docs/operators/update/_category_.yml
  website/docs/reference/_category_.yml
  website/docs/security/_category_.yml
  website/docs/understanding-ferretdb.md
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
  website/versions.json
Labels: documentation, trust

#3835 Clean-up tests a bit
  cmd/envtool/tests_test.go
  integration/cursors/batch_test.go
  integration/cursors/getmore_test.go
  integration/cursors/kill_test.go
  integration/cursors/tailable_test.go
  internal/util/iterator/testiterator/testiterator.go
Labels: code/chore

#3840 Allow bypassing authentication
  internal/backends/postgresql/metadata/pool/pool.go
  internal/backends/postgresql/metadata/registry.go
  internal/clientconn/conninfo/conn_info.go
Labels: code/chore

#3833 Add tests for tailable cursors
  integration/cursors/getmore_test.go
  integration/cursors/helpers.go
  integration/cursors/tailable_test.go
Labels: code/chore

#3847 Add missing logging parameter
  internal/handler/msg_find.go
Labels: code/chore

#3849 Test cross-session cursors
  integration/cursors/tailable_sessions_test.go
Labels: code/chore

#3831 Support capped collection cleanup
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/commands_administration_test.go
  integration/setup/listener.go
  internal/handler/handler.go
  internal/handler/msg_compact.go
  internal/handler/registry/hana.go
  internal/handler/registry/mysql.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/registry.go
  internal/handler/registry/sqlite.go
  website/docs/reference/supported-commands.md
Labels: code/feature

#3824 Use MongoDB 7
  build/deps/legacy-mongo-shell.Dockerfile
  build/deps/mongo.Dockerfile
  build/version/mongodb.txt
  build/version/version_test.go
  integration/aggregate_documents_test.go
  integration/basic_test.go
  integration/commands_administration_compat_test.go
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/commands_freemonitoring_test.go
  integration/create_test.go
  integration/cursors/getmore_test.go
  integration/diff_09_dbstats_scale_test.go
  integration/indexes_command_compat_test.go
  integration/query_compat_test.go
  integration/query_test.go
  integration/shareddata/scalars.go
  integration/update_compat_test.go
  internal/backends/database.go
  internal/handler/common/aggregations/stages/group.go
  internal/handler/common/common.go
  internal/handler/handlererrors/error.go
  internal/handler/handlererrors/errorcode_string.go
  internal/handler/msg_create.go
  internal/handler/msg_datasize.go
  internal/handler/msg_dbstats.go
  internal/handler/msg_drop.go
  internal/handler/msg_getparameter.go
  internal/handler/msg_renamecollection.go
  internal/handler/msg_validate.go
Labels: code/chore

#3854 Simplify tailable cursor tests
  .golangci.yml
  integration/cursors/tailable_test.go
  internal/util/debug/debug.go
Labels: code/chore

#3864 Add `upsert` tests
  integration/findandmodify_compat_test.go
  integration/update_field_compat_test.go
Labels: code/chore, community

#3859 Add cursor tests
  integration/cursors/batch_test.go
  integration/cursors/getmore_test.go
Labels: code/chore

#3869 Prepare v1.17.0 release
  CHANGELOG.md
  website/docusaurus.config.js
  website/versioned_docs/version-v1.17/aggregation-operations/_category_.yml
  website/versioned_docs/version-v1.17/aggregation-operations/aggregation-pipeline-and-commands.md
  website/versioned_docs/version-v1.17/aggregation-operations/aggregation-stages.md
  website/versioned_docs/version-v1.17/basic-operations/_category_.yml
  website/versioned_docs/version-v1.17/basic-operations/create.md
  website/versioned_docs/version-v1.17/basic-operations/delete.md
  website/versioned_docs/version-v1.17/basic-operations/index.md
  website/versioned_docs/version-v1.17/basic-operations/read.md
  website/versioned_docs/version-v1.17/basic-operations/update.md
  website/versioned_docs/version-v1.17/configuration/_category_.yml
  website/versioned_docs/version-v1.17/configuration/flags.md
  website/versioned_docs/version-v1.17/configuration/observability.md
  website/versioned_docs/version-v1.17/configuration/operation-modes.md
  website/versioned_docs/version-v1.17/contributing/_category_.yml
  website/versioned_docs/version-v1.17/contributing/index.md
  website/versioned_docs/version-v1.17/contributing/writing-guide.md
  website/versioned_docs/version-v1.17/diff.md
  website/versioned_docs/version-v1.17/indexes.md
  website/versioned_docs/version-v1.17/main.md
  website/versioned_docs/version-v1.17/migration/_category_.yml
  website/versioned_docs/version-v1.17/migration/migrating-from-mongodb.md
  website/versioned_docs/version-v1.17/migration/premigration-testing.md
  website/versioned_docs/version-v1.17/operators/_category_.yml
  website/versioned_docs/version-v1.17/operators/query/_category_.yml
  website/versioned_docs/version-v1.17/operators/query/array-operators.md
  website/versioned_docs/version-v1.17/operators/query/bitwise-operators.md
  website/versioned_docs/version-v1.17/operators/query/comparison-operators.md
  website/versioned_docs/version-v1.17/operators/query/element-operators.md
  website/versioned_docs/version-v1.17/operators/query/evaluation-operators.md
  website/versioned_docs/version-v1.17/operators/query/logical-operators.md
  website/versioned_docs/version-v1.17/operators/update/_category_.yml
  website/versioned_docs/version-v1.17/operators/update/array-update-operators.md
  website/versioned_docs/version-v1.17/operators/update/field-update-operators.md
  website/versioned_docs/version-v1.17/pushdown.md
  website/versioned_docs/version-v1.17/quickstart-guide/_category_.yml
  website/versioned_docs/version-v1.17/quickstart-guide/deb.md
  website/versioned_docs/version-v1.17/quickstart-guide/docker.md
  website/versioned_docs/version-v1.17/quickstart-guide/go.md
  website/versioned_docs/version-v1.17/quickstart-guide/macos.md
  website/versioned_docs/version-v1.17/quickstart-guide/rpm.md
  website/versioned_docs/version-v1.17/quickstart-guide/windows.md
  website/versioned_docs/version-v1.17/reference/_category_.yml
  website/versioned_docs/version-v1.17/reference/glossary.md
  website/versioned_docs/version-v1.17/reference/supported-commands.md
  website/versioned_docs/version-v1.17/security/_category_.yml
  website/versioned_docs/version-v1.17/security/authentication.md
  website/versioned_docs/version-v1.17/security/tls-connections.md
  website/versioned_docs/version-v1.17/telemetry.md
  website/versioned_docs/version-v1.17/understanding-ferretdb.md
  website/versioned_sidebars/version-v1.17-sidebars.json
  website/versions.json
Labels: code/chore, trust

#3865 Add CI configuration for Citus
  .github/workflows/_integration.yml
  .github/workflows/go-extra.yml
  build/deps/citus.Dockerfile
  docker-compose.yml
Labels: code/chore

#3848 Implement `createUser` command
  integration/setup/listener.go
  integration/users/create_user_test.go
  internal/handler/handlererrors/error.go
  internal/handler/handlererrors/errorcode_string.go
  internal/handler/msg_createuser.go
  website/versioned_docs/version-v1.15/reference/supported-commands.md
Labels: code/feature

#3880 Bump deps
  .github/workflows/docs.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  .github/workflows/packages.yml
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#3871 Fix tests
  integration/commands_administration_test.go
Labels: code/chore

#3883 Add release blogpost for v1.17.0
  website/blog/2023-12-19-ferretdb-releases-v117.md
  website/static/img/blog/ferretdb-v1.17.0.jpg
Labels: trust, blog/marketing

#3850 Add MySQL backend registry
  .golangci.yml
  cmd/envtool/envtool.go
  internal/backends/mysql/metadata/indexes.go
  internal/backends/mysql/metadata/metadata.go
  internal/backends/mysql/metadata/pool/pool.go
  internal/backends/mysql/metadata/pool/uri.go
  internal/backends/mysql/metadata/registry.go
  internal/backends/mysql/metadata/registry_test.go
  internal/util/testutil/mysql.go
Labels: code/chore

#3799 Add support for tailable cursors
  SECURITY.md
  integration/cursors/tailable_test.go
  internal/clientconn/cursor/cursor.go
  internal/clientconn/cursor/cursor_test.go
  internal/clientconn/cursor/registry.go
  internal/clientconn/cursor/type_string.go
  internal/handler/common/find.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_drop.go
  internal/handler/msg_dropdatabase.go
  internal/handler/msg_find.go
  internal/handler/msg_getmore.go
  internal/handler/msg_killcursors.go
  website/docs/reference/supported-commands.md
Labels: code/feature

#3866 Implement `dropUser` command
  integration/users/create_user_test.go
  integration/users/drop_user_test.go
  internal/handler/handlererrors/error.go
  internal/handler/handlererrors/errorcode_string.go
  internal/handler/msg_dropuser.go
Labels: code/feature

#3886 Fix local MySQL setup
  Taskfile.yml
  cmd/envtool/envtool.go
Labels: code/chore

#3889 Update blog links
  website/blog/2023-12-18-ferretdb-neon-add-mongodb-compatibility.md
Labels: blog/marketing

#3887 Enable OpLog and tailable cursors
  Taskfile.yml
  cmd/ferretdb/main.go
  integration/setup/listener.go
  internal/backends/decorators/oplog/backend.go
  internal/backends/decorators/oplog/collection.go
  internal/backends/postgresql/collection.go
  internal/backends/sqlite/collection.go
  internal/handler/handler.go
  internal/handler/msg_create.go
  internal/handler/registry/hana.go
  internal/handler/registry/mysql.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/registry.go
  internal/handler/registry/sqlite.go
Labels: code/chore

#3867 Implement `dropAllUsersFromDatabase` command
  integration/users/drop_all_users_from_database_test.go
  internal/handler/msg_createuser.go
  internal/handler/msg_dropallusersfromdatabase.go
Labels: code/feature

#3892 Fix clean-up on `aggregate` errors
  internal/handler/msg_aggregate.go
Labels: code/chore

#3891 Use `dropAllUsersFromDatabase` in tests
  integration/users/create_user_test.go
  integration/users/drop_all_users_from_database_test.go
  integration/users/drop_user_test.go
Labels: code/bug

#3872 Add `awaitData` tests
  integration/cursors/awaitdata_test.go
Labels: code/chore

#3890 Add utilities for working with passwords
  go.mod
  internal/handler/msg_hostinfo.go
  internal/util/password/password.go
  internal/util/password/plain.go
  internal/util/password/plain_test.go
Labels: code/chore

#3805 Add support for `--skip` in `envtool tests run`
  Taskfile.yml
  cmd/envtool/envtool.go
  cmd/envtool/tests.go
Labels: code/chore

#3896 Small clean-ups
  .github/workflows/docs.yml
  .github/workflows/packages.yml
  CONTRIBUTING.md
  README.md
  build/.textlintrc
  build/deps/ferretdb-prettier.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  website/blog/2023-11-15-how-to-package-and-deploy-ferretdb-with-acorn.md
Labels: code/chore

#3719 Add basic SAP HANA backend
  Taskfile.yml
  integration/pushdown.go
  integration/setup/helpers.go
  internal/backends/backend_test.go
  internal/backends/hana/backend.go
  internal/backends/hana/collection.go
  internal/backends/hana/database.go
  internal/backends/hana/database_test.go
  internal/backends/hana/hana.go
  internal/backends/hana/query.go
  internal/backends/hana/query_iterator.go
  internal/backends/hana/query_test.go
  internal/backends/hana/sjson_wrapper.go
  internal/util/testutil/hana.go
Labels: code/chore, trust

#3893 Add more cursor tests
  integration/cursors/getmore_test.go
Labels: code/chore

#3901 Refactor `ConnInfo` in preparation for new auth
  internal/clientconn/conninfo/conn_info.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_connectionstatus.go
  internal/handler/msg_find.go
  internal/handler/msg_getmore.go
  internal/handler/msg_killcursors.go
Labels: code/chore

#3756 Add some small improvements to the linter that checks open issues
  internal/backends/mysql/metadata/registry_test.go
  internal/util/ctxutil/ctxutil_test.go
  tools/checkcomments/checkcomments.go
  tools/checkcomments/checkcomments_test.go
  tools/checkcomments/client.go
  tools/checkcomments/testdata/testdata.go
  tools/cleantool/cleantool.go
  tools/go.mod
  tools/go.sum
Labels: code/chore

#3908 Forbid `bson.E/D/M/A`, except integration tests
  .golangci-new.yml
  .golangci.yml
Labels: code/chore

#3912 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#3911 Make `AssertEqual` helper handle duplicate keys
  internal/util/testutil/equal.go
  internal/util/testutil/equal_test.go
Labels: code/chore

#3909 Don't cleanup capped collections if there is nothing to cleanup
  internal/handler/handler.go
Labels: code/chore

#3914 Drop test users on cleanup
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/users/create_user_test.go
  integration/users/drop_all_users_from_database_test.go
  integration/users/drop_user_test.go
Labels: code/chore

#3900 Implement `awaitData` tailable cursors
  integration/cursors/awaitdata_test.go
  integration/cursors/tailable_test.go
  internal/handler/common/find.go
  internal/handler/msg_find.go
  internal/handler/msg_getmore.go
  website/versioned_docs/version-v1.16/reference/supported-commands.md
Labels: code/feature
