Repository FerretDB/FerretDB, pull requests merged in 2023-06, with the labels that each got.

#2658 Allow query to be type null in `distinct` command
  integration/distinct_test.go
  internal/handlers/common/distinct.go
Labels: code/bug

#2759 Simplify `CountIterator`
  internal/handlers/common/count_iterator.go
  internal/util/iterator/iterator.go
Labels: code/chore

#2758 Check for `nil` values in iterators explicitly
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/tigris/tigrisdb/query_iterator.go
  internal/util/iterator/count.go
  internal/util/iterator/func.go
  internal/util/iterator/values.go
Labels: code/chore

#2771 Trigger GC to run finalizers
  cmd/ferretdb/main.go
  integration/setup/startup.go
Labels: code/chore

#2772 Update `golangci-lint` config
  .golangci-new.yml
  .golangci.yml
  Taskfile.yml
  integration/Taskfile.yml
  tools/Taskfile.yml
Labels: code/chore

#2774 Remove the need to call `DeepCopy` in some places
  internal/clientconn/conn.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/tigris/msg_insert.go
Labels: code/chore

#2770 Clean-up `lazyerrors`, use them in more places
  .golangci-new.yml
  integration/.golangci-new.yml
  internal/handlers/pg/pgdb/pool.go
  internal/util/lazyerrors/lazyerrors.go
  internal/util/lazyerrors/lazyerrors_test.go
Labels: code/chore

#2713 Fix path collisions for multiple update operators
  integration/findandmodify_compat_test.go
  integration/shareddata/composites.go
  internal/handlers/common/update.go
Labels: code/bug

#2730 Replace document slices with iterators
  internal/handlers/common/distinct.go
  internal/handlers/pg/msg_count.go
  internal/handlers/pg/msg_distinct.go
  internal/handlers/tigris/msg_distinct.go
Labels: code/chore

#2672 Document aggregation operations
  website/docs/aggregation-operations/_category_.yml
  website/docs/aggregation-operations/aggregation-pipeline-and-commands.md
  website/docs/aggregation-operations/aggregation-stages.md
  website/docs/configuration/_category_.yml
  website/docs/contributing/_category_.yml
  website/docs/diff.md
  website/docs/indexes.md
  website/docs/pushdown.md
  website/docs/reference/_category_.yml
  website/docs/security.md
  website/docs/telemetry.md
  website/static/img/docs/aggregation-stages.jpg
Labels: documentation, trust

#2779 Fix `findAndModify` tests for MongoDB 6.0.6
  integration/findandmodify_compat_test.go
Labels: code/chore

#2777 Implement a few command stubs
  .golangci-new.yml
  internal/handlers/pg/msg_explain.go
  internal/handlers/sqlite/cmd_query.go
  internal/handlers/sqlite/msg_createindexes.go
  internal/handlers/sqlite/msg_explain.go
  internal/handlers/sqlite/msg_hello.go
  internal/handlers/sqlite/msg_ismaster.go
  internal/util/testutil/db.go
  internal/util/testutil/path.go
Labels: code/chore

#2769 Add more handler tests
  integration/commands_administration_test.go
  integration/commands_diagnostic_test.go
  integration/commands_freemonitoring_test.go
  integration/explain_compat_test.go
  internal/handlers/common/setfreemonitoring.go
  internal/handlers/pg/msg_datasize.go
Labels: code/chore

#2785 Remove `findAndModify` integration tests with `$` prefixed key for MongoDB 6.0.6 compatibility
  integration/findandmodify_compat_test.go
Labels: code/chore

#2737 Improve authentication documentation
  .github/workflows/website-preview.yml
  internal/handlers/pg/msg_saslstart.go
  website/blog/2023-01-04-ferretdb-beta-version-authentication.md
  website/docs/aggregation-operations/_category_.yml
  website/docs/configuration/flags.md
  website/docs/quickstart-guide/docker.md
  website/docs/security.md
  website/docs/security/_category_.yml
  website/docs/security/authentication.md
  website/docs/security/tls-connections.md
Labels: documentation, trust

#2787 Prepare v1.3.0 release
  .github/RELEASE_CHECKLIST.md
  CHANGELOG.md
Labels: code/chore

#2790 Make `testutil.Logger` easier to use
  .golangci-new.yml
  cmd/envtool/envtool_test.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/handlers/pg/pgdb/pgdb_test.go
  internal/handlers/tigris/tigrisdb/query_test.go
  internal/handlers/tigris/tigrisdb/tigrisdb_test.go
  internal/util/telemetry/telemetry_test.go
  internal/util/testutil/testutil.go
Labels: code/chore

#2791 Add blog post for FerretDB v1.3.0
  website/blog/2023-05-22-ferretdb-v-1-2-0-minor-release.md
  website/blog/2023-06-05-ferretdb-v-1-3-0-new-release.md
  website/static/img/blog/ferretdb-v1.3.0.jpg
Labels: trust, blog/marketing

#2792 Add `release` tag to release blog post
  website/blog/2023-04-11-ferretdb-1-0-ga-opensource-mongodb-alternative.md
Labels: trust, blog/marketing

#2798 Bump deps
  .golangci.yml
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/.golangci-new.yml
  integration/.golangci.yml
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: deps

#2801 Merge test workflows to fix coverage calculation
  .github/workflows/go-trust.yml
  .github/workflows/go.yml
  .github/workflows/integration-trust.yml
Labels: code/chore

#2782 Improve `testDistinctCompat`
  integration/distinct_compat_test.go
  integration/distinct_test.go
Labels: code/chore

#2799 Use iterator in `$sum` aggregation accumulator
  integration/aggregate_documents_test.go
  internal/handlers/common/aggregations/operators/accumulators/sum.go
Labels: code/chore, area/aggregations

#2810 Bump Go to 1.20.5
  build/deps/ferretdb-wrangler.Dockerfile
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
Labels: deps

#2784 Fix free monitoring tests for MongoDB 6.0.6
  integration/commands_freemonitoring_test.go
Labels: code/chore

#2727 Bump MongoDB to 6.0.6
  build/deps/legacy-mongo-shell.Dockerfile
  build/deps/mongo6.Dockerfile
Labels: deps

#2773 Implement `envtool tests shard` command
  cmd/envtool/envtool.go
  cmd/envtool/tests.go
  cmd/envtool/tests_test.go
Labels: code/chore

#2820 Shard integration tests
  .github/codecov.yml
  .github/workflows/go.yml
  Taskfile.yml
  cmd/envtool/envtool.go
  cmd/envtool/envtool_test.go
  cmd/envtool/tests.go
  cmd/envtool/tests_test.go
Labels: code/chore

#2823 Add textlint rules for en dashes and em dashes
  build/.textlintrc
  internal/bson/document.go
  website/blog/2022-08-23-open-source-is-in-danger.md
  website/blog/2023-01-04-ferretdb-beta-version-authentication.md
  website/blog/2023-01-17-ferretdb-0-8-1-version-release.md
Labels: documentation, code/chore, trust

#2821 Describe current test naming conventions in the contributing guidelines
  CONTRIBUTING.md
  integration/indexes_compat_test.go
Labels: code/chore

#2204 Add Blog Post on Document Databases
  website/blog/2023-06-09-document-databases-definition-features-use-cases.md
  website/static/img/.DS_Store
  website/static/img/blog/document-databases.jpg
Labels: trust, blog/marketing

#2825 Add tests for `find`/`getMore` `batchSize`
  integration/helpers.go
  integration/query_test.go
Labels: code/chore

#2752 Add more test cases for index validation
  integration/indexes_compat_test.go
  integration/indexes_test.go
  internal/handlers/pg/msg_createindexes.go
Labels: code/chore

#2789 Implement `$type` aggregation operator
  integration/aggregate_documents_compat_test.go
  internal/handlers/common/aggregations/expression.go
  internal/handlers/common/aggregations/operators/accumulators/sum.go
  internal/handlers/common/aggregations/operators/operators.go
  internal/handlers/common/aggregations/operators/type.go
  internal/handlers/common/aggregations/stages/group.go
  internal/handlers/common/aggregations/stages/projection/projection.go
  internal/handlers/common/aggregations/stages/unwind.go
Labels: code/feature, area/aggregations

#2832 Fix running single test with `task`
  CONTRIBUTING.md
  Taskfile.yml
Labels: code/chore

#2783 Implement simple `$addFields/$set` aggregation pipeline stages
  integration/aggregate_documents_compat_test.go
  internal/handlers/common/add_fields_iterator.go
  internal/handlers/common/aggregations/stages/add_fields.go
  internal/handlers/common/aggregations/stages/group.go
  internal/handlers/common/aggregations/stages/set.go
  internal/handlers/common/aggregations/stages/stages.go
  internal/handlers/common/validate.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
Labels: code/feature

#2846 Prevent tests deadlock when backend is down
  integration/setup/client.go
  integration/setup/listener.go
Labels: code/chore, trust

#2848 Fix `unimplemented-non-default` tag usages
  internal/handlers/common/find.go
  internal/handlers/commonparams/extract_params.go
  internal/handlers/commonparams/extract_params_test.go
Labels: code/chore

#2849 Bump deps
  CONTRIBUTING.md
  build/deps/markdownlint.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: deps

#2844 Add more tests for `$set` and `$addFields` aggregation stages
  integration/aggregate_documents_compat_test.go
  integration/aggregate_documents_test.go
  internal/handlers/common/aggregations/stages/add_fields.go
  internal/handlers/common/aggregations/stages/group.go
  internal/handlers/common/aggregations/stages/set.go
  internal/handlers/common/aggregations/stages/validate.go
  internal/handlers/common/validate.go
Labels: code/chore

#2833 Improve benchmarks
  .github/workflows/js.yml
  Taskfile.yml
  integration/.golangci.yml
  integration/Taskfile.yml
  integration/benchmarks_test.go
  integration/go.mod
  integration/go.sum
  integration/setup/setup.go
  integration/setup/startup.go
  integration/shareddata/benchmark_provider.go
  integration/shareddata/benchmarks.go
  integration/shareddata/faker.go
  integration/shareddata/shareddata.go
  internal/util/testutil/db.go
  tools/Taskfile.yml
Labels: code/chore

#2829 Handle `$type` aggregation operator errors properly
  integration/aggregate_documents_compat_test.go
  integration/aggregate_documents_test.go
  internal/handlers/common/aggregations/operators/operators.go
  internal/handlers/common/aggregations/operators/operators_errors.go
  internal/handlers/common/aggregations/operators/type.go
  internal/handlers/common/aggregations/stages/projection/projection.go
  internal/handlers/common/aggregations/stages/projection/projection_iterator.go
  internal/handlers/common/projection.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
Labels: code/chore, area/aggregations

#2814 Implement `createIndexes` for unique indexes
  integration/helpers.go
  integration/indexes_compat_test.go
  integration/indexes_test.go
  integration/insert_command_test.go
  integration/insert_compat_test.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/pg/msg_createindexes.go
  internal/handlers/pg/msg_insert.go
  internal/handlers/pg/msg_listindexes.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/database_metadata.go
  internal/handlers/pg/pgdb/indexes.go
  internal/handlers/pg/pgdb/indexes_test.go
  internal/handlers/tigris/msg_insert.go
Labels: code/feature

#2858 Add blogpost on FerretDB v1.4.0
  website/blog/2023-06-19-ferretdb-v-1-4-0-new-release.md
  website/static/img/blog/ferretdb-v1.4.0.jpg
Labels: trust, blog/marketing

#2853 Add more validation and tests for `$unset`
  integration/aggregate_documents_test.go
  integration/findandmodify_test.go
  internal/handlers/common/aggregations/stages/unset.go
  internal/handlers/common/update.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/types/documentpatherrorcode_string.go
  internal/types/path.go
Labels: code/chore, area/aggregations

#2860 Make it easier to debug GitHub Actions
  .github/workflows/go-trust.yml
  .github/workflows/go.yml
  integration/setup/startup.go
Labels: code/chore

#2866 Unify tests for indexes
  integration/indexes_compat_test.go
Labels: code/chore

#2870 Add blog post on "Meet FerretDB at Percona University in Casablanca and Belgrade"
  website/blog/2023-06-21-meet-ferretdb-percona-university-casablanca-belgrade.md
  website/static/img/blog/percona-university.jpg
Labels: trust, blog/marketing

#2865 Implement `count` for SQLite
  internal/handlers/common/count_iterator.go
  internal/handlers/pg/msg_count.go
  internal/handlers/sqlite/msg_count.go
  internal/handlers/sqlite/msg_update.go
  internal/types/array.go
  internal/types/document.go
  internal/types/document_test.go
Labels: code/feature

#2875 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#2879 Fix fuzzing corpus collection
  .github/workflows/go.yml
  cmd/fuzztool/fuzztool.go
Labels: code/chore

#2876 Update supported commands
  website/docs/reference/supported-commands.md
Labels: documentation, trust

#2828 Update contributing docs
  CONTRIBUTING.md
Labels: code/chore

#2850 Add operators support for `$addFields`
  integration/aggregate_documents_compat_test.go
  internal/handlers/common/add_fields_iterator.go
  internal/handlers/common/aggregations/operators/operators.go
  internal/handlers/common/aggregations/operators/operators_errors.go
  internal/handlers/common/aggregations/operators/type.go
  internal/handlers/common/aggregations/stages/projection/projection.go
  internal/handlers/common/aggregations/stages/validate.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
Labels: code/chore, area/aggregations

#2885 Unskip test that passes now
  integration/commands_diagnostic_test.go
  internal/handlers/common/aggregations/stages/group.go
Labels: code/chore

#2886 Tweak contributing guidelines
  CONTRIBUTING.md
Labels: code/chore

#2887 Fix Github link for Dance repository
  website/docs/contributing/index.md
Labels: documentation

#2861 Support cursors for aggregation pipelines
  integration/aggregate_documents_test.go
  integration/query_test.go
  internal/handlers/common/getmore.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_find.go
Labels: code/enhancement

#2895 Add handler's metrics registration
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/handlers/hana/hana.go
  internal/handlers/handlers.go
  internal/handlers/pg/pg.go
  internal/handlers/sqlite/sqlite.go
  internal/handlers/tigris/tigris.go
Labels: code/chore

#2904 Clean-up some code and comments
  cmd/envtool/envtool.go
  ferretdb/ferretdb.go
  integration/setup/client.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/handlers/common/count_iterator.go
  internal/handlers/commoncommands/msg_listcommands.go
  internal/util/iterator/func.go
  internal/util/iterator/slice.go
  internal/util/iterator/values.go
  internal/util/iterator/with_close.go
  internal/util/telemetry/reporter.go
Labels: code/chore

#2908 Fix cancelation signals propagation
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/listener.go
  integration/setup/setup.go
  internal/clientconn/listener.go
  internal/handlers/handlers.go
  internal/util/resource/resource.go
  internal/util/testutil/testutil.go
Labels: code/chore

#2912 Fix collection name starting with dot validation
  integration/basic_test.go
  internal/handlers/pg/msg_create.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/pgdb.go
Labels: code/enhancement

#2911 Add blog post on "How to Configure FerretDB to work on Percona Distribution for PostgreSQL"
  website/blog/2023-06-26-configure-ferretdb-work-percona-distribution-postgresql.md
  website/static/img/blog/displaying-studio3t-data.png
  website/static/img/blog/percona-ferretdb.png
  website/static/img/blog/postgresql.png
Labels: trust, blog/marketing

#2864 Enable cursor support for PostgreSQL and SQLite
  README.md
  Taskfile.yml
  cmd/ferretdb/main.go
  integration/setup/listener.go
  integration/setup/setup.go
  internal/backends/collection.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/metadata/pool/db.go
  internal/backends/sqlite/query_iterator.go
  internal/clientconn/cursor/cursor.go
  internal/clientconn/cursor/registry.go
  internal/handlers/common/count.go
  internal/handlers/common/find.go
  internal/handlers/common/getmore.go
  internal/handlers/common/insert.go
  internal/handlers/pg/msg_aggregate.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/msg_getmore.go
  internal/handlers/pg/pg.go
  internal/handlers/registry/pg.go
  internal/handlers/registry/registry.go
  internal/handlers/registry/sqlite.go
  internal/handlers/registry/tigris.go
  internal/handlers/sjson/sjson_test.go
  internal/handlers/sqlite/msg_drop.go
  internal/handlers/sqlite/msg_find.go
  internal/handlers/sqlite/msg_getmore.go
  internal/handlers/sqlite/sqlite.go
  internal/handlers/tigris/tigris.go
  internal/util/iterator/closer.go
  internal/util/resource/resource.go
  internal/util/testutil/testutil.go
Labels: code/feature

#2884 Improve validation for `createIndexes` and `dropIndexes`
  integration/indexes_compat_test.go
  integration/indexes_test.go
  internal/handlers/commonerrors/error.go
  internal/handlers/commonerrors/errorcode_string.go
  internal/handlers/pg/msg_createindexes.go
  internal/handlers/pg/msg_dropindexes.go
Labels: code/enhancement

#2930 Bump deps, add permissions monitoring
  .github/workflows/clean.yml
  .github/workflows/conform-pr.yml
  .github/workflows/debug.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/go-trust.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  .github/workflows/packages.yml
  .github/workflows/permissions.yml
  .github/workflows/security.yml
  .github/workflows/website-preview.yml
  build/deps/ferretdb-wrangler.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps, trust

#2934 Fix integration tests after bumping deps
  integration/basic_test.go
Labels: code/chore

#2932 Update benchmark to use cursors
  integration/benchmarks_test.go
Labels: code/chore

#2931 Crush PNG images
  website/static/img/blog/FerretDB-is-now-Beta.-1-980x551.png
  website/static/img/blog/Maintainer@5x-1-300x300.png
  website/static/img/blog/blog-img.png
  website/static/img/blog/cf73bb31-fa1b-4465-8277-e73da46127de-1650484034538-1-300x120.png
  website/static/img/blog/developer-preview.png
  website/static/img/blog/displaying-studio3t-data.png
  website/static/img/blog/ferret-rpi-1-1024x390.png
  website/static/img/blog/ferretdb-1-1-0-release.png
  website/static/img/blog/ferretdb-demo-creating-database.png
  website/static/img/blog/ferretdb-demo-page.png
  website/static/img/blog/image1-1.png
  website/static/img/blog/image2.png
  website/static/img/blog/image3.png
  website/static/img/blog/image5.png
  website/static/img/blog/image6.png
  website/static/img/blog/image7.png
  website/static/img/blog/mongodb-alternatives.png
  website/static/img/blog/percona-ferretdb.png
  website/static/img/blog/perconalive.png
  website/static/img/blog/postgresql.png
  website/static/img/guis/logo-light.png
  website/static/img/logo-light.png
Labels: trust, blog/marketing

#2937 Set `minWireVersion` to 0
  internal/handlers/common/common.go
Labels: code/chore, trust, packages

#2878 Test `getMore` integration test using one connection pool
  ferretdb/ferretdb.go
  integration/commands_diagnostic_test.go
  integration/query_test.go
  integration/setup/client.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/setup/test_helpers.go
  internal/util/teststress/stress.go
Labels: code/chore

#2933 Use cursors in `find` command
  .github/workflows/js.yml
  Taskfile.yml
  integration/Taskfile.yml
  internal/handlers/pg/msg_drop.go
  internal/handlers/pg/msg_dropdatabase.go
  internal/handlers/pg/msg_find.go
  internal/handlers/pg/pgdb/pool.go
  internal/handlers/pg/pgdb/query_iterator.go
  internal/handlers/pg/pgdb/transactions.go
  internal/handlers/pg/pgdb/transactions_test.go
  internal/handlers/sqlite/msg_drop.go
  internal/handlers/sqlite/msg_dropdatabase.go
  internal/handlers/sqlite/msg_find.go
Labels: code/enhancement

#2938 Add better metrics for connections
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/listener.go
  integration/setup/startup.go
  internal/clientconn/conn.go
  internal/clientconn/connmetrics/conn_metrics.go
  internal/clientconn/connmetrics/listener_metrics.go
  internal/clientconn/cursor/registry.go
  internal/clientconn/listener.go
  internal/handlers/hana/hana.go
  internal/handlers/pg/msg_serverstatus.go
  internal/handlers/pg/pg.go
  internal/handlers/registry/hana.go
  internal/handlers/registry/pg.go
  internal/handlers/registry/registry.go
  internal/handlers/registry/sqlite.go
  internal/handlers/registry/tigris.go
  internal/handlers/sqlite/msg_serverstatus.go
  internal/handlers/sqlite/sqlite.go
  internal/handlers/tigris/msg_serverstatus.go
  internal/handlers/tigris/tigris.go
  internal/util/observability/funccall.go
Labels: code/chore

#2929 Use cursors with iterator in `aggregate` command
  integration/aggregate_documents_compat_test.go
  integration/aggregate_documents_test.go
  integration/helpers.go
  integration/indexes_compat_test.go
  integration/query_test.go
  internal/handlers/common/aggregations/stages/collstats.go
  internal/handlers/common/aggregations/stages/group.go
  internal/handlers/common/aggregations/stages/unwind.go
  internal/handlers/pg/msg_aggregate.go
Labels: code/chore

#2936 Implement proper response for `createIndexes`
  integration/indexes_command_compat_test.go
  integration/indexes_compat_test.go
  internal/handlers/pg/msg_createindexes.go
  internal/handlers/pg/msg_listindexes.go
  internal/handlers/pg/msg_update.go
  internal/handlers/pg/pgdb/collections.go
  internal/handlers/pg/pgdb/indexes.go
  internal/handlers/pg/pgdb/indexes_test.go
  internal/handlers/pg/pgdb/insert.go
  internal/handlers/pg/pgdb/pgdb_test.go
Labels: code/chore

#2907 Re-implement `DELETE` for SQLite backend
  integration/delete_command_compat_test.go
  integration/delete_compat_test.go
  internal/backends/collection.go
  internal/backends/sqlite/collection.go
  internal/handlers/common/delete.go
  internal/handlers/pg/msg_delete.go
  internal/handlers/sqlite/msg_delete.go
  internal/handlers/tigris/msg_delete.go
Labels: code/chore

#2924 Validate database names for SQLite handler
  integration/basic_test.go
  internal/handlers/pg/pgdb/databases.go
  internal/handlers/sqlite/msg_create.go
Labels: code/chore

#2946 Add `insert` documents type validation
  integration/insert_command_test.go
  internal/handlers/common/insert.go
  internal/handlers/pg/msg_insert.go
Labels: code/chore
