Repository FerretDB/FerretDB, pull requests merged in 2024-05, with the labels that each got.

#4262 Remove old BSON implementation
  .golangci.yml
  internal/bson/bson_test.go
  internal/bson/oldbson/array.go
  internal/bson/oldbson/array_test.go
  internal/bson/oldbson/binary.go
  internal/bson/oldbson/binary_test.go
  internal/bson/oldbson/bool.go
  internal/bson/oldbson/bool_test.go
  internal/bson/oldbson/cstring.go
  internal/bson/oldbson/cstring_test.go
  internal/bson/oldbson/datetime.go
  internal/bson/oldbson/datetime_test.go
  internal/bson/oldbson/document.go
  internal/bson/oldbson/document_test.go
  internal/bson/oldbson/double.go
  internal/bson/oldbson/double_test.go
  internal/bson/oldbson/int32.go
  internal/bson/oldbson/int32_test.go
  internal/bson/oldbson/int64.go
  internal/bson/oldbson/int64_test.go
  internal/bson/oldbson/null.go
  internal/bson/oldbson/object_id.go
  internal/bson/oldbson/object_id_test.go
  internal/bson/oldbson/oldbson.go
  internal/bson/oldbson/oldbson_test.go
  internal/bson/oldbson/regex.go
  internal/bson/oldbson/regex_test.go
  internal/bson/oldbson/string.go
  internal/bson/oldbson/string_test.go
  internal/bson/oldbson/tag.go
  internal/bson/oldbson/tag_string.go
  internal/bson/oldbson/testdata/all.hex
  internal/bson/oldbson/testdata/array_all.hex
  internal/bson/oldbson/testdata/array_fuzz1.hex
  internal/bson/oldbson/testdata/handshake1.hex
  internal/bson/oldbson/testdata/handshake2.hex
  internal/bson/oldbson/testdata/handshake3.hex
  internal/bson/oldbson/testdata/handshake4.hex
  internal/bson/oldbson/timestamp.go
  internal/bson/oldbson/timestamp_test.go
Labels: code/chore

#4263 Port BSON changes
  internal/bson/array.go
  internal/bson/bson.go
  internal/bson/bson_test.go
  internal/bson/decode.go
  internal/bson/document.go
  internal/bson/logging.go
  internal/bson/logging_test.go
  internal/bson/raw_array.go
  internal/bson/raw_document.go
  internal/bson/tag.go
  internal/bson/tag_string.go
Labels: code/chore

#4265 Move tools cache directory
  Taskfile.yml
  tools/Taskfile.yml
  tools/checkcomments/checkcomments_test.go
  tools/checkcomments/client.go
Labels: code/chore

#4266 Use more shards on CI
  .github/workflows/_integration.yml
  .github/workflows/go.yml
Labels: code/chore

#4272 Bump Go to 1.22.3 and deps
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
  website/go.mod
Labels: deps, trust, packages

#4277 Update linters configuration
  .golangci-new.yml
  .golangci.yml
  Taskfile.yml
  integration/.golangci-new.yml
  integration/.golangci.yml
  integration/Taskfile.yml
  internal/driver/driver.go
  tools/Taskfile.yml
Labels: code/chore

#4223 Sort new fields in lexicographic order during update
  integration/findandmodify_compat_test.go
  integration/update_array_compat_test.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  internal/handler/common/update.go
  internal/handler/common/update_array_operators.go
Labels: code/chore

#4278 Fix embedded package panic
  ferretdb/ferretdb.go
  ferretdb/ferretdb_test.go
  integration/embedded_test.go
Labels: code/bug

#4294 Make maximum document size configurable
  cmd/ferretdb/main.go
  integration/insert_command_test.go
  integration/setup/listener.go
  integration/setup/setup.go
  internal/handler/cmd_query.go
  internal/handler/common/ismaster.go
  internal/handler/handler.go
  internal/handler/msg_buildinfo.go
  internal/handler/msg_hello.go
  internal/handler/msg_ismaster.go
  internal/handler/registry/hana.go
  internal/handler/registry/mysql.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/registry.go
  internal/handler/registry/sqlite.go
Labels: code/feature

#4289 Fix `env-data`
  integration/Taskfile.yml
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/shareddata_test.go
Labels: code/chore

#4302 Bump deps
  .golangci-new.yml
  .prettierignore
  Taskfile.yml
  build/.markdownlint.yml
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/markdownlint.Dockerfile
  build/deps/mysql.Dockerfile
  build/deps/postgres.Dockerfile
  build/deps/trivy.Dockerfile
  build/ferretdb/all-in-one.Dockerfile
  go.mod
  go.sum
  integration/.golangci-new.yml
  integration/go.mod
  integration/go.sum
  internal/backends/backend_test.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/registry_test.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: deps

#4297 Add blog post about deploying FerretDB on Taikun CloudWorks
  website/blog/2024-05-27-deploy-ferretdb-kubernetes-taikun-cloudworks.md
  website/static/img/blog/ferretdb-taikun.jpg
Labels: trust, blog/marketing

#4307 Port some changes from v2
  .golangci.yml
  integration/.golangci.yml
  integration/aggregate_documents_compat_test.go
  integration/aggregate_stats_compat_test.go
  integration/aggregate_stats_test.go
  integration/basic_test.go
  integration/benchmarks_test.go
  integration/commands_administration_compat_test.go
  integration/commands_administration_test.go
  integration/commands_authentication_test.go
  integration/commands_diagnostic_test.go
  integration/commands_freemonitoring_test.go
  integration/commands_replication_test.go
  integration/count_command_compat_test.go
  integration/count_compat_test.go
  integration/cursors/awaitdata_test.go
  integration/cursors/getmore_test.go
  integration/cursors/helpers.go
  integration/cursors/kill_test.go
  integration/cursors/tailable_sessions_test.go
  integration/cursors/tailable_test.go
  integration/delete_command_compat_test.go
  integration/diff_08_names_test.go
  integration/findandmodify_compat_test.go
  integration/findandmodify_test.go
  integration/hello_command_test.go
  integration/indexes_command_compat_test.go
  integration/insert_command_compat_test.go
  integration/integration.go
  integration/oplog/basic_oplog_test.go
  integration/oplog/update_oplog_test.go
  integration/pushdown.go
  integration/query_command_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_test.go
  integration/renamecollection_test.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/setup/startup.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  integration/update_field_test.go
  integration/users/connection_test.go
  integration/users/create_user_test.go
  integration/users/drop_all_users_from_database_test.go
  integration/users/drop_user_test.go
  integration/users/update_user_test.go
  integration/users/usersinfo_test.go
  internal/types/types.go
  internal/wire/op_msg.go
  internal/wire/op_msg_section.go
  internal/wire/op_msg_test.go
Labels: code/chore

#4311 Extract user creation and move to `backends` package
  cmd/ferretdb/main.go
  internal/backends/user.go
  internal/handler/authenticate.go
  internal/handler/msg_createuser.go
  internal/handler/msg_updateuser.go
  internal/util/password/password.go
Labels: code/chore

#4319 Populate `env-data` for running `FerretDB`
  .github/workflows/go.yml
  CONTRIBUTING.md
  Taskfile.yml
  integration/Taskfile.yml
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/shareddata_test.go
  integration/users/connection_test.go
Labels: code/chore
