Repository FerretDB/FerretDB, pull requests merged in 2024-01, with the labels that each got.

#3915 Cleanup `awaitData` tailable cursor
  internal/handler/msg_getmore.go
Labels: code/feature

#3924 Cleanup a closed issue
  internal/handler/sjson/sjson_test.go
Labels: code/chore

#3899 Implement and test OpLog for update operations
  integration/oplog/basic_oplog_test.go
  integration/oplog/update_oplog_test.go
  internal/backends/decorators/oplog/collection.go
  internal/backends/decorators/oplog/oplog.go
  internal/handler/common/find.go
  website/docs/reference/supported-commands.md
Labels: code/chore

#3934 Ignore `sparse` index parameter for now
  internal/handler/msg_createindexes.go
Labels: code/chore

#3851 Allow filtering by name in `ListDatabases` and `ListCollections`
  internal/backends/backend.go
  internal/backends/backend_test.go
  internal/backends/collection_test.go
  internal/backends/database.go
  internal/backends/decorators/oplog/collection.go
  internal/backends/postgresql/backend.go
  internal/backends/postgresql/database.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/database.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_collstats.go
  internal/handler/msg_explain.go
  internal/handler/msg_find.go
Labels: code/chore

#3917 Disallow `maxTimeMS` for non-awaitData cursors in `getMore` command
  integration/cursors/getmore_test.go
  internal/handler/msg_getmore.go
Labels: code/enhancement

#3897 Implement `usersInfo` command
  integration/users/drop_all_users_from_database_test.go
  integration/users/usersinfo_test.go
  internal/handler/commands.go
  internal/handler/msg_createuser.go
  internal/handler/msg_dropallusersfromdatabase.go
  internal/handler/msg_dropuser.go
  internal/handler/msg_usersinfo.go
  website/docs/reference/supported-commands.md
Labels: code/feature

#3937 Disallow native passwords for MySQL
  internal/backends/mysql/metadata/pool/uri.go
  internal/backends/mysql/metadata/registry_test.go
Labels: code/chore

#3925 Add the necessary for replica set fields to `ismaster` response
  Taskfile.yml
  build/mongodb.conf
  build/mongodb_secured.conf
  cmd/envtool/envtool.go
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  internal/handler/cmd_query.go
  internal/handler/common/ismaster.go
  internal/handler/handler.go
  internal/handler/msg_ismaster.go
  internal/handler/registry/hana.go
  internal/handler/registry/mysql.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/registry.go
  internal/handler/registry/sqlite.go
  website/docs/configuration/flags.md
  website/docs/reference/supported-commands.md
Labels: code/chore

#3935 Fix `awaitData` cursor panic
  integration/cursors/awaitdata_test.go
  internal/handler/msg_getmore.go
Labels: code/bug

#3932 Use `usersInfo` in `dropAllUsersFromDatabase` tests
  integration/users/drop_all_users_from_database_test.go
Labels: code/chore

#3941 Allow Native Passwords for testcase
  internal/backends/mysql/metadata/pool/uri.go
  internal/backends/mysql/metadata/registry_test.go
Labels: code/chore

#3947 Prepare v1.18.0 release
  CHANGELOG.md
  cmd/ferretdb/main.go
  website/docs/reference/supported-commands.md
  website/docusaurus.config.js
  website/versioned_docs/version-v1.16/reference/supported-commands.md
  website/versioned_docs/version-v1.18/aggregation-operations/_category_.yml
  website/versioned_docs/version-v1.18/aggregation-operations/aggregation-pipeline-and-commands.md
  website/versioned_docs/version-v1.18/aggregation-operations/aggregation-stages.md
  website/versioned_docs/version-v1.18/basic-operations/_category_.yml
  website/versioned_docs/version-v1.18/basic-operations/create.md
  website/versioned_docs/version-v1.18/basic-operations/delete.md
  website/versioned_docs/version-v1.18/basic-operations/index.md
  website/versioned_docs/version-v1.18/basic-operations/read.md
  website/versioned_docs/version-v1.18/basic-operations/update.md
  website/versioned_docs/version-v1.18/configuration/_category_.yml
  website/versioned_docs/version-v1.18/configuration/flags.md
  website/versioned_docs/version-v1.18/configuration/observability.md
  website/versioned_docs/version-v1.18/configuration/operation-modes.md
  website/versioned_docs/version-v1.18/contributing/_category_.yml
  website/versioned_docs/version-v1.18/contributing/index.md
  website/versioned_docs/version-v1.18/contributing/writing-guide.md
  website/versioned_docs/version-v1.18/diff.md
  website/versioned_docs/version-v1.18/indexes.md
  website/versioned_docs/version-v1.18/main.md
  website/versioned_docs/version-v1.18/migration/_category_.yml
  website/versioned_docs/version-v1.18/migration/migrating-from-mongodb.md
  website/versioned_docs/version-v1.18/migration/premigration-testing.md
  website/versioned_docs/version-v1.18/operators/_category_.yml
  website/versioned_docs/version-v1.18/operators/query/_category_.yml
  website/versioned_docs/version-v1.18/operators/query/array-operators.md
  website/versioned_docs/version-v1.18/operators/query/bitwise-operators.md
  website/versioned_docs/version-v1.18/operators/query/comparison-operators.md
  website/versioned_docs/version-v1.18/operators/query/element-operators.md
  website/versioned_docs/version-v1.18/operators/query/evaluation-operators.md
  website/versioned_docs/version-v1.18/operators/query/logical-operators.md
  website/versioned_docs/version-v1.18/operators/update/_category_.yml
  website/versioned_docs/version-v1.18/operators/update/array-update-operators.md
  website/versioned_docs/version-v1.18/operators/update/field-update-operators.md
  website/versioned_docs/version-v1.18/pushdown.md
  website/versioned_docs/version-v1.18/quickstart-guide/_category_.yml
  website/versioned_docs/version-v1.18/quickstart-guide/deb.md
  website/versioned_docs/version-v1.18/quickstart-guide/docker.md
  website/versioned_docs/version-v1.18/quickstart-guide/go.md
  website/versioned_docs/version-v1.18/quickstart-guide/macos.md
  website/versioned_docs/version-v1.18/quickstart-guide/rpm.md
  website/versioned_docs/version-v1.18/quickstart-guide/windows.md
  website/versioned_docs/version-v1.18/reference/_category_.yml
  website/versioned_docs/version-v1.18/reference/glossary.md
  website/versioned_docs/version-v1.18/reference/supported-commands.md
  website/versioned_docs/version-v1.18/security/_category_.yml
  website/versioned_docs/version-v1.18/security/authentication.md
  website/versioned_docs/version-v1.18/security/tls-connections.md
  website/versioned_docs/version-v1.18/telemetry.md
  website/versioned_docs/version-v1.18/understanding-ferretdb.md
  website/versioned_sidebars/version-v1.18-sidebars.json
  website/versions.json
Labels: documentation, trust

#3950 Add blog post for FerretDB release v1.18.0
  website/blog/2024-01-08-new-ferretdb-v118-support-oplog-functionality.md
  website/static/img/blog/ferretdb-v1.18.0.jpg
Labels: trust, blog/marketing

#3951 Tweak blog post a bit
  website/blog/2024-01-08-new-ferretdb-v118-support-oplog-functionality.md
Labels: trust, blog/marketing

#3955 Bump deps
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  website/docs/basic-operations/performing.md
  website/docs/configuration/observability.md
  website/docs/contributing/how-to-contribute.md
  website/docs/reference/glossary.md
  website/docs/understanding-ferretdb.md
  website/versioned_docs/version-v1.16/basic-operations/performing.md
  website/versioned_docs/version-v1.16/configuration/observability.md
  website/versioned_docs/version-v1.16/contributing/how-to-contribute.md
  website/versioned_docs/version-v1.16/reference/glossary.md
  website/versioned_docs/version-v1.16/understanding-ferretdb.md
  website/versioned_docs/version-v1.17/basic-operations/performing.md
  website/versioned_docs/version-v1.17/configuration/observability.md
  website/versioned_docs/version-v1.17/contributing/how-to-contribute.md
  website/versioned_docs/version-v1.17/reference/glossary.md
  website/versioned_docs/version-v1.17/understanding-ferretdb.md
  website/versioned_docs/version-v1.18/basic-operations/performing.md
  website/versioned_docs/version-v1.18/configuration/observability.md
  website/versioned_docs/version-v1.18/contributing/how-to-contribute.md
  website/versioned_docs/version-v1.18/reference/glossary.md
  website/versioned_docs/version-v1.18/understanding-ferretdb.md
Labels: documentation, deps, trust

#3960 Add documentation for oplog
  website/docs/configuration/oplog-support.md
  website/versioned_docs/version-v1.18/configuration/oplog-support.md
Labels: documentation, trust

#3964 Fix Taskfile.yml indentation
  Taskfile.yml
Labels: code/chore, trust, packages

#3965 Speed-up Docker builds
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
Labels: code/chore, trust, packages

#3919 Fix `maxTimeMS` for `getMore` command
  integration/cursors/awaitdata_test.go
  integration/cursors/getmore_test.go
  integration/cursors/tailable_test.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_find.go
  website/docs/reference/supported-commands.md
Labels: code/enhancement

#3940 Run more `maxTimeMS` tests
  integration/cursors/getmore_test.go
  internal/handler/handlererrors/error.go
  internal/handler/handlererrors/errorcode_string.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_find.go
Labels: code/enhancement

#3928 Store passwords for PLAIN authentication mechanism
  integration/users/create_user_test.go
  integration/users/usersinfo_test.go
  internal/handler/msg_createuser.go
  internal/handler/msg_usersinfo.go
Labels: code/feature

#3970 Use PBKDF2 for storing `PLAIN` passwords
  .github/mergify.yml
  integration/users/create_user_test.go
  integration/users/drop_all_users_from_database_test.go
  integration/users/drop_user_test.go
  internal/backends/mysql/metadata/pool/pool.go
  internal/backends/mysql/metadata/registry.go
  internal/backends/postgresql/metadata/registry.go
  internal/clientconn/conninfo/conn_info.go
  internal/handler/handler.go
  internal/handler/sjson/sjson_marshal_unmarshal_test.go
  internal/util/password/plain.go
  internal/util/password/plain_test.go
Labels: code/chore

#3931 Fix `upsert` with `$setOnInsert` operator
  integration/.golangci-new.yml
  integration/findandmodify_compat_test.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  internal/handler/common/findandmodify.go
  internal/handler/common/update.go
  internal/handler/common/upsertoperation_string.go
  internal/handler/msg_findandmodify.go
  internal/handler/msg_update.go
Labels: code/bug, community

#3971 Small fixes and tweaks
  .github/mergify.yml
  internal/bson/document.go
  internal/bson/document_test.go
  internal/bson/testdata/all.hex
  internal/types/binary.go
  tools/checkcomments/checkcomments_test.go
  website/docs/reference/supported-commands.md
Labels: code/chore

#3976 Fix search queries
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
Labels: documentation, trust

#3973 Implement `updateUser` command
  integration/setup/helpers.go
  integration/users/create_user_test.go
  integration/users/update_user_test.go
  internal/handler/handlererrors/error.go
  internal/handler/handlererrors/errorcode_string.go
  internal/handler/msg_createuser.go
  internal/handler/msg_updateuser.go
Labels: code/feature

#3979 Small assorted tweaks
  .github/settings.yml
  .gitignore
  docker-compose.override.yml.example
  internal/util/testutil/postgresql.go
Labels: code/chore

#3967 Add MySQL backend Registry
  internal/backends/mysql/metadata/metadata.go
  internal/backends/mysql/metadata/registry.go
  internal/backends/postgresql/metadata/registry.go
  internal/backends/sqlite/metadata/registry.go
Labels: code/chore

#3905 Add new BSON decoding package
  .golangci.yml
  Taskfile.yml
  go.mod
  go.sum
  internal/bson2/array.go
  internal/bson2/bson2.go
  internal/bson2/decode.go
  internal/bson2/document.go
  internal/bson2/document_test.go
  internal/bson2/encode.go
  internal/bson2/size.go
  internal/bson2/slog.go
  internal/bson2/tag.go
  internal/bson2/tag_string.go
  internal/bson2/testdata/all.hex
  internal/bson2/testdata/handshake1.hex
  internal/bson2/testdata/handshake2.hex
  internal/bson2/testdata/handshake3.hex
  internal/bson2/testdata/handshake4.hex
Labels: code/chore

#3987 Refactor `bson2` encoding/decoding
  internal/bson2/array.go
  internal/bson2/bson2.go
  internal/bson2/document.go
  internal/bson2/document_test.go
  internal/bson2/encode.go
  internal/bson2/raw_array.go
  internal/bson2/raw_document.go
Labels: code/chore

#3980 Use `usersInfo` for `createUser` and `dropUser` integration tests
  integration/users/create_user_test.go
  integration/users/drop_user_test.go
Labels: code/chore

#3988 Improve `bson2` fuzzing
  .github/workflows/go.yml
  internal/bson2/document_test.go
  internal/bson2/slog.go
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: code/chore

#3994 Update contributing documentation
  CONTRIBUTING.md
  internal/backends/postgresql/helpers.go
  internal/handler/sjson/schema_test.go
Labels: code/chore

#3995 Use `ListCollection` with a filter
  internal/handler/msg_compact.go
Labels: code/chore

#3993 Add tests for MySQL registry
  internal/backends/mysql/metadata/indexes.go
  internal/backends/mysql/metadata/metadata.go
  internal/backends/mysql/metadata/registry.go
  internal/backends/mysql/metadata/registry_test.go
Labels: code/chore

#3972 Support creating an index on nested fields for SQLite
  integration/indexes_compat_test.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/metadata/registry_test.go
Labels: code/feature

#3990 Fix validation process for creating duplicate `_id` index
  integration/indexes_compat_test.go
  internal/handler/msg_createindexes.go
Labels: code/bug

#4002 Prepare CI to having multiple main branches
  .github/workflows/_integration.yml
  .github/workflows/debug.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/go-trusted.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  .github/workflows/packages.yml
  .github/workflows/security.yml
  build/version/version.go
Labels: code/chore

#3996 Ignore `$readPreference` field
  internal/handler/common/count.go
  internal/handler/common/delete_params.go
  internal/handler/common/distinct.go
  internal/handler/common/find.go
  internal/handler/common/findandmodify.go
  internal/handler/common/update_params.go
Labels: code/chore

#4000 Hide `*types.Document` from `wire` struct fields
  internal/clientconn/conn.go
  internal/handler/cmd_query.go
  internal/handler/common/ismaster.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_buildinfo.go
  internal/handler/msg_collstats.go
  internal/handler/msg_compact.go
  internal/handler/msg_connectionstatus.go
  internal/handler/msg_count.go
  internal/handler/msg_create.go
  internal/handler/msg_createindexes.go
  internal/handler/msg_createuser.go
  internal/handler/msg_currentop.go
  internal/handler/msg_datasize.go
  internal/handler/msg_dbstats.go
  internal/handler/msg_debugerror.go
  internal/handler/msg_delete.go
  internal/handler/msg_distinct.go
  internal/handler/msg_drop.go
  internal/handler/msg_dropallusersfromdatabase.go
  internal/handler/msg_dropdatabase.go
  internal/handler/msg_dropindexes.go
  internal/handler/msg_dropuser.go
  internal/handler/msg_explain.go
  internal/handler/msg_find.go
  internal/handler/msg_findandmodify.go
  internal/handler/msg_getcmdlineopts.go
  internal/handler/msg_getfreemonitoringstatus.go
  internal/handler/msg_getlog.go
  internal/handler/msg_getmore.go
  internal/handler/msg_getparameter.go
  internal/handler/msg_hello.go
  internal/handler/msg_hostinfo.go
  internal/handler/msg_insert.go
  internal/handler/msg_ismaster.go
  internal/handler/msg_killcursors.go
  internal/handler/msg_listcollections.go
  internal/handler/msg_listcommands.go
  internal/handler/msg_listdatabases.go
  internal/handler/msg_listindexes.go
  internal/handler/msg_logout.go
  internal/handler/msg_ping.go
  internal/handler/msg_renamecollection.go
  internal/handler/msg_saslstart.go
  internal/handler/msg_serverstatus.go
  internal/handler/msg_setfreemonitoring.go
  internal/handler/msg_update.go
  internal/handler/msg_updateuser.go
  internal/handler/msg_usersinfo.go
  internal/handler/msg_validate.go
  internal/handler/msg_whatsmyuri.go
  internal/handler/sjson/sjson_test.go
  internal/wire/op_msg.go
  internal/wire/op_msg_test.go
  internal/wire/op_query.go
  internal/wire/op_query_test.go
  internal/wire/op_reply.go
  internal/wire/op_reply_test.go
Labels: code/chore

#3997 Add deep `bson2` decoding
  .github/workflows/_integration.yml
  .github/workflows/conform-pr.yml
  .github/workflows/debug.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  .github/workflows/packages.yml
  .github/workflows/permissions.yml
  .github/workflows/security.yml
  .github/workflows/website-preview.yml
  internal/bson2/document_test.go
  internal/bson2/raw_array.go
  internal/bson2/raw_document.go
  internal/bson2/slog.go
Labels: code/chore

#4011 Expose raw documents in the `wire` package
  .golangci.yml
  CONTRIBUTING.md
  Taskfile.yml
  cmd/envtool/envtool.go
  integration/go.mod
  integration/go.sum
  internal/bson2/slog.go
  internal/util/logging/logging.go
  internal/wire/op_msg.go
  internal/wire/wire_test.go
  tools/checkcomments/checkcomments.go
Labels: code/chore

#4016 Prepare release
  CHANGELOG.md
  website/docusaurus.config.js
  website/versioned_docs/version-v1.19/aggregation-operations/_category_.yml
  website/versioned_docs/version-v1.19/aggregation-operations/aggregation-pipeline-and-commands.md
  website/versioned_docs/version-v1.19/aggregation-operations/aggregation-stages.md
  website/versioned_docs/version-v1.19/basic-operations/_category_.yml
  website/versioned_docs/version-v1.19/basic-operations/create.md
  website/versioned_docs/version-v1.19/basic-operations/delete.md
  website/versioned_docs/version-v1.19/basic-operations/performing.md
  website/versioned_docs/version-v1.19/basic-operations/read.md
  website/versioned_docs/version-v1.19/basic-operations/update.md
  website/versioned_docs/version-v1.19/configuration/_category_.yml
  website/versioned_docs/version-v1.19/configuration/flags.md
  website/versioned_docs/version-v1.19/configuration/observability.md
  website/versioned_docs/version-v1.19/configuration/operation-modes.md
  website/versioned_docs/version-v1.19/configuration/oplog-support.md
  website/versioned_docs/version-v1.19/contributing/_category_.yml
  website/versioned_docs/version-v1.19/contributing/how-to-contribute.md
  website/versioned_docs/version-v1.19/contributing/writing-guide.md
  website/versioned_docs/version-v1.19/diff.md
  website/versioned_docs/version-v1.19/indexes.md
  website/versioned_docs/version-v1.19/main.md
  website/versioned_docs/version-v1.19/migration/_category_.yml
  website/versioned_docs/version-v1.19/migration/migrating-from-mongodb.md
  website/versioned_docs/version-v1.19/migration/premigration-testing.md
  website/versioned_docs/version-v1.19/operators/_category_.yml
  website/versioned_docs/version-v1.19/operators/query/_category_.yml
  website/versioned_docs/version-v1.19/operators/query/array-operators.md
  website/versioned_docs/version-v1.19/operators/query/bitwise-operators.md
  website/versioned_docs/version-v1.19/operators/query/comparison-operators.md
  website/versioned_docs/version-v1.19/operators/query/element-operators.md
  website/versioned_docs/version-v1.19/operators/query/evaluation-operators.md
  website/versioned_docs/version-v1.19/operators/query/logical-operators.md
  website/versioned_docs/version-v1.19/operators/update/_category_.yml
  website/versioned_docs/version-v1.19/operators/update/array-update-operators.md
  website/versioned_docs/version-v1.19/operators/update/field-update-operators.md
  website/versioned_docs/version-v1.19/pushdown.md
  website/versioned_docs/version-v1.19/quickstart-guide/_category_.yml
  website/versioned_docs/version-v1.19/quickstart-guide/deb.md
  website/versioned_docs/version-v1.19/quickstart-guide/docker.md
  website/versioned_docs/version-v1.19/quickstart-guide/go.md
  website/versioned_docs/version-v1.19/quickstart-guide/macos.md
  website/versioned_docs/version-v1.19/quickstart-guide/rpm.md
  website/versioned_docs/version-v1.19/quickstart-guide/windows.md
  website/versioned_docs/version-v1.19/reference/_category_.yml
  website/versioned_docs/version-v1.19/reference/glossary.md
  website/versioned_docs/version-v1.19/reference/supported-commands.md
  website/versioned_docs/version-v1.19/security/_category_.yml
  website/versioned_docs/version-v1.19/security/authentication.md
  website/versioned_docs/version-v1.19/security/tls-connections.md
  website/versioned_docs/version-v1.19/telemetry.md
  website/versioned_docs/version-v1.19/understanding-ferretdb.md
  website/versioned_sidebars/version-v1.19-sidebars.json
  website/versions.json
Labels: documentation, code/chore, trust

#4012 Add tests for new SCRAM-SHA-256 authentication support
  integration/users/connection_test.go
  integration/users/create_user_test.go
  integration/users/drop_all_users_from_database_test.go
  integration/users/usersinfo_test.go
Labels: code/feature

#4015 Add `TODO` comments for logging
  ferretdb/ferretdb.go
  internal/util/logging/logging.go
Labels: code/chore

#4019 Add `bson2` helpers for conversions and logging
  internal/bson2/raw_array.go
  internal/bson2/raw_document.go
  internal/bson2/slog.go
Labels: code/chore

#4003 Setup MySQL backend
  internal/backends/mysql/backend.go
  internal/backends/mysql/collection.go
  internal/backends/mysql/database.go
  internal/backends/mysql/query_iterator.go
Labels: code/chore

#4010 Add blog post on Ubicloud managed postgres
  website/blog/2024-01-29-add-mongodb-compatibility-ubicloud-managed-postgres.md
  website/static/img/blog/contact-app-ubicloud.png
  website/static/img/blog/ferretdb-ubicloud.jpg
Labels: trust, blog/marketing

#4020 Add release blog post for v1.19.0
  website/blog/2024-01-30-new-ferretdb-v119-release.md
  website/static/img/blog/ferretdb-v1.19.0.jpg
Labels: trust, blog/marketing
