Repository FerretDB/FerretDB, pull requests merged in 2024-07, with the labels that each got.

#4405 Update comments about interfaces
  .golangci.yml
  integration/.golangci.yml
  integration/shareddata/benchmark_provider.go
  integration/shareddata/provider.go
  internal/bson/array.go
  internal/bson/document.go
  internal/bson/raw_array.go
  internal/bson/raw_document.go
  internal/clientconn/connmetrics/conn_metrics.go
  internal/clientconn/connmetrics/listener_metrics.go
  internal/clientconn/cursor/registry.go
  internal/clientconn/listener.go
  internal/handler/handler.go
  internal/util/state/metrics.go
  internal/wire/op_msg.go
  internal/wire/op_query.go
  internal/wire/op_reply.go
Labels: code/chore

#4402 Check database name for authentication
  integration/setup/listener.go
  internal/handler/cmd_query.go
  internal/handler/msg_saslstart.go
Labels: code/chore

#4404 Refactor runnables
  cmd/envtool/envtool.go
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/listener.go
  integration/setup/startup.go
  internal/clientconn/listener.go
  internal/util/ctxutil/ctxutil.go
  internal/util/debug/debug.go
  internal/util/telemetry/reporter.go
Labels: code/chore

#4406 Add tests for `ctxutil.Sigterm`
  internal/util/ctxutil/sigterm_test.go
Labels: code/chore

#4380 Setup OpenTelemetry exporter for FerretDB
  Taskfile.yml
  cmd/envtool/tests.go
  cmd/ferretdb/main.go
  integration/setup/startup.go
  internal/util/observability/observability.go
Labels: code/chore

#4364 Implement Docker healthcheck
  cmd/ferretdb/main.go
  cmd/ferretdb/ping.go
Labels: code/chore

#4408 Extract `types` and `zap` code into separate files
  internal/bson/array.go
  internal/bson/bson.go
  internal/bson/document.go
  internal/bson/logging_test.go
  internal/bson/raw_array.go
  internal/bson/raw_document.go
  internal/bson/types.go
  internal/util/logging/console_handler.go
  internal/util/logging/console_handler_test.go
  internal/util/logging/handler.go
  internal/util/logging/logging.go
  internal/util/logging/zap.go
Labels: code/chore

#4416 Bump Go and deps
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  website/go.mod
Labels: deps

#4399 Implement Kubernetes startup probe
  cmd/envtool/envtool.go
  cmd/ferretdb/main.go
  integration/setup/startup.go
  internal/util/debug/debug.go
  internal/util/debug/debug_test.go
Labels: code/feature

#4423 Disable OTEL in tests where collection name might have non-UTF-8 symbols
  integration/diff_08_names_test.go
  integration/setup/client.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/setup/startup.go
Labels: code/chore

#4424 Document Kubernetes probes
  .gitignore
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
  cmd/envtool/envtool.go
  cmd/ferretdb/main.go
  integration/setup/startup.go
  internal/clientconn/listener.go
  internal/util/debug/debug.go
  internal/util/debug/debug_test.go
  website/docs/configuration/flags.md
  website/docs/configuration/observability.md
  website/docs/quickstart-guide/docker.md
  website/static/humans.txt
  website/static/robots.txt
Labels: documentation

#4425 Stop Otel exporter gracefully in `envtool`
  cmd/envtool/tests.go
  integration/aggregate_documents_compat_test.go
  integration/aggregate_documents_test.go
  integration/aggregate_stats_compat_test.go
  integration/aggregate_stats_test.go
  integration/diff_08_names_test.go
  integration/setup/client.go
  integration/setup/startup.go
Labels: code/chore

#4420 Include `OpReply` error handling
  internal/clientconn/conn.go
Labels: code/chore

#4407 Test `authSource`
  integration/users/connection_test.go
Labels: code/chore

#4419 Return `connectionStatus` command `db` field
  integration/commands_authentication_test.go
  integration/integration.go
  integration/setup/setup.go
  integration/users/connection_test.go
  internal/backends/mysql/metadata/registry.go
  internal/backends/postgresql/metadata/registry.go
  internal/clientconn/conninfo/conn_info.go
  internal/handler/commands.go
  internal/handler/msg_connectionstatus.go
  internal/handler/msg_logout.go
  internal/handler/msg_saslcontinue.go
  internal/handler/msg_saslstart.go
  internal/handler/msg_saslstart_test.go
Labels: code/chore

#4381 Implement checkswitch to handle regular switches
  internal/bson/decode.go
  tools/checkswitch/checkswitch.go
  tools/checkswitch/testdata/testdata.go
Labels: code/chore

#4432 Add stub for named `slog` logger helper
  .golangci.yml
  internal/handler/msg_getlog.go
  internal/util/logging/buffer.go
  internal/util/logging/buffer_test.go
  internal/util/logging/handler_test.go
  internal/util/logging/logging.go
Labels: code/enhancement

#4279 Add blogpost on "monitoring FerretDB performance using Coroot"
  website/blog/2024-07-09-monitor-ferretdb-performance-using-coroot.md
  website/static/img/blog/ferretdb-coroot.jpg
  website/static/img/blog/ferretdb-coroot/client-connection.png
  website/static/img/blog/ferretdb-coroot/client-dashboard-1.png
  website/static/img/blog/ferretdb-coroot/client-dashboard-2.png
  website/static/img/blog/ferretdb-coroot/client-dashboard-3.png
  website/static/img/blog/ferretdb-coroot/continuous-profiling.png
  website/static/img/blog/ferretdb-coroot/distributed-tracing.png
  website/static/img/blog/ferretdb-coroot/grafana-prometheus.png
  website/static/img/blog/ferretdb-coroot/log-monitoring.png
  website/static/img/blog/ferretdb-coroot/log-warning.png
  website/static/img/blog/ferretdb-coroot/postgres-metrics-1.png
  website/static/img/blog/ferretdb-coroot/postgres-metrics-2.png
Labels: trust, blog/marketing

#4440 Ignore `$readPreferences` for `insert`
  internal/handler/common/insert.go
Labels: code/chore

#4426 Implement Kubernetes Readiness probe
  cmd/ferretdb/main.go
  cmd/ferretdb/ping.go
Labels: code/chore

#4436 Document logging
  .golangci.yml
  CONTRIBUTING.md
  Taskfile.yml
  cmd/ferretdb/main.go
  integration/Taskfile.yml
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/handler/msg_getlog.go
  internal/util/debug/debug.go
  internal/util/logging/buffer.go
  internal/util/logging/buffer_test.go
  internal/util/logging/console_handler.go
  internal/util/logging/zap.go
  internal/util/observability/observability.go
  website/docs/configuration/observability.md
Labels: documentation

#4451 Update linters configuration
  .golangci-new.yml
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/.golangci-new.yml
  integration/setup/startup.go
  internal/bson/types.go
  internal/handler/sjson/sjson.go
  internal/types/types.go
  internal/util/ctxutil/ctxutil.go
  internal/util/logging/logging.go
  internal/util/testutil/testtb/tb.go
Labels: code/chore

#4435 Add support for named `slog` loggers
  cmd/ferretdb/main.go
  internal/util/logging/handler_test.go
  internal/util/logging/logging.go
  internal/util/logging/zap.go
  internal/util/telemetry/reporter.go
  internal/util/telemetry/reporter_test.go
  internal/util/telemetry/telemetry.go
  internal/util/telemetry/telemetry_test.go
Labels: code/chore

#4454 Increase setup timeout in tests
  integration/setup/listener.go
  internal/handler/handler.go
  internal/handler/registry/hana.go
  internal/handler/registry/mysql.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/sqlite.go
  website/docs/quickstart-guide/docker.md
Labels: code/chore

#4450 Port pgx logger
  internal/util/logging/pgx.go
Labels: code/chore

#4449 Handle `authSource` in low level driver
  internal/driver/driver.go
  internal/driver/driver_test.go
  internal/wire/op_reply.go
Labels: code/chore

#4452 Use single definition of order for `checkswitch`
  internal/bson/decode.go
  tools/checkswitch/checkswitch.go
  tools/checkswitch/testdata/testdata.go
Labels: code/chore

#4455 Clarify the meaning of the passed context
  internal/clientconn/conn.go
  internal/handler/cmd_query.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_buildinfo.go
  internal/handler/msg_collmod.go
  internal/handler/msg_collstats.go
  internal/handler/msg_compact.go
  internal/handler/msg_connectionstatus.go
  internal/handler/msg_count.go
  internal/handler/msg_create.go
  internal/handler/msg_createindexes.go
  internal/handler/msg_createuser.go
  internal/handler/msg_currentop.go
  internal/handler/msg_datasize.go
  internal/handler/msg_dbstats.go
  internal/handler/msg_debugerror.go
  internal/handler/msg_delete.go
  internal/handler/msg_distinct.go
  internal/handler/msg_drop.go
  internal/handler/msg_dropallusersfromdatabase.go
  internal/handler/msg_dropdatabase.go
  internal/handler/msg_dropindexes.go
  internal/handler/msg_dropuser.go
  internal/handler/msg_explain.go
  internal/handler/msg_find.go
  internal/handler/msg_findandmodify.go
  internal/handler/msg_getcmdlineopts.go
  internal/handler/msg_getfreemonitoringstatus.go
  internal/handler/msg_getlog.go
  internal/handler/msg_getmore.go
  internal/handler/msg_getparameter.go
  internal/handler/msg_hello.go
  internal/handler/msg_hostinfo.go
  internal/handler/msg_insert.go
  internal/handler/msg_ismaster.go
  internal/handler/msg_killcursors.go
  internal/handler/msg_listcollections.go
  internal/handler/msg_listcommands.go
  internal/handler/msg_listdatabases.go
  internal/handler/msg_listindexes.go
  internal/handler/msg_logout.go
  internal/handler/msg_ping.go
  internal/handler/msg_renamecollection.go
  internal/handler/msg_saslcontinue.go
  internal/handler/msg_saslstart.go
  internal/handler/msg_serverstatus.go
  internal/handler/msg_setfreemonitoring.go
  internal/handler/msg_update.go
  internal/handler/msg_updateuser.go
  internal/handler/msg_usersinfo.go
  internal/handler/msg_validate.go
  internal/handler/msg_whatsmyuri.go
Labels: code/chore

#4457 Use `slog` in `clientconn` package
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/listener.go
  internal/clientconn/conn.go
  internal/clientconn/listener.go
Labels: code/chore

#4466 Use `slog` in `postgresql` backend
  cmd/envtool/envtool.go
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/listener.go
  internal/backends/helpers_test.go
  internal/backends/postgresql/backend.go
  internal/backends/postgresql/database_test.go
  internal/backends/postgresql/metadata/pool/opendb.go
  internal/backends/postgresql/metadata/pool/pool.go
  internal/backends/postgresql/metadata/registry.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/registry.go
Labels: code/chore

#4467 Use `slog` in `sqlite` backend
  internal/backends/helpers_test.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/collection_test.go
  internal/backends/sqlite/database_test.go
  internal/backends/sqlite/metadata/pool/opendb.go
  internal/backends/sqlite/metadata/pool/pool.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/backends/sqlite/sqlite_test.go
  internal/handler/registry/sqlite.go
Labels: code/chore

#4476 Remove `FuncCall`
  integration/setup/client.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/backends/backend.go
  internal/backends/collection.go
  internal/backends/database.go
  internal/backends/decorators/oplog/collection.go
  internal/backends/hana/query_iterator.go
  internal/backends/mysql/metadata/registry.go
  internal/backends/mysql/query_iterator.go
  internal/backends/postgresql/metadata/pool/transaction.go
  internal/backends/postgresql/metadata/registry.go
  internal/backends/postgresql/query_iterator.go
  internal/backends/sqlite/metadata/pool/pool.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/query_iterator.go
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/util/fsql/db.go
  internal/util/fsql/tx.go
  internal/util/observability/funccall.go
  internal/util/testutil/testutil.go
Labels: code/chore

#4463 Use `slog` in `mysql` and `hana` backends
  cmd/envtool/envtool.go
  internal/backends/hana/backend.go
  internal/backends/hana/database_test.go
  internal/backends/helpers_test.go
  internal/backends/mysql/backend.go
  internal/backends/mysql/metadata/pool/opendb.go
  internal/backends/mysql/metadata/pool/pool.go
  internal/backends/mysql/metadata/registry.go
  internal/backends/mysql/metadata/registry_test.go
  internal/handler/registry/hana.go
  internal/handler/registry/mysql.go
Labels: code/chore

#4471 Use `slog` in `oplog` and `cursor` packages
  internal/backends/decorators/oplog/backend.go
  internal/backends/decorators/oplog/collection.go
  internal/backends/decorators/oplog/database.go
  internal/clientconn/conn.go
  internal/clientconn/cursor/cursor.go
  internal/clientconn/cursor/cursor_test.go
  internal/clientconn/cursor/registry.go
  internal/handler/handler.go
Labels: code/chore

#4474 Use `slog` in `otel`
  cmd/envtool/tests.go
  cmd/ferretdb/main.go
  integration/setup/startup.go
  internal/util/observability/observability.go
Labels: code/chore

#4477 Add OTel spans
  cmd/envtool/tests.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/backends/backend.go
  internal/backends/collection.go
  internal/backends/database.go
  internal/clientconn/conn.go
  internal/handler/handler.go
Labels: code/feature

#4473 Use `slog` in `debug` package
  cmd/envtool/envtool.go
  cmd/ferretdb/main.go
  cmd/ferretdb/ping.go
  integration/setup/startup.go
  internal/util/debug/debug.go
  internal/util/debug/debug_test.go
Labels: code/chore

#4479 Implement `slog.LogValuer` interface for `types` package
  internal/types/array.go
  internal/types/binary.go
  internal/types/document.go
  internal/types/logging.go
  internal/types/logging_test.go
  internal/types/null.go
  internal/types/object_id.go
  internal/types/regex.go
  internal/types/timestamp.go
Labels: code/chore

#4481 Use `slog` in integration tests
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/setup/startup.go
  internal/util/logging/logging.go
  internal/util/logging/zap.go
  internal/util/testutil/logging.go
Labels: code/chore

#4462 Use `slog` in `main.go` and embedded `ferretdb` package
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/startup.go
  internal/util/logging/buffer.go
  internal/util/logging/buffer_test.go
  internal/util/logging/handler.go
  internal/util/logging/logging.go
  internal/util/logging/logging_test.go
  internal/util/logging/zap.go
Labels: code/chore

#4464 Use slog in `fsql`
  internal/backends/hana/backend.go
  internal/backends/mysql/metadata/pool/opendb.go
  internal/backends/sqlite/metadata/pool/opendb.go
  internal/util/fsql/db.go
  internal/util/fsql/tx.go
Labels: code/chore

#3895 Implement `/debug/archive` handler
  internal/util/debug/debug.go
  internal/util/debug/debug_test.go
Labels: code/chore, community

#4484 Enable and document OTLP configuration
  Taskfile.yml
  cmd/envtool/tests.go
  cmd/ferretdb/main.go
  integration/setup/startup.go
  internal/util/observability/observability.go
  website/docs/configuration/flags.md
  website/docs/configuration/observability.md
Labels: documentation, code/feature, trust

#4470 Use `slog` in handler
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/go.mod
  integration/setup/listener.go
  internal/handler/cmd_query.go
  internal/handler/commands.go
  internal/handler/common/count.go
  internal/handler/common/delete_params.go
  internal/handler/common/distinct.go
  internal/handler/common/explain.go
  internal/handler/common/find.go
  internal/handler/common/findandmodify.go
  internal/handler/common/insert.go
  internal/handler/common/unimplemented.go
  internal/handler/common/update_params.go
  internal/handler/handler.go
  internal/handler/handlerparams/extract_params.go
  internal/handler/handlerparams/extract_params_test.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_find.go
  internal/handler/msg_getlog.go
  internal/handler/msg_getmore.go
  internal/handler/msg_listdatabases.go
  internal/handler/msg_saslcontinue.go
  internal/handler/msg_saslstart.go
  internal/handler/registry/hana.go
  internal/handler/registry/mysql.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/registry.go
  internal/handler/registry/sqlite.go
Labels: code/chore

#4486 Drop old dependency
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/util/testutil/logging.go
Labels: code/chore

#4485 Refactor and document `/debug/archive` handler
  internal/util/debug/debug.go
  internal/util/debug/debug_test.go
  website/docs/configuration/observability.md
Labels: documentation, code/chore

#4478 Provide systemd unit file in `.deb` and `.rpm` packages
  build/ferretdb.service
  build/nfpm.yml
  website/docs/quickstart-guide/deb.md
  website/docs/quickstart-guide/go.md
  website/docs/quickstart-guide/macos.md
  website/docs/quickstart-guide/rpm.md
  website/docs/quickstart-guide/systemd.md
  website/docs/quickstart-guide/windows.md
  website/docusaurus.config.js
Labels: documentation, code/feature, trust

#4480 Use `slog` in envtool
  Taskfile.yml
  cmd/envtool/envtool.go
  cmd/envtool/envtool_test.go
  cmd/envtool/fuzz.go
  cmd/envtool/tests.go
  cmd/envtool/tests_test.go
  internal/util/logging/zap.go
Labels: code/chore

#4489 Cleanup logging
  .golangci.yml
  cmd/envtool/envtool_test.go
  cmd/envtool/tests_test.go
  ferretdb/ferretdb.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/backends/hana/database_test.go
  internal/backends/helpers_test.go
  internal/backends/mysql/metadata/registry_test.go
  internal/backends/postgresql/database_test.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/backends/sqlite/collection_test.go
  internal/backends/sqlite/database_test.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/backends/sqlite/sqlite_test.go
  internal/clientconn/cursor/cursor_test.go
  internal/clientconn/cursor/registry.go
  internal/driver/driver_test.go
  internal/handler/handlerparams/extract_params_test.go
  internal/util/debug/debug_test.go
  internal/util/logging/handler.go
  internal/util/logging/logging.go
  internal/util/logging/logging_test.go
  internal/util/telemetry/reporter_test.go
  internal/util/telemetry/telemetry_test.go
  internal/util/testutil/logging.go
  internal/util/testutil/postgresql.go
Labels: code/chore

#4492 Prepare v1.23.0 release
  .github/RELEASE_CHECKLIST.md
  CHANGELOG.md
  website/docusaurus.config.js
  website/versioned_docs/version-v1.20/configuration/observability.md
  website/versioned_docs/version-v1.23/aggregation-operations/_category_.yml
  website/versioned_docs/version-v1.23/aggregation-operations/aggregation-pipeline-and-commands.md
  website/versioned_docs/version-v1.23/aggregation-operations/aggregation-stages.md
  website/versioned_docs/version-v1.23/basic-operations/_category_.yml
  website/versioned_docs/version-v1.23/basic-operations/create.md
  website/versioned_docs/version-v1.23/basic-operations/delete.md
  website/versioned_docs/version-v1.23/basic-operations/performing.md
  website/versioned_docs/version-v1.23/basic-operations/read.md
  website/versioned_docs/version-v1.23/basic-operations/update.md
  website/versioned_docs/version-v1.23/configuration/_category_.yml
  website/versioned_docs/version-v1.23/configuration/flags.md
  website/versioned_docs/version-v1.23/configuration/observability.md
  website/versioned_docs/version-v1.23/configuration/operation-modes.md
  website/versioned_docs/version-v1.23/configuration/oplog-support.md
  website/versioned_docs/version-v1.23/contributing/_category_.yml
  website/versioned_docs/version-v1.23/contributing/how-to-contribute.md
  website/versioned_docs/version-v1.23/contributing/writing-guide.md
  website/versioned_docs/version-v1.23/diff.md
  website/versioned_docs/version-v1.23/indexes.md
  website/versioned_docs/version-v1.23/main.md
  website/versioned_docs/version-v1.23/migration/_category_.yml
  website/versioned_docs/version-v1.23/migration/migrating-from-mongodb.md
  website/versioned_docs/version-v1.23/migration/premigration-testing.md
  website/versioned_docs/version-v1.23/operators/_category_.yml
  website/versioned_docs/version-v1.23/operators/query/_category_.yml
  website/versioned_docs/version-v1.23/operators/query/array-operators.md
  website/versioned_docs/version-v1.23/operators/query/bitwise-operators.md
  website/versioned_docs/version-v1.23/operators/query/comparison-operators.md
  website/versioned_docs/version-v1.23/operators/query/element-operators.md
  website/versioned_docs/version-v1.23/operators/query/evaluation-operators.md
  website/versioned_docs/version-v1.23/operators/query/logical-operators.md
  website/versioned_docs/version-v1.23/operators/update/_category_.yml
  website/versioned_docs/version-v1.23/operators/update/array-update-operators.md
  website/versioned_docs/version-v1.23/operators/update/field-update-operators.md
  website/versioned_docs/version-v1.23/pushdown.md
  website/versioned_docs/version-v1.23/quickstart-guide/_category_.yml
  website/versioned_docs/version-v1.23/quickstart-guide/deb.md
  website/versioned_docs/version-v1.23/quickstart-guide/docker.md
  website/versioned_docs/version-v1.23/quickstart-guide/go.md
  website/versioned_docs/version-v1.23/quickstart-guide/macos.md
  website/versioned_docs/version-v1.23/quickstart-guide/rpm.md
  website/versioned_docs/version-v1.23/quickstart-guide/systemd.md
  website/versioned_docs/version-v1.23/quickstart-guide/windows.md
  website/versioned_docs/version-v1.23/reference/_category_.yml
  website/versioned_docs/version-v1.23/reference/glossary.md
  website/versioned_docs/version-v1.23/reference/supported-commands.md
  website/versioned_docs/version-v1.23/security/_category_.yml
  website/versioned_docs/version-v1.23/security/authentication.md
  website/versioned_docs/version-v1.23/security/tls-connections.md
  website/versioned_docs/version-v1.23/telemetry.md
  website/versioned_docs/version-v1.23/understanding-ferretdb.md
  website/versioned_sidebars/version-v1.23-sidebars.json
  website/versions.json
Labels: documentation, trust, do not merge

#4491 Alignment and Bugfixes for SAP HANA backend
  internal/backends/hana/backend.go
  internal/backends/hana/collection.go
  internal/backends/hana/database.go
  internal/backends/hana/hana.go
  internal/backends/hana/query.go
  internal/backends/hana/query_test.go
  internal/backends/hana/sjson_wrapper.go
Labels: code/chore, trust

#4496 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#4495 Port small things from v2
  .golangci.yml
  cmd/envtool/fuzz.go
  cmd/envtool/testdata/subtest_test.go
  cmd/envtool/tests.go
  cmd/envtool/tests_test.go
  integration/commands_administration_test.go
  integration/setup/client.go
  integration/setup/startup.go
  internal/handler/msg_listcommands.go
Labels: code/chore

#4497 Remove `zap` remnants
  ferretdb/ferretdb.go
  ferretdb/ferretdb_test.go
  go.mod
  go.sum
  internal/util/logging/handler.go
Labels: code/chore

#4498 Add blog post for FerretDB v1.23 release
  CHANGELOG.md
  website/blog/2023-05-09-ferretdb-v-1-1-0-released.md
  website/blog/2023-05-22-ferretdb-v-1-2-0-minor-release.md
  website/blog/2023-06-05-ferretdb-v-1-3-0-new-release.md
  website/blog/2023-06-19-ferretdb-v-1-4-0-new-release.md
  website/blog/2023-07-04-ferretdb-v-1-5-0-beta-support-sqlite.md
  website/blog/2023-07-17-ferretdb-v-1-6-0.md
  website/blog/2023-08-14-ferretdb-new-release-v180.md
  website/blog/2023-08-29-new-ferretdb-release-v190.md
  website/blog/2023-09-26-ferretdb-releases-v1110.md
  website/blog/2023-10-11-ferretdb-v112-available.md
  website/blog/2023-10-24-ferretdb-v1130-new-postgresql-backend.md
  website/blog/2023-11-07-ferretdb-releases-v1140.md
  website/blog/2023-11-20-ferretdb-releases-v1150.md
  website/blog/2023-12-05-new-ferretdb-release-v116.md
  website/blog/2023-12-19-ferretdb-releases-v117.md
  website/blog/2024-01-08-new-ferretdb-v118-support-oplog-functionality.md
  website/blog/2024-07-26-ferretdb-releases-v123-improved-observability.md
  website/static/img/blog/ferretdb-v1.23.0.jpg
  website/static/img/blog/otel-tracing.png
Labels: trust, blog/marketing

#4499 Update `listDatabases` integration test filter input
  integration/commands_administration_test.go
Labels: code/chore

#4506 Fix Terser plugin build error
  build/deps/docusaurus-docs.Dockerfile
  website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.mdx
  website/static/blog/2022-11-14/delete-1.tpl
  website/static/blog/2022-11-14/delete-2.tpl
  website/static/blog/2022-11-14/insert-1.tpl
  website/static/blog/2022-11-14/insert-2.tpl
  website/static/blog/2022-11-14/update-1.tpl
  website/static/blog/2022-11-14/update-2.tpl
  website/static/blog/2022-11-14/update-3.tpl
Labels: documentation, trust

#4509 Fix `checkdocs` Github cache on CI
  .github/workflows/docs.yml
  Taskfile.yml
Labels: code/chore

#4508 Enable zoom on images
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
Labels: documentation, trust, blog/marketing
