Repository FerretDB/FerretDB, pull requests merged in 2024-02, with the labels that each got.

#4029 Expose new authentication enabling flag
  cmd/ferretdb/main.go
Labels: code/chore

#4030 Bump deps and speed-up `checkcomments`
  .github/workflows/security.yml
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-prettier.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/legacy-mongo-shell.Dockerfile
  build/deps/mongo.Dockerfile
  build/deps/mysql.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  integration/indexes_compat_test.go
  integration/users/connection_test.go
  internal/backends/postgresql/collection.go
  internal/handler/common/aggregations/stages/unwind.go
  internal/handler/msg_createuser.go
  internal/handler/msg_dropuser.go
  internal/handler/msg_getmore.go
  internal/handler/msg_updateuser.go
  internal/handler/msg_usersinfo.go
  tools/checkcomments/checkcomments.go
  tools/checkcomments/checkcomments_test.go
  tools/checkcomments/client.go
  tools/go.mod
  tools/go.sum
Labels: deps, code/chore

#3999 Display `envtool run test` progress with run and/or skip flags
  cmd/envtool/tests.go
  cmd/envtool/tests_test.go
Labels: code/chore

#4027 Use Ubicloud for CI runners
  .github/workflows/_integration.yml
  internal/handler/common/find.go
  website/docs/reference/supported-commands.md
Labels: code/chore

#4047 Truncate release blog post
  website/blog/2024-01-30-new-ferretdb-v119-release.md
Labels: blog/marketing

#4034 Implement `database.Stats` for MySQL backend
  internal/backends/mysql/database.go
  internal/backends/mysql/mysql.go
Labels: code/chore

#4046 Minor cleanups
  .github/workflows/_integration.yml
  .github/workflows/go.yml
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  docker-compose.yml
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  integration/indexes_compat_test.go
  integration/query_test.go
  integration/setup/helpers.go
  internal/bson2/document.go
  internal/clientconn/conn.go
  internal/util/must/must.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: code/chore

#4049 Add experimental pushdown for dot notation
  cmd/ferretdb/main.go
  internal/backends/postgresql/query.go
  internal/backends/postgresql/query_test.go
  internal/handler/handler.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_explain.go
  internal/handler/msg_find.go
  internal/handler/registry/mysql.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/registry.go
  internal/handler/registry/sqlite.go
Labels: code/chore

#4038 Add blog post on Disaster Recovery for FerretDB with Elotl Nova
  website/blog/2024-02-12-guide-disaster-recovery-ferretdb-elotl-nova-kubernetes.md
  website/static/img/blog/ferretdb-elotl-nova.jpg
  website/static/img/blog/ferretdb-nova/ferretdb-before-recovery-without-nova.png
  website/static/img/blog/ferretdb-nova/ferretdb-before-recovery.png
  website/static/img/blog/ferretdb-nova/ferretdb-recovery.png
  website/static/img/blog/maciek-urbanski.jpg
Labels: trust, blog/marketing

#4039 Update Codapi
  website/static/codapi/snippet.js
Labels: trust, blog/marketing

#4059 Bump Go to 1.21.7
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
Labels: deps

#4031 Add utility for hashing SCRAM-SHA-256 password
  go.mod
  internal/util/password/scramsha256.go
  internal/util/password/scramsha256_test.go
Labels: code/feature

#4004 Use rootless `scratch` containers for production Docker images
  CHANGELOG.md
  build/docker/group
  build/docker/passwd
  build/docker/production.Dockerfile
Labels: code/chore, trust, packages

#4037 Add blogpost on FerretDB stack on Tembo
  website/blog/2024-02-13-run-mongodb-workloads-ferretdb-tembo.md
  website/static/img/blog/ferretdb-tembo-connection.png
  website/static/img/blog/ferretdb-tembo-stack.png
  website/static/img/blog/ferretdb-tembo.jpg
Labels: trust, blog/marketing

#4076 Implement `bson2.RawDocument` checking
  internal/bson2/bson2.go
  internal/bson2/decodemode_string.go
  internal/bson2/document_test.go
  internal/bson2/raw_array.go
  internal/bson2/raw_document.go
Labels: code/chore

#4080 Add helper for decoding document sequences
  internal/bson2/bson2.go
  internal/bson2/document.go
  internal/bson2/document_test.go
  internal/bson2/raw_array.go
  internal/bson2/raw_document.go
  internal/bson2/slog.go
Labels: code/chore

#3989 Add SCRAM-SHA-256 authentication support
  integration/users/connection_test.go
  integration/users/create_user_test.go
  integration/users/update_user_test.go
  internal/backends/mysql/metadata/registry.go
  internal/backends/postgresql/metadata/registry.go
  internal/clientconn/conninfo/conn_info.go
  internal/handler/cmd_query.go
  internal/handler/commands.go
  internal/handler/handler.go
  internal/handler/handlererrors/error.go
  internal/handler/handlererrors/errorcode_string.go
  internal/handler/msg_createuser.go
  internal/handler/msg_saslcontinue.go
  internal/handler/msg_saslstart.go
  internal/handler/msg_saslstart_plain_test.go
  internal/handler/msg_updateuser.go
  internal/handler/msg_usersinfo.go
  internal/util/password/scramsha256.go
  internal/util/password/scramsha256_test.go
Labels: code/feature

#4086 Remove SCRAM-SHA-256 implementation TODO links
  internal/handler/msg_createuser.go
  internal/handler/msg_usersinfo.go
Labels: code/chore

#4085 Update telemetry host
  .github/RELEASE_CHECKLIST.md
  cmd/ferretdb/main.go
  internal/handler/msg_getlog.go
  internal/util/telemetry/reporter.go
  website/docs/telemetry.md
Labels: code/chore

#4078 Add SCRAM-SHA-1 authentication support
  integration/users/connection_test.go
  integration/users/create_user_test.go
  integration/users/usersinfo_test.go
  internal/handler/msg_createuser.go
  internal/handler/msg_saslcontinue.go
  internal/handler/msg_saslstart.go
  internal/handler/msg_updateuser.go
  internal/util/password/scram.go
  internal/util/password/scramsha1.go
  internal/util/password/scramsha1_test.go
  internal/util/password/scramsha256.go
  internal/util/password/scramsha256_test.go
Labels: code/feature

#4094 Use Go 1.22 and bump deps
  .golangci-new.yml
  CONTRIBUTING.md
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/postgres.Dockerfile
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  go.mod
  go.sum
  integration/.golangci-new.yml
  integration/go.mod
  integration/go.sum
  internal/backends/backend_test.go
  tools/check.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
  tools/old.go
  tools/tools.go
Labels: deps

#4096 Add more fields to requests and responses
  internal/handler/common/delete_params.go
  internal/handler/common/find.go
  internal/handler/common/findandmodify.go
  internal/handler/common/insert.go
  internal/handler/common/ismaster.go
  internal/handler/common/update_params.go
  internal/wire/op_msg.go
Labels: code/chore

#4069 Reorganize and fix `update`/`upsert` logic
  integration/findandmodify_compat_test.go
  integration/findandmodify_test.go
  integration/integration.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
  integration/update_field_test.go
  internal/handler/common/filter.go
  internal/handler/common/update.go
  internal/handler/common/update_params.go
  internal/handler/handlererrors/error.go
  internal/handler/handlererrors/errorcode_string.go
  internal/handler/msg_findandmodify.go
  internal/handler/msg_update.go
Labels: code/chore, community

#4106 Revert SQLite version bump
  integration/go.mod
  integration/go.sum
Labels: deps

#4077 Fix Codapi file error
  website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.mdx
  website/docusaurus.config-blog.js
  website/static/codapi/init.js
Labels: trust, blog/marketing

#4108 Use `bson2` package for wire queries and replies
  internal/handler/cmd_query.go
  internal/handler/common/ismaster.go
  internal/handler/sjson/sjson_test.go
  internal/wire/msg_body.go
  internal/wire/op_msg.go
  internal/wire/op_msg_test.go
  internal/wire/op_query.go
  internal/wire/op_query_test.go
  internal/wire/op_reply.go
  internal/wire/op_reply_test.go
  internal/wire/wire_test.go
Labels: code/chore

#4028 Make logger configurable in the embedded `ferretdb` package
  ferretdb/ferretdb.go
  internal/bson2/slog.go
  internal/util/logging/logging.go
Labels: code/chore

#4116 Update correct image link
  website/blog/2024-02-20-postgresql-can-it-be-a-database-for-everything.md
Labels: blog/marketing

#4101 Fix `envtool run test` `-run` and `-skip` flags
  cmd/envtool/testdata/subtest_test.go
  cmd/envtool/tests.go
  cmd/envtool/tests_test.go
Labels: code/chore

#4083 Add MySQL backend collection
  internal/backends/mysql/collection.go
  internal/backends/mysql/helpers.go
  internal/backends/mysql/insert.go
  internal/backends/mysql/mysql.go
  internal/backends/mysql/query_iterator.go
  internal/backends/postgresql/query_iterator.go
Labels: code/chore

#4121 Add ignoring maxTimeMS argument in count, insert, update, delete
  internal/handler/common/count.go
  internal/handler/common/delete_params.go
  internal/handler/common/insert.go
Labels: code/bug

#4102 Add Pulumi blog post
  website/blog/2024-02-26-run-deploy-ferretdb-kubernetes-using-pulumi.md
  website/static/img/blog/ferretdb-pulumi.jpg
Labels: trust, blog/marketing

#4126 Use correct salt length
  cmd/envtool/tests_test.go
  internal/util/password/scramsha1.go
  internal/util/password/scramsha1_test.go
  internal/util/password/scramsha256.go
  internal/util/password/scramsha256_test.go
Labels: code/chore

#4131 Skip stuck tailable cursor test
  integration/cursors/awaitdata_test.go
Labels: code/chore

#4075 Enforce new authentication
  integration/setup/setup.go
  integration/users/connection_test.go
  internal/backends/postgresql/metadata/registry.go
  internal/clientconn/conninfo/conn_info.go
  internal/handler/authenticate.go
  internal/handler/commands.go
  internal/handler/msg_createuser.go
  internal/handler/msg_saslstart.go
Labels: code/chore

#4110 Replace `bson` with `bson2` in `wire`
  .github/settings.yml
  .golangci.yml
  Taskfile.yml
  internal/backends/decorators/dummy/dummy_test.go
  internal/backends/decorators/oplog/oplog_test.go
  internal/backends/hana/dummy_test.go
  internal/backends/postgresql/dummy_test.go
  internal/backends/postgresql/metadata/pool/dummy_test.go
  internal/bson2/bson2.go
  internal/bson2/bson2_test.go
  internal/bson2/decode.go
  internal/bson2/document.go
  internal/bson2/encode.go
  internal/bson2/raw_document.go
  internal/clientconn/clientconn_test.go
  internal/handler/handler_test.go
  internal/handler/handlererrors/error.go
  internal/handler/proxy/proxy_test.go
  internal/util/debug/debug_test.go
  internal/util/debugbuild/debugbuild_test.go
  internal/util/fsql/fsql_test.go
  internal/util/iterator/testiterator/testiterator_test.go
  internal/util/must/must_test.go
  internal/util/observability/observability_test.go
  internal/util/resource/resource_test.go
  internal/util/testutil/teststress/stress_test.go
  internal/util/testutil/testtb/tb_test.go
  internal/wire/msg_body.go
  internal/wire/op_msg.go
  internal/wire/op_msg_test.go
  internal/wire/op_query.go
  internal/wire/op_query_test.go
  internal/wire/op_reply.go
  internal/wire/op_reply_test.go
  internal/wire/wire_test.go
Labels: code/chore

#4135 Improve `OP_MSG` validity checks
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  integration/shareddata/faker.go
  internal/util/testutil/logging.go
  internal/util/testutil/testutil.go
  internal/wire/msg_body.go
  internal/wire/op_msg.go
Labels: code/chore
