Repository FerretDB/FerretDB, pull requests merged in 2024-03, with the labels that each got.

#4111 Support speculative authenticate
  internal/handler/cmd_query.go
  internal/handler/msg_saslstart.go
Labels: code/chore

#4137 Add MySQL backend
  internal/backends/mysql/backend.go
  internal/backends/mysql/collection.go
  internal/backends/mysql/insert.go
  internal/util/fsql/db.go
Labels: code/chore

#4129 Fix `saslContinue` crashing due to not found authentication conversation
  integration/users/connection_test.go
  internal/handler/msg_saslcontinue.go
  internal/handler/msg_saslstart.go
Labels: code/bug

#4143 Cleanup TODO for speculative authenticate
  internal/handler/msg_createuser.go
  internal/handler/msg_usersinfo.go
  website/docs/reference/supported-commands.md
Labels: code/chore

#4145 Fix MySQL collection stats
  internal/backends/mysql/collection.go
Labels: code/chore

#4155 Use Go 1.22.1
  build/docker/all-in-one.Dockerfile
  build/docker/development.Dockerfile
  build/docker/production.Dockerfile
  go.mod
  integration/go.mod
  tools/check.go
  tools/go.mod
  tools/golangci/go.mod
  tools/old.go
  tools/tools.go
Labels: deps, trust, packages

#4113 Advertise SCRAM / SASL support in addition to PLAIN
  integration/commands_administration_test.go
  integration/create_test.go
  integration/hello_command_test.go
  integration/query_test.go
  integration/setup/helpers.go
  integration/users/usersinfo_test.go
  internal/handler/handlerparams/typecode_test.go
  internal/handler/msg_getparameter.go
  internal/handler/msg_hello.go
  internal/handler/msg_usersinfo.go
  website/docs/reference/supported-commands.md
Labels: code/feature

#4139 Add linter to check truncate tag in blog posts
  tools/checkdocs/checkdocs.go
  tools/checkdocs/checkdocs_test.go
  website/blog/2024-01-08-new-ferretdb-v118-support-oplog-functionality.md
Labels: code/chore

#4163 Fix PLAIN mechanism authentication incorrectly working
  integration/users/connection_test.go
  internal/backends/mysql/metadata/registry.go
  internal/backends/postgresql/metadata/registry.go
  internal/clientconn/conninfo/conn_info.go
  internal/handler/authenticate.go
  internal/handler/msg_logout.go
  internal/handler/msg_saslstart.go
Labels: code/chore

#4167 Fix logging of deeply nested documents
  go.mod
  integration/basic_test.go
  integration/benchmarks_test.go
  integration/go.mod
  integration/integration.go
  integration/nested_document_test.go
  internal/bson/bson_test.go
  internal/bson2/array.go
  internal/bson2/bson2_test.go
  internal/bson2/document.go
  internal/bson2/logging.go
  internal/bson2/logging_test.go
  internal/bson2/raw_array.go
  internal/bson2/raw_document.go
  internal/bson2/testdata/nested.hex
  internal/handler/sjson/sjson_test.go
  internal/util/lazyerrors/lazyerrors_test.go
  internal/util/password/plain_test.go
  internal/util/password/scramsha1_test.go
  internal/util/password/scramsha256_test.go
  internal/wire/op_msg.go
  internal/wire/op_msg_test.go
  internal/wire/wire_test.go
  tools/checkcomments/checkcomments.go
  tools/checkcomments/checkcomments_test.go
  tools/checkcomments/client.go
  tools/go.mod
  tools/golangci/go.mod
Labels: code/chore

#4156 Support localhost exception
  CONTRIBUTING.md
  ferretdb/ferretdb.go
  integration/commands_authentication_test.go
  integration/commands_diagnostic_test.go
  integration/hello_command_test.go
  integration/setup/setup.go
  integration/users/connection_test.go
  integration/users/create_user_test.go
  integration/users/drop_all_users_from_database_test.go
  integration/users/drop_user_test.go
  integration/users/update_user_test.go
  integration/users/usersinfo_test.go
  internal/clientconn/conn.go
  internal/clientconn/conninfo/conn_info.go
  internal/clientconn/conninfo/conn_info_test.go
  internal/handler/authenticate.go
  internal/handler/commands.go
  internal/handler/msg_whatsmyuri.go
  website/blog/2022-11-21-ferretdb-0-6-2-version-release.md
Labels: code/chore

#4170 Do not use the flow style in the diff output
  internal/bson2/array.go
  internal/bson2/document.go
  internal/bson2/logging.go
  internal/bson2/logging_test.go
  internal/bson2/raw_array.go
  internal/bson2/raw_document.go
  internal/clientconn/conn.go
  internal/wire/msg_body.go
  internal/wire/op_msg.go
  internal/wire/op_query.go
  internal/wire/op_reply.go
  internal/wire/wire_test.go
  website/docs/configuration/operation-modes.md
  website/docs/migration/premigration-testing.md
Labels: documentation, code/chore, trust

#4172 Remove some closed issues from documentation
  website/docs/reference/supported-commands.md
Labels: documentation, trust

#4175 Do not use `fjson`
  .golangci.yml
  integration/users/connection_test.go
  internal/bson/bson.go
  internal/bson/bson_test.go
  internal/bson2/array.go
  internal/bson2/bson2.go
  internal/bson2/bson2_test.go
  internal/bson2/document.go
  internal/bson2/logging.go
  internal/bson2/logging_test.go
  internal/bson2/raw_array.go
  internal/bson2/raw_document.go
  internal/util/testutil/dump.go
  internal/util/testutil/equal.go
  internal/util/testutil/hexdump.go
  internal/wire/op_msg.go
  internal/wire/op_query.go
  internal/wire/op_reply.go
  internal/wire/wire_test.go
Labels: code/chore

#4178 Fix `speculativeAuthenticate` panic on empty database
  internal/handler/cmd_query.go
Labels: code/chore

#4180 Move Docker build files
  .dockerignore
  .github/dependabot.yml
  Taskfile.yml
  build/buildkitd.toml
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/all-in-one/entrypoint.sh
  build/ferretdb/all-in-one/ferretdb.sh
  build/ferretdb/all-in-one/postgresql.sh
  build/ferretdb/development.Dockerfile
  build/ferretdb/group
  build/ferretdb/passwd
  build/ferretdb/production.Dockerfile
Labels: code/chore, trust, packages

#4187 Bump protobuf dependency to make CI happy
  .gitignore
  Taskfile.yml
  build/trivy-ignore.yml.example
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: deps

#4160 Use authentication enabled docker for integration test
  Taskfile.yml
  integration/cursors/getmore_test.go
  integration/cursors/tailable_sessions_test.go
  integration/distinct_test.go
  integration/query_test.go
  integration/setup/client.go
  integration/setup/setup.go
  integration/users/connection_test.go
  internal/handler/common/find.go
Labels: code/chore

#4190 Bump `pgx`
  Taskfile.yml
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#4118 Improve capped collection cleanup
  integration/commands_administration_test.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  internal/handler/handler.go
Labels: code/enhancement, community

#4149 Make batch sizes configurable
  cmd/ferretdb/main.go
  integration/setup/listener.go
  integration/setup/setup.go
  internal/backends/hana/backend.go
  internal/backends/helpers_test.go
  internal/backends/postgresql/backend.go
  internal/backends/postgresql/collection.go
  internal/backends/postgresql/database_test.go
  internal/backends/postgresql/metadata/registry.go
  internal/backends/postgresql/metadata/registry_test.go
  internal/backends/sqlite/backend.go
  internal/backends/sqlite/collection.go
  internal/backends/sqlite/collection_test.go
  internal/backends/sqlite/database_test.go
  internal/backends/sqlite/metadata/registry.go
  internal/backends/sqlite/metadata/registry_test.go
  internal/backends/sqlite/sqlite_test.go
  internal/handler/handler.go
  internal/handler/msg_insert.go
  internal/handler/registry/hana.go
  internal/handler/registry/mysql.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/registry.go
  internal/handler/registry/sqlite.go
  internal/util/fsql/db.go
Labels: code/enhancement, community

#4202 Add blog post for FerretDB v1.21 release
  website/blog/2024-03-21-new-ferretdb-v121-release.md
  website/static/img/blog/ferretdb-v1.21.0.jpg
Labels: blog/marketing

#4201 Bump deps
  .github/workflows/debug.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/go-trusted.yml
  .github/workflows/go.yml
  .github/workflows/js.yml
  .github/workflows/packages.yml
  .github/workflows/security.yml
  build/deps/docusaurus-docs.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/legacy-mongo-shell.Dockerfile
  build/deps/mongo.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: deps

#4194 Add blog post for Openziti
  website/blog/2024-03-22-run-ferretdb-securely-using-openziti.md
  website/static/img/blog/ferretdb-openziti.jpg
Labels: trust, blog/marketing

#4193 Make our own low-level driver for testing
  .golangci.yml
  internal/driver/driver.go
  internal/driver/driver_test.go
Labels: code/chore

#4211 Use non-privileged `scratch` for production Docker images
  build/ferretdb/production.Dockerfile
Labels: code/chore, trust, packages

#4218 Fix TCP port for debug handler in Docker images
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
  website/docs/configuration/observability.md
  website/versioned_docs/version-v1.21/configuration/observability.md
Labels: code/chore, trust, packages
