Repository FerretDB/FerretDB, pull requests merged in 2024-08, with the labels that each got.

#4503 Fix log message
  internal/clientconn/conn.go
  internal/clientconn/listener.go
Labels: code/chore

#4502 Use `wireclient` package
  integration/go.mod
  integration/go.sum
  integration/setup/client.go
  integration/setup/conn.go
  integration/setup/setup.go
  internal/driver/driver.go
  internal/driver/driver_test.go
Labels: code/chore

#4510 Document logging changes
  .github/workflows/cleanup.yml
  .github/workflows/debug.yml
  .github/workflows/go.yml
  .github/workflows/packages.yml
  .golangci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  ferretdb/ferretdb_test.go
  internal/types/logging_test.go
  internal/util/logging/buffer_test.go
  internal/util/logging/handler.go
  internal/util/logging/handler_test.go
Labels: code/chore

#4483 Prototype OTel context propagation
  integration/basic_test.go
  integration/setup/listener.go
  internal/clientconn/conn.go
  internal/util/observability/propagation.go
  internal/util/observability/propagation_test.go
Labels: code/chore

#4501 Convert BSON values of `wirebson` to `types`
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/bson/types.go
  internal/handler/wire.go
Labels: code/chore

#4518 Fix CI for documentation preview
  .github/workflows/website-preview.yml
Labels: code/chore

#4517 Add blog post on building a RESTful API with Deno
  website/blog/2024-08-07-build-restful-api-deno-oak-ferretdb.md
  website/static/img/blog/ferretdb-deno.jpg
  website/static/img/blog/ferretdb-deno/delete-record.png
  website/static/img/blog/ferretdb-deno/deno-connection.png
  website/static/img/blog/ferretdb-deno/get-records.png
  website/static/img/blog/ferretdb-deno/insert-record.png
  website/static/img/blog/ferretdb-deno/update-record.png
Labels: trust, blog/marketing

#4519 Add `Taskfile` target to `pngcrush` all new images
  Taskfile.yml
  tools/github/client.go
Labels: code/chore

#4522 Update missing image
  website/blog/2024-07-26-ferretdb-releases-v123-improved-observability.md
Labels: trust, blog/marketing

#4523 Use Go 1.22.6
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
  go.mod
  integration/go.mod
  tools/go.mod
  tools/golangci/go.mod
  website/go.mod
Labels: deps, trust, packages

#4525 Fix broken links
  website/docs/quickstart-guide/deb.md
  website/docs/quickstart-guide/rpm.md
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
  website/versioned_docs/version-v1.23/quickstart-guide/deb.md
  website/versioned_docs/version-v1.23/quickstart-guide/rpm.md
Labels: documentation, trust

#4535 Minor cleanup
  internal/bson/bson.go
  internal/bson/types.go
  internal/clientconn/conn.go
  internal/handler/cmd_query.go
  internal/handler/msg_getlog.go
  internal/handler/users/createuser.go
  internal/handler/wire.go
  internal/util/testutil/dump.go
Labels: code/chore

#4536 Fix critical typo in telemetry documentation
  website/docs/telemetry.md
  website/versioned_docs/version-v1.21/telemetry.md
  website/versioned_docs/version-v1.22/telemetry.md
  website/versioned_docs/version-v1.23/telemetry.md
Labels: documentation

#4537 Ignore Stable API fields
  internal/handler/common/count.go
  internal/handler/common/delete_params.go
  internal/handler/common/distinct.go
  internal/handler/common/explain.go
  internal/handler/common/find.go
  internal/handler/common/findandmodify.go
  internal/handler/common/insert.go
  internal/handler/common/update_params.go
Labels: code/bug, trust, packages

#4067 Ignore apiVersion field from StableAPI
  internal/handler/common/count.go
  internal/handler/common/delete_params.go
  internal/handler/common/distinct.go
  internal/handler/common/explain.go
  internal/handler/common/find.go
  internal/handler/common/findandmodify.go
  internal/handler/common/insert.go
  internal/handler/common/update_params.go
Labels: community

#4544 Bump Docusaurus
  build/deps/docusaurus-docs.Dockerfile
Labels: documentation, trust, blog/marketing

#4547 Fix Docker's `HEALTHCHECK` in production image
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
Labels: code/bug, packages

#4546 Added Elestio as one-click deploy option
  README.md
Labels: documentation

#4549 Fix duplicate field on `hello` op query
  internal/handler/cmd_query.go
Labels: code/bug

#4548 Remove `wireconn` tests for now
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
  integration/go.mod
  integration/setup/conn.go
  integration/setup/setup.go
Labels: code/chore

#4550 Support `saslStart` and `saslContinue` OpQuery
  internal/handler/cmd_query.go
  internal/handler/handlererrors/error.go
  internal/handler/handlererrors/errorcode_string.go
  internal/handler/msg_saslcontinue.go
Labels: code/chore

#4552 Fix `saslContinue` completing handshake too early
  internal/handler/commands.go
  internal/handler/handlererrors/error.go
  internal/handler/handlererrors/errorcode_string.go
  internal/handler/msg_saslcontinue.go
Labels: code/chore

#4558 Pass `GITHUB_TOKEN` to tools tests
  .github/workflows/go.yml
  CONTRIBUTING.md
  Taskfile.yml
  tools/Taskfile.yml
  tools/checkcomments/checkcomments_test.go
  tools/checkdocs/checkdocs.go
  tools/checkdocs/checkdocs_test.go
  tools/cleantool/cleantool.go
  tools/github/client.go
  tools/github/client_test.go
  tools/go.mod
Labels: code/chore

#4557 Add docs for new authentication
  website/docs/configuration/flags.md
  website/docs/quickstart-guide/docker.md
  website/docs/security/authentication.md
Labels: documentation, trust

#4219 Implement our own changelog generator
  .github/RELEASE_CHECKLIST.md
  Taskfile.yml
  internal/backends/sqlite/backend.go
  internal/handler/msg_saslstart.go
  tools/Taskfile.yml
  tools/generatechangelog/generatechangelog.go
  tools/generatechangelog/generatechangelog_test.go
  tools/generatechangelog/test_template.yml
  tools/go.mod
  tools/tools.go
Labels: code/chore, community

#4562 Add blog post for v1.24
  website/blog/2024-08-28-ferretdb-releases-v124-sqlite-authentication-support.md
  website/static/img/blog/ferretdb-v1.24.0.jpg
Labels: trust, blog/marketing

#4563 Add Cozystack to README
  README.md
Labels: documentation

#4564 Bump deps
  build/deps/jaeger.Dockerfile
  build/deps/postgres.Dockerfile
  build/deps/trivy.Dockerfile
  build/ferretdb/all-in-one.Dockerfile
  cmd/ferretdb/main.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  integration/query_comparison_compat_test.go
  internal/backends/backend_test.go
  internal/bson/bson.go
  internal/handler/msg_saslcontinue.go
  internal/handler/msg_saslstart.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: deps
