Repository FerretDB/FerretDB, pull requests merged in 2024-10, with the labels that each got.

#4599 Bump Go version
  .github/workflows/packages.yml
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
  go.mod
  integration/go.mod
  tools/definedockertag/main.go
  tools/definedockertag/main_test.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/tools.go
  website/go.mod
Labels: code/chore, trust, packages

#4598 Fix stats for MySQL backend
  internal/backends/mysql/mysql.go
Labels: code/bug

#4602 Port tools from v2
  tools/Taskfile.yml
  tools/github/client.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
  tools/tools.go
Labels: code/chore

#4607 Add separate CI job for defining Docker tags
  .github/workflows/cleanup.yml
  .github/workflows/packages.yml
Labels: trust

#4603 Update `definedockertag` logic and use it
  .github/workflows/cleanup.yml
  .github/workflows/packages.yml
  tools/definedockertag/main.go
  tools/definedockertag/main_test.go
Labels: code/chore

#4608 Update handling of all-in-one Docker images
  tools/definedockertag/main.go
  tools/definedockertag/main_test.go
Labels: code/chore, trust, packages
