Repository FerretDB/FerretDB, pull requests merged in 2024-04, with the labels that each got.

#4238 Bump deps
  .github/workflows/docs.yml
  .golangci-new.yml
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-prettier.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/legacy-mongo-shell.Dockerfile
  build/deps/mongo.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/.golangci-new.yml
  integration/go.mod
  integration/go.sum
  internal/handler/common/aggregations/stages/projection/projection.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: deps

#4237 Fix some comments
  internal/bson/raw_document.go
  internal/driver/driver.go
  internal/util/iterator/func.go
Labels: code/chore

#4247 Add dummy setup flags
  cmd/ferretdb/main.go
Labels: code/chore

#4257 Fix some comments
  integration/count_command_compat_test.go
  integration/query_command_compat_test.go
  integration/update_compat_test.go
  internal/backends/mysql/mysql.go
  internal/handler/common/aggregations/operators/expr.go
  internal/handler/common/aggregations/stages/group.go
  internal/handler/handler.go
Labels: code/chore

#4251 Improve error message for `state.json`
  cmd/ferretdb/main.go
  cmd/ferretdb/main_unix.go
  cmd/ferretdb/main_windows.go
  internal/util/state/provider.go
Labels: code/enhancement
