Repository FerretDB/FerretDB, pull requests merged in 2024-06, with the labels that each got.

#4305 Update example in documentation
  website/docs/basic-operations/read.md
  website/versioned_docs/version-v1.21/basic-operations/read.md
Labels: documentation, community

#4310 Allow database and user setup with CLI flags
  cmd/ferretdb/main.go
  internal/backends/mysql/metadata/registry_test.go
  internal/backends/user.go
  internal/handler/authenticate.go
  internal/handler/handler.go
  internal/handler/msg_saslcontinue.go
  internal/handler/msg_saslstart.go
  internal/handler/registry/hana.go
  internal/handler/registry/mysql.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/registry.go
  internal/handler/registry/sqlite.go
Labels: code/feature

#4355 Add stub for the Docker healthcheck
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
  cmd/ferretdb/main.go
Labels: code/chore

#4375 Bump deps
  build/deps/ferretdb-prettier.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/backends/backend_test.go
  internal/backends/sqlite/metadata/pool/pool_test.go
  internal/backends/sqlite/metadata/registry_test.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
  website/go.mod
Labels: deps

#4373 Remove `PLAIN` mechanism from new authentication
  ferretdb/ferretdb.go
  integration/commands_administration_test.go
  integration/commands_authentication_test.go
  integration/hello_command_test.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  integration/users/connection_test.go
  integration/users/create_user_test.go
  integration/users/drop_all_users_from_database_test.go
  integration/users/drop_user_test.go
  integration/users/update_user_test.go
  integration/users/usersinfo_test.go
  internal/backends/mysql/metadata/registry.go
  internal/backends/postgresql/metadata/registry.go
  internal/clientconn/conninfo/conn_info.go
  internal/handler/authenticate.go
  internal/handler/handler.go
  internal/handler/msg_createuser.go
  internal/handler/msg_logout.go
  internal/handler/msg_saslcontinue.go
  internal/handler/msg_saslstart.go
  internal/handler/msg_updateuser.go
  internal/handler/registry/hana.go
  internal/handler/registry/mysql.go
  internal/handler/registry/postgresql.go
  internal/handler/registry/sqlite.go
Labels: code/chore

#4379 Fix codecov CLI version
  .github/workflows/_integration.yml
  .github/workflows/go.yml
Labels: code/chore

#4368 Handle supported mechanisms in `hello` and `getParameters` commands
  integration/commands_administration_test.go
  integration/hello_command_test.go
  integration/users/create_user_test.go
  integration/users/usersinfo_test.go
  internal/backends/user.go
  internal/handler/msg_getparameter.go
  internal/handler/msg_hello.go
  internal/util/password/plain.go
  internal/util/password/plain_test.go
Labels: code/chore

#4309 Add `restart: on-failure` to all containers
  website/docs/quickstart-guide/docker.md
  website/docs/security/authentication.md
  website/docs/security/tls-connections.md
  website/versioned_docs/version-v1.19/quickstart-guide/docker.md
  website/versioned_docs/version-v1.19/security/authentication.md
  website/versioned_docs/version-v1.19/security/tls-connections.md
  website/versioned_docs/version-v1.20/quickstart-guide/docker.md
  website/versioned_docs/version-v1.20/security/authentication.md
  website/versioned_docs/version-v1.20/security/tls-connections.md
  website/versioned_docs/version-v1.21/quickstart-guide/docker.md
  website/versioned_docs/version-v1.21/security/authentication.md
Labels: documentation, community

#4386 Port `wire` package changes
  internal/wire/msg_body.go
  internal/wire/op_msg.go
  internal/wire/op_query.go
  internal/wire/op_reply.go
  internal/wire/wire_test.go
Labels: code/chore

#4390 Include `SpeculativeAuthenticate` changes
  internal/handler/cmd_query.go
  internal/handler/common/client_metadata.go
  internal/handler/common/client_metadata_test.go
  internal/handler/common/ismaster.go
  internal/handler/handler.go
  internal/handler/handlererrors/error.go
  internal/handler/handlererrors/errorcode_string.go
  internal/handler/msg_hello.go
  internal/handler/msg_ismaster.go
Labels: code/chore

#4391 Fix `saslContinue` prematurely returning `done`
  internal/backends/mysql/metadata/registry.go
  internal/backends/postgresql/metadata/registry.go
  internal/clientconn/conninfo/conn_info.go
  internal/clientconn/conninfo/conn_info_test.go
  internal/handler/authenticate.go
  internal/handler/cmd_query.go
  internal/handler/commands.go
  internal/handler/handler.go
  internal/handler/msg_logout.go
  internal/handler/msg_saslcontinue.go
  internal/handler/msg_saslstart.go
  internal/handler/msg_saslstart_test.go
Labels: code/chore

#4397 Replace deprecated syntax in Dockerfiles
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
Labels: code/chore, trust, packages

#4378 Add Kubernetes probes stubs
  internal/util/debug/debug.go
Labels: code/feature

#4401 Add release blog post for FerretDB v.1.22.0
  website/blog/2024-06-27-new-ferretdb-v122-user-setup-feature.md
  website/static/img/blog/ferretdb-v1.22.0.jpg
Labels: trust, blog/marketing

#4377 Add blog post on running FerretDB and CloudNativePG on Kubernetes
  website/blog/2024-06-28-run-ferretdb-cloudnativepg-kubernetes.md
  website/static/img/blog/ferretdb-cloudnativepg.jpg
Labels: trust, blog/marketing
