Repository FerretDB/FerretDB, pull requests merged in 2025-01, with the labels that each got.

#4678 Bump deps
  .golangci-new.yml
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-prettier.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
  go.mod
  go.sum
  integration/.golangci-new.yml
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
  website/go.mod
Labels: documentation, deps, trust

#4658 Add blogpost for managed FerretDB on Taikun
  website/blog/2025-01-16-run-mongodb-workloads-ferretdb-taikun-cloudworks.md
  website/static/img/blog/ferretdb-taikun2.jpg
Labels: trust, blog/marketing

#4686 Reformat with settings from v2
  .prettierignore
  Taskfile.yml
  build/legacy-mongo-shell/test.example.js
  build/legacy-mongo-shell/test.js
  website/babel.config.js
  website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.mdx
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
  website/sidebars.js
  website/src/components/HomepageFeatures/index.js
  website/versions.json
Labels: documentation, trust

#4698 Disable xfail CI configuration for now
  .github/workflows/conform-pr.yml
  .github/workflows/debug.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/go.yml
  .github/workflows/security.yml
  .github/workflows/testscripts.yml
  .github/workflows/website-preview.yml
  build/version/version.go
  tools/definedockertag/main.go
  tools/definedockertag/main_test.go
  website/docs/installation/ferretdb/docker.md
Labels: code/chore

#4695 Skip private issue links in `checkcomments` by a flag
  integration/shareddata/faker.go
  internal/mongoerrors/mongoerrors.go
  tools/checkcomments/checkcomments.go
  tools/checkcomments/testdata/testdata.go
Labels: code/chore

#4708 Fix Dependabot config
  .github/dependabot.yml
  .gitmodules
Labels: code/chore

#4691 Fix error mapping generation
  internal/mongoerrors/generate.go
  internal/mongoerrors/mongoerrors.go
Labels: code/chore

#4713 Do not use Git LFS for Go files
  .github/workflows/docs.yml
Labels: code/chore

#4703 Refactor extract and convert in `genwrap` tool
  internal/documentdb/documentdb_api/documentdb_api.go
  internal/documentdb/genwrap/convert.go
  internal/documentdb/genwrap/convert_test.go
  internal/documentdb/genwrap/extract.go
  internal/documentdb/genwrap/extract_test.go
  internal/documentdb/genwrap/generate.go
  internal/documentdb/genwrap/generate_test.go
  internal/documentdb/genwrap/genwrap.go
Labels: code/chore
