Repository FerretDB/FerretDB, pull requests merged in 2025-03, with the labels that each got.

#4851 Update URL to join Slack
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  website/blog/2022-10-03-introducing-ferretdb-beacon-telemetry-service.md
  website/blog/2022-10-12-contribute-to-ferretdb-on-windows.md
  website/blog/2024-04-29-deploy-ferretdb-in-kubernetes-using-kubedb-managed-postgres.md
  website/docs/introduction.md
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
  website/versioned_docs/version-v1.24/main.md
Labels: documentation, trust

#4842 Remove old code for tracking operations
  integration/currentop_test.go
  internal/handler/handler.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_count.go
  internal/handler/msg_currentop.go
  internal/handler/msg_delete.go
  internal/handler/msg_distinct.go
  internal/handler/msg_explain.go
  internal/handler/msg_find.go
  internal/handler/msg_findandmodify.go
  internal/handler/msg_getmore.go
  internal/handler/msg_insert.go
  internal/handler/msg_update.go
  internal/handler/operation/operation.go
  internal/handler/operation/registry.go
Labels: code/chore

#4841 Use new DocumentDB API for `listDatabases`
  integration/commands_administration_test.go
  internal/documentdb/documentdb.go
  internal/documentdb/pool_databases.go
  internal/handler/cmd_query.go
  internal/handler/msg_compact.go
  internal/handler/msg_connectionstatus.go
  internal/handler/msg_create.go
  internal/handler/msg_debugerror.go
  internal/handler/msg_drop.go
  internal/handler/msg_dropdatabase.go
  internal/handler/msg_getcmdlineopts.go
  internal/handler/msg_getfreemonitoringstatus.go
  internal/handler/msg_getlog.go
  internal/handler/msg_hello.go
  internal/handler/msg_hostinfo.go
  internal/handler/msg_ismaster.go
  internal/handler/msg_killcursors.go
  internal/handler/msg_listcommands.go
  internal/handler/msg_listdatabases.go
  internal/handler/msg_logout.go
  internal/handler/msg_ping.go
  internal/handler/msg_renamecollection.go
  internal/handler/msg_serverstatus.go
  internal/handler/msg_setfreemonitoring.go
  internal/handler/msg_whatsmyuri.go
Labels: code/enhancement

#4855 Implement `currentOp` command
  integration/currentop_test.go
  internal/handler/msg_currentop.go
  internal/handler/msg_reindex.go
Labels: code/feature

#4832 Improve messages about DocumentDB version
  .github/RELEASE_CHECKLIST.md
  build/version/documentdb.go
  internal/documentdb/pool_new.go
  internal/handler/msg_getlog.go
  internal/util/telemetry/reporter.go
Labels: code/enhancement

#4834 Recommend using full tags/versions
  .github/dependabot.yml
  README.md
  build/version/version.go
  website/docs/installation/documentdb/deb.md
  website/docs/installation/documentdb/docker.md
  website/docs/installation/evaluation.md
  website/docs/installation/ferretdb/deb.md
  website/docs/installation/ferretdb/docker.md
Labels: documentation, trust

#4859 Prepare release
  CHANGELOG.md
Labels: code/chore, trust, packages

#4865 Unskip tests that refer to closed issue
  integration/update_field_compat_test.go
Labels: code/chore

#4866 Use GitHub-hosted CI runners
  .github/workflows/_integration.yml
Labels: code/chore

#4872 Skip flaky `currentOp` test and add TODO
  integration/currentop_test.go
Labels: code/chore

#4850 Add migration guide from v1.x to v2.x
  internal/handler/msg_create.go
  website/docs/migration/_category_.yml
  website/docs/migration/diff.md
  website/docs/migration/migrating-from-mongodb.md
  website/docs/migration/migrating-from-v1.md
  website/docs/migration/premigration-testing.md
Labels: documentation, trust

#4854 Add basic troubleshooting guide
  website/docs/contributing/_category_.yml
  website/docs/guides/replication.md
  website/docs/installation/documentdb/docker.md
  website/docs/installation/ferretdb/docker.md
  website/docs/migration/migrating-from-v1.md
  website/docs/migration/premigration-testing.md
  website/docs/reference/_category_.yml
  website/docs/troubleshooting/_category_.yml
  website/docs/troubleshooting/overview.md
Labels: documentation, trust

#4884 Add FerretDB v2 GA blog post
  website/blog/2025-03-05-ferretdb-v2-ga-open-source-mongodb-alternative-ready-for-production.md
  website/static/img/blog/ferretdb-v2-ga.png
Labels: trust, blog/marketing

#4888 Adjust pool connection timeout
  internal/documentdb/pool_new.go
Labels: code/chore

#4885 Start working on a new release
  CHANGELOG.md
  Taskfile.yml
  build/deps/postgres-documentdb.Dockerfile
  build/ferretdb/evaluation.Dockerfile
  build/version/documentdb.go
  website/docs/installation/documentdb/docker.md
  website/docs/installation/ferretdb/docker.md
Labels: documentation, code/chore, trust

#4867 Document non-enforced format of log messages in `envtool` package
  cmd/envtool/envtool.go
  cmd/envtool/setup.go
  cmd/envtool/tests_test.go
Labels: code/chore

#4863 Update TODO URLs for `listDatabase` tests
  build/version/documentdb.go
  integration/commands_administration_compat_test.go
  integration/commands_administration_test.go
  internal/handler/msg_listcollections.go
Labels: code/chore

#4890 Check issue URLs in documentation
  tools/checkdocs/checkdocs.go
  tools/checkdocs/checkdocs_test.go
Labels: code/chore

#4861 Add example telemetry report to documentation
  website/docs/telemetry.md
  website/versioned_docs/version-v2.0/telemetry.md
Labels: documentation, trust

#4911 Make production builds of the `main` branch
  tools/definedockertag/main.go
  tools/definedockertag/main_test.go
Labels: code/chore, trust, packages

#4907 Refactor `clientconn`
  internal/clientconn/conn.go
  internal/clientconn/conn_test.go
Labels: code/chore

#4916 Bump deps
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-prettier.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/markdownlint.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#4908 Add basic structure for middlewares
  internal/handler/commands.go
  internal/handler/middleware/auth.go
  internal/handler/middleware/middleware.go
  internal/handler/middleware/observability.go
  internal/mongoerrors/error.go
  website/versioned_docs/version-v1.24/configuration/observability.md
  website/versioned_docs/version-v2.0/configuration/observability.md
Labels: code/chore

#4886 Add full text search guide
  website/docs/guides/requests/1-insert-text-data.js
  website/docs/guides/requests/2-create-text-index.js
  website/docs/guides/requests/3-basic-text-search.js
  website/docs/guides/requests/4-compound-text-index.js
  website/docs/guides/requests/5-relevance-score.js
  website/docs/guides/responses/3-basic-text-search.js
  website/docs/guides/responses/5-relevance-score.js
  website/docs/guides/text-search.mdx
  website/docs/guides/vector-search.mdx
  website/versioned_docs/version-v2.0/guides/requests/1-insert-text-data.js
  website/versioned_docs/version-v2.0/guides/requests/2-create-text-index.js
  website/versioned_docs/version-v2.0/guides/requests/3-basic-text-search.js
  website/versioned_docs/version-v2.0/guides/requests/4-compound-text-index.js
  website/versioned_docs/version-v2.0/guides/requests/5-relevance-score.js
  website/versioned_docs/version-v2.0/guides/responses/3-basic-text-search.js
  website/versioned_docs/version-v2.0/guides/responses/5-relevance-score.js
  website/versioned_docs/version-v2.0/guides/text-search.mdx
  website/versioned_docs/version-v2.0/guides/vector-search.mdx
Labels: documentation, trust

#4919 Move message processing in `clientconn` to a function
  internal/clientconn/conn.go
Labels: code/chore

#4904 Add colorized levels to `console` logger
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/util/logging/console_handler.go
  internal/util/logging/console_handler_test.go
  website/docs/configuration/observability.md
  website/versioned_docs/version-v1.24/configuration/observability.md
  website/versioned_docs/version-v2.0/configuration/observability.md
Labels: code/enhancement

#4906 Add guide for GUI apps
  website/docs/usage/integrations/_category_.yml
  website/docs/usage/integrations/overview.md
  website/static/img/docs/gui-connection.jpg
Labels: documentation, trust

#4932 Configure connection pool size in tests
  .github/workflows/testscripts.yml
  integration/commands_diagnostic_test.go
  integration/cursor/batch_test.go
  integration/cursor/getmore_test.go
  integration/setup/setup.go
  internal/handler/handler.go
Labels: code/chore

#4918 refactored: help command flags into groups
  cmd/ferretdb/main.go
Labels: code/enhancement

#4933 Sync flags grouping with docs
  cmd/ferretdb/main.go
  website/docs/configuration/flags.md
Labels: documentation, code/enhancement, trust

#4925 Improve integration benchmarks
  integration/Taskfile.yml
  integration/benchmarks_test.go
  integration/setup/setup.go
  integration/setup/startup.go
  integration/shareddata/benchmark_provider.go
  integration/shareddata/benchmarks.go
  integration/shareddata/generator.go
  integration/shareddata/shareddata.go
Labels: code/chore

#4926 Add TTL index guide
  website/docs/guides/requests/1-create-ttl-index.js
  website/docs/guides/requests/2-insert-ttl-data.js
  website/docs/guides/ttl-index.mdx
Labels: documentation, trust

#4944 Add a note to documentation about PR titles
  .github/PROCESS.md
Labels: documentation

#4947 Handle `OP_QUERY` in middleware using interface
  internal/clientconn/conn.go
  internal/handler/cmd_query.go
  internal/handler/commands.go
  internal/handler/middleware/middleware.go
  internal/handler/middleware/observability.go
Labels: code/chore

#4948 Update/backport full-text and TTL indexes guides
  website/docs/guides/full-text-search.mdx
  website/docs/guides/ttl-indexes.mdx
  website/versioned_docs/version-v2.0/guides/full-text-search.mdx
  website/versioned_docs/version-v2.0/guides/requests/1-create-ttl-index.js
  website/versioned_docs/version-v2.0/guides/requests/2-insert-ttl-data.js
  website/versioned_docs/version-v2.0/guides/ttl-indexes.mdx
Labels: documentation, trust

#4927 Update `deb` and `rpm` installation docs
  website/docs/installation/documentdb/deb.md
  website/docs/installation/documentdb/docker.md
  website/docs/installation/evaluation.md
  website/docs/installation/ferretdb/deb.md
  website/docs/installation/ferretdb/docker.md
  website/docs/installation/ferretdb/rpm.md
Labels: documentation, trust

#4952 Backport documentation changes to v2.0
  website/docusaurus.config.js
  website/versioned_docs/version-v2.0/configuration/observability.md
  website/versioned_docs/version-v2.0/installation/documentdb/deb.md
  website/versioned_docs/version-v2.0/installation/documentdb/docker.md
  website/versioned_docs/version-v2.0/installation/evaluation.md
  website/versioned_docs/version-v2.0/installation/ferretdb/deb.md
  website/versioned_docs/version-v2.0/installation/ferretdb/docker.md
  website/versioned_docs/version-v2.0/installation/ferretdb/rpm.md
Labels: documentation, trust

#4974 Use ERROR level logging for failed tests
  cmd/envtool/tests.go
  cmd/envtool/tests_test.go
Labels: code/chore

#4980 Disable tracing in benchmarks for now
  integration/Taskfile.yml
  integration/setup/setup.go
  integration/setup/startup.go
Labels: code/chore

#4986 Add TODOs
  .github/ISSUE_TEMPLATE/bug.yml
  build/version/documentdb.go
  internal/handler/msg_listdatabases.go
Labels: code/chore

#4981 Do not decode incoming document twice
  internal/handler/msg_aggregate.go
  internal/handler/msg_collmod.go
  internal/handler/msg_collstats.go
  internal/handler/msg_compact.go
  internal/handler/msg_count.go
  internal/handler/msg_create.go
  internal/handler/msg_createindexes.go
  internal/handler/msg_createuser.go
  internal/handler/msg_datasize.go
  internal/handler/msg_dbstats.go
  internal/handler/msg_debugerror.go
  internal/handler/msg_delete.go
  internal/handler/msg_distinct.go
  internal/handler/msg_drop.go
  internal/handler/msg_dropallusersfromdatabase.go
  internal/handler/msg_dropdatabase.go
  internal/handler/msg_dropindexes.go
  internal/handler/msg_dropuser.go
  internal/handler/msg_endsessions.go
  internal/handler/msg_explain.go
  internal/handler/msg_find.go
  internal/handler/msg_findandmodify.go
  internal/handler/msg_getlog.go
  internal/handler/msg_getmore.go
  internal/handler/msg_getparameter.go
  internal/handler/msg_hello.go
  internal/handler/msg_insert.go
  internal/handler/msg_ismaster.go
  internal/handler/msg_killallsessions.go
  internal/handler/msg_killallsessionsbypattern.go
  internal/handler/msg_killcursors.go
  internal/handler/msg_killsessions.go
  internal/handler/msg_listcollections.go
  internal/handler/msg_listindexes.go
  internal/handler/msg_refreshsesssions.go
  internal/handler/msg_reindex.go
  internal/handler/msg_renamecollection.go
  internal/handler/msg_saslcontinue.go
  internal/handler/msg_saslstart.go
  internal/handler/msg_setfreemonitoring.go
  internal/handler/msg_update.go
  internal/handler/msg_updateuser.go
  internal/handler/msg_validate.go
  internal/handler/session/registry.go
  internal/handler/session/session.go
Labels: code/enhancement

#4732 Add post on MongoDB queries and operations on FerretDB
  website/blog/2025-01-16-run-mongodb-workloads-ferretdb-taikun-cloudworks.md
  website/blog/2025-02-10-replication-ferretdb-enabling-high-availability-performance.md
  website/blog/2025-02-25-new-ferretdb-v2-rc2-release-with-debian-packages-and-better-indexing-support.md
  website/blog/2025-02-28-best-alternative-to-mongodb-data-api-and-http-endpoints.md
  website/blog/2025-03-27-20-must-try-mongodb-queries-operations-ferretdb.md
  website/static/img/blog/mongodb-operations-ferretdb.jpg
Labels: trust, blog/marketing

#4970 Add basic documentation for supported commands
  .github/settings.yml
  .prettierignore
  README.md
  build/trivy.yml
  integration/basic_test.go
  integration/diff_02_names_test.go
  internal/dataapi/api/README.md
  internal/dataapi/api/api.go
  internal/dataapi/api/openapi-patched.json
  internal/handler/commands.go
  internal/handler/msg_ferretdebugerror.go
  internal/handler/msg_getlog.go
  website/docs/configuration/operation-modes.md
  website/docs/installation/_category_.yml
  website/docs/introduction.md
  website/docs/migration/compatibility.md
  website/docs/migration/diff.md
  website/docs/migration/migrating-from-mongodb.md
  website/docs/migration/migrating-from-v1.md
  website/docs/migration/premigration-testing.md
  website/docs/reference/aggregation-operations/_category_.yml
  website/docs/reference/operators/_category_.yml
  website/docs/security/_category_.yml
  website/docs/usage/concepts.md
  website/docs/usage/indexes.md
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
  website/versioned_docs/version-v1.24/security/_category_.yml
  website/versioned_docs/version-v2.0/introduction.md
  website/versioned_docs/version-v2.0/migration/compatibility.md
  website/versioned_docs/version-v2.0/migration/diff.md
  website/versioned_docs/version-v2.0/migration/migrating-from-mongodb.md
  website/versioned_docs/version-v2.0/migration/migrating-from-v1.md
  website/versioned_docs/version-v2.0/migration/premigration-testing.md
  website/versioned_docs/version-v2.0/security/_category_.yml
  website/versioned_docs/version-v2.0/usage/concepts.md
Labels: documentation, trust

#4991 Update feature blog post
  website/blog/2025-03-27-20-must-try-mongodb-queries-operations-ferretdb.md
Labels: blog/marketing
