Repository FerretDB/FerretDB, pull requests merged in 2025-09, with the labels that each got.

#5382 Use generated structs in Data API
  internal/dataapi/api/api.go
  internal/dataapi/api/gen.go
  internal/dataapi/api/openapi.json
  internal/dataapi/listener_test.go
  internal/dataapi/server/aggregate.go
  internal/dataapi/server/delete_many.go
  internal/dataapi/server/delete_one.go
  internal/dataapi/server/find.go
  internal/dataapi/server/find_one.go
  internal/dataapi/server/insert_many.go
  internal/dataapi/server/insert_one.go
  internal/dataapi/server/json.go
  internal/dataapi/server/server.go
  internal/dataapi/server/server_test.go
  internal/dataapi/server/update_many.go
  internal/dataapi/server/update_one.go
Labels: code/chore

#5466 Update cloud installation docs
  website/docs/installation/ferretdb-cloud.md
  website/versioned_docs/version-v2.5/installation/ferretdb-cloud.md
Labels: documentation, trust

#5427 Add `PostgreSQL` metrics
  internal/documentdb/documentdb_test.go
  internal/documentdb/pool.go
  internal/documentdb/pool_new.go
  internal/documentdb/tracer.go
Labels: code/chore

#5508 Use Go 1.25.1
  CONTRIBUTING.md
  build/ferretdb-bw/Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/eval-dev.Dockerfile
  build/ferretdb/eval.Dockerfile
  build/ferretdb/production.Dockerfile
  cmd/ferretdb/gomaxprocs.go
  cmd/ferretdb/main.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/documentdb/documentdb.go
  internal/documentdb/genwrap/extract_test.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/mcphost/go.mod
  website/go.mod
Labels: deps

#5509 Bump deps
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  tools/go.mod
  tools/go.sum
Labels: deps
