Repository FerretDB/FerretDB, pull requests merged in 2025-07, with the labels that each got.

#5318 Remove `must.NotFail(wire[bson].NewXXX(` pattern
  integration/auth_test.go
  integration/op_query_test.go
  integration/session/endsessions_test.go
  integration/session/killallsessions_test.go
  integration/session/killallsessionsbypattern_test.go
  integration/session/killsessions_test.go
  integration/session/refreshsessions_test.go
  integration/session/startsession_test.go
  integration/setup/setup.go
  internal/dataapi/server/aggregate.go
  internal/dataapi/server/delete_many.go
  internal/dataapi/server/delete_one.go
  internal/dataapi/server/find.go
  internal/dataapi/server/find_one.go
  internal/dataapi/server/insert_many.go
  internal/dataapi/server/insert_one.go
  internal/dataapi/server/update_many.go
  internal/dataapi/server/update_one.go
  internal/handler/msg_buildinfo.go
  internal/handler/msg_connectionstatus.go
  internal/handler/msg_datasize.go
  internal/handler/msg_drop.go
  internal/handler/msg_dropuser.go
  internal/handler/msg_explain.go
  internal/handler/msg_getcmdlineopts.go
  internal/handler/msg_getlog.go
  internal/handler/msg_getparameter.go
  internal/handler/msg_hello.go
  internal/handler/msg_hostinfo.go
  internal/handler/msg_killcursors.go
  internal/handler/msg_listcommands.go
  internal/handler/msg_serverstatus.go
  internal/handler/msg_setfreemonitoring.go
  internal/handler/msg_updateuser.go
Labels: code/chore

#5314 Allow users to perform user management commands
  .github/workflows/go.yml
  cmd/envtool/setup.go
  docker-compose.yml
  internal/documentdb/genwrap/genwrap.go
  internal/documentdb/user.go
  internal/handler/msg_createuser.go
Labels: code/bug

#5327 Avoid extra marshaling
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/handler/middleware/request.go
  internal/handler/middleware/response.go
  tools/go.mod
  tools/go.sum
Labels: code/chore

#5328 Split command handling and handlers
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/setup/listener.go
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/dataapi/listener_test.go
  internal/handler/commands.go
  internal/handler/handler.go
  internal/handler/middleware/middleware.go
  internal/handler/middleware/mode.go
  internal/handler/middleware/response.go
  internal/handler/proxy/proxy.go
Labels: code/chore

#5258 Add YugabyteDB to local setup
  Taskfile.yml
  build/deps/yugabytedb.Dockerfile
  build/yugabytedb/init.sql
  cmd/envtool/setup.go
  docker-compose.yml
Labels: code/feature

#5334 Add HyperDX blog post
  website/blog/2025-07-15-full-stack-observability-hyperdx-ferretdb.md
  website/docs/compatible-applications/applications.js
  website/static/img/blog/ferretdb-hyperdx.jpg
  website/static/img/blog/hyperdx-dashboard.png
  website/static/img/compatible-applications/hyperdx-logo.png
  website/versioned_docs/version-v2.3/compatible-applications/applications.js
Labels: documentation, trust, blog/marketing

#5364 Add components in codecov
  .github/codecov.yml
Labels: code/chore

#5368 Add Vault blog post
  website/blog/2025-07-23-dynamic-database-credentials-with-hashicorp-vault-and-ferretdb.md
  website/docs/compatible-applications/applications.js
  website/static/img/blog/ferretdb-vault.jpg
  website/static/img/compatible-applications/vault-logo.png
  website/versioned_docs/version-v2.4/compatible-applications/applications.js
Labels: documentation, trust, blog/marketing

#5326 Refactor normal and error responses
  internal/clientconn/conn.go
  internal/clientconn/listener.go
  internal/dataapi/server/aggregate.go
  internal/dataapi/server/delete_many.go
  internal/dataapi/server/delete_one.go
  internal/dataapi/server/errors.go
  internal/dataapi/server/find.go
  internal/dataapi/server/find_one.go
  internal/dataapi/server/insert_many.go
  internal/dataapi/server/insert_one.go
  internal/dataapi/server/server.go
  internal/dataapi/server/server_test.go
  internal/dataapi/server/update_many.go
  internal/dataapi/server/update_one.go
  internal/documentdb/pool_cursors.go
  internal/handler/handler.go
  internal/handler/middleware/middleware.go
  internal/handler/middleware/request.go
  internal/handler/middleware/response.go
  internal/handler/msg_collstats.go
  internal/handler/msg_createindexes.go
  internal/handler/proxy/proxy.go
  internal/mongoerrors/error.go
  internal/mongoerrors/mongoerrors.go
  internal/util/tlsutil/tlsutil.go
Labels: code/chore

#5362 Make accessing YugabyteDB logs easier
  Taskfile.yml
Labels: code/chore

#5383 Extract wiring into a separate package
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  integration/go.mod
  integration/go.sum
  integration/setup/listener.go
  internal/clientconn/conn.go
  internal/dataapi/listener.go
  internal/dataapi/listener_test.go
  internal/dataapi/server/server.go
  internal/dataapi/server/server_test.go
  internal/documentdb/pool.go
  internal/handler/handler.go
  internal/util/setup/setup.go
  internal/util/state/metrics.go
  internal/util/state/provider.go
Labels: code/chore

#5361 Use Codecov for flaky integration tests detection
  .github/workflows/_integration.yml
  .github/workflows/go.yml
  .gitignore
  Taskfile.yml
  tools/go.mod
  tools/go.sum
Labels: code/chore

#5388 Small cleanup
  cmd/ferretdb/gomaxprocs.go
  cmd/ferretdb/main.go
  internal/dataapi/listener.go
  internal/util/setup/setup.go
Labels: code/chore

#5274 Add YugabyteDB integration tests
  .github/workflows/go.yml
  Taskfile.yml
  integration/cursor/getmore_test.go
  integration/setup/helpers.go
  integration/setup/listener.go
  integration/setup/setup.go
  integration/setup/setup_compat.go
  tools/checkcomments/checkcomments.go
  tools/checkcomments/testdata/testdata.go
Labels: code/feature
