Repository FerretDB/FerretDB, pull requests merged in 2025-04, with the labels that each got.

#4996 Add more tests for error handling
  integration/basic_test.go
  integration/setup/setup.go
  internal/handler/msg_ferretdebugerror.go
Labels: code/chore

#4936 Fix version detection for embeddable package
  .gitattributes
  .github/workflows/_integration.yml
  .github/workflows/go.yml
  .golangci.yml
  build/version/mongodb.txt
  build/version/version.go
  build/version/version_test.go
  cmd/ferretdb/main.go
  internal/util/debug/archive.go
  internal/util/debug/debug_test.go
  internal/util/resource/resource.go
Labels: code/bug

#5005 Use Go 1.24.2
  build/ferretdb-bw/Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/evaluation.Dockerfile
  build/ferretdb/production.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/golangci/go.mod
  website/go.mod
Labels: deps, trust, packages

#5011 Create redirects for `/v2.0/` documentation URLs
  .github/RELEASE_CHECKLIST.md
  website/docusaurus.config.js
Labels: documentation, trust

#5012 Disable commit check for now
  build/version/version.go
Labels: code/chore

#4810 Update changelog generator
  .github/RELEASE_CHECKLIST.md
  .github/release.yml
  CHANGELOG.md
  Taskfile.yml
  build/ferretdb-bw/ferretdb/ferretdb.go
  build/ferretdb/evaluation.Dockerfile
  tools/generatechangelog/changelog.md.template
  tools/generatechangelog/generatechangelog.go
  tools/generatechangelog/generatechangelog_test.go
  tools/generatechangelog/test_template.yml
  tools/github/github.go
  tools/go.mod
  tools/go.sum
  website/blog/2024-02-12-guide-disaster-recovery-ferretdb-elotl-nova-kubernetes.md
Labels: code/chore

#5004 Add blogpost on FerretDB v2.1.0 release
  website/blog/2025-04-03-ferretdb-v210-release-performance-improvements-bug-fixes.md
  website/static/img/blog/ferretdb-v2.1.0.jpg
Labels: trust, blog/marketing

#5015 Update Docker images
  CHANGELOG.md
  README.md
  build/deps/postgres-documentdb.Dockerfile
  build/ferretdb/evaluation.Dockerfile
  build/version/documentdb.go
  internal/documentdb/pool_new.go
  website/docs/installation/documentdb/docker.md
  website/docs/installation/ferretdb/docker.md
Labels: documentation, trust

#5016 Do not send zero values to telemetry
  Taskfile.yml
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  internal/clientconn/connmetrics/conn_metrics.go
  internal/clientconn/connmetrics/conn_metrics_test.go
  internal/clientconn/connmetrics/listener_metrics.go
  internal/util/telemetry/reporter.go
  internal/util/telemetry/reporter_test.go
Labels: code/chore

#5026 Move tests for sessions
  integration/auth_test.go
  integration/currentop_test.go
  integration/indexes_command_test.go
  integration/integration.go
  integration/op_query_test.go
  integration/session/endsessions_test.go
  integration/session/killallsessions_test.go
  integration/session/killallsessionsbypattern_test.go
  integration/session/killsessions_test.go
  integration/session/refreshsessions_test.go
  integration/session/startsession_test.go
Labels: code/chore

#5024 Update deps
  build/deps/docusaurus-docs.Dockerfile
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/ferretdb-wrangler.Dockerfile
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: deps

#5025 Minor tweaks for proxy code
  internal/clientconn/conn.go
  internal/handler/proxy/proxy.go
Labels: code/chore

#5037 Move `findAndModify` integration tests
  integration/aggregate_compat_test.go
  integration/aggregate_variables_compat_test.go
  integration/compattestcaseresulttype_string.go
  integration/count_compat_test.go
  integration/delete_compat_test.go
  integration/distinct_compat_test.go
  integration/explain_compat_test.go
  integration/indexes_command_compat_test.go
  integration/indexes_compat_test.go
  integration/insert_compat_test.go
  integration/integration.go
  integration/query/findandmodify_compat_test.go
  integration/query/findandmodify_test.go
  integration/query_array_compat_test.go
  integration/query_command_compat_test.go
  integration/query_comparison_compat_test.go
  integration/query_compat_test.go
  integration/query_element_compat_test.go
  integration/query_evaluation_compat_test.go
  integration/query_logical_compat_test.go
  integration/query_projection_compat_test.go
  integration/update_array_compat_test.go
  integration/update_compat_test.go
  integration/update_field_compat_test.go
Labels: code/chore

#5027 Bump deps
  build/version/documentdb.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/documentdb/pool_new.go
  tools/go.mod
  tools/go.sum
Labels: deps

#5042 Update wire
  cmd/ferretdb/readyz.go
  go.mod
  go.sum
  integration/auth_test.go
  integration/go.mod
  integration/go.sum
  integration/op_query_test.go
  internal/clientconn/conn.go
  internal/handler/cmd_query.go
  tools/go.mod
  tools/go.sum
Labels: code/chore

#5050 Use "PostgreSQL with DocumentDB extension" phrase
  README.md
  website/docs/troubleshooting/overview.md
  website/versioned_docs/version-v2.0/troubleshooting/overview.md
  website/versioned_docs/version-v2.1/troubleshooting/overview.md
Labels: documentation, trust

#4998 Add blog post on FerretDB and CNPG
  website/blog/2025-04-11-run-ferretdb-postgres-documentdb-extension-cnpg-kubernetes.md
  website/static/img/blog/ferretdb-cnpg.jpg
Labels: trust, blog/marketing

#4971 Add Kubernetes installation guide
  website/docs/installation/documentdb/deb.md
  website/docs/installation/documentdb/kubernetes.md
  website/docs/installation/ferretdb/deb.md
  website/docs/installation/ferretdb/kubernetes.md
  website/docs/installation/ferretdb/macos.md
  website/docs/installation/ferretdb/rpm.md
  website/docs/installation/ferretdb/systemd.md
  website/docs/installation/ferretdb/windows.md
Labels: documentation, trust

#5040 Rename `evaluation` image to `eval-dev`
  .github/workflows/packages.yml
  Taskfile.yml
  build/ferretdb/eval-dev.Dockerfile
  tools/definedockertag/main.go
  tools/definedockertag/main_test.go
Labels: code/feature, trust, packages

#4961 Remove MongoDB driver v1
  go.mod
  go.sum
  internal/dataapi/listener_test.go
  internal/dataapi/server/json.go
  internal/mongoerrors/error.go
  internal/mongoerrors/mongoerrors.go
  internal/mongoerrors/mongoerrors_test.go
  internal/util/logging/mongo_handler.go
Labels: code/chore, community

#5053 Backport Kubernetes docs to 2.1
  website/versioned_docs/version-v2.1/installation/documentdb/deb.md
  website/versioned_docs/version-v2.1/installation/documentdb/kubernetes.md
  website/versioned_docs/version-v2.1/installation/ferretdb/deb.md
  website/versioned_docs/version-v2.1/installation/ferretdb/kubernetes.md
  website/versioned_docs/version-v2.1/installation/ferretdb/macos.md
  website/versioned_docs/version-v2.1/installation/ferretdb/rpm.md
  website/versioned_docs/version-v2.1/installation/ferretdb/systemd.md
  website/versioned_docs/version-v2.1/installation/ferretdb/windows.md
Labels: documentation

#5041 Supervise services in evaluation image
  build/ferretdb/99-start-ferretdb.sh
  build/ferretdb/development.Dockerfile
  build/ferretdb/eval-dev.Dockerfile
  build/ferretdb/evaluation/entrypoint.sh
  build/ferretdb/evaluation/supervisord.conf
  build/ferretdb/production.Dockerfile
Labels: code/feature, trust, packages

#5062 Update OpenAPI spec description
  .prettierignore
  build/trivy.yml
  internal/dataapi/api/README.md
  internal/dataapi/api/api.go
  internal/dataapi/api/openapi-original.json
  internal/dataapi/api/openapi.json
Labels: documentation

#5033 Add blog post on migrating to FerretDB with dsync
  website/blog/2025-04-16-migrate-mongodb-data-ferretdb-dsync.md
  website/static/img/blog/ferretdb-migration-dsync.jpg
Labels: trust, blog/marketing

#5066 Backport `.deb` installation guide
  website/versioned_docs/version-v2.1/installation/documentdb/deb.md
Labels: documentation, trust

#5067 Fix docker health check on evaluation image
  build/ferretdb/eval-dev.Dockerfile
  build/ferretdb/evaluation/entrypoint.sh
Labels: code/chore, trust, packages

#5051 Create `ferretdb-eval` docker image with production build
  .github/workflows/packages.yml
  Taskfile.yml
  build/ferretdb/eval.Dockerfile
Labels: code/feature, trust, packages

#5055 Implement handler `Handle` function
  internal/handler/commands.go
  internal/handler/handler.go
Labels: code/chore

#5069 Use `Handle` function in Data API
  internal/dataapi/server/aggregate.go
  internal/dataapi/server/delete_many.go
  internal/dataapi/server/delete_one.go
  internal/dataapi/server/find.go
  internal/dataapi/server/find_one.go
  internal/dataapi/server/insert_many.go
  internal/dataapi/server/insert_one.go
  internal/dataapi/server/server.go
  internal/dataapi/server/update_many.go
  internal/dataapi/server/update_one.go
Labels: code/chore

#5072 Unconvert syntax examples in documentation
  website/docs/guides/vector-search.mdx
Labels: documentation, trust

#5070 Use `Handle` function in `clientconn`
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/clientconn/conn.go
  internal/handler/handler.go
  internal/handler/msg_delete.go
  internal/handler/msg_insert.go
  internal/handler/msg_update.go
Labels: code/chore

#5084 Unexport handlers
  integration/basic_test.go
  internal/handler/commands.go
  internal/handler/handler.go
  internal/handler/msg_aggregate.go
  internal/handler/msg_buildinfo.go
  internal/handler/msg_collmod.go
  internal/handler/msg_collstats.go
  internal/handler/msg_compact.go
  internal/handler/msg_connectionstatus.go
  internal/handler/msg_count.go
  internal/handler/msg_create.go
  internal/handler/msg_createindexes.go
  internal/handler/msg_createuser.go
  internal/handler/msg_currentop.go
  internal/handler/msg_datasize.go
  internal/handler/msg_dbstats.go
  internal/handler/msg_delete.go
  internal/handler/msg_distinct.go
  internal/handler/msg_drop.go
  internal/handler/msg_dropallusersfromdatabase.go
  internal/handler/msg_dropdatabase.go
  internal/handler/msg_dropindexes.go
  internal/handler/msg_dropuser.go
  internal/handler/msg_endsessions.go
  internal/handler/msg_explain.go
  internal/handler/msg_ferretdebugerror.go
  internal/handler/msg_find.go
  internal/handler/msg_findandmodify.go
  internal/handler/msg_getcmdlineopts.go
  internal/handler/msg_getfreemonitoringstatus.go
  internal/handler/msg_getlog.go
  internal/handler/msg_getmore.go
  internal/handler/msg_getparameter.go
  internal/handler/msg_hello.go
  internal/handler/msg_hostinfo.go
  internal/handler/msg_insert.go
  internal/handler/msg_ismaster.go
  internal/handler/msg_killallsessions.go
  internal/handler/msg_killallsessionsbypattern.go
  internal/handler/msg_killcursors.go
  internal/handler/msg_killsessions.go
  internal/handler/msg_listcollections.go
  internal/handler/msg_listcommands.go
  internal/handler/msg_listdatabases.go
  internal/handler/msg_listindexes.go
  internal/handler/msg_logout.go
  internal/handler/msg_ping.go
  internal/handler/msg_refreshsesssions.go
  internal/handler/msg_reindex.go
  internal/handler/msg_renamecollection.go
  internal/handler/msg_saslcontinue.go
  internal/handler/msg_saslstart.go
  internal/handler/msg_serverstatus.go
  internal/handler/msg_setfreemonitoring.go
  internal/handler/msg_startsession.go
  internal/handler/msg_update.go
  internal/handler/msg_updateuser.go
  internal/handler/msg_usersinfo.go
  internal/handler/msg_validate.go
  internal/handler/msg_whatsmyuri.go
Labels: code/chore

#5056 Use new `wire` helpers
  .github/CODEOWNERS
  .golangci.yml
  Taskfile.yml
  integration/.golangci-new.yml
  integration/.golangci.yml
  integration/integration.go
  internal/clientconn/conn.go
  internal/handler/msg_collmod.go
  internal/handler/msg_count.go
  internal/handler/msg_createuser.go
  internal/handler/msg_explain.go
  internal/handler/msg_find.go
  internal/handler/msg_validate.go
  internal/util/devbuild/devbuild.go
  internal/util/testutil/equal.go
  internal/util/testutil/equal_test.go
  tools/checkswitch/testdata/bson/bson.go
  tools/go.mod
  tools/go.sum
Labels: code/chore

#5094 Use new `wire` helpers
  .github/CODEOWNERS
  .golangci.yml
  Taskfile.yml
  go.mod
  go.sum
  integration/.golangci-new.yml
  integration/.golangci.yml
  integration/basic_test.go
  integration/currentop_test.go
  integration/go.mod
  integration/go.sum
  integration/integration.go
  integration/update_compat_test.go
  internal/clientconn/conn.go
  internal/handler/msg_collmod.go
  internal/handler/msg_count.go
  internal/handler/msg_createuser.go
  internal/handler/msg_explain.go
  internal/handler/msg_find.go
  internal/handler/msg_validate.go
  internal/util/devbuild/devbuild.go
  internal/util/testutil/equal.go
  internal/util/testutil/equal_test.go
  tools/checkswitch/testdata/bson/bson.go
  tools/go.mod
  tools/go.sum
Labels: code/chore

#5101 Fix linters for v1
  .github/workflows/docs.yml
  .golangci-new.yml
  CONTRIBUTING.md
  Taskfile.yml
  build/certs/Makefile
  build/certs/client-cert.pem
  build/certs/client-key.pem
  build/certs/client.pem
  build/certs/rootCA-cert.pem
  build/certs/rootCA-key.pem
  build/certs/server-cert.pem
  build/certs/server-key.pem
  build/certs/server.pem
  build/ferretdb/all-in-one.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/production.Dockerfile
  go.mod
  go.sum
  integration/.golangci-new.yml
  integration/Taskfile.yml
  integration/go.mod
  integration/go.sum
  internal/util/state/metrics_test.go
  tools/Taskfile.yml
  tools/checkcomments/checkcomments_test.go
  tools/checkcomments/testdata/testdata.go
  tools/checkdocs/checkdocs_test.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  website/go.mod
Labels: code/chore

#5099 Fix Docker tags for pre-release git tags
  tools/definedockertag/main.go
  tools/definedockertag/main_test.go
Labels: code/chore

#5083 Use volume for `state` directory
  build/ferretdb/eval-dev.Dockerfile
  build/ferretdb/eval.Dockerfile
  build/ferretdb/evaluation/entrypoint.sh
Labels: code/feature, trust, packages

#5100 Fix Docker tags for pre-release git tags
  tools/definedockertag/main.go
  tools/definedockertag/main_test.go
Labels: code/chore

#5076 Update evaluation Docker image documentation
  .github/RELEASE_CHECKLIST.md
  README.md
  website/docs/installation/evaluation.md
  website/docs/installation/ferretdb/docker.md
Labels: documentation, code/chore, trust

#5082 Reorgonize cts output files
  tools/go.mod
  tools/go.sum
  website/docs/guides/full-text-search.mdx
  website/docs/guides/full-text-search/1-insert-text-data.request.js
  website/docs/guides/full-text-search/1-insert-text-data.response.js
  website/docs/guides/full-text-search/2-create-text-index.request.js
  website/docs/guides/full-text-search/2-create-text-index.response.js
  website/docs/guides/full-text-search/3-basic-text-search.request.js
  website/docs/guides/full-text-search/3-basic-text-search.response.js
  website/docs/guides/full-text-search/4-compound-text-index.request.js
  website/docs/guides/full-text-search/4-compound-text-index.response.js
  website/docs/guides/full-text-search/5-relevance-score.request.js
  website/docs/guides/full-text-search/5-relevance-score.response.js
  website/docs/guides/ttl-indexes.mdx
  website/docs/guides/ttl-indexes/1-create-ttl-index.request.js
  website/docs/guides/ttl-indexes/1-create-ttl-index.response.js
  website/docs/guides/ttl-indexes/2-insert-ttl-data.request.js
  website/docs/guides/ttl-indexes/2-insert-ttl-data.response.js
  website/docs/guides/vector-search.mdx
  website/docs/guides/vector-search/1-insert-vector.request.js
  website/docs/guides/vector-search/1-insert-vector.response.js
  website/docs/guides/vector-search/2-hnsw-index.request.js
  website/docs/guides/vector-search/2-hnsw-index.response.js
  website/docs/guides/vector-search/3-hnsw-search.request.js
  website/docs/guides/vector-search/3-hnsw-search.response.js
  website/docs/guides/vector-search/4-ivf-index.request.js
  website/docs/guides/vector-search/4-ivf-index.response.js
  website/docs/guides/vector-search/5-ivf-search.request.js
  website/docs/guides/vector-search/5-ivf-search.response.js
Labels: code/chore
