Repository FerretDB/FerretDB, pull requests merged in 2025-02, with the labels that each got.

#4727 Do not use a global variable for logging
  internal/handler/handler.go
  internal/handler/msg_getlog.go
  internal/util/logging/buffer.go
  internal/util/logging/buffer_test.go
  internal/util/logging/handler.go
Labels: code/chore

#4743 Bump deps
  build/deps/trivy.Dockerfile
  build/ferretdb/development.Dockerfile
  build/ferretdb/evaluation.Dockerfile
  build/ferretdb/production.Dockerfile
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  website/go.mod
Labels: deps

#4714 Check DocumentDB issues in `checkcomments` and `checkdocs`
  tools/checkcomments/checkcomments.go
  tools/checkcomments/testdata/testdata.go
  tools/checkdocs/checkdocs.go
  tools/checkdocs/checkdocs_test.go
  tools/github/github.go
  tools/github/github_test.go
  tools/github/issue.go
Labels: code/chore

#4717 Add replication blog post
  website/blog/2025-02-10-replication-ferretdb-enabling-high-availability-performance.md
  website/static/img/blog/replication.jpg
Labels: trust, blog/marketing

#4749 Add explicit `platform: linux/amd64` to docs
  website/docs/guides/replication.md
  website/docs/installation/ferretdb/docker.md
  website/docs/security/authentication.md
  website/docs/security/tls-connections.md
Labels: documentation

#4751 Remove "all backends" from the issue template
  .github/ISSUE_TEMPLATE/chore.yml
Labels: code/chore

#4753 Add missing space in command
  website/docs/migration/migrating-from-mongodb.md
Labels: documentation

#4735 Implement `reIndex` command
  integration/indexes_command_compat_test.go
  integration/indexes_command_test.go
  integration/indexes_compat_test.go
  internal/handler/commands.go
  internal/handler/msg_createindexes.go
  internal/handler/msg_dropindexes.go
  internal/handler/msg_reindex.go
Labels: code/feature

#4740 Update config flags
  Taskfile.yml
  cmd/ferretdb/main.go
  website/docs/configuration/flags.md
  website/docs/telemetry.md
Labels: documentation, trust

#4752 Update TLS docs
  website/docs/security/tls-connections.md
Labels: documentation, trust

#4723 Add/update TODO comments for some issues
  cmd/envtool/envtool.go
  cmd/envtool/tests_test.go
  cmd/ferretdb/main.go
  integration/commands_administration_test.go
  integration/setup/startup.go
  internal/documentdb/documentdb.go
  internal/documentdb/pool_databases.go
  internal/handler/msg_listdatabases.go
Labels: code/chore

#4711 Remove `golang.org/x/exp/maps` package
  .golangci-new.yml
  .golangci.yml
  build/deps/jaeger.Dockerfile
  build/deps/trivy.Dockerfile
  go.mod
  go.sum
  integration/.golangci-new.yml
  integration/.golangci.yml
  integration/go.mod
  integration/go.sum
  integration/shareddata/benchmarks.go
  integration/shareddata/provider.go
  integration/shareddata/shareddata.go
  internal/handler/msg_currentop.go
  internal/handler/msg_explain.go
  internal/handler/msg_listcommands.go
  internal/handler/msg_listdatabases.go
  internal/handler/operation/registry.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
Labels: code/chore

#4760 Set `GOARM64` explicitly
  build/ferretdb/development.Dockerfile
  build/ferretdb/evaluation.Dockerfile
  build/ferretdb/production.Dockerfile
Labels: code/enhancement, trust, packages

#4759 Use `/` consistently in MongoDB URIs
  website/docs/migration/migrating-from-mongodb.md
  website/docs/migration/premigration-testing.md
  website/docs/security/tls-connections.md
Labels: documentation

#4775 Use Go 1.24.0
  .editorconfig
  .golangci.yml
  CONTRIBUTING.md
  build/ferretdb/development.Dockerfile
  build/ferretdb/evaluation.Dockerfile
  build/ferretdb/production.Dockerfile
  build/version/version.go
  cmd/ferretdb/main.go
  go.mod
  integration/.golangci.yml
  integration/commands_administration_test.go
  integration/go.mod
  integration/integration.go
  internal/util/logging/handler_test.go
  internal/util/state/metrics_test.go
  tools/checkcomments/checkcomments.go
  tools/checkcomments/checkcomments_test.go
  tools/checkdocs/checkdocs.go
  tools/checkdocs/checkdocs_test.go
  tools/go.mod
  tools/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
  tools/golangci/golangci.go
  tools/tools.go
  website/go.mod
Labels: code/chore, trust, packages

#4784 Use directories instead of files for state and telemetry
  build/version/version.go
  cmd/ferretdb/main.go
  cmd/ferretdb/readyz.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  internal/clientconn/listener.go
  internal/handler/handler.go
  internal/handler/msg_getlog.go
  internal/util/debug/debug.go
  internal/util/logging/buffer_test.go
  internal/util/logging/logging.go
  internal/util/observability/observability.go
  internal/util/state/provider.go
  internal/util/state/provider_test.go
  internal/util/state/provider_unix.go
  internal/util/state/provider_windows.go
  internal/util/telemetry/reporter.go
  internal/util/telemetry/reporter_test.go
Labels: code/chore

#4787 Reformat request/response `.js` files
  Taskfile.yml
  website/docs/guides/requests/1-insert-vector.js
  website/docs/guides/requests/2-hnsw-index.js
  website/docs/guides/requests/3-hnsw-search.js
  website/docs/guides/requests/4-ivf-index.js
  website/docs/guides/requests/5-ivf-search.js
  website/docs/guides/requests/index-syntax.js
  website/docs/guides/requests/search-syntax.js
  website/docs/guides/responses/3-hnsw-search.js
  website/docs/guides/responses/3-hnsw-search.json
  website/docs/guides/responses/5-ivf-search.js
  website/docs/guides/responses/5-ivf-search.json
  website/docs/guides/vector-search.mdx
  website/docs/usage/read.md
Labels: documentation

#4796 Update Docker image tag in v1 docs
  website/versioned_docs/version-v1.24/quickstart-guide/docker.md
  website/versioned_docs/version-v1.24/security/authentication.md
  website/versioned_docs/version-v1.24/security/tls-connections.md
Labels: documentation, trust

#4795 Make handler take over the pool
  .github/workflows/docs.yml
  .github/workflows/website-preview.yml
  Taskfile.yml
  cmd/ferretdb/main.go
  integration/setup/listener.go
  internal/clientconn/listener.go
  internal/documentdb/pool_new.go
  internal/handler/handler.go
  tools/checkdocs/checkdocs.go
Labels: code/chore

#4799 Add test helper
  internal/dataapi/listener_test.go
  internal/documentdb/documentdb_test.go
  internal/documentdb/genwrap/extract_test.go
  internal/util/testutil/db.go
  internal/util/testutil/postgresql.go
Labels: code/chore

#4800 Convert `json5` to `js` responses in docs
  website/docs/contributing/writing-guide.md
  website/docs/guides/replication.md
  website/docs/reference/operators/query/array-operators.md
  website/docs/reference/operators/query/bitwise-operators.md
  website/docs/reference/operators/query/comparison-operators.md
  website/docs/reference/operators/query/element-operators.md
  website/docs/reference/operators/query/evaluation-operators.md
  website/docs/reference/operators/query/logical-operators.md
  website/docs/reference/operators/update/array-update-operators.md
  website/docs/reference/operators/update/field-update-operators.md
  website/docs/usage/aggregations.md
  website/docs/usage/indexes.md
  website/docs/usage/read.md
Labels: documentation

#4716 Add `mongo` slog format
  cmd/ferretdb/main.go
  internal/handler/msg_getlog.go
  internal/util/logging/attrs.go
  internal/util/logging/buffer.go
  internal/util/logging/console_handler.go
  internal/util/logging/handler.go
  internal/util/logging/handler_test.go
  internal/util/logging/mongo_handler.go
  internal/util/logging/mongo_handler_test.go
  website/docs/configuration/observability.md
Labels: code/feature

#4778 Re-introduce embeddable package
  .golangci.yml
  README.md
  cmd/ferretdb/main.go
  ferretdb/ferretdb.go
  ferretdb/ferretdb_test.go
  go.mod
  go.sum
  integration/.golangci-new.yml
  integration/go.mod
  integration/go.sum
  internal/util/state/provider_other.go
  website/docs/installation/ferretdb/go.md
  website/docs/telemetry.md
Labels: documentation, code/feature, trust

#4805 Tweak Docusaurus configuration
  integration/findandmodify_compat_test.go
  website/docusaurus.config-blog.js
  website/docusaurus.config.js
Labels: documentation, trust

#4807 Make embeddable package logging configurable
  ferretdb/ferretdb.go
  ferretdb/ferretdb_test.go
  internal/util/testutil/logging.go
Labels: code/feature

#4767 Update release checklist and `.deb` installation guide
  .github/RELEASE_CHECKLIST.md
  website/docs/installation/documentdb/deb.md
  website/docs/installation/ferretdb/deb.md
Labels: documentation, code/chore, trust

#4804 Implement `dbStats` command
  integration/basic_test.go
  integration/commands_administration_test.go
  internal/handler/msg_dbstats.go
Labels: code/feature

#4802 Enable building FerretDB as PostgreSQL background worker
  .gitignore
  CHANGELOG.md
  build/ferretdb-bw/Dockerfile
  build/ferretdb-bw/Makefile
  build/ferretdb-bw/README.md
  build/ferretdb-bw/ferretdb/Makefile
  build/ferretdb-bw/ferretdb/ferretdb.go
  build/ferretdb-bw/ferretdb/ferretdb.h
  build/ferretdb-bw/ferretdb_loader/Makefile
  build/ferretdb-bw/ferretdb_loader/ferretdb_loader.c
Labels: code/feature

#4812 Update Docker tags
  .github/workflows/packages.yml
  CHANGELOG.md
  tools/definedockertag/main.go
  tools/definedockertag/main_test.go
Labels: trust, packages

#4815 Enable Docker Hub and quay.io
  tools/definedockertag/main.go
  tools/definedockertag/main_test.go
Labels: trust, packages

#4816 Prepare v2.0.0-rc.2 release
  CHANGELOG.md
  README.md
  build/version/version.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/go.mod
  tools/go.sum
  website/docs/installation/documentdb/deb.md
  website/static/ferrets-are-working.svg
Labels: trust, packages

#4817 Add blog post for rc2 release
  .github/RELEASE_CHECKLIST.md
  website/blog/2025-02-25-new-ferretdb-v2-rc2-release-with-debian-packages-and-better-indexing-support.md
  website/static/img/blog/ferretdb-v2-rc2.jpg
Labels: trust, blog/marketing

#4823 Change `dbStats` tests TODO links
  integration/commands_administration_test.go
Labels: code/chore

#4831 Update TODO comment
  Taskfile.yml
  ferretdb/ferretdb.go
  internal/handler/msg_currentop.go
Labels: code/chore

#4837 Publish build info, state, and CLI flags in expvar
  build/version/version.go
  cmd/ferretdb/main.go
  ferretdb/ferretdb_test.go
  internal/dataapi/listener_test.go
  internal/documentdb/documentdb_test.go
  internal/documentdb/genwrap/extract_test.go
  internal/documentdb/pool_new.go
  internal/handler/msg_setfreemonitoring.go
  internal/util/iface/iface.go
  internal/util/state/metrics_test.go
  internal/util/state/provider.go
  internal/util/state/provider_test.go
  internal/util/state/state.go
  internal/util/testutil/postgresql.go
  website/versioned_docs/version-v1.24/configuration/observability.md
Labels: documentation, code/enhancement, trust

#4754 Enforce log messages format in development builds
  cmd/envtool/tests.go
  cmd/ferretdb/main.go
  integration/setup/setup.go
  integration/setup/startup.go
  internal/clientconn/conn.go
  internal/dataapi/server/aggregate.go
  internal/dataapi/server/delete_many.go
  internal/dataapi/server/delete_one.go
  internal/dataapi/server/find.go
  internal/dataapi/server/find_one.go
  internal/dataapi/server/insert_many.go
  internal/dataapi/server/insert_one.go
  internal/dataapi/server/server.go
  internal/dataapi/server/update_many.go
  internal/dataapi/server/update_one.go
  internal/documentdb/genwrap/genwrap.go
  internal/util/logging/console_handler.go
  internal/util/logging/handler.go
  internal/util/scram/message.go
  internal/util/telemetry/reporter.go
  internal/util/testutil/logging.go
  internal/util/testutil/testutil.go
Labels: code/enhancement

#4845 Move comment in docs to fix DocCard
  website/docs/migration/diff.md
Labels: documentation, trust

#4849 Make Data API without authentication if requested
  Taskfile.yml
  internal/dataapi/listener.go
  internal/dataapi/listener_test.go
  internal/dataapi/server/server.go
  internal/util/debug/debug.go
Labels: code/bug

#4739 Add Data API blogpost
  website/blog/2025-02-28-best-alternative-to-mongodb-data-api-and-http-endpoints.md
  website/static/img/blog/data-api-deleteone.png
  website/static/img/blog/data-api-find.png
  website/static/img/blog/data-api-updateone.png
  website/static/img/blog/mongodb-data-api.jpg
Labels: trust, blog/marketing
