Repository FerretDB/FerretDB, pull requests merged in 2025-06, with the labels that each got.

#5211 Unskip test
  integration/delete_test.go
Labels: code/chore

#5210 Disable Markdownlint rule that clashes with MDX
  build/.markdownlint.yml
  website/blog/2022-11-14-mongodb-crud-operations-with-ferretdb.mdx
  website/blog/2023-10-31-mongodb-sorting-scalar.md
  website/docs/configuration/flags.md
  website/docs/guides/full-text-search.mdx
  website/docs/guides/ttl-indexes.mdx
  website/docs/guides/vector-search.mdx
  website/versioned_docs/version-v1.24/configuration/flags.md
  website/versioned_docs/version-v1.24/pushdown.md
  website/versioned_docs/version-v2.1/configuration/flags.md
  website/versioned_docs/version-v2.1/guides/full-text-search.mdx
  website/versioned_docs/version-v2.1/guides/ttl-indexes.mdx
  website/versioned_docs/version-v2.1/guides/vector-search.mdx
  website/versioned_docs/version-v2.2/configuration/flags.md
  website/versioned_docs/version-v2.2/guides/full-text-search.mdx
  website/versioned_docs/version-v2.2/guides/ttl-indexes.mdx
  website/versioned_docs/version-v2.2/guides/vector-search.mdx
Labels: documentation, trust

#5202 Update CTS tool to wrap long lines
  tools/go.mod
  tools/go.sum
  website/docs/guides/fixtures/books.js
  website/docs/guides/full-text-search/2-insert-data.request.js
  website/docs/guides/full-text-search/4-basic-text-search.response.js
  website/docs/guides/full-text-search/7-relevance-score.response.js
  website/docs/guides/vector-search/2-insert-data.request.js
  website/docs/guides/vector-search/4-hnsw-search.response.js
  website/docs/guides/vector-search/7-ivf-search.response.js
Labels: documentation, trust

#5215 Use Ollama in local setup
  .gitignore
  Taskfile.yml
  docker-compose.override.yml.example
Labels: code/chore

#5223 Update TODO comments
  internal/handler/msg_compact.go
  internal/handler/msg_findandmodify.go
  internal/handler/msg_insert.go
  internal/handler/msg_update.go
Labels: code/chore

#5251 Build production Docker images for PRs
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/definedockertag/main.go
  tools/definedockertag/main_test.go
  tools/go.mod
  tools/go.sum
Labels: code/chore, trust, packages

#5261 Update DocumentDB
  CHANGELOG.md
  build/deps/postgres-documentdb.Dockerfile
  build/ferretdb-bw/Dockerfile
  build/ferretdb/eval-dev.Dockerfile
  build/ferretdb/eval.Dockerfile
  build/version/documentdb.go
  integration/aggregate_compat_test.go
  integration/query_compat_test.go
  internal/documentdb/documentdb_api_internal/documentdb_api_internal.go
  website/docs/contributing/writing-guide.md
  website/docs/installation/documentdb/docker.md
  website/docs/installation/documentdb/kubernetes.md
  website/docs/installation/ferretdb/docker.md
  website/docs/installation/ferretdb/kubernetes.md
  website/docs/installation/ferretdb/systemd.md
  website/docs/reference/aggregation-operations/_category_.yml
  website/docs/reference/operators/update/_category_.yml
  website/docs/security/tls-connections.md
  website/docs/troubleshooting/overview.md
  website/docs/usage/data-api.md
Labels: documentation, trust, packages

#5275 Add Compass to compatible apps
  website/docs/compatible-applications/applications.js
  website/versioned_docs/version-v2.3/compatible-applications/applications.js
Labels: documentation, trust

#5270 Add PayloadCMS to compatible apps
  website/docs/compatible-applications/applications.js
  website/static/img/compatible-applications/payloadcms-logo.png
  website/versioned_docs/version-v2.3/compatible-applications/applications.js
Labels: documentation, trust

#4999 Add blog post on setting up LibreChat with FerretDB
  website/blog/2025-06-23-replacing-mongodb-with-ferretdb-librechat.md
  website/static/img/blog/ferretdb-librechat.jpg
  website/static/img/blog/librechat-interface.jpg
Labels: trust, blog/marketing

#5285 Add NodeBB compatibility blog post
  website/blog/2025-06-25-building-scalable-community-forums-nodebb-and-ferretdb.md
  website/static/img/blog/ferretdb-nodebb.jpg
  website/static/img/blog/nodebb-admin-dashboard.png
  website/static/img/blog/nodebb-compass.png
  website/static/img/blog/nodebb-topic.png
Labels: trust, blog/marketing

#5287 Add `mcphost` as tool
  Taskfile.yml
  build/.trivyignore
  tools/mcphost/go.mod
  tools/mcphost/go.sum
  tools/mcphost/mcphost.go
Labels: code/chore

#5276 Bring back Codecov and Coveralls integration
  .github/workflows/_integration.yml
  .github/workflows/go.yml
Labels: code/chore

#5296 Add Dependabot configuration for mcphost
  .github/dependabot.yml
Labels: code/chore

#5301 Extend middleware requests and responses
  cmd/ferretdb/main_test.go
  integration/indexes_compat_test.go
  integration/setup/helpers.go
  integration/setup/listener.go
  internal/documentdb/genwrap/generate_test.go
  internal/handler/cmd_query.go
  internal/handler/middleware/request.go
  internal/handler/middleware/response.go
  internal/handler/proxy/proxy.go
  internal/util/debug/archive.go
  internal/util/debug/debug.go
  internal/util/telemetry/reporter.go
  internal/util/telemetry/telemetry_test.go
Labels: code/chore

#5304 Add Growthbook blogpost
  website/blog/2025-06-27-enabling-feature-flags-ab-testing-growthbook-ferretdb.md
  website/static/img/blog/ferretdb-growthbook.jpg
  website/static/img/blog/growthbook-collections.png
  website/static/img/blog/growthbook-data.png
  website/static/img/blog/growthbook-experiment.png
Labels: trust, blog/marketing

#5307 Bump deps
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  tools/golangci/go.mod
  tools/golangci/go.sum
  tools/mcphost/go.mod
  tools/mcphost/go.sum
Labels: deps
