Repository FerretDB/FerretDB, pull requests merged in 2025-05, with the labels that each got.

#5078 Rename binaries and packages
  Taskfile.yml
Labels: code/enhancement, trust, packages

#5117 Decode `dropIndexes` response
  integration/indexes_command_compat_test.go
  integration/indexes_compat_test.go
  internal/documentdb/bsonhex/decoder.go
  internal/documentdb/documentdb_api/documentdb_api.go
  internal/documentdb/documentdb_api/procedure.go
  internal/documentdb/documentdb_api_internal/documentdb_api_internal.go
  internal/documentdb/genwrap/convert.go
  internal/documentdb/genwrap/convert_test.go
  internal/documentdb/genwrap/generate.go
  internal/handler/msg_dropindexes.go
  internal/handler/msg_reindex.go
Labels: code/enhancement

#5123 Run CTS tests against TTL Indexes guide examples
  Taskfile.yml
  tools/go.mod
  tools/go.sum
  website/docs/guides/ttl-indexes.json
  website/docs/guides/ttl-indexes/1-create-ttl-index.request.js
  website/docs/guides/ttl-indexes/1-create-ttl-index.response.js
  website/docs/guides/ttl-indexes/2-insert-ttl-data.request.js
Labels: documentation, code/chore, trust

#5121 Run CTS tests against Full Text Search guide examples
  website/docs/guides/books.fixture.json
  website/docs/guides/fixtures/books.js
  website/docs/guides/full-text-search.json
  website/docs/guides/full-text-search.mdx
  website/docs/guides/full-text-search/1-create-text-index.request.js
  website/docs/guides/full-text-search/1-create-text-index.response.js
  website/docs/guides/full-text-search/1-insert-text-data.request.js
  website/docs/guides/full-text-search/1-insert-text-data.response.js
  website/docs/guides/full-text-search/2-basic-text-search.request.js
  website/docs/guides/full-text-search/2-basic-text-search.response.js
  website/docs/guides/full-text-search/2-create-text-index.request.js
  website/docs/guides/full-text-search/2-create-text-index.response.js
  website/docs/guides/full-text-search/3-basic-text-search.request.js
  website/docs/guides/full-text-search/3-basic-text-search.response.js
  website/docs/guides/full-text-search/3-drop-text-index.request.js
  website/docs/guides/full-text-search/3-drop-text-index.response.js
  website/docs/guides/full-text-search/4-compound-text-index.request.js
  website/docs/guides/full-text-search/5-relevance-score.request.js
  website/docs/guides/full-text-search/5-relevance-score.response.js
Labels: documentation, code/chore, trust

#5132 Remove old TODOs
  website/docs/guides/replication.md
  website/docs/installation/ferretdb/docker.md
  website/docs/security/authentication.md
  website/docs/security/tls-connections.md
  website/versioned_docs/version-v2.0/guides/replication.md
  website/versioned_docs/version-v2.0/installation/ferretdb/docker.md
  website/versioned_docs/version-v2.0/security/authentication.md
  website/versioned_docs/version-v2.0/security/tls-connections.md
  website/versioned_docs/version-v2.1/guides/replication.md
  website/versioned_docs/version-v2.1/installation/ferretdb/docker.md
  website/versioned_docs/version-v2.1/security/authentication.md
  website/versioned_docs/version-v2.1/security/tls-connections.md
Labels: documentation, trust

#5124 Document update process for new releases
  website/docs/configuration/observability.md
  website/docs/installation/documentdb/deb.md
  website/docs/installation/documentdb/docker.md
  website/docs/installation/ferretdb/deb.md
  website/docs/installation/ferretdb/docker.md
Labels: documentation, trust

#5136 Publish FerretDB v2.2.0 release blog post
  website/blog/2025-05-09-ferretdb-v220-arm-architecture-support.md
  website/static/img/blog/ferretdb-v2.2.0.jpg
Labels: trust, blog/marketing

#5156 Update docker tags in docs
  website/versioned_docs/version-v2.2/installation/ferretdb/docker.md
Labels: documentation

#5157 Update tags for next release
  website/docs/installation/ferretdb/docker.md
Labels: documentation

#5109 Add `enableTelemetry` config for embedded FerretDB
  ferretdb/ferretdb.go
  internal/util/telemetry/telemetry.go
  website/docs/telemetry.md
Labels: code/feature

#5077 Use `runtime.Cleanup` for resource tracking
  internal/util/resource/resource.go
  internal/util/resource/resource_test.go
Labels: code/chore

#5079 Enable `onInlineAuthors` in blog settings
  website/blog/2022-10-06-how-to-start-ferretdb-locally-with-docker.md
  website/blog/2022-10-12-contribute-to-ferretdb-on-windows.md
  website/blog/2023-01-25-ferretdb-fetches-data-query-pushdown.md
  website/blog/2023-06-21-meet-ferretdb-percona-university-casablanca-belgrade.md
  website/blog/2023-07-13-run-ferretdb-on-stackgres.md
  website/blog/2023-07-19-community-matters-fireside-chat-cockroachdb.md
  website/blog/2023-08-18-ferretdb-going-postgres-ibiza-2023.md
  website/blog/2023-08-24-meet-us-civo-navigate-london.md
  website/blog/2023-09-28-how-to-contribute-to-open-source-2022.md
  website/blog/2023-09-29-ferretdb-database-choice-enmeshed-customers.md
  website/blog/2023-10-30-building-mongodb-like-developer-experience-vultr.md
  website/blog/2023-11-08-fastnetmon-picked-ferretdb-saas-offering.md
  website/blog/2024-02-12-guide-disaster-recovery-ferretdb-elotl-nova-kubernetes.md
  website/blog/2024-02-20-postgresql-can-it-be-a-database-for-everything.md
  website/blog/authors.yml
  website/docusaurus.config-blog.js
Labels: trust, blog/engineering

#5166 Make `conninfo` a resource
  internal/clientconn/conn.go
  internal/clientconn/conninfo/conninfo.go
  internal/dataapi/listener.go
  internal/dataapi/server/server.go
Labels: code/chore

#5131 Improve insert operations in guides
  website/docs/guides/full-text-search.json
  website/docs/guides/full-text-search.mdx
  website/docs/guides/full-text-search/1-drop-books-collection.request.js
  website/docs/guides/full-text-search/1-drop-books-collection.response.js
  website/docs/guides/full-text-search/2-insert-data.request.js
  website/docs/guides/full-text-search/2-insert-data.response.js
  website/docs/guides/full-text-search/3-create-text-index.request.js
  website/docs/guides/full-text-search/3-create-text-index.response.js
  website/docs/guides/full-text-search/4-basic-text-search.request.js
  website/docs/guides/full-text-search/4-basic-text-search.response.js
  website/docs/guides/full-text-search/5-drop-text-index.request.js
  website/docs/guides/full-text-search/5-drop-text-index.response.js
  website/docs/guides/full-text-search/6-compound-text-index.request.js
  website/docs/guides/full-text-search/6-compound-text-index.response.js
  website/docs/guides/full-text-search/7-relevance-score.request.js
  website/docs/guides/full-text-search/7-relevance-score.response.js
  website/docs/guides/vector-search.json
  website/docs/guides/vector-search.mdx
  website/docs/guides/vector-search/1-drop-books-collection.request.js
  website/docs/guides/vector-search/1-drop-books-collection.response.js
  website/docs/guides/vector-search/2-insert-data.request.js
  website/docs/guides/vector-search/2-insert-data.response.js
  website/docs/guides/vector-search/3-hnsw-index.request.js
  website/docs/guides/vector-search/3-hnsw-index.response.js
  website/docs/guides/vector-search/4-hnsw-search.request.js
  website/docs/guides/vector-search/4-hnsw-search.response.js
  website/docs/guides/vector-search/5-drop-hnsw-index.request.js
  website/docs/guides/vector-search/5-drop-hnsw-index.response.js
  website/docs/guides/vector-search/6-ivf-index.request.js
  website/docs/guides/vector-search/6-ivf-index.response.js
  website/docs/guides/vector-search/7-ivf-search.request.js
  website/docs/guides/vector-search/7-ivf-search.response.js
Labels: documentation, trust

#5182 Add `permissions` to GitHub Actions workflows
  .github/workflows/cleanup.yml
  .github/workflows/cts.yml
  .github/workflows/debug.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/go.yml
  .github/workflows/security.yml
  .github/workflows/testscripts.yml
  .github/workflows/website-preview.yml
Labels: code/chore

#5199 Add test for inserting zero timestamp
  integration/query/insert_test.go
Labels: code/chore
