Repository FerretDB/FerretDB, pull requests merged in 2025-08, with the labels that each got.

#5400 Enable MongoDB test commands
  build/mongodb-secure.conf
  build/mongodb.conf
Labels: code/chore

#5403 Update Prometheus metrics
  build/version/documentdb.go
  internal/clientconn/connmetrics/conn_metrics.go
  internal/clientconn/connmetrics/listener_metrics.go
  internal/documentdb/cursor/registry.go
  internal/documentdb/pool.go
  internal/documentdb/pool_new.go
  internal/documentdb/tracer.go
  internal/handler/session/registry.go
  internal/util/debug/debug.go
  internal/util/state/metrics.go
  website/docs/configuration/flags.md
  website/docs/configuration/observability.md
Labels: code/chore

#5423 Update documentation to point to the next release
  .github/RELEASE_CHECKLIST.md
  build/ferretdb/development.Dockerfile
  build/ferretdb/eval-dev.Dockerfile
  build/ferretdb/eval.Dockerfile
  build/ferretdb/production.Dockerfile
  build/version/documentdb.go
  website/docs/contributing/writing-guide.md
  website/docs/usage/data-api.md
Labels: deps, trust, packages

#5428 Bump YugabyteDB to stable version
  build/deps/yugabytedb.Dockerfile
Labels: code/chore

#5412 Add release blog post for FerretDB v2.5.0
  website/blog/2025-08-14-ferretdb-v250-is-available.md
  website/static/img/blog/ferretdb-v2.5.0.jpg
Labels: trust, blog/marketing

#5429 Use QEMU on arm64 for Yugabyte for now
  cmd/envtool/envtool.go
  cmd/envtool/setup.go
  docker-compose.yml
Labels: code/chore

#5441 Update content guide
  website/blog/_guide/content-process.md
Labels: blog/marketing

#5442 Update compatible apps
  website/docs/compatible-applications/applications.js
  website/static/img/compatible-applications/formio-logo.jpeg
  website/versioned_docs/version-v2.5/compatible-applications/applications.js
Labels: documentation, trust

#5450 Add TODO comment about Debian 13 Trixie
  build/ferretdb/development.Dockerfile
  build/ferretdb/eval-dev.Dockerfile
  build/ferretdb/eval.Dockerfile
  build/ferretdb/production.Dockerfile
  build/version/documentdb.go
Labels: code/chore, trust, packages

#5467 Add helpers for lazy logging
  internal/util/logging/lazy.go
  internal/util/logging/logging.go
Labels: code/chore

#5443 Avoid hijacking connections from the pool and immediately closing them
  integration/cursor/batch_test.go
  integration/cursor/getmore_test.go
  internal/documentdb/cursor/cursor.go
  internal/documentdb/cursor/registry.go
  internal/documentdb/pool_cursors.go
Labels: code/chore
